### ISSUE TITLE
Event creating connection

### ISSUE THREAD

**Issue by mucskaati** [jerosoler/Drawflow#101]
Hello,

Is there an event which will be fired when I click on input edge and try to make a connection?

My usecase: I need to fire event when a user is trying to make a connection. When a user click on input edge of node and try to make connection then the editor will fire an event. I know there is an event when the connection is created, but i want something like connectionCreating and not connectionCreated.

Thanks.

**Comment by jerosoler** [comment]
Hello  @mucskaati 

View #10 and #70 

This similar issues with deleting node.

**Comment by mucskaati** [comment]
Thanks, but it would be great if will you add this event in future...

**Comment by jerosoler** [comment]
If I plan to add. Events prevents in the future.
