### ISSUE TITLE
Emitting from child to parent [Vue 3]

### ISSUE THREAD

**Issue by mucskaati** [jerosoler/Drawflow#102]
Hello,

how can I emit event from child component ( which is a registered node) to parent component where I am initializing drawflow and adding nodes? 

Thanks.

**Comment by ananddoesembed** [comment]
you can use event bus for it. check comment #37

**Comment by mucskaati** [comment]
@ananddoesembed  Yes, but in Vue 3 is event bus deprecated, but I found a solution.

In Vue 3 is need to be used a third party package for creating event bus.
For example [Mitt](https://github.com/developit/mitt)
