### ISSUE TITLE
[FEAT] ConnectionSelected event

### ISSUE THREAD

**Issue by BobBDE** [jerosoler/Drawflow#103]
Hello,

First I want to say thank you for this library. I've been using it for few weeks and it works well even if it is a small lib, nice job !

Is is possible to add a ConnectionSelected even similar to the NodeSelected event ? I quickly check the library and it seems that it could be easy to add as the event is already detected inside the lib but not dispatch. 

In this event it would be nice to have the node the id_output, id_input, output_class, input_class values (the same as the connection creation). 

What do you think about this? If you think this is a good idea I could work on a Pull Request

Have a nice day ! :)

**Comment by jerosoler** [comment]
Hello!

Thanks a lot! 🎉

Good idea.

If they could be added.
It would have to add:

- **connectionSelected**
- **connectionUnselected**

I will try to add it or if you want you can do a PR.

Jero

**Comment by BobBDE** [comment]
I pulled the project and tried to work on it but I couldn't make the dev environement work. Could you provide information to make it work for dev ? Like a ReadMe for contributing.

**Comment by jerosoler** [comment]
Hello @BobBDE 

I will add a contribution file.
Basic instructions:
```
Fork
npm install
npm run dev
```

Added events in version: 0.0.34;)

Commits: 
https://github.com/jerosoler/Drawflow/commit/0e80eb321233293e9089b35d4c734ca1e1d5cbe5
https://github.com/jerosoler/Drawflow/commit/06793aad18c419322077cae6eb88bf7d2c24160e
https://github.com/jerosoler/Drawflow/commit/366fb8eebdf420350ffed0cdbfd903ffd061c2f2

Updated NPM package

**Comment by BobBDE** [comment]
Hi,

Thank you for this quick update ! 

I tried the npm run dev script but it doesn't work. 
It builds correclty and open chrome on 0.0.0.0:8080 but chrome can't open the 0.0.0.0 address. 

I removed the '--host 0.0.0.0' option in the dev script to serve the site on localhost and this works for me. 

Is there a reason for this '--host 0.0.0.0' option ? I think this complicate the dev environement and so contribution.s 

Once again, thank you for your reactivity !

**Comment by jerosoler** [comment]
Hi,

The reason for the host 0.0.0.0, is that it allows to use localhost and the local IP (which allows to see it on the phone at the same time, since the library supports mobile)

I see that it is a very common problem.
https://github.com/webpack/webpack-dev-server/issues/882

I will add it to the contribution file.

I close the issue, thank you! ;)
