### ISSUE TITLE
Can't get an id in a var

### ISSUE THREAD

**Issue by davidhui2047** [jerosoler/Drawflow#104]
I have a select option here:

case 'email':
          var template = `
        <div>
            Day(s) to Complete: 
            <select id="e_time" df-e_time>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
        </div>
        `;
          editor.addNode('email', 1, 1, pos_x, pos_y, 'custom-node', {
            "e_time": ""
          }, template);
          break;
I would like to use a loop to generate the option.

Here is my attempt:

case 'email':
      var template = `
    <div>
        Day(s) to Complete: 
        <select id="e_time" df-e_time>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
        </select>
    </div>
    <script>
        window.onload = function() {testing()};
        function testing() {
            var elm = document.getElementById('e_time'),
                df = document.createDocumentFragment();
            for (var i = 1; i <= 42; i++) {
                var option = document.createElement('option');
                option.value = i;
                option.appendChild(document.createTextNode("option #" + i));
                df.appendChild(option);
            }
            elm.appendChild(df);
        }
    </script>
    `;
      editor.addNode('email', 1, 1, pos_x, pos_y, 'custom-node', {
        "e_time": ""
      }, template);
      break;
if I put the loop inside the variable, then the program crash.

case 'email':
  var template = `
<div>
    Day(s) to Complete: 
    <select id="e_time" df-e_time>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
    </select>
</div>
`;
  editor.addNode('email', 1, 1, pos_x, pos_y, 'custom-node', {
    "e_time": ""
  }, template);
  break;
  
<script>
    window.onload = function() {testing()};
    function testing() {
        var elm = document.getElementById('e_time'),
            df = document.createDocumentFragment();
        for (var i = 1; i <= 42; i++) {
            var option = document.createElement('option');
            option.value = i;
            option.appendChild(document.createTextNode("option #" + i));
            df.appendChild(option);
        }
        elm.appendChild(df);
    }
</script>
if I put the loop outside the switch statement, then the script doesn't run, I guess it's because it can't get the id.

I would like to ask what should I do?

**Comment by jerosoler** [comment]
Hello @davidhui2047 

No use `script tag` in html template. 

More simple:

```javascript 
var template = `<div> Day(s) to Complete: <select id="e_time" df-e_time>`;
for (var i = 1; i <= 42; i++) {
  template += `<option value="${i}">${i}</option>`;
}
template += `</select> </div> `;

editor.addNode('email', 1, 1, 200, 500, 'custom-node', { "e_time": "" }, template);

```

Jero

**Comment by davidhui2047** [comment]
Thanks jerosoler!
I have solved the problem,
I really appreciate your help!
