### ISSUE TITLE
Is there any function can convert editable chart to non-editable with showing the stored data 

### ISSUE THREAD

**Issue by davidhui2047** [jerosoler/Drawflow#105]
Hi jerosoler,

Is there any function can convert this:
![image](https://user-images.githubusercontent.com/68799326/106588047-72c9d480-659e-11eb-9f2e-003228409809.png)
to this?
![image](https://user-images.githubusercontent.com/68799326/106588092-7f4e2d00-659e-11eb-9955-e95cfc277afa.png)

**Comment by jerosoler** [comment]
Hello @davidhui2047 

There is no function.

You would have to program it.

Surely with some CSS classes it could be done. And adding and removing some class.

**Comment by davidhui2047** [comment]
Thanks
