### ISSUE TITLE
Textarea inside node - how to change size

### ISSUE THREAD

**Issue by pavlyuts** [jerosoler/Drawflow#106]
Hi! Thanks again for great tool!

May you please to give me an idea bout how to fix an issue with textarea size change inside the node? 

The node cathes any drag, so textarea resize won't work, only node move hapens.

**Comment by jerosoler** [comment]
Hello @pavlyuts 

You can use `editor.draggable_inputs = false;` default is true. This option affects "input, textarea, select and contenteditable".

Other opción is:
```javascript
editor.on("click", function(e) {
      if(e.target.tagName === "TEXTAREA") {
        editor.draggable_inputs = false;
        console.log("click");
      } else {
        editor.draggable_inputs = true;
      }
    })
```

or: 

```javascript
editor.on("clickEnd", function(e) {
      if(e.target.tagName === "TEXTAREA") {
        editor.drag = false;
        console.log("click");
      }
    })
```

Choose the one that best suits you.

Jero

**Comment by pavlyuts** [comment]
Cool! Thank you so much! )))
