### ISSUE TITLE
What can the modules be used for?

### ISSUE THREAD

**Issue by davidhui2047** [jerosoler/Drawflow#108]
Hi jerosoler,

I would like to ask what can the modules be used for?

**Comment by davidhui2047** [comment]
Hi jerosoler,

I have another question, is there any function that can add a name for the connection like this?
![image](https://user-images.githubusercontent.com/68799326/107111435-3ea72a00-68a4-11eb-9ee7-5850666d696f.png)

**Comment by jerosoler** [comment]
Hello @davidhui2047 

View modules in the demo: https://jerosoler.github.io/Drawflow/

![image](https://user-images.githubusercontent.com/30957047/107113938-77261400-6862-11eb-9a9a-d1d4a4d07445.png)

To create insulated boxes.

For the connection name, is not implementet. View other issues: https://github.com/jerosoler/Drawflow/issues/18
