### ISSUE TITLE
rendering lists

### ISSUE THREAD

**Issue by mbazzo** [jerosoler/Drawflow#109]
hello, I want to render a list of data. would you have any example of how to implement this in your component?

**Comment by jerosoler** [comment]
Hi @mbazzo ,

I can't quite understand her question.
Could you detail it more?

Jero

**Comment by mbazzo** [comment]
@jerosoler 
Hi,
I'm trying to render a simple "ul> li" list;
I'm passing an array of objects to do this rendering, but I'm not getting it.

**Comment by jerosoler** [comment]
See this example.
That a list is generated.
View: https://github.com/jerosoler/Drawflow/issues/104#issuecomment-770906985

**Comment by mbazzo** [comment]
OK.
i'm using vue, i'll try to do that inside it.
another detail that I’m not able to do is load a saved layout, when it’s vue.
I'm probably doing something wrong. Would you have any examples using the vue?

**Comment by jerosoler** [comment]
View issues closed th vue: https://github.com/jerosoler/Drawflow/issues?q=is%3Aissue+label%3AVue+is%3Aclosed

Or simple example: https://github.com/jerosoler/Drawflow/issues/34

**Comment by mbazzo** [comment]
thank you
