### ISSUE TITLE
pressing delete key inside contenteditable=true element deletes the current node

### ISSUE THREAD

**Issue by taroongunessee** [jerosoler/Drawflow#11]
I'm using contenteditable elements inside html nodes.  When the user presses the delete key, the node is removed.  This behaviour works fine inside input text and textarea.  
Example code:

`var find = 
            <div>
              <div class=title-box><svg class=icon>
                <use xlink:href=#magnifying-glass></use></svg><span class="changeable" contenteditable="true" placeholder="Enter name ">Find</span></div>
                <div class=content-box>
                  <input ondrop="dropit(event)" class="form-control clsAlphaNoOnly" placeholder="Enter search text" ondragover="allowDropit(event)" required=true df-find>
                </div>
            </div>;
 editor.addNode('find', 1, 2, pos_x, pos_y, 'find', {"find": ""}, find.replace(/\s\s+/g, ' ') );`

Can you add contenteditable elements to this exception also?  Thank you very much

**Comment by jerosoler** [comment]
Fix in commit: https://github.com/jerosoler/Drawflow/commit/0064c26e929570b31aa4bafe2a948ecb7a72c86a
