### ISSUE TITLE
Show warning before deleting node

### ISSUE THREAD

**Issue by nodegin** [jerosoler/Drawflow#110]
Hi, thanks for this awesome library!
Is it possible to inject an async callback for prompting the user to confirm node deletion?
Like using window.confirm or via custom Vue dialog
Thanks!

**Comment by jerosoler** [comment]
Hello @nodegin 

Thanks! 🎉

View other similar issues: #10 #70 #98

**Comment by nodegin** [comment]
Thank you @jerosoler!
I will try it
