### ISSUE TITLE
Limiting maximum connection of node

### ISSUE THREAD

**Issue by nodegin** [jerosoler/Drawflow#111]
Is it possible to limit maximum output to / input from of a node?
For example:
If A1 connected to B1 then A2 cannot connect to B1 since B1 maximum input is 1
If A1 connected to B1 and there is a B2, A1 cannot connect to B2 since A1 maximum output is 1
Thanks!

**Comment by jerosoler** [comment]
Hello @nodegin 

Use events `connectionCreated` for remove connections.

You have to create your logic. 

View examples to limit  sigle connection: https://github.com/jerosoler/Drawflow/issues/35

Jero

**Comment by nodegin** [comment]
Thank you @jerosoler, the example worked for me!
