### ISSUE TITLE
Accessing node data from Vue?

### ISSUE THREAD

**Issue by nodegin** [jerosoler/Drawflow#114]
Hello, I added a node with following line
`editor.addNode('name', 1, 1, pos_x, pos_y, '', { test: 1 }, 'v-component', 'vue');`

How can I access `test: 1` in Vue `v-component`?

**Comment by jerosoler** [comment]
Hello  @nodegin 

Pass as prop or get Info of node.
View: https://github.com/jerosoler/Drawflow/issues/37 and https://github.com/jerosoler/Drawflow/issues/40

Maybe it will also work for you: https://github.com/jerosoler/Drawflow/issues/39

Jero


Jero

**Comment by nodegin** [comment]
@jerosoler  Shouldn't the props passed in `addNode `? it looks odd passed in registerNode so we cannot really passing node instance's data to vue

**Comment by nodegin** [comment]
OK I found that we can use `this.$el.parentElement.parentElement.id`
