### ISSUE TITLE
Moving the canvas / setting initial position?

### ISSUE THREAD

**Issue by nodegin** [jerosoler/Drawflow#115]
Sorry for another issue, is it possible to programmatically set the canvas position just like by dragging with mouse?
I want to center the nodes on load, tried setting `canvas_x` but not effecting

**Comment by jerosoler** [comment]
Hello @nodegin 

View: https://github.com/jerosoler/Drawflow/issues/88

😉

**Comment by nodegin** [comment]
Thank you @jerosoler!
Sorry for late reply
