### ISSUE TITLE
UUID as node ID

### ISSUE THREAD

**Issue by pavlyuts** [jerosoler/Drawflow#116]
Thanks again for a coold tool and I need your advice.

I need every node has UUID as the primary ID for each node of each flow is unique. Sure, I can put it to node name or any extra field, but it is not the best way.

I have rviewed the code and found that you just keeping the max node id nr at class variable and assign it, then ++. It looks like I can tweak your code to put UUID there and for a first look it should work. However, you know you code much better and may you advice if you rely on digital node ID somewhere? 

May be you interested to got the pull request on that? It looks like it will be back-compatible to digital node id and made no problems. Another approach is to add configuration variable like this.useuuid and made conditional id allocation on new node.

Any suggestion?

**Comment by jerosoler** [comment]
Hello @pavlyuts 

I think you will have no problem if you modify it.
Everything is a matter of testing it.

Maybe you have to tweak some function for some parseInt (...).

But I think there is no problem.

Jero

**Comment by pavlyuts** [comment]
I did, both int style andUUID, managed over useuuid property. First feelings: it works fine! 

UUID appears everywhere on place of int ID and all the create/conntect/drop works fine. Even mixed scenario with load of int and add UUID works well. 

parseInt (...) is not an issue because it returns NaN which is aways false in any comparision, so the code detect next int id correctly in the mixed environment. I can't test hard, I have no VUE skills and may be other skills too. I did as muche testing as I can.

I will do a pull request for your rewiev.

**Comment by jerosoler** [comment]
Ohh good job @pavlyuts 

I have a question, could the getUuid function return the same uuid?
I see that it has come out of here:
https://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid

I review it! But if not, the function can always be overwritten.

Thanks! ;)

**Comment by pavlyuts** [comment]
> I have a question, could the getUuid function return the same uuid?
Theoretically there are 1 to too-much-billion chance. And do not forget that you generate just a dosen or two of UUIDS. 

Non-uniqe uuid problem may be dangerous if you generate it by billlions, like in a case of big databases. In our case, I am sure it is not an issue. In our case, the probability is VERY low even the math.random is a not crypto-class source. I can't mind a reason to implement much more sophisticated code and require cripto extensions.

Most of discussion on Stackoverflow was about performance and decrase chance to duplicate. I have choosen the simpler one, considering that 36-time maths even pseudorandom has very low probability. If you look for better, you may use variant, enriched with timestamp and time since page load.
https://stackoverflow.com/a/8809472

If you are great perectonist, you may use some special like uuid module https://github.com/uuidjs/uuid, but I am not sure it will work god in the brouser.

IMHO, even simple x36 pseudorandom is a good enough. It is not a military crypto )))

**Comment by jerosoler** [comment]
Merget! 😉
