### ISSUE TITLE
is multiple nodes possible?

### ISSUE THREAD

**Issue by nsisodiya** [jerosoler/Drawflow#125]
Can we draw like this?

![image](https://user-images.githubusercontent.com/333455/109427525-c94cf600-7a18-11eb-865d-b883553876f1.png)

**Comment by jerosoler** [comment]
Hello @nsisodiya 

Yes support multiple inputs and outputs.

View demo https://jerosoler.github.io/Drawflow/ node "Multiple inputs/outputs"

Jero

**Comment by nsisodiya** [comment]
Thanks a lot.
