### ISSUE TITLE
[Question] how to do if-conditional block? and do you have paid support for answering questions?

### ISSUE THREAD

**Issue by simkimsia** [jerosoler/Drawflow#127]

**Comment by jerosoler** [comment]
Hello @simkimsia 

A conditional block, it's simple.

It only has one input and 2 outputs.
Output 1: if
Output 2: else.

You can contact me directly in the email of my profile. https://github.com/jerosoler

Jero

**Comment by dearsina** [comment]
This is how I do conditional blocks.

![conditions](https://user-images.githubusercontent.com/3647339/111282202-6bd6bd00-8646-11eb-841b-b0fb4c11024b.png)

**Comment by danielpc12** [comment]
> This is how I do conditional blocks. As @jerosoler says, you have to create a system where output 1 and output 2 take on the role of true and false. It's a little faffy to set up, but once you're rolling it's actually quite beautiful. Thanks again to Jero for a really nice library.
> 
> ![conditions](https://user-images.githubusercontent.com/3647339/111282202-6bd6bd00-8646-11eb-841b-b0fb4c11024b.png)

How you made it?

**Comment by dearsina** [comment]
It's pretty simple, from a Drawflow.js perspective, it's just a node with two outputs. The conditional logic happens on the backend.
