### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by ishpreetkaurwebner** [jerosoler/Drawflow#131]
I am facing a weired issue.
Export is working perfectly fine.
When I add a new, remove a node, then export shows perfect json data and I'am saving that exported output in database.
Next time, I imported from database and everything shown as original which is exported.

There is one issue. 

![image](https://user-images.githubusercontent.com/9744665/109997525-4ab4c900-7d36-11eb-89ac-30494f5de897.png)

In image, you can see that there is text box on each node and each node has default text. But, when I change the content in the textbox, no change is reflected in the exported json, it shows original content.

**Comment by jerosoler** [comment]
Hello,

Are you using the df variables?

You can use the attribute df- * in inputs, textarea or select to synchronize with the node data.

Multiple attributes parents support df - * - * ...

Jero

**Comment by ishpreetkaurwebner** [comment]
Whether any value also need to be passed in df- attributes or just blank like
`<input type="text" name="email" value="Set email" df-name/>`                      or
`<input type="text" name="email" value="Set email" df-name="something"/>`

**Comment by ishpreetkaurwebner** [comment]
Thanks a lot @jerosoler , with just adding df-*, correct value is showing after export, import. Working perfectly fine.
