### ISSUE TITLE
update connection lines from one node to another

### ISSUE THREAD

**Issue by chakanish** [jerosoler/Drawflow#132]
Hello,

Hope you are doing good.

I am back with another question 😃 

I am able to add nodes and create connections between them. However one feature I am not able to find. If I have 3 nodes and 2 of them are connected. I want to be able to click and drag the route line from one node to the other.

Example:: 
![image](https://user-images.githubusercontent.com/13881545/110203522-b0b76280-7e94-11eb-9aac-a220d69f3720.png)

In the above image if I want to move the connecting line from the node to the right to the node on the left. How do I do it? Is this feature available in the library?

Regards,
Anish

**Comment by jerosoler** [comment]
Hello,

That function is not available.
You have to delete the line and create a new line.

Jero

**Comment by chakanish** [comment]
ok. are you planning to add this feature anytime soon?

Also is there an option to restrict an output to have only one link coming from it?

**Comment by jerosoler** [comment]
Hello @chakanish 

For force only one output view:  https://github.com/jerosoler/Drawflow/issues/35#issuecomment-691876863

**Comment by chakanish** [comment]
thanks. it worked!!!
