### ISSUE TITLE
Input and output circles on top and bottom of nodes

### ISSUE THREAD

**Issue by ishpreetkaurwebner** [jerosoler/Drawflow#134]
Whether small circles for input and output connections can be placed at top and bottom in-place of left and right positions? If you have any idea to place those small circles on top and bottom irrespective of height of div, please share the sample change which might help to place small circles on top and bottom.

**Comment by jerosoler** [comment]
View: https://github.com/jerosoler/Drawflow/issues/20 

Closed for duplicated
