### ISSUE TITLE
line_path option is not working

### ISSUE THREAD

**Issue by nodegin** [jerosoler/Drawflow#136]
Hello,

I try to set the line width but no luck
`editor.line_path = 100`

Result:
<img width="88"  src="https://user-images.githubusercontent.com/8536244/110923543-5e7ab380-8364-11eb-98bc-5ffe782e5e40.png">

Please help!! thanks

**Comment by jerosoler** [comment]
Hello @nodegin 

Use css 
```css
.drawflow .connection .main-path {
    stroke-width: 10px;
}

**Comment by nodegin** [comment]
Hi @jerosoler , thank you for quick response! It works
