### ISSUE TITLE
How to make nodes resizable and collapsible?

### ISSUE THREAD

**Issue by gogzor** [jerosoler/Drawflow#137]
Hey! I've been using your lib for a while now, seems to fit every need, except that I found few things that are missing.

**How to achieve these?**

1. Resizable nodes
2. Collapsible nodes

Sometimes contents of a node can be too massive, so would be good to be able to collapse such content or in other cases just resize node.

Please help.

Thank you!

**Comment by jerosoler** [comment]
Hello @gogzor 

Variable-sized nodes are possible.
You just have to specify a `width: auto` with css.

If they were resizable, the value of the node size would have to be saved in the export.

Inside a node you can add a collapside, since it supports html.

**Comment by puzzle404** [comment]
You cannot change the size of the node, because every time I try to modify the size, for example, of the textarea that is inside, it takes the click as if I wanted to move the node. How can this be resolved?
