### ISSUE TITLE
Adding/Deleting outputs

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#14]
Hi, first of all,great script.
I would like to know if there is any method available to add/delete output of any node?

**Comment by jerosoler** [comment]
Hello Thanks!

You mean? 

![image](https://user-images.githubusercontent.com/30957047/88205775-8b4f4e80-cc4d-11ea-8388-c5dc64f827d5.png)

To: 
![image](https://user-images.githubusercontent.com/30957047/88205862-a91cb380-cc4d-11ea-8836-2043a136d953.png)

**Comment by MehbubRashid** [comment]
Yes,exactly.Is it possible?

**Comment by jerosoler** [comment]
Currently does not allow it.

It can be a good feature. Take note.

If you need it maybe you could do something like this: view **setTimeout** 

```javascript 
editor.start();

var html = `
<div><input type="text" df-name></div>
`;

var data = { "name": '' };

var html = document.createElement("div");
html.innerHTML= '<div><input type="text" df-name></div>';

editor.registerNode('test', html);
editor.addNode('github', 0, 1, -300, 300, 'github', data, 'test', true);
editor.addNode('github', 2, 3, 150, 300, 'github', data, 'test', true);
editor.addConnection(1, 2, 'output_1', 'input_2')

setTimeout(function(){
  const info = editor.getNodeFromId(1);

  editor.addNode(info.name, Object.keys(info.inputs).length, Object.keys(info.outputs).length +1, info.pos_x, info.pos_y, info.class, info.data, info.html, info.typenode);
  editor.removeNodeId('node-1');
  // REDRAW connections  with
  //editor.addConnection(....)

}, 1500);
```

**Comment by MehbubRashid** [comment]
Thanks.i thought of something like that.

But it would be so great if you add support for this function.There might be case where users need to add button on the node and on adding a new button,a new output also added for that button (just like manychat message flow builder)

**Comment by MehbubRashid** [comment]
Hi, @jerosoler  i have tried the method you mentioned.everything works fine.but when i try to get the connections from the old node,there is no connection in the array.even if i called `const info = editor.getNodeFromId(1);` before removing the node using `editor.removeNodeId('node-1');` 

0 connection in the info array.Strange

**Comment by jerosoler** [comment]
Hi! @MehbubRashid 

mmmmm not cloning object correctment. 

Try: 
```javascript
  const info = JSON.parse(JSON.stringify(editor.getNodeFromId(5)));
  editor.removeNodeId('node-5');
  console.log(info);
```

I look to correct it

**Comment by MehbubRashid** [comment]
Yes, after adding `JSON.parse(JSON.stringify())`, it works...But why does it work?Can you tell me the reason behind it? I wish to learn the theory behind it.

i think `editor.getNodeFromId(5)` and `JSON.parse(JSON.stringify(editor.getNodeFromId(5)));` this two are same thing.but first one works and second one does not.Why? :D

**Comment by MehbubRashid** [comment]
Okay, after searching in google, i found out its a proper way of cloning objects.Learned a new thing.Thanks again

**Comment by MehbubRashid** [comment]
Hi, @jerosoler , do you have plan to add the (deleteSpecificOutput) function anytime soon?

**Comment by jerosoler** [comment]
Hello

I would like to add.

- addNodeOutput
- addNodeInput
- deleteNodeOutput
- deleteNodeInput

I haven't had time to look at it yet.

**Comment by MehbubRashid** [comment]
Great,though i have manually implemented them.but would like to see official implementation soon.thanks

**Comment by jerosoler** [comment]
I just added addNodeOutput and addNodeInput. https://github.com/jerosoler/Drawflow/commit/1f84ededf6f9be82db67ef32971d1b1b1b2ca202
I've also fixed the getNodeFromId export. https://github.com/jerosoler/Drawflow/commit/a62cdb0690103740ec66d3320eeb2f3436a184f2

I have doubts about how to implement deleteNodeOutput/Input.

For example the node with 3 outputs.
[output_1, output_2, output3]
Execute delete output_2 function.

How would it look?
one:
[output_1, output_2]

Oh
two:
[output_1, output_3]

The first option seems the most logical. What do you think?

Another option is to always remove the last output.

How have you implemented it?

**Comment by MehbubRashid** [comment]
Yes,i also have implemented the first option.This will give additional benefits.

**Comment by jerosoler** [comment]
Added functions `removeNodeInput(id, input_class)` and `removeNodeOutput(id, output_class)`

Commit: https://github.com/jerosoler/Drawflow/commit/af83a1281f444555859c0f6b5329e8417f9b91ad

Try please ;)

**Comment by MehbubRashid** [comment]
Thank you so much for adding these features!!
