### ISSUE TITLE
fixed editor_mode but allow clicking on lines?

### ISSUE THREAD

**Issue by nodegin** [jerosoler/Drawflow#140]
Hello, I want to allow user to click on lines to highlight the route but disallow them to moving nodes (editing), currently if editor_mode set to fixed all click event will not work. How can I achieve this?

**Comment by jerosoler** [comment]
Hello

For example: 
```javascript
    editor.on("click", function(event) { 
        if(event.target.tagName === "path") {
            editor.editor_mode = 'edit';
        } 
    });

    editor.on("clickEnd", function(event) {
        editor.editor_mode = 'fixed';

    });
```

**Comment by nodegin** [comment]
@jerosoler Thanks it worked!
