### ISSUE TITLE
Prevent multiple input connections for a node 

### ISSUE THREAD

**Issue by ishpreetkaurwebner** [jerosoler/Drawflow#144]
I know multiple inputs and outputs are possible. It is perfectly fine. 
Right now, one node can accept multiple connections as input from different nodes. Is there any way exist to prevent multiple connections from different nodes. One bubble (small round circle) of node should accept only one connection?

**Comment by jerosoler** [comment]
Hello @ishpreetkaurwebner 

View https://github.com/jerosoler/Drawflow/issues/35

Jero

**Comment by ishpreetkaurwebner** [comment]
@jerosoler, 
Amazing. Your solution working perfectly.
