### ISSUE TITLE
Save page

### ISSUE THREAD

**Issue by khatbahusain** [jerosoler/Drawflow#145]
thank you for this amazing library @jerosoler 
However is there anyway to save the editor with what I type inside the input box in order to reload it later ?
I tried import/export this works fine but not with the text I typed inside the boxes 
Thanks again :)

**Comment by jerosoler** [comment]
Hello @khatbahusain 

You can use the attribute df- * in inputs, textarea or select to synchronize with the node data.

Multiple attributes parents support df - * - * ...

View #131 

And doc: https://github.com/jerosoler/Drawflow#nodes

Jero

**Comment by khatbahusain** [comment]
Thank you :)
