### ISSUE TITLE
example import/export 

### ISSUE THREAD

**Issue by khatbahusain** [jerosoler/Drawflow#146]
I'm trying the export/import and it works fine within the same session of work (with some JS)
it also works when I hard code the export data like this : `edit.import(hard_code_json_file)`

but I can't reuse the data after saving to an external file. Can you please provide me an example of how to save an export to a external file and import it after 👍 

Thanks alot :)

![image](https://user-images.githubusercontent.com/68100379/112733995-5bc2b580-8f43-11eb-9065-7e8a778bedb4.png)

**Comment by jerosoler** [comment]
Hello @khatbahusain 

Importing and saving the file is up to the backend.
What language do you use?

Can you show the console log of what you are trying to import?

**Comment by khatbahusain** [comment]
Thank you for your help, I appreciate it :)
I'm using flask in order to save my data as json to reuse the same data(html+inputs data ..) every time I open the app ..

flask code:
<img width="508" alt="flask" src="https://user-images.githubusercontent.com/68100379/112854797-7d8c7b80-90ae-11eb-93e2-68592b1e46e5.png">

my js code:
<img width="480" alt="js" src="https://user-images.githubusercontent.com/68100379/112855021-ba587280-90ae-11eb-9055-063e48ff6226.png">

and console.log:
<img width="447" alt="console" src="https://user-images.githubusercontent.com/68100379/112855175-dd832200-90ae-11eb-8b9e-25add6cc70a7.png">

It works like this: 
<img width="592" alt="working" src="https://user-images.githubusercontent.com/68100379/112856117-c1cc4b80-90af-11eb-8ede-a7577a2481c7.png">

note: I converted from (json-js) to (json-python) and conversely

**Comment by jerosoler** [comment]
The problem is the return is plain text. 

Try 
```javascript
editor.import(JSON.stringify(YOUR_DATA));
```

**Comment by khatbahusain** [comment]
Yes the problem is related to type of data
I've tried to do that using JSON.stringify(DATA)
But this what I get:
![image](https://user-images.githubusercontent.com/68100379/112859168-de1db780-90b2-11eb-911c-0d49631d24c2.png)

I really don't understand why I can't read the imported variable from flask !

**Comment by jerosoler** [comment]
View https://stackoverflow.com/questions/13081532/return-json-response-from-flask-view
