### ISSUE TITLE
Connecting one input with unlimited outputs

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#15]
![images (76)](https://user-images.githubusercontent.com/34944930/88225732-cc1a8800-cc8c-11ea-9968-e9f0379f72aa.jpeg)

Please see the picture.Its a common case when the input of any node has to be connected with the outputs of multiple (in fact unlimited) nodes.

I can see its already possible.But can i prevent more than 1 wire coming out of 1 output?

In a nutshell:
An input can be connected with unlimited outputs.
But one output can only be connected with one input.

**Comment by jerosoler** [comment]
Yes. It's possible.

Multiple input/outputs

View demo https://jerosoler.github.io/Drawflow/

**Comment by MehbubRashid** [comment]
Hi, thanks for your reply.i noticed that its possible.but can i restrict such that only one wire can come out of one output?

Because one input can be connected with unlimited outputs.but one output can connect with only one input.

Cause I dont want users to be able to choose multiple results for one action.one result can be caused by multiple actions.but one action can produce only one result.

**Comment by jerosoler** [comment]
Not actually.

Something similar comment in: https://github.com/jerosoler/Drawflow/issues/10

For example:
Create a new event to detect before setting up the connection and validate it.

**Comment by MehbubRashid** [comment]
Thanks, i figured out i can do this using the new connection created event.On that event, i check if a connection already exist with the output,then i simply remove the old connection and establish the new connection.This gives me what i want to achieve (Not having more than one connection from an output).

Thank  you very much for this amazing plugin

**Comment by MehbubRashid** [comment]
Hi,sorry to bother again.is it possible to remove a single connection?

**Comment by jerosoler** [comment]
Just recently I added method "addConnection". (https://github.com/jerosoler/Drawflow/commit/de99a4e2d42bfbaf2a0ed49cd064721f7c0840b6)

A new method "removeSingleConnection()" would have to be added

**Comment by MehbubRashid** [comment]
Awesome! Thanks.Will be waiting eagerly for it

**Comment by jerosoler** [comment]
Thanks for pull request! (Sorry for close) 

Added in version 0.0.13

Commit: https://github.com/jerosoler/Drawflow/commit/b6669a20e759b6defe0eeb73def406955ee979ee

**Comment by MehbubRashid** [comment]
No problem, thanks
