### ISSUE TITLE
Link Connection to a Button

### ISSUE THREAD

**Issue by xxxx-dev** [jerosoler/Drawflow#150]
Hello!, I'm a beginner trying to use your drawflow (Thanks a lot 🥇), and I wanna to link connection to a button(onclick) create a connection between two modules.When I use AddConnection & AddNodeOutput the console always declaring undefined functions.

**Comment by jerosoler** [comment]
Hello @xxxx-dev 

How do you call the functions?

```javascript
const editor = new Drawflow(id);
...
editor.addConnection(15,16,'output_1','input_1')
```
The first letter is lowercase
