### ISSUE TITLE
importing dynamic input values 

### ISSUE THREAD

**Issue by iamnikhilrohan** [jerosoler/Drawflow#155]
Hey @jerosoler , i'm trying Drawflow recently. And im facing a bit of a issue. 

![blah](https://user-images.githubusercontent.com/80256767/114414523-83b14a80-9bcc-11eb-9594-27eaa31f66c0.png)

and this my javascript file where education fields() is been called.

`var room = 1;

     function education_fields(){
         room++;
        var objTo = document.getElementById('education_fields')
        var Degree = document.getElementById('Degree')
        val=Degree.value;
        var divtest = document.createElement("div");
        divtest.setAttribute("class", "form-group removeclass"+room);
        var rdiv = 'removeclass'+room;
        divtest.innerHTML = `
            <div>
                    <input type="text" df-Degree id="Degree" name="Degree[]" value="`+val+`" placeholder="Degree">
                    <span>
                      <button class="btn btn-danger" type="button" onclick="remove_education_fields(` +room+ `);"> <span class="glyphicon glyphicon-minus" aria-hidden="true"></span> </button>
                    </span>
                    <div class="clear"></div>
            </div>
            `;
        objTo.appendChild(divtest)
        Degree.value="";
     }`

when user clicks on the success button, education_fields() is called and new input tag is placed in the block. but when i import them, the values do not get stored. how do i solve this?

**Comment by jerosoler** [comment]
Hello @iamnikhilrohan 

You are modifying the html directly.
You have to save the html to export it.

View: #40 

They can also serve you #97 and #73
