### ISSUE TITLE
How does API returns all connections made to the node?

### ISSUE THREAD

**Issue by princeyogesh** [jerosoler/Drawflow#156]

**Comment by princeyogesh** [comment]
Is there any way to know whether two nodes are connected to each other

**Comment by jerosoler** [comment]
Hello @princeyogesh 

View methods: https://github.com/jerosoler/Drawflow#methods


```javascript 
editor.getNodeFromId(id) // return info of node id number of node Ex: 5
```

**Comment by princeyogesh** [comment]
oh great @jerosoler  thanks , you can close the issue now
