### ISSUE TITLE
Connectors stay static with collapsible blocks.

### ISSUE THREAD

**Issue by iamnikhilrohan** [jerosoler/Drawflow#157]
i have multiple collapsible blocks but when i collapse them, the connectors dont move.
![collap](https://user-images.githubusercontent.com/80256767/114765581-f2380900-9d82-11eb-8c89-ba2741c925b7.png)

**Comment by jerosoler** [comment]
Hello @iamnikhilrohan 

Update the node connections with the method. When it collapses or uncollapses.

Use method:
```javascript
updateConnectionNodes(id)
```

**Comment by iamnikhilrohan** [comment]
> Hello @iamnikhilrohan
> 
> Update the node connections with the method. When it collapses or uncollapses.
> 
> Use method:
> 
> ```js
> updateConnectionNodes(id)
> ```

i tried doing that but still it does not work.

**Comment by jerosoler** [comment]
Any error in the console?

Sorry, look at the documentation again

It is called like this:

```javascript
editor.updateConnectionNodes('node-5');
```

use
```javascript
editor.updateConnectionNodes('node-'+selectedNode);
```

**Comment by iamnikhilrohan** [comment]
> Any error in the console?
> 
> Sorry, look at the documentation again
> 
> It is called like this:
> 
> ```js
> editor.updateConnectionNodes('node-5');
> ```
> 
> use
> 
> ```js
> editor.updateConnectionNodes('node-'+selectedNode);
> ```

i tried that too and it didn't work.
is there any way i can move the bubble position to the top of the part where by block header is placed instead of the middle of the block?

**Comment by jerosoler** [comment]
You can modify them with css
