### ISSUE TITLE
Writing text on connections

### ISSUE THREAD

**Issue by housefrommars** [jerosoler/Drawflow#161]
Is there a way to write some text on connections to the nodes, that would be binding to the connections and not the nodes themselves. 

For example:

![Screenshot from 2021-04-21 12-05-03](https://user-images.githubusercontent.com/7488109/115536338-fdff6000-a299-11eb-9ff9-39972e0a9136.png)

**Comment by jerosoler** [comment]
Hello @housefrommars  

Not implemented. 
You can see some solutions: https://github.com/jerosoler/Drawflow/issues/18

Jero
