### ISSUE TITLE
How to make connection starting from input circle and ending on output circle?

### ISSUE THREAD

**Issue by princeyogesh** [jerosoler/Drawflow#162]

**Comment by jerosoler** [comment]
uhmmm reverse connection method?  Or two  methods?

**Comment by princeyogesh** [comment]
yes @jerosoler  kind of reverse connection i am looking for,

**Comment by princeyogesh** [comment]
currently i am not able to start connection drag from input circle. as well as cannot drop the connection on output circle.

please help me how can achieve this

**Comment by princeyogesh** [comment]
I just want to draw connection from any node to any other node, without caring whether input or output circle

**Comment by jerosoler** [comment]
You are requesting three changes.

1: That a connection can be made in reverse.
2: That an output can be disconnected from output.
3: That an input can be connected to an input or an output to an output or input to an output. What no longer makes sense that they are called like that. And it also comes into conflict with the second question it raises.


For all these changes you will have to modify the library.

It is just a javascript file. You can take a look at it:
https://github.com/jerosoler/Drawflow/blob/master/src/drawflow.js

I think the best option is to modify the library with a single type of input and that it allows the connection itself.

What you want to create is a diagram right?
Don't use the json that to create a workflow.
