### ISSUE TITLE
Prevent double click event of connection

### ISSUE THREAD

**Issue by ishpreetkaurwebner** [jerosoler/Drawflow#166]
Double click of connection is creating a problem.

Original flow is:

![image](https://user-images.githubusercontent.com/9744665/116916813-70454c80-ac6b-11eb-9cde-ccbd2892c42a.png)

On double click the connection between Existing Deal and Send Email node,
connection becomes as shown in following screenshot:

![image](https://user-images.githubusercontent.com/9744665/116916964-a387db80-ac6b-11eb-81b0-5f883546bdcc.png)

Whether any event exists for such change in this library? How to stop such weird change on double click of connection?

Thanks a lot for quick reply until now.

**Comment by jerosoler** [comment]
Hello  @ishpreetkaurwebner 

In the demo do you have the same problem? https://jerosoler.github.io/Drawflow/

Do you use? 
```javascript
editor.reroute = true;
editor.reroute_fix_curvature = true;
```

I guess it could be prevented with the "click" event. Or add eventlistener to drawflow parent.

**Comment by ishpreetkaurwebner** [comment]
> Hello @ishpreetkaurwebner
> 
> In the demo do you have the same problem? https://jerosoler.github.io/Drawflow/
> 
> Do you use?
> 
> ```js
> editor.reroute = true;
> editor.reroute_fix_curvature = true;
> ```
> 
> I guess it could be prevented with the "click" event. Or add eventlistener to drawflow parent.

Yes, I have used these lines and my issue is not same as demo you are showing. Demo is working fine. My problem is: On double click, connection becomes two separate lines, one line is attached to output bubble of first node, and second line is attached to input bubble of second node.

**Comment by ishpreetkaurwebner** [comment]
@jerosoler - It will be better if on double click, nothing will change, the change happens in demo, that is also not our requirement.
Can you give idea on which drawflow event, I can prevent any change?

**Comment by ishpreetkaurwebner** [comment]
@jerosoler Thanks a lot for your quick reply. With your hint: `editor.reroute = false;`, my problem is solved.
