### ISSUE TITLE
Is it possible to store nodes and connections in LocalStorage?

### ISSUE THREAD

**Issue by adamburczy** [jerosoler/Drawflow#173]
Hello, when I create nodes non-programmatically, for example using drag and drop on demo:  https://jerosoler.github.io/Drawflow/, after I refresh page, everything I added disappear. Is there way to keep it after page refresh for example, storing it to LocalStorage, and then adding to HTML code of page?

**Comment by jerosoler** [comment]
Hello @adamburczy 

Yes is possible.

View to save object in localstorage: 
https://stackoverflow.com/questions/2010892/storing-objects-in-html5-localstorage

Use `editor.export()` and `editor.import()`  to save and load.

Jero

**Comment by adamburczy** [comment]
But how to save and load using editor.export() and editor.import()? Here is how im trying to do it now, and it's not working:

`
// save created node to localStorage    
editor.on('nodeCreated', function(id) {
      let new_node = document.getElementById('node-'+id);
      localStorage.setItem(random, new_node.innerHTML);
    })

// add it to the HTML code of page
window.onload = function load(){
  Object.keys(localStorage).forEach(function(key){
      document.body.innerHTML +=localStorage.getItem(key);
  })
};

`

**Comment by adamburczy** [comment]
Thanks for your reply @jerosoler ! It's working, I can get the JSON object, with nodes using editor.export() and editor.import(), but I have one more question, and I will be happy, if you could help me. Im not sure if I understand those methods. I have JSON object, and I can save it to the localStorage with storage.setItem(keyName, keyVale), but how can I add those created nodes from JSON into DOM?

**Comment by jerosoler** [comment]
Hello, @adamburczy 

With the function `editor.import("YOUR JSON");` 

It should load its nodes into the DOM.

Jero
