### ISSUE TITLE
how to draw Node shape like ladder

### ISSUE THREAD

**Issue by princeyogesh** [jerosoler/Drawflow#174]
![image](https://user-images.githubusercontent.com/29053720/118921333-9fd7a280-b955-11eb-98d7-a1c77fab19dc.png)
I want node shape like ladder , how can i achive this shape for node in this library.
.Two verticle parallel lines joined by two horizantal lines.

with this
![image](https://user-images.githubusercontent.com/29053720/118923003-8ab04300-b958-11eb-9b15-37a1e3bf1d94.png)

I am able to draw two verticle parralle lines, but
could not able to draw horizantal line with this 

Horizantal lines should be fixed , horizantal lines should be from i/o bubble of left verticle line to i/o bubble of right verticle line

**Comment by jerosoler** [comment]
Hello @princeyogesh 

Try this: https://github.com/jerosoler/Drawflow/issues/158#issuecomment-821245180

Jero
