### ISSUE TITLE
Is it possible to export a diagram to a pdf file?

### ISSUE THREAD

**Issue by OlegDynga** [jerosoler/Drawflow#177]
Perhaps by means of Canvas...

**Comment by jerosoler** [comment]
Hello! 

It is not canvas it is html.

View this library: https://github.com/MrRio/jsPDF
and View: https://github.com/jerosoler/Drawflow/issues/67#issuecomment-726790902

Jero

**Comment by OlegDynga** [comment]
Hello!

Thanks for the tip!
I will study these tools.

Oleg





пн, 24 мая 2021 г. в 21:30, Jero Soler ***@***.***>:
