### ISSUE TITLE
Is their any possibility of creating dynamic body along with number of input and output

### ISSUE THREAD

**Issue by RohithDru** [jerosoler/Drawflow#179]
1)Hi just i am using Drawflow which awesome, trying to integrate in the javascript. Now i have requirement
of creating section dynamically where dynamically assigning an input node along with the output node. 
Is their any way we can achieve it easily i mean based on the button using click even trying to get this approach.
2)Second is their any way once everything is done in js can move to angular. Does it supports the paltfom.

Will be most helpful with the inputs. Thanks in advance.

**Comment by jerosoler** [comment]
Hello @RohithDru 

For dinamyc input / ouputs view: 
https://github.com/jerosoler/Drawflow/issues/165#issuecomment-831463588

I have not worked with angular, but there are people who do.
It's vanilla javascript so it should work.
For angular view: https://github.com/jerosoler/Drawflow/issues/160 or https://github.com/jerosoler/Drawflow/search?q=angular&type=issues

Jero

**Comment by RohithDru** [comment]
> Hello @RohithDru
> 
> For dinamyc input / ouputs view:
> [#165 (comment)](https://github.com/jerosoler/Drawflow/issues/165#issuecomment-831463588)
> 
> I have not worked with angular, but there are people who do.
> It's vanilla javascript so it should work.
> For angular view: #160 or https://github.com/jerosoler/Drawflow/search?q=angular&type=issues
> 
> Jero

@jerosoler Hi just wanted to know how can we able to create  section(body) along with the input and ouput node, is their any way, as i was trying to add an button event i wanted to happen in this scenario. Is their any way it will be most helpful to me

**Comment by jerosoler** [comment]
I do not understand. What do you want?

**Comment by RohithDru** [comment]
> I do not understand. What do you want?

I Want to  know is their any way, we can assian nodes to the section(dynamically)  dynamically for the individual section input and output instead of 
editor.addNode(name, 1, 0, posx, posy, class, data, html); ? Is their any way 
Button on click even want create an body/section want to define number of inputs and outputs .....

**Comment by jerosoler** [comment]
In editor.addNode You can add the value you want.

In the body section button you can use increase o decrease numbers with https://github.com/jerosoler/Drawflow/issues/165#issuecomment-831463588
