### ISSUE TITLE
current positions and final positions

### ISSUE THREAD

**Issue by AliZaibazr** [jerosoler/Drawflow#181]
Can we get the current positions of nodes, and the final position when the move completed?

**Comment by jerosoler** [comment]
Hello @AliZaibazr 

Use [events](https://github.com/jerosoler/Drawflow#events) `nodeSelected` and `nodeMoved`
And [Methods](https://github.com/jerosoler/Drawflow#methods) `getNodeFromId` 

Jero

**Comment by AliZaibazr** [comment]
Is there any example to use these methods in vue.js 
I am using them in a way
`this.editor.on('nodeMoved', function(id){
      this.getCoords(id)
})`

getCoords in an other method in which getNodeFromId is called, but unable to call this method from event.

**Comment by jerosoler** [comment]
Use arrow functions

View https://github.com/jerosoler/Drawflow/issues/65#issuecomment-726160493

Jero

**Comment by AliZaibazr** [comment]
Thank You @jerosoler
