### ISSUE TITLE
Parallel flow detection..?

### ISSUE THREAD

**Issue by NakulVadnere** [jerosoler/Drawflow#185]
Is there any way to detect independent flow in a module? As all nodes are in same json. Or I have to go for custom algorithm to detect the independent flow ?

**Comment by jerosoler** [comment]
Hello @NakulVadnere 

The export separates the modules in this format.
```json
{
    "drawflow": {
        "Home": {
            "data": {}
        },
        "Other": {
          "data": {}
},
}
}
```
In data all nodes in module.

**Comment by Anuj-Kushwah-ak** [comment]
I want to differentiate 2 or more independent flows in same module(i.e. in module "Home").

**Comment by jerosoler** [comment]
Hello @Anuj-Kushwah-ak 

They cannot be differentiated.

But you can go through the json and get all the flow.
Since each node has its input and output connections.

But if you want to differentiate them, you can use the modules function or even create more than one editor at the same time.

**Comment by Anuj-Kushwah-ak** [comment]
@jerosoler , as you have told about module functions but in README file there is only mentioned about related to clear and get module, so i would like you to tell me more about those modules function to identify the flows.

**Comment by jerosoler** [comment]
Hello

The modules in Demo: https://jerosoler.github.io/Drawflow/
Are the tabs:
![image](https://user-images.githubusercontent.com/30957047/121854783-e8834100-ccf2-11eb-9327-17368227ca29.png)

Modules info: https://github.com/jerosoler/Drawflow#modules
