### ISSUE TITLE
 Update the data field partially

### ISSUE THREAD

**Issue by AlenaPliusnina** [jerosoler/Drawflow#186]
Can I update the data field partially? If I use updateNodeDataFromId then all content of data field is replaced.

**Comment by jerosoler** [comment]
Hello @AlenaPliusnina 

First `getNodeFromId(id)	` and get data.
Modify data field. 
and update with `updateNodeDataFromId`

Jero

**Comment by AlenaPliusnina** [comment]
@jerosoler Okay good idea, thank you:)
