### ISSUE TITLE
Rename modules

### ISSUE THREAD

**Issue by mcesaro** [jerosoler/Drawflow#189]
It would be nice to have a editor.renameModule(oldName, newName) function. Might be handy when developinf, for wxample a multi tabbed editor where tab name is modue name,

**Comment by jerosoler** [comment]
Hi @mcesaro 

I point it out to add.

While you can use:
```javascript 
editor.drawflow.drawflow["New_NAME"] = editor.drawflow.drawflow["Other"];
delete editor.drawflow.drawflow["Other"];
```

Also use if you are in the same module
```
editor.changeModule("New_NAME");
```

Jero

**Comment by mcesaro** [comment]
Hi @jerosoler, very good suggestions! 
I was already using the second method, and in some use cases the first one will work well. Thank you!
