### ISSUE TITLE
How can I set each connection names and ID

### ISSUE THREAD

**Issue by Yusufzai** [jerosoler/Drawflow#190]
If I have two or more connections in any data widget I want to define a name and ID.

**For example** 

First connection -> If the given condition is true then it will send a link.

Second connection -> If the given condition is false then it will send a Unique code.

This will help the end-user to understand the workflow.

![Screenshot_4](https://user-images.githubusercontent.com/22294055/123209588-783ca280-d4de-11eb-9270-fbc85a01547b.png)

**Comment by Yusufzai** [comment]
Something link in Twilio the condition is mentioned so anyone can understand.

![Screenshot_3](https://user-images.githubusercontent.com/22294055/123209665-90acbd00-d4de-11eb-88cb-a1d5cbfac803.png)

**Comment by jerosoler** [comment]
Hello @Yusufzai 

Maybe this can help you https://github.com/jerosoler/Drawflow/issues/18#issuecomment-666954819

It's something like this, what do you want?

Jero

**Comment by Yusufzai** [comment]
Well, I think it will better to add a parameter in the addNode function to define a single [sting] or multiple [array] names.

One more question How can add or update the number of connections using the input field

**Comment by jerosoler** [comment]
I plan to add this https://github.com/jerosoler/Drawflow/issues/45#issuecomment-701554099 ;)

**Comment by Yusufzai** [comment]
Well Sounds Good :)

**Comment by gunasekharravilla** [comment]
> If I have two or more connections in any data widget I want to define a name and ID.
> 
> **For example**
> 
> First connection -> If the given condition is true then it will send a link.
> 
> Second connection -> If the given condition is false then it will send a Unique code.
> 
> This will help the end-user to understand the workflow.
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/22294055/123209588-783ca280-d4de-11eb-9270-fbc85a01547b.png)

Hello @Yusufzai  please share the repo link for the interface which you shared in screenshot

**Comment by Yusufzai** [comment]
@gunasekharravilla  Sorry I can't its an internal corporate app.

**Comment by gunasekharravilla** [comment]
ok no problem  @Yusufzai  i developed my own design its working fine
