### ISSUE TITLE
How can add or update the number of connections using the input field

### ISSUE THREAD

**Issue by Yusufzai** [jerosoler/Drawflow#191]
I want to add or edit a number of connections using the input field

editor.addNode('split-based-on', [DynamicallyUpdate], [DynamicallyUpdate], pos_x, pos_y, 'split-based-on', { widget_name: '', variable: ''}, splitBasedOn );

**Comment by jerosoler** [comment]
Hi!

Methods: https://github.com/jerosoler/Drawflow#methods

Use methods `addNodeInput` or `addNodeOutput` for add. 

Or delete: `removeNodeInput` `removeNodeOutput`

More info: https://github.com/jerosoler/Drawflow/issues/165#issuecomment-831463588
