### ISSUE TITLE
How can I get and add my custom data inside connections query

### ISSUE THREAD

**Issue by Yusufzai** [jerosoler/Drawflow#192]
I want to add my custom data inside connections and also I want to fetch data. So is there any parameter

![Screenshot_5](https://user-images.githubusercontent.com/22294055/123437499-59790180-d5ed-11eb-934c-3bcb2667416e.png)

For Example Like 

![Screenshot_6](https://user-images.githubusercontent.com/22294055/123437727-9cd37000-d5ed-11eb-8aaa-36f6fcb825b9.png)

**Comment by jerosoler** [comment]
View to store extra data: 
https://github.com/jerosoler/Drawflow/issues/97 and https://github.com/jerosoler/Drawflow/issues/73

**Comment by Yusufzai** [comment]
Thanks for the solution it worked :)
