### ISSUE TITLE
Save data when edited on modal

### ISSUE THREAD

**Issue by Yusufzai** [jerosoler/Drawflow#197]
How can I JSON save data when I edit it on modal.

**For Example :** 

I have this -> https://prnt.sc/18xbkn5

Now I have updated my data like -> https://prnt.sc/18xbuok

and I want to save the data in my workflow

How can I save it?

**Comment by jerosoler** [comment]
Hello @Yusufzai 

Use attributes df- for save data.  https://github.com/jerosoler/Drawflow#nodes

The modal append in drawflow div. No in body. 

Or use `updateNodeDataFromId` method for update data manualy.

View in demo "DbClick!" node. 

Jero

**Comment by Yusufzai** [comment]
Thanks for the reply @jerosoler 

I think my question is not clear to you 

Let me clarify my query.

1.  I have a widget that uses the df-* attribute.
2. I entered a value in that widget. Screenshot -> 
![Screenshot_1](https://user-images.githubusercontent.com/22294055/124556945-8bdcf700-de56-11eb-824f-5e5cf2c28a28.png)

3. Now I clicked on "Show JSON data" ( A button created by me but using the same functionality as in your export button and also I have changed the modal using code mirror )
4. So the output value of exported JSON data is -> 
![Screenshot_2](https://user-images.githubusercontent.com/22294055/124556985-98614f80-de56-11eb-985a-9e718729f1fe.png)

5. Now If I edit inside the JSON data directly from the modal like ->
![Screenshot_3](https://user-images.githubusercontent.com/22294055/124557012-9e573080-de56-11eb-85f7-476f4cee27d2.png)

6. How can I save this and output it to my widget on save btn click -> 
![Screenshot_4](https://user-images.githubusercontent.com/22294055/124557030-a4e5a800-de56-11eb-8fe9-b7890dce401f.png)


Note 1 - : . I am already using df- * attribute
Note 2 - :   I am not asking about  DBclick example.

Hope this time I am clear to you :)

**Comment by jerosoler** [comment]
uhmmm. Okay. 

Use `updateNodeDataFromId`  

But I see that more than one node can be edited.
**Import** the new Json on Save for regenerate flow.

**Comment by Yusufzai** [comment]
Yes, More than one code can be edited. How can I Import the new Json on Save for regenerate flow as this is exactly I want?

**Comment by jerosoler** [comment]
Yes simple!

```javascript 
editor.import(YOUR_DATA);
```

If you use modules. Save the module name and.
To be at the same point.

```javascript
editor.changeModule('nameofmodule');
```

**Comment by Yusufzai** [comment]
The import data should be the JSON data right?

editor.import(YOUR_JSON_DATA);

**Comment by jerosoler** [comment]
Yes! 
View example: https://github.com/jerosoler/drawflow-minimap-example/blob/main/index.html

**Comment by Yusufzai** [comment]
Thanks for the help :)
