### ISSUE TITLE
Panning wont work when outside the .drawflow class

### ISSUE THREAD

**Issue by shidcordero** [jerosoler/Drawflow#199]
I've notice this issue when I'm fixing the fullscreen mode issue I reported earlier. So the issue was when I do pan outside the `.drawflow`, it wont let me. but doing it inside, it will let me do panning. I've check in the demo and it works fine. Any guess what I'm missing here?

![image](https://user-images.githubusercontent.com/26376208/124628347-f6238500-deb2-11eb-9b03-cc505b171596.png)

**Comment by jerosoler** [comment]
uhmmm try changing class "mt-1 parent-drawflow" to "parent-drawflow mt-1".

**Comment by jerosoler** [comment]
Exists a PR for bug: https://github.com/jerosoler/Drawflow/pull/141

**Comment by shidcordero** [comment]
works great. thanks.
