### ISSUE TITLE
Is it possible to disable the right click (contextmenu)

### ISSUE THREAD

**Issue by spapas** [jerosoler/Drawflow#203]
Hello, first of all thank you for this great project! 

Second, is there a way to configure drawflow to *not* display the close button on right click on a node? I just want to display the normal browser right button context menu.

Thank you very much and kind regards,
Serafeim

**Comment by jerosoler** [comment]
Hello @spapas 

Thanks! 

For view normal context menu and not display close button. 

```javascript
   editor.contextmenu = (e) => {
            editor.drag = false;
            editor.drag_point = false;
            editor.connection = false;
            editor.ele_selected = null;
            editor.editor_selected = false;
            editor.dispatch('contextmenu', e);      
          }

          editor.start();
```
Add code before start. 

View other options: https://github.com/jerosoler/Drawflow/issues/80 https://github.com/jerosoler/Drawflow/issues/47  https://github.com/jerosoler/Drawflow/issues/187

**Comment by spapas** [comment]
Thank you so much for the quick and perfect solution and the recommendations! I am greateful!

Kind regards,
Serafeim
