### ISSUE TITLE
Possible to add rerouteMoved event?

### ISSUE THREAD

**Issue by shidcordero** [jerosoler/Drawflow#204]
I'm saving all user changes inside drawflow like the list below:
```
 this.editor.on('nodeCreated', this.save)
this.editor.on('nodeRemoved', this.save)
this.editor.on('nodeMoved', this.save)
this.editor.on('connectionCreated', this.save)
this.editor.on('connectionRemoved', this.save)
this.editor.on('addReroute', this.save)
this.editor.on('removeReroute', this.save)
```

and I've notice that there's no rerouteMoved event. Is it possible to add rerouteMoved event?

**Comment by shidcordero** [comment]
I actually need it now so I'm planning to create a patch for it but I don't know how to start with, can you guide me how I can do it?

**Comment by jerosoler** [comment]
She thought the event existed.  👀

I'll add it today.

View guite to PR:
https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by jerosoler** [comment]
Added event in 0.0.45 
```javascript
  editor.on("rerouteMoved", function(id) {
      console.log("Moved reroute " + id);
    })
```

**Comment by shidcordero** [comment]
works great. thanks
