### ISSUE TITLE
Multiple updateNodeDataFromId not working?

### ISSUE THREAD

**Issue by sheksushant** [jerosoler/Drawflow#209]
I am trying to updateNodeDataFromId for data of 2 select dropdown fields in same node. 
both are marked correctly but only the last one called works. In this case the "second" will work.

Code Sample:

editor.updateNodeDataFromId(newNodeID,{"first" : "test1"}); // wont work
editor.updateNodeDataFromId(newNodeID,{"second" : "test2"}); // works fine

**Comment by jerosoler** [comment]
Hello @sheksushant 
Update node update all values. 

Try: 
editor.updateNodeDataFromId(newNodeID,{"first" : "test1","second" : "test2"}); 

Jero

**Comment by sheksushant** [comment]
Above code worked,

Thank you for the quick response.
