### ISSUE TITLE
Using in react.js

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#21]
Hi,hope you are doing well

I have another question.can i use it with react js?if yes,how?

**Comment by jerosoler** [comment]
Hi.

I have not touched react just vue.

It can be used since it is pure javascript.

Do you want to make components like in the case of VUE?

https://github.com/jerosoler/Drawflow#for-vue-example

https://github.com/jerosoler/Drawflow#register-node

In case you don't want to make components as nodes, you can use it without any problem.

**Comment by jerosoler** [comment]
Hi!  @MehbubRashid 

It would be interesting to use the React.j components just like in Vue. (I will study it)

I did a little test with react (I don't know much).

Here is the code in case it works for you:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test Drawflow React</title>
  <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css">
  <script src="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.js"></script>
 
</head>
<body>

  <div id="drawflow"></div>
  <script>
    class NodeBox extends React.Component {
      render() {
      return React.createElement('div', null,  React.createElement('input', {placeholder:'name', type:'text', 'df-name': '' }));
      }
    }


    var id = document.getElementById("drawflow");
    const editor = new Drawflow(id);
    editor.start();
            
    
    editor.addNode('NodeBox', 1, 1, 100, 150, "NodeBox", { name: ''}, 'NodeBox',false);

    editor.addNode('NodeBox', 1, 1, 300, 200, "NodeBox", { name: ''}, 'NodeBox',false);

    const domContainer = document.querySelectorAll('.NodeBox .drawflow_content_node');
    domContainer.forEach((element, i) => {
        ReactDOM.render(
        React.createElement(NodeBox, {toWhat: 'World'}, null),
        element
      );
    });
    

  </script>

<style>
  #drawflow {
    position: relative;
    width: 90vw;
    height: 800px;
    border: 1px solid red;
  }
  </style>
</body>
</html>
```

**Comment by MehbubRashid** [comment]
Hi, i was thinking about using in react js files in development mode.not in html files or browser. 

But i think it will simply work if i npm install and use import statement.

**Comment by MehbubRashid** [comment]
Hi @jerosoler i am curious about why you used export instead of module.exports?because most of the npm packages i used, uses require statement after installing the package.but you used export,so we need to import.

Any specific reason behind that?just curious

**Comment by jerosoler** [comment]
Hello

If I remember correctly. I did it to make the version mimifed and at the same time support import for npm.
