### ISSUE TITLE
Event :: moduleRemoved (Not working)

### ISSUE THREAD

**Issue by shailesh345** [jerosoler/Drawflow#211]
editor.on('moduleRemoved', function(name) {
      console.log(name);
    })

<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 47); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">List of available events:</p>

Event | Return | Description
-- | -- | --
nodeCreated | id | id of Node
nodeRemoved | id | id of Node
nodeSelected | id | id of Node
nodeUnselected | true | Unselect node
nodeMoved | id | id of Node
connectionStart | { output_id, output_class } | id of nodes and ouput selected
connectionCancel | true | Connection Cancel
connectionCreated | { output_id, input_id, output_class, input_class } | id's of nodes and ouput/input selected
connectionRemoved | { output_id, input_id, output_class, input_class } | id's of nodes and ouput/input selected
connectionSelected | { output_id, input_id, output_class, input_class } | id's of nodes and ouput/input selected
connectionUnselected | true | Unselect connection
addReroute | id | id of Node output
removeReroute | id | id of Node output
rerouteMoved | id | id of Node output
moduleCreated | name | name of Module
moduleChanged | name | name of Module
moduleRemoved | name | name of Module
click | event | Click event
clickEnd | event | Once the click changes have been made
contextmenu | event | Click second button mouse event
mouseMove | { x, y } | Position
keydown | event | Keydown event
zoom | zoom_level | Level of zoom
translate | { x, y } | Position translate editor
import | import | Finish import
export | data | Data export

<h3 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-events-example" class="anchor" aria-hidden="true" href="https://github.com/jerosoler/Drawflow#events-example" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none; float: left; line-height: 1; margin-left: -20px; padding-right: 4px;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a></h3><br class="Apple-interchange-newline">

**Comment by jerosoler** [comment]
Hello
I just tested and it works.
Complete html example.

Are you listening to the event before deleting the module?

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Drawflow</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css"
    />
    
    <script src="https://unpkg.com/drawflow@0.0.45/dist/drawflow.min.js"></script>
    <script src="minimap-drawflow.js"></script>
    <style>
      #drawflow {
        position: relative;
        width: 800px;
        height: 800px;
        border: 1px solid red;
      }
      </style>
  </head>
  <body>
    
    <div id="drawflow"></div>
    <div><div id="minimap"></div></div>
    <script>
          var id = document.getElementById("drawflow");
          const editor = new Drawflow(id);
         
          editor.start();

          editor.on('moduleRemoved', function(name) {
            alert(name);
          })
          
          editor.addModule('Other');
          editor.removeModule('Other');
    </script>
  </body>
</html>

```
