### ISSUE TITLE
Method :: updateNodeDataFromId

### ISSUE THREAD

**Issue by shailesh345** [jerosoler/Drawflow#212]
How to update HTML data of selected node?

updateNodeDataFromId | Update data element. Ex: 5, { name: 'Drawflow' }
-- | --

Example 
editor.updateNodeDataFromId(2,{ name: 'Drawflow' }); //This will update data of node but how to target html of node?

**Comment by jerosoler** [comment]
For update node html view https://github.com/jerosoler/Drawflow/issues/40
