### ISSUE TITLE
livewire modal

### ISSUE THREAD

**Issue by aptvaltechtest** [jerosoler/Drawflow#213]
Using Laravel 8 and calling a  jetstream modal erases the diagram but leaves the background wallpaper.

Not sure of the examples you need but I'm using the modal components as listed here:

https://jetstream.laravel.com/2.x/stacks/livewire.html

and touching anything livewire seems to erase the diagram.

**Comment by jerosoler** [comment]
Hello

Uhmmm...

I have not worked with laravel.

The html is being re-renders  again? Server new html?

**Comment by aptvaltechtest** [comment]
All I can really tell you is that the content is wiped as the modal opens and I'm pretty sure it's a livewire issue but after that I run out ideas....their documentation makes mention of passing through listeners and other issues but I don't know how it might relate.

**Comment by jerosoler** [comment]
if you inspect the DOM are the elements still there?

you can check before and after opening the modal.

Css change???

**Comment by aptvaltechtest** [comment]
Hmmm

It goes from:

<div id="drawflow" style="height:81vh;" class="w-full min-h-1/2 h-screen parent-drawflow" ondrop="drop(event)" ondragover="allowDrop(event)" tabindex="0"><div class="drawflow"><div class="parent-node"><div id="node-13" class="drawflow-node lgdashboard" style="top: 179px; left: 494px;"><div class="inputs"><div class="input input_1"></div><div class="input input_2"></div><div class="input input_3"></div><div class="input input_4"></div><div class="input input_5"></div></div><div class="drawflow_content_node">


to

<div id="drawflow" style="height:81vh;" class="w-full min-h-1/2 h-screen" ondrop="drop(event)" ondragover="allowDrop(event)"></div>

apart from the substantive changes I note that it crops "parent-drawflow"

**Comment by aptvaltechtest** [comment]
It goes from:

`<div id="drawflow" style="height:81vh;" class="w-full min-h-1/2 h-screen parent-drawflow" ondrop="drop(event)" ondragover="allowDrop(event)" tabindex="0"><div class="drawflow"><div class="parent-node"><div id="node-13" class="drawflow-node lgdashboard" style="top: 179px; left: 494px;"><div class="inputs"><div class="input input_1"></div><div class="input input_2"></div><div class="input input_3"></div><div class="input input_4"></div><div class="input input_5"></div></div><div class="drawflow_content_node">
`

to

`<div id="drawflow" style="height:81vh;" class="w-full min-h-1/2 h-screen" ondrop="drop(event)" ondragover="allowDrop(event)"></div>

Noting that it crops 'parent-drawflow' but I wouldn't know how to fix it.
`

**Comment by aptvaltechtest** [comment]
FIXED

simply add wire:ignore to the first div
