### ISSUE TITLE
Right panel for configuration of nodes

### ISSUE THREAD

**Issue by Matt2012** [jerosoler/Drawflow#215]
I would like to be able to configure the node in a slide out right panel. In the situation where you might want to add a lot of variables to a form connected with an input such as connecting to an API at that stage and needing URL, headers, etc. Has this been considered? Or a similar approach to needing more room for configuration.

**Comment by jerosoler** [comment]
Hello @Matt2012 

Use methods 
`getNodeFromId(id)` and `updateNodeDataFromId`

View: https://github.com/jerosoler/Drawflow/issues/197

Jero
