### ISSUE TITLE
Option to add default input and direction arrows

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#22]
Hi @jerosoler, i am proposing a new feature which may be called as "default input"

Suppose i only use one input port in all of my nodes.Since the port area is visually too small,sometimes user fails to connect with the input.This will happen a lot if there are so many nodes and hence the view is too small.Then user will have to zoom everytime and connect with the inputs.this is not a good idea

To solve this,we can define a default input option while configuring the plugin.If user drags the connection to any place of the node,it will be connected with that default input.so user has a big area to drop his connection,instead of that small input port area.This will improve the user experience a lot. trust me.

Popular flow builders like manychat also have this option.user can drop the connection on any part of the node,and it gets comnected.Since in our case, we can have multiple inputs,so we can define a default input for that operation.

Another feature request is a nice arrow at the end of the connection for presenting the flow direction.These two feature will make this plugin even powerful.

**Comment by jerosoler** [comment]
Hello @MehbubRashid 

Just comment in #20 Arrow function: 

Example: 
![image](https://user-images.githubusercontent.com/30957047/89502912-0aa05e80-d7c6-11ea-89e7-a0a74f06e68f.png)

View code in #20.

I take a look at the other.

**Comment by MehbubRashid** [comment]
Thanks..just an off-topic question.
Suppose i am developing a javascript library.how can i let users to use both import and require statement in order to use my library? 

For example,  the npm lorem-ipsum package lets users use any of these(import or require). Both of them works.

How can i achive similar thing?

**Comment by jerosoler** [comment]
Create a package with build commonjs (require) and  ES6 (import).

**Comment by MehbubRashid** [comment]
@jerosoler did not understand properly :(

**Comment by jerosoler** [comment]
It is not my strong point.
But you can watch tutorials online.
https://2ality.com/2019/10/hybrid-npm-packages.html

**Comment by MehbubRashid** [comment]
@jerosoler thanks..please kindly take a look at the other feature(default input)..
It is even more difficult on smartphones to connect with inputs.you cannot see the input port because of your finger.so having that functionality would be great

**Comment by jerosoler** [comment]
Hi! 

Added in version 0.0.20
Commit: https://github.com/jerosoler/Drawflow/commit/46a4545b89297dfa2a6c4bb9e61bc5a21af5ca88

Add in your code:
```javascript 
editor.force_first_input = true;
```
;)

**Comment by MehbubRashid** [comment]
Awesome!! Really man.thanks for your dedication!!
This library is going to be huge popular ;)
I will check on my computer and then close the issue.

**Comment by jerosoler** [comment]
@MehbubRashid Have you tried it?

**Comment by MehbubRashid** [comment]
not yet, i am staying outside of home for few days.currently dont have access to my computer..will test soon in couple of days.

**Comment by MehbubRashid** [comment]
Hi @jerosoler, i have checked that. Great job!! Now its lot more easier to make connections.

But today suddenly i noticed the demo is throwing error on console in IE11..can you check?

**Comment by jerosoler** [comment]
Perfect! Create a new issue: #24 for IE11 support. 

Close the actual issue.

**Comment by MehbubRashid** [comment]
hi @jerosoler , you should add ```editor.force_first_input = true;``` in the documentation.

**Comment by jerosoler** [comment]
In the next updated "editor options" in the docs.
