### ISSUE TITLE
Can I specify one line curvature style different from others?

### ISSUE THREAD

**Issue by Richard0323** [jerosoler/Drawflow#221]
Hi

I have modified regular line style by refacture curvature function like other post (green line)

but I need some specific line use origin curvature function (red line)

please give me some tips to do that, thanks!

![截圖 2021-06-04 下午3 47 15拷貝](https://user-images.githubusercontent.com/83625633/128475235-a6a794c0-164a-4be4-8a0a-99e763a78d0d.png)

**Comment by jerosoler** [comment]
Hi 

View: https://github.com/jerosoler/Drawflow/issues/20#issuecomment-774637314

**Comment by Richard0323** [comment]
Really appreciate!
