### ISSUE TITLE
not able to run drawflow index.html with new code changes in drawflow.js and pointing script to .js file.

### ISSUE THREAD

**Issue by sompoo** [jerosoler/Drawflow#223]
Hi , 
I am utilizing drawflow for my project purpose and I have followed the steps given in readme file. 
It works well when script sources to drawflow.min.js from githlink .
Now I tried to add few buttons and its functionality and pointed the script to drawflow,js , it gives an error as below 

![image](https://user-images.githubusercontent.com/15907328/129180356-1c975dee-cfcc-4204-a019-e2a491345082.png)

![image](https://user-images.githubusercontent.com/15907328/129180464-c53ec01e-217c-45af-b77e-8427d9732861.png)

Can you please help in this regard ?

**Comment by jerosoler** [comment]
Hi @sompoo 

How are you importing drawflow?

**Comment by sompoo** [comment]
hi  @jerosoler ,
I am importing drawflow at start of the drawflow.js thinking that when control will come on line 101 on index.html , it will have the Drawflow already imported and available.
 
![image](https://user-images.githubusercontent.com/15907328/129184771-c63bcb0b-b508-48d7-95ca-ad8e32fb624b.png)

Please suggest the correct way if this is wrong.

**Comment by sompoo** [comment]
yes I installed drawflow package before importing and followed the steps as mentioned in readme. 
If possible can we please connect over a call to quickly to check where this is going wrong?

**Comment by jerosoler** [comment]
How is the server running?
With what command?
