### ISSUE TITLE
how to convert src/drawflow.js to drawflow.min.js

### ISSUE THREAD

**Issue by gunasekharravilla** [jerosoler/Drawflow#225]
please explain how to convert drawflow.js to drawflow.min.js

**Comment by jerosoler** [comment]
Hi @gunasekharravilla 

With webpack.  Read more https://webpack.js.org/guides/production/

Run the packaje.json command ```npm run build``` https://github.com/jerosoler/Drawflow/blob/master/package.json

This command execute this script: https://github.com/jerosoler/Drawflow/blob/master/webpack.config.js

I am not an expert on webpack, but there are many tutorials on the internet.

Jero

**Comment by gunasekharravilla** [comment]
thanks @jerosoler  

if possible implement connection labeling and export to json in connections as below 
```
"connection": [
                  {
                    "node": "2",
                     "output": "input_1"
                     "label": "yes or no"

                    }
                  ]
```

**Comment by jerosoler** [comment]
Not implemented. 
View for solutions: https://github.com/jerosoler/Drawflow/issues/18
