### ISSUE TITLE
'Mouse move' in an input or a textarea element that inside a node triggers the node to move

### ISSUE THREAD

**Issue by smartsl** [jerosoler/Drawflow#227]
'Mouse move' in an input or a textarea element that inside a node triggers the node itself to move.

So there is no way to select a range of text. That should be the expected reaction.

**Comment by jerosoler** [comment]
Hi @smartsl 

Try:
```javascript
editor.draggable_inputs = false;
```

View options: 
https://github.com/jerosoler/Drawflow#editor-options

**Comment by smartsl** [comment]
Thanks very much. Didn't notice that option earlier. :P
