### ISSUE TITLE
Lock some connection Output 

### ISSUE THREAD

**Issue by MuhammadBilalIshrat** [jerosoler/Drawflow#232]
how can I lock the output node to avoid making more connections or any connection with some node and its specific port 
like ( I want to lock right top  output of some specific Node it should be unclickable and undragable)
also, how can I reverse this process when I need it.
if(true){
lock top right 1st output some Nodes
}else{
unlock  
}

**Comment by jerosoler** [comment]
Hi @MuhammadBilalIshrat 

For example adding class disabled to the output:

![Screenshot_20210828_105310](https://user-images.githubusercontent.com/30957047/131212377-1766668f-0ae9-406d-b9bb-11d690967d9c.png)

And javascript
```javascript
        editor.on("clickEnd", (e)=> {
            if(e.target.classList[0] === "output") {
                if(e.target.classList[2] === "disabled") {
                    editor.connection_ele.remove();
                }
            }
        })
```

You could count the number of node entries ...

**Comment by MuhammadBilalIshrat** [comment]
thank you so mcuh
