### ISSUE TITLE
Display delete button on link selection?

### ISSUE THREAD

**Issue by rsvidevince** [jerosoler/Drawflow#235]
I've followed the #80 to display delete buttons upon node selection (left button click), instead of right click.

Now I would like to do the same with the segment links. Is there a way to override the left click action, similar to overriding editor.contextmenu?

**Comment by rsvidevince** [comment]
My bad, it's called click, who would guess.
Thanks!

**Comment by jerosoler** [comment]
Hi! 

Yes the function is `click`

Other option using events and more simply:
```javascript
        editor.on("clickEnd", (event)=> {
            if(editor.connection_selected) {
                editor.contextmenu(event);
            }
        })
```
