### ISSUE TITLE
How to get data in a component VUE?

### ISSUE THREAD

**Issue by proyavin** [jerosoler/Drawflow#236]
```javascript
// Main.vue

const ref = this.$refs.drawflow
const newEditor = new Drawflow(ref, Vue, this)

const data = { customField: 'customFieldData' }

this.editor.registerNode('CustomNode', Component, props, options)
this.editor.addNode('nameNewModule', 0, 1, 150, 300, 'github', data, 'CustomNode', 'vue')
```

```javascript
// Component.vue

mounted () {
   // How to get `customField` param?
   // console.log(...) -> customFieldData
}
```

**Comment by jerosoler** [comment]
Hello @proyavin 

Get the id of element with:

```javascript
  const id = this.$el.parentElement.parentElement.id;
```

View example: https://github.com/jerosoler/Drawflow/issues/37#issuecomment-717822302

And use function `getNodeFromId`

**Comment by proyavin** [comment]
@jerosoler thank you!

**Comment by zynth17** [comment]
is there any way on doing this with the new composition api?

**Comment by jerosoler** [comment]
Hi @zynth17 

It's possible:
```vue
<template>
 <div ref="el">Hola</div>
</template>

<script>
import { onMounted, ref } from 'vue'

export default {
  setup() {
   
   const el = ref(null);
      
    onMounted(() => {
      console.log(el.value.parentElement.parentElement.id);
    });

    return {
      el
    }
  }
}
</script>

```


And view: 

https://github.com/jerosoler/Drawflow/issues/102#issuecomment-766333278

**Comment by lemg98** [comment]
> 
> 
> Hello @proyavin
> 
> Get the id of element with:
> 
> ```js
>   const id = this.$el.parentElement.parentElement.id;
> ```
> 
> View example: [#37 (comment)](https://github.com/jerosoler/Drawflow/issues/37#issuecomment-717822302)
> 
> And use function `getNodeFromId`

I'm getting id on this way but trough me an error when drop a new element. I did this on onMounted hook.
