### ISSUE TITLE
Drawflow keeps moving after releasing mouse outside

### ISSUE THREAD

**Issue by dollarunderscore** [jerosoler/Drawflow#237]
If you click in the drawflow container and move the mouse outside the container and then move the mouse back into the container, the container content is moved although the mouse is not clicked anymore.

To reproduce the issue:
1. go to the demo page https://jerosoler.github.io/Drawflow/
2. click in the drawflow container and move mouse to the left outside
3. release the mouse
4. move the mouse back into the container

=> container content is moving with the mouse when not clicked

**Comment by jerosoler** [comment]
Hello @dollarunderscore 

You can prevent the behavior like this:

```javascript
 editor.start();
          document.addEventListener('mousemove', function(e) {
              if(e.target.closest(".parent-drawflow") === null) {
                editor.dragEnd(e);
              }
          });
```
Even I like the normal way better. You can use this method.

**Comment by dollarunderscore** [comment]
Thanks for the answer, the dragEnd has helped me a lot. i have optimized the code a bit so that it is only executed on the "mouseleave" event. 

With jQuery (change this.drawfow to your drawflow instance):
```javascript
$("#drawflow").on("mouseleave", (event) => {
    this.drawflow.dragEnd(event.originalEvent);
});
```
