### ISSUE TITLE
contenteditable is working fine ?

### ISSUE THREAD

**Issue by gunasekharravilla** [jerosoler/Drawflow#238]
` <label   contenteditable df-answer>editable</label>`

Is Above syntax is Correct ?

if yes but its not working

**Comment by jerosoler** [comment]
Yes is correct. 

But it is recommended to put the true attribute. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable
```javascript
<label contenteditable="true" df-answer>editable</label>


```

This is a bug of previous versions.

I just uploaded the new version 0.0.49 that fixes it.

**Comment by gunasekharravilla** [comment]
Thank you for super fast response 😍
