### ISSUE TITLE
Zoom listening to mouse clientX && clientY

### ISSUE THREAD

**Issue by richardbiros** [jerosoler/Drawflow#239]
Hi, is there some option to zoom canvas to the mouse position. I can't find any option for this functionality and I think it's more user friendly to zoom where user has mouse position rather than to the middle of canvas.

**Comment by jerosoler** [comment]
Hi @richardbiros 

There is currently nothing of the sort.

I've been playing a bit and from what I see it can be achieved in two ways. The mathematical formula remains to be found.

In case you want to try.

First option listening to events.
```javascript
    let mouse_x = 0;
    let mouse_y = 0;
    editor.on('mouseMove', ({x, y}) => {
        mouse_x = x;
        mouse_y = y;
    })
    editor.on('zoom', (zoom) => {
        editor.canvas_x =  editor.canvas_x + mouse_x;  // you have to find the coordinate with the delta.
        editor.canvas_y = editor.canvas_y + mouse_y; // you have to find the coordinate with the delta.
    })
```

And other option is override the funcion  `zoom_refresh`

Jero
