### ISSUE TITLE
Lines miss-aligning

### ISSUE THREAD

**Issue by venki559** [jerosoler/Drawflow#245]
![image](https://user-images.githubusercontent.com/48545532/131970703-95c67f34-93d3-4f6e-bf42-e89079db2ac1.png)

We are facing line miss-alignment issue for a while. We haven't changed anything related to it but somehow issue came. I can't pinpoint the issue. Can you guys help me out with this

**Comment by jerosoler** [comment]
Hi @venki559 

View: https://github.com/jerosoler/Drawflow/issues/123#issuecomment-784149366

**Comment by venki559** [comment]
Hi @jerosoler , Thanks for quick reply. 

I added text-align: initial. But issue still exists. I think it might to do with styling I guess, because I having same issue with sample app which not been touched in over a year

![image](https://user-images.githubusercontent.com/48545532/131973485-60430890-ca75-4055-a44d-3475fdedcff5.png)

**Comment by jerosoler** [comment]
If you move a node, is the line positioned correctly?

The sylesheet is in header?

Use method import  to load nodes?

**Comment by venki559** [comment]
Replacing existing css file with original one fixed that issue.
