### ISSUE TITLE
Not able to Connect on input value using addConnection function

### ISSUE THREAD

**Issue by Yusufzai** [jerosoler/Drawflow#247]
https://prnt.sc/1r76pf7

**Comment by jerosoler** [comment]
In your screenshot I see that you are printing input_1 twice, can that be your problem?

If you make the manual call if your interface works for you.

Remember the values are: id_output, id_input, output_class, input_class in this order.

Ex: 15,16, 'output_1', 'input_1'

**Comment by Yusufzai** [comment]
I have already solved the issue. Just forget to close the issue but thanks for your reply :)
