### ISSUE TITLE
property sidebar for blocks

### ISSUE THREAD

**Issue by hamedf62** [jerosoler/Drawflow#25]
greeting and thank you for the great package which is unique i believe!

is there any way to have blocks property sidebar onclick to add extra conditions and rules for filtering blocks?

**Comment by jerosoler** [comment]
Hello @hamedf62 

Thank you! ;)

What sidebar are you referring to?

**Comment by jerosoler** [comment]
Are you referring to functions? 

Mehtod | Description
--- | ---
addNodeInput(id) | Add input to node. Ex id: 5
addNodeOutput(id) | Add output to node. Ex id: 5
removeNodeInput(id, input_class) | Remove input to node. Ex id: 5, input_2
removeNodeOutput(id, output_class) | Remove output to node. Ex id: 5, output_2

**Comment by hamedf62** [comment]
Your Welcome @jerosoler 
Indeed i want to draw a process of data blocks to filter and join them to prepare clear data table.
Something like complex query.

So i have to define few condtions for some blocks.
For example filter table based on a column value.

These configuration can be done in a for for every blocks in side bar (property window).

**Comment by jerosoler** [comment]
Hello

Something similar to the "DB click" node in the demo? https://jerosoler.github.io/Drawflow/

If so, you would have to create your logic to generate the sidebar.

**Comment by hamedf62** [comment]
> Hello
> 
> Something similar to the "DB click" node in the demo? https://jerosoler.github.io/Drawflow/
> 
> If so, you would have to create your logic to generate the sidebar.

Great.. let me go ahead and update.

**Comment by hamedf62** [comment]
Hi again @jerosoler 
finally i could ass sidebar for html content for nodes as we may have many field to fill by user and inside the node may not enough space available.

i made some changes in index.html and only extra definition in drawflow.main.js

so we have to seperate html content for nodes, one for node Title and one for HTML content.
for this in Addnode method added extra argument to handle HTML content.

i thought it would be good idea to consider this change in next version to increase applicability of your great package.
you may want see demo:
![image](https://user-images.githubusercontent.com/45401212/90418434-59090380-e0ca-11ea-8e7c-2f671a0e2ef2.png)
** also i added a capability to change Node showing name by user as we may have many same type node and user may want to better control the process (can send revised Index.html) if you interested.

Thank you

**Comment by jerosoler** [comment]
@hamedf62 perfect! 

It would be interesting to see the changes in a fork.

So I can see it and other users can see it.

Or you can copy here the changes made.
