### ISSUE TITLE
label:question Is it possible to put a name on the connection line? 

### ISSUE THREAD

**Issue by kennykanp** [jerosoler/Drawflow#256]
Is it possible to put a name on the connection line? 
Something like:
```
                        "input_1": {
                            "connections": [
                                {
                                    "node": "16",
                                    "input": "output_1",
                                    "name": "custom_name_here" <== is it possible?
                                }
                            ]
                        }
```

in the interface it would be something like: 
![image](https://user-images.githubusercontent.com/22874631/133576844-e8eb7b62-1043-470f-b68e-14971a6c7398.png)

**Comment by jerosoler** [comment]
Hello @kennykanp 

Not implemented.

View possible solutions: https://github.com/jerosoler/Drawflow/issues/18

I plan to implement something like https://github.com/jerosoler/Drawflow/issues/45#issuecomment-701554099. But I haven't had time.
