### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by LA1709** [jerosoler/Drawflow#259]
I am working in react with drawflow, I have created a ref to the drawflow editor. On running the method `removeNodeId` on the `editor.current`, it gives me the following error - `TypeError: Cannot read properties of undefined (reading 'data')`. 
**Note:** I can run all other methods like `getNodeId` and they work as intended.

![image](https://user-images.githubusercontent.com/44612117/134902994-980ecf2f-f7da-47a1-856c-ba6fd3f5ddc1.png)

Here it can be seen, I log the node in the console before attempting to remove it and then it throws and error when the `removeNodeId` method is called on it.

**Comment by jerosoler** [comment]
Hi @LA1709 

How are you deleting the node?

```javascript
removeNodeId(id);
```

The id is "node-id" example: "node-5"

```javascript 
removeNodeId(`node-${id}`);
```


Are you doing it the right way?

**Comment by LA1709** [comment]
No! Thank you so much! I was just passing the id (for example: 5) to the function.
