### ISSUE TITLE
node.js browserify > ParseError: Unexpected token

### ISSUE THREAD

**Issue by hamedf62** [jerosoler/Drawflow#26]
in browserify the js file to bundle below error halt the process which is belong to css.

`ow-delete{position:absolute;display:block;width:30px;height:30px;background:#000;color:#fff;z-index:4;border:2px solid #fff;line-height:30px;font-weight:700;text-align:center;border-radius:50%;font-family:monospace;cursor:pointer}.drawflow>.drawflow-delete{margin-left:-15px;margin-top:15px}.parent-node .drawflow-delete{right:-15px;top:-15px}
^
**ParseError: Unexpected token`**

the browserify command is:
**browserify dflow.js -o bundle.js**

and the dflow.js file includes:
`var Drawflow = require('drawflow')
var styleDrawflow = require('drawflow/dist/drawflow.min.css')

var id = document.getElementById("drawflow");
const editor = new Drawflow(id);
editor.start();`

**Comment by jerosoler** [comment]
Hello

Have tried with browserify-css?

**Comment by hamedf62** [comment]
> browserify-css

Hi again :)
yes browserify-css also return same error,

below command i used:
**browserify -t browserify-css dflow.js > sbundle.js**

**Comment by jerosoler** [comment]
Why not download the repository and take the files from the dist folder?

**Comment by hamedf62** [comment]
> Why not download the repository and take the files from the dist folder?

well... let me try @jerosoler

**Comment by hamedf62** [comment]
> Why not download the repository and take the files from the dist folder?

it ran perfectly nice.

actually i decided to use DrawFlow to build Visual Trading Strategy Builder in stock market.

as i already have NON-Visual strategy builder in R. 
so decided to mix it with Shiny app in R.
i hope it would be applicable.

**Comment by jerosoler** [comment]
Good luck with your project! 👍
