### ISSUE TITLE
df-data as camelCase

### ISSUE THREAD

**Issue by SilasNiewierra** [jerosoler/Drawflow#261]
Hi Jero,

I'm passing data to my nodes and synchronize them with the `df-` keyword.
but when I export the nodes, I get the data without the passed name in camelCase.
Am I doing something wrong, or is this the expected behavior? Can we get the camelCase values from the export?

Example:
```js
// adding the node
  this.editor.addNode(
        "TRIGGER",
        0,
        1,
        pos_x,
        pos_y,
        "TRIGGER",
        {
         eventName: 'new-test',
        },
        "TRIGGER",
        'vue',
      )
```

```js
// step
 <input
        class="dynamic-field"
        type="text"
        df-eventName
        placeholder=""
        :value="eventName"
      />
```

```json
// exported json
{
1:{
    class: "TRIGGER"
    data:{
      eventName: "new-test"
      eventname: "new-updated-test"
    }
    html: "TRIGGER"
    id: 1
    inputs: {}
    name: "TRIGGER"
    outputs: {output_1: {…}}
    pos_x: 211
    pos_y: 174
    typenode: "vue"
  }
}
```

**Comment by jerosoler** [comment]
Hi @SilasNiewierra 

He did not know that the browser transformed him.
I see that in the vue documentation they also comment something on this. https://vuejs.org/v2/guide/components-props.html

From what I see it is a general html thing that the attributes is lowercase once the node is rendered.

For example: 
```html
<input df-nameValue>
```

Is rendered in browser with: 
![image](https://user-images.githubusercontent.com/30957047/135215806-decc9c6f-6d34-4ecc-8e52-db3fa5b63329.png)

In this case we cannot use CamelCase.

The only thing you can do is use multiple values in format kebab-Case.

For example: 
```javascript
editor.addNode('github', 2, 2, 150, 100, 'github', { name: { value: "TESTTTTTTT4" }}, html);
```
and  html 
```html
<input df-name-value>
```

Jero

**Comment by SilasNiewierra** [comment]
Hi Jero,

thanks a lot.
That's good to know. I will use kebab-case or map the lowercase names later on.
Thanks again for the great library.

Silas
