### ISSUE TITLE
how to get node id to remove a node?

### ISSUE THREAD

**Issue by SilasNiewierra** [jerosoler/Drawflow#262]
Hi Jero,

I'm trying to delete a node, but i don't know where I can get the needed `id` from?

**Comment by jerosoler** [comment]
Hi 

For delete node is the function for node number 4. 
```javascript 
editor.removeNodeId('node-4');
```

You can use the events for example:
```javascript 
editor.on('nodeCreated', function(id) {
  console.log("Node created " + id);
})

editor.on('nodeSelected', function(id) {
  console.log("Node selected " + id);
})
```

In html is the **id** of node for example in demo the "welcome" node is "node-1". 
![image](https://user-images.githubusercontent.com/30957047/135230650-e62d07c7-52ce-473b-928a-dad215330c4f.png)

**Comment by SilasNiewierra** [comment]
My bad I just had a detailed look at your documentation and right click did the trick 👍 
Is there an option to customize the delete button, using an custom icon and maybe show it all the time not just on right click?

**Comment by jerosoler** [comment]
View: #80 or #47

**Comment by SilasNiewierra** [comment]
Thank you so much 😄

**Comment by Curious-sr** [comment]
i want all the data related to a node by giving the node id how can i get that ? is there any method for it? like updateNodeDataFromId(nodeId,nodeDataArr)

**Comment by Curious-sr** [comment]
ok i got it getNodeDataFromId(nodeId)
