### ISSUE TITLE
Is there any possibility to get sequence of connected nodes.

### ISSUE THREAD

**Issue by amikum1997** [jerosoler/Drawflow#265]
Is there any way to get drawFlowId of all nodes before the selected_node Id? I tried but with some conditions, it was going in the infinite loop please suggest any solution, if you have any idea about this let me know.

**Comment by amikum1997** [comment]
I was thinking that we can convert your lib to react lib because I don't think any other react library provides these many features that you have in this library.

**Comment by jerosoler** [comment]
Hi @amikum1997 

You can get the nodes connected to the node with the function:  `getNodeFromId(id)` and so on until the end of the flow.

I have seen that someone has already converted to react https://github.com/ImuruKevol/react-Drawflow or https://github.com/valerii15298/Drawflow-react

**Comment by amikum1997** [comment]
thanks a lot.
