### ISSUE TITLE
Editing node HTML without reloading the page

### ISSUE THREAD

**Issue by adamburczy** [jerosoler/Drawflow#268]
Every time I edit node HTML like that: 
editor.drawflow.drawflow.Home.data[id].html = "..."
I need to reload the page to see new HTML. Is there a way to edit HTML without need to reload the page?

**Comment by jerosoler** [comment]
Hi 

You only pass data to export, not in editor.

View example in https://github.com/jerosoler/Drawflow/issues/252

Other option is export data an import now.
