### ISSUE TITLE
build list of blocks from Json input

### ISSUE THREAD

**Issue by hamedf62** [jerosoler/Drawflow#27]
hi again

it's possible to build model based on json file which is fantastic.

my question: is it possible to build list of block at Left Col (class="col") based on the same Json file?

want to send list of blocks from server.

**Comment by jerosoler** [comment]
it is possible.  You just have to loop through the json.

Even though it may not be the best option, since it may be that some block is not in the json.

Better to pass a list from the server with all blocks.
