### ISSUE TITLE
Lines not showing on import data

### ISSUE THREAD

**Issue by PedroCDLoureiro** [jerosoler/Drawflow#270]
Hi @jerosoler , primally thanks for your library.

My problem happens after the import the data, only after moving the node the lines showing.

Before:
![image](https://user-images.githubusercontent.com/52416553/137189991-deb25d8e-0abf-41c1-a9e7-88a7ad29f4f8.png)

After:
![image](https://user-images.githubusercontent.com/52416553/137191448-28fef95f-7426-481f-bda9-db0098584da5.png)

I took a test with the function updateConnectionNodes, but not resolve the problem

My code: 

```
var exportdata = JSON.stringify(this.dados.flow)
    exportdata = JSON.parse(exportdata)
    this.editor.import(exportdata)
    this.editor.on('import', function() {
            this.editor.updateConnectionNodes('node-6')
            this.editor.updateConnectionNodes('node-7')
            this.editor.updateConnectionNodes('node-8')
            this.editor.updateConnectionNodes('node-9')
            this.editor.updateConnectionNodes('node-10')
  })
```

You can help me please?

**Comment by PedroCDLoureiro** [comment]
Yes, before the import

**Comment by PedroCDLoureiro** [comment]
Yes, css is correctly, loaded before import and the height of drawflow too.

The coordenates of connections are null after the import:

![image](https://user-images.githubusercontent.com/52416553/137206832-34074a29-6530-4549-aa06-bdbe4ab4e0a3.png)

**Comment by PedroCDLoureiro** [comment]
The height it's 100%, with 800px not showing too.

**Comment by PedroCDLoureiro** [comment]
Your data:

![image](https://user-images.githubusercontent.com/52416553/137309921-612c7df6-2389-4b77-94d0-53dc791f74cb.png)

My data: `{"drawflow":{"Home":{"data":{"6":{"id":6,"data":{},"html":"\n                            <div>\n                            <div class=\"title-box inicio\"><i class=\"fas fa-play\"></i> Início</div>\n                            </div>\n                            ","name":"inicio","class":"inicio","pos_x":-55.42857142857143,"pos_y":388,"inputs":{},"outputs":{"output_1":{"connections":[{"node":"7","output":"input_1"}]}},"typenode":false},"7":{"id":7,"data":{"nome_menu1":"Suporte 2","text_inferior":"Mens Inferior","text_superior":"Mens Superior","quantidade_menus":"1"},"html":"\n                            <div>\n                                <div class=\"title-box\"><i class=\"fas fa-comment-alt\"></i> Menu </div>\n                                <div class=\"box\">\n                                <p style=\"font-weight: 600;\">Tag's disponíveis: {nome} {telefone}</p>\n                                <p>Mensagem superior:</p>\n                                <textarea df-text_superior> </textarea><input type=\"text\" df-nome_menu1 placeholder=\"Nome do menu 1\"><p>Mensagem inferior:</p>\n                                <textarea df-text_inferior> </textarea>\n                                </div>\n                            </div>\n                            ","name":"multiple","class":"multiple","pos_x":145.57142857142858,"pos_y":207,"inputs":{"input_1":{"connections":[{"node":"6","input":"output_1"}]}},"outputs":{"output_1":{"connections":[{"node":"8","output":"input_1"},{"node":"9","output":"input_1"},{"node":"10","output":"input_1"}]}},"typenode":false},"8":{"id":8,"data":{"text_bot":"Msg despedida"},"html":"\n                        <div>\n                            <div class=\"title-box\"><i class=\"fas fa-robot\"></i> BOT </div>\n                            <div class=\"box\">\n                            <p style=\"font-weight: 600;\">Tag's disponíveis: {nomes} {telefone}</p>\n                            <p>Mensagem de despedida:</p>\n                            <textarea df-text_bot> </textarea>\n                            </div>\n                        </div>\n                        ","name":"bot","class":"bot","pos_x":517.5714285714286,"pos_y":26,"inputs":{"input_1":{"connections":[{"node":"7","input":"output_1"}]}},"outputs":{},"typenode":false},"9":{"id":9,"data":{"chat_usuario":"67","text_usuario":"Msg despedida"},"html":"\n                        <div>\n                            <div class=\"title-box\"><i class=\"fas fa-comments\"></i> Chat Usuário </div>\n                            <div class=\"box\">                            \n                            <div class=\"div-select\">\n                            <select df-chat_usuario><option value=\"\">Selecione o usuário</option><option value=\"67\">Giovanni Pucci</option><option value=\"265\">Sony</option><option value=\"279\">Sony 1</option></select>\n                            </div>\n                            <p style=\"font-weight: 600;\">Tag's disponíveis: {nome} {telefone}</p>\n                            <p>Mensagem de despedida:</p>\n                            <textarea df-text_usuario> </textarea>\n                            </div>\n                        </div>\n                        ","name":"chat_usuario","class":"chat_usuario","pos_x":550.5714285714286,"pos_y":280,"inputs":{"input_1":{"connections":[{"node":"7","input":"output_1"}]}},"outputs":{},"typenode":false},"10":{"id":10,"data":{"chat_setor":"","text_setor":"Msg despedida {nome}","chat_usuario":"1"},"html":"\n                        <div>\n                            <div class=\"title-box\"><i class=\"fas fa-comments\"></i> Chat Setor </div>\n                            <div class=\"box\">\n                            <div class=\"div-select\">\n                            <select df-chat_usuario><option value=\"\">Selecione o setor</option><option value=\"1\">Suporte 2</option></select>\n                            </div>\n                            <p style=\"font-weight: 600;\">Tag's disponíveis: {nome} {telefone}</p>\n                            <p>Mensagem de despedida:</p>\n                            <textarea df-text_setor> </textarea>\n                            </div>\n                        </div>\n                        ","name":"chat_setor","class":"chat_setor","pos_x":551.8571428571429,"pos_y":574.5714285714286,"inputs":{"input_1":{"connections":[{"node":"7","input":"output_1"}]}},"outputs":{},"typenode":false}}}}}`

**Comment by jerosoler** [comment]
You can delay the import of the json 250 ms.

Or change mounted with nextTick:
```javascript
  mounted() {
       this.$nextTick(() => {
         this.init()
       });
  },
```

**Comment by PedroCDLoureiro** [comment]
The problem was a Vue stepper, that's right now.

thks
