### ISSUE TITLE
Q: Navigate

### ISSUE THREAD

**Issue by wduandy** [jerosoler/Drawflow#273]
It is possible to navigate on the nodes given the output data? The purpose for this it is to create a chatbot. 

Thanks!

**Comment by jerosoler** [comment]
View example of export data in README. https://github.com/jerosoler/Drawflow/#export-example

Example of translate on the canvas: https://github.com/jerosoler/Drawflow/issues/88#issue-767398282

Not example with chatbox. 

the community has done things: https://github.com/jerosoler/Drawflow/network/dependents?package_id=UGFja2FnZS0xMTI3NDI3NjA5
