### ISSUE TITLE
¿How to work logic to drag div to drawflow?

### ISSUE THREAD

**Issue by alejandroVaron** [jerosoler/Drawflow#277]
i'm new to vue,

I was trying to make the div be dragged to the drawflow as in the example, but I can't do it

![image](https://user-images.githubusercontent.com/53543861/137888937-688b5fc2-d04a-414f-ba0c-c6a28c0589f2.png)

I was trying to do it by seeing if the mouse enters or leaves the div, but I think it is not the correct way.

Thanks.

**Comment by alejandroVaron** [comment]
These are the methods:

![image](https://user-images.githubusercontent.com/53543861/137889823-fa0f3896-8f53-4bee-9e65-c5ffaf0a8093.png)

**Comment by jerosoler** [comment]
Hi! @alejandroVaron 

I think he has the events reversed

View demo code:
```html
<div class="drag-drawflow" draggable="true" ondragstart="drag(event)" data-node="dbclick">
        <i class="fas fa-mouse"></i><span> DBClick!</span>
</div>
```

And th drawflow div:
```html
 <div id="drawflow" ondrop="drop(event)" ondragover="allowDrop(event)"> .... </div>
```

In your code you don't have the event drop in drawflow.

Check out the demo.
