### ISSUE TITLE
access output_name of pre blocks

### ISSUE THREAD

**Issue by hamedf62** [jerosoler/Drawflow#28]
dear @jerosoler, thank you again for advises which cause i progress in my project.

the new issue:
suppose a selection list of output available in block #1

then connect #1 to #2
is there any way to access the chosen name of #1 output (or even block#1 name) in block #2 as input name?
i.e : need to know what is input1 and input2 name in block #2 to do specific jobs like comparison between inputs.

![image](https://user-images.githubusercontent.com/45401212/90036367-334dba00-dcd8-11ea-99c7-c63503b4bd5d.png)

Regards

**Comment by jerosoler** [comment]
Hello 

Use events for connections created `connectionCreated` event.

View docs https://github.com/jerosoler/Drawflow#events-example

**Comment by jerosoler** [comment]
Please close issue solved

**Comment by hamedf62** [comment]
Thank you for advising.

Actually i need to access the name of output selected in first block, in second block to control the process.


Is there any procedure to get output name of any nodes?

Pardon me am new on Javascript

**Comment by jerosoler** [comment]
Hello

With conectioncreated you access: output_id, input_id, output_class, input_class.

The output_class is the number of ouput of node.

**Comment by hamedf62** [comment]
Great @jerosoler

**Comment by hamedf62** [comment]
> Hello
> 
> With conectioncreated you access: output_id, input_id, output_class, input_class.
> 
> The output_class is the number of ouput of node.

Thank you it helped.

but indeed i need the value of HTML input VALUE in second block.

for example in the attached image, if i select "AVGVOL" from first block this value passed to second block to inform user to know what condition he would apply. 
right now only the input_id passed in event.

regards

**Comment by jerosoler** [comment]
Variables are not passed automatically.

You can access the node information with: `getNodeFromId(id)`

You will have to hand pass the variable to the next node. For example:
editor.drawflow.draflow['home'].data[id].data.value = newvalue.
