### ISSUE TITLE
Hi, I am facing an issue while connecting the nodes. the connecrtion doesn't start from the centre but begins a bit below. Sharing the screenshot. Can u please help

### ISSUE THREAD

**Issue by MaleehaYasvi** [jerosoler/Drawflow#283]
<img width="429" alt="drawflow issue" src="https://user-images.githubusercontent.com/72785139/139391183-da9be285-e9a4-430d-8cd5-9b66ed299aa0.PNG">

**Comment by MaleehaYasvi** [comment]
No, its not working

**Comment by jerosoler** [comment]
Can you detail more information about your code?

Does it have a fixed high or a percentage? Can you try a fixed?

**Comment by MaleehaYasvi** [comment]
#drawflow {
  position: relative;
  text-align:fixed;
  width: calc(100vw - 301px);
  height: calc(100% - 90px);
  top: 40px;
  background: var(--background-color);
  background-size: 25px 25px;
  background-image:
   linear-gradient(to right, #f1f1f1 1px, transparent 1px),
   linear-gradient(to bottom, #f1f1f1 1px, transparent 1px);
} 
This is the css I have written

**Comment by jerosoler** [comment]
Try for discart:
```css
#drawflow {
...
width: 800px;
height:800px;
...
}
```

**Comment by MaleehaYasvi** [comment]
I tried, it is not working

**Comment by MaleehaYasvi** [comment]
Is there any other way we can do to resolve this?

**Comment by jerosoler** [comment]
Can you provide your code?

Or better yet! Create a codesanbox code?

Are you using some kind of library? Bootstrap type?  Can you remove the css from the library to discard?

**Comment by MaleehaYasvi** [comment]
I am using materialise css and doing this in vue 2

**Comment by jerosoler** [comment]
Can you provide an example of your code in codesandbox, codepen ...?

**Comment by MaleehaYasvi** [comment]
https://codepen.io/KikePuma/pen/OJXXXdb 
I am following this code

**Comment by jerosoler** [comment]
That code is working.

We need to see the code that is not working.

**Comment by MaleehaYasvi** [comment]
Its working now. I added margin in connection in css.
