### ISSUE TITLE
How to pass data between nodes?

### ISSUE THREAD

**Issue by zebek95** [jerosoler/Drawflow#285]
when i connect nodes is only for visual propose or i can pass data between nodes?

**Comment by jerosoler** [comment]
Hi @zebek95 

Is only for visual propose. 

It can be done with the **nodeDataChanged** event.

It must be taken into account that each output is not linked to an input.

All the logic would have to be generated. On the other hand, the outputs currently cannot define the type of output data.

It is not the best option in this case.

It would be something like this:
```javascript
    editor.on('nodeDataChanged', (id) => {
       /* 
        Get data node 

        Get new value of node

        Pass new value to nodes connection.
       */ 
    })
```

New connections and canceled connections should also be detected. For that we have the connectionCreated and connectionRemoved events.

I hope it helps you.

**Comment by zebek95** [comment]
@jerosoler thanks :)
