### ISSUE TITLE
Export issue in data field

### ISSUE THREAD

**Issue by hamedf62** [jerosoler/Drawflow#29]
whenever use select HTML element in any block and choose an option as selected,

when click on Export the Json result does not include any "date" field.

but when select an option manually the json rebuilds and this time include "data" field on selected item.

thank you

**Comment by jerosoler** [comment]
Hello @hamedf62 

You use correct df- attribute?

Copy text of docs: 
You can use the attribute df-* in inputs, textarea or select to synchronize with the node data.

Atrributs multiples parents support df-*-*...

View https://github.com/jerosoler/Drawflow#node-example

**Comment by jerosoler** [comment]
Hello @hamedf62 

Is it solved?

**Comment by jerosoler** [comment]
Closed due to inactivity
