### ISSUE TITLE
I am creating a component for a node in vue and using modal and tooltip inside the node but it is not working. Are these not supported by drawflow?

### ISSUE THREAD

**Issue by MaleehaYasvi** [jerosoler/Drawflow#291]

**Comment by jerosoler** [comment]
Hi

Please try to provide as much information as possible.

Vue2? Vue3?

In case it is vue 2 it is passing the parent instance with "this".
```javascript
this.editor = new Drawflow(id, Vue, this);
```
Jero

**Comment by MaleehaYasvi** [comment]
it is vue 2 and yes, i am passing this in it

**Comment by jerosoler** [comment]
Provide more information to continue.

**Comment by MaleehaYasvi** [comment]
i have created a component ABC and i am calling that in drawflow.vue by using addNode() method. In ABC, i have a button and on its click, i want a modal to open. but it is not happening in ABC neither the tooltip is working

**Comment by jerosoler** [comment]
Can you show your component?

Are you using a third party library? In this case, how are you loading it?

**Comment by MaleehaYasvi** [comment]
<template>


<a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>


  

  <div id="modal1" class="modal">

    <div class="modal-content">

      <h4>Modal Header</h4>

      <p>A bunch of text</p>

    </div>

    <div class="modal-footer">

      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>

    </div>

  </div>


<template>



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MaleehaYasvi** [comment]
It is resolved now. I added this while i register the node as well.
this.editor.registerNode('NodeClasss', NodeClass, props, options, this);

**Comment by jerosoler** [comment]
Oh perfect! 

I'm glad it worked out.

But the function only admits 4 arguments:
```javascript 
registerNode (name, html, props = null, options = null) {
...
}

```
