### ISSUE TITLE
Module parse failed: Unexpected token (1:30710) with vue2

### ISSUE THREAD

**Issue by dvillaume** [jerosoler/Drawflow#293]
Hello,

i'm having problems while testing with vue2 (with the instructions from  [#263 (comment)](https://github.com/jerosoler/Drawflow/issues/263#issuecomment-930449781)).

I receive the following message : 

`
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                          13:27:30

 error  in ./node_modules/drawflow/dist/drawflow.min.js

Module parse failed: Unexpected token (1:30710)`

I did try to figure what can happen in this but could'nt catch it. 

`        // Vue 2
        let wrapper = new this.render({
          parent: this.parent,
          render: h => h(this.noderegister[html].html, { props: this.noderegister[html].props }),
          ...this.noderegister[html].options
        }).$mount()
        // `

May you advice me about this ?

Regards,
David

**Comment by jerosoler** [comment]
Hi @dvillaume 

Are you using drawflow like this?

```javascript 
import Vue from 'vue'

....


Vue.prototype.$df = new Drawflow(id, Vue, this);

```

**Comment by dvillaume** [comment]
Hello,
Seems the error came from a badly initialzed project, everything is good with a brand new one.
Thanks very much for your time and for this super project.
