### ISSUE TITLE
Unable to connect the dynamically created Nodes using the Connector

### ISSUE THREAD

**Issue by Aravinda93** [jerosoler/Drawflow#296]
I am new to the library and trying to create a few `Nodes` dynamically and connect them using the `Connector` but for some reason, I am unable to connect the created nodes. Can you please let me know how can I connect these nodes?

I have added complete code in [Codesandbox](https://codesandbox.io/s/sweet-swanson-jm5e3?file=/pages/index.vue).

Also, why does the `Nodes` have only one `Port` for connection? Is there any option for the `Nodes` to have `Port` on all 4 sides of it? Any help with regards to this issue would be really appreciated.

Following is the issue I am facing:
![CPT2111102205-1288x856](https://user-images.githubusercontent.com/29374160/141193510-a4157c4d-0b26-4738-9044-0fb1e2a58d6b.gif)

**Comment by RuslanHimikEvchev** [comment]
You are trying to connect output to output. 
In your example, 
`this.editor.addNode(name, 0, 1, 150, 300, "github", data, html);`
second and third arguments - is num of inputs and outputs
`Drawflow.addNode (name, num_in, num_out, ele_pos_x, ele_pos_y, classoverride, data, html, typenode = false){...}`

**Comment by jerosoler** [comment]
Hi @Aravinda93 

Nodes have inputs and outputs. The outputs can only be connected to the inputs. It is a flow tool not a drawing tool.

As @RuslanHimikEvchev  comments 

You can put as many inputs and outputs as you want.
Change in your code for example:
```javascript
this.editor.addNode (name, 2, 3, 150, 300, "github", data, html);
```
If you want connectors on all 4 sides you can take a look at: https://github.com/jerosoler/Drawflow/issues/20#issuecomment-679976512

**Comment by Aravinda93** [comment]
Hello @RuslanHimikEvchev @jerosoler Thanks a lot for the response and clarification, I am understanding things more clearly now.  As I am a bit new to this visualization tool I was a bit confused.

I have two small doubts and am unable to find anything with regards to it in the doc:

1. Can we assign the `Unique ID` to `Connector`? The `Nodes` have the automatic `ID` assigned during creation but there isn't anything for `Connector` when its `Created` just the `Input/Output Node ID` with the `Port IDs`. Is there any possibility to add it during creation for `Connector`?

2. I am adding the `HTML Button and Input` fields during the creation of the `Nodes`, I would like to perform some tasks after the `Button click` but for some reason, nothing happens when I click even though I have added the method. Also, upon the click, I would like to know which `Nodes button` was clicked. Is there a way to achieve this? Should I rely on `nodeSelected` for this? Also, would like to update the text in the `Input` fields after the creation and based on user input.

I have posted the complete working code in [CodeSandbox](https://codesandbox.io/s/sweet-swanson-jm5e3?file=/pages/index.vue).

Any idea or suggestion would be really appreciated. Thanks a lot in advance.

**Comment by jerosoler** [comment]
Hi @Aravinda93 

The question one:  We cannot pass a unique id to the connections.

The question Two: Seeing as you are using nuxt - vue2, I recommend that you take a look at this example: https://github.com/jerosoler/Drawflow/issues/263#issuecomment-930449781

The example shows how to use SFC de vue as nodes. Also how to get the id of each node. What I see in codesandbox is using the html nodes.

I close the issue so as not to mix problems.
