### ISSUE TITLE
How can I update the value of the HTML Template field based on the value provided after Node creation?

### ISSUE THREAD

**Issue by Aravinda93** [jerosoler/Drawflow#297]
I am using the `DrawFlow` within my `Vuejs/Nuxtjs` application to create dynamic `Nodes`. Each of the created `Node` will have an `HTML Button` and `Input text` fields. Upon clicking on the `HTML Button` a `Bootstrap Modal` will be displayed to provide the values. The provided values are stored within the `Vuex Store`. Now I want each of `Node` to get the values provided to these `Modal` and display it within the `Input Text` field created against each `Node`.

I followed various issues and comments in this library to understand and progress so far but was unable to update the `Input text` field for each node based on the value provided for the `Bootstrap Modal`.

I have added a complete code sample in [Codesandbox](https://codesandbox.io/s/fervent-hellman-pnk43?file=/pages/index.vue) for your reference.

Steps to follow:
1. Click on the `Add Node` button, a `Node` with `HTML Button` and `Input Text` field will be displayed. 
2. Click on the `Event Info` button in `Node`, A modal will be displayed.
3. Provide some value to the `Event Type` field in the modal and submit the information, the information is stored within the `Vuex Store`.
4. Now I would like to update the `Input Text` field within my created `Drawflow Node` with the value provided in the `Modal`.

I am unable to do this, is there any method/function that I can make use of to update the values? Please help

**Comment by jerosoler** [comment]
Hi @Aravinda93 

Watching the codesandbox demo. I see that you are not using the **df-** values of Drawflow.
The df- is for export data. 

So the problem is its logic.
I also don't see that in your input you have a v-model to update-it.
```javascript 
<input type="text" placeholder="Event Type" disabled size="15" />
```

In drawflow we have a function **updateNodeDataFromId(id, {....})** to update the df-values.

Perhaps a demo with vue3 will serve as an example:
REPO: https://github.com/jerosoler/drawflow-vue3-example
DEMO: https://jerosoler.github.io/drawflow-vue3-example/

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for your response and links. I was able to make it to work up until a certain point. But I am unable to understand how to update the values of the `Input Text` field. I could not find any example of `updateNodeDataFromId`. Can you please let me know how can I update the values of the `Input Text` field in the `Node`?

I have updated my code in [CodeSandbox](https://codesandbox.io/s/fervent-hellman-pnk43?file=/pages/index.vue).

**Comment by jerosoler** [comment]
When to save the modal. The information obtained is:
```javascript
{
        "name": "Node : 1",
        "eventType": "bbbbbbb"
    },
```
It should do this:
```javascript
editor.updateNodeDataFromId(1,{
        "name": "Node : 1",
        "eventType": "bbbbbbb"
    })
```



 


For example in demo: https://jerosoler.github.io/Drawflow/
![image](https://user-images.githubusercontent.com/30957047/141492495-f2c7f803-011f-4a3f-9873-bd158d98b263.png)

add code to the console:
```javascript 
editor.updateNodeDataFromId(6, {"name": "TESTTT"});
```
And the result:
![image](https://user-images.githubusercontent.com/30957047/141492618-6d6e5c80-1684-4d26-b4a5-1d8951cf887d.png)


Jero

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for your response.
I added the `Watch` in the `Vue component of the Drawflow` and updated it whenever a new value has been added to `Node`
