### ISSUE TITLE
I want to have a confirmtaion before deleting a connection. i have used editor.removeConnection = function() {} method, and whenever i click on delete, this gets triggered. What should i write in my confirm message inorder to delete the connection

### ISSUE THREAD

**Issue by MaleehaYasvi** [jerosoler/Drawflow#298]

**Comment by MaleehaYasvi** [comment]
_this.editor.removeConnection = function(id) {
		const res = confirm('are u sure u want to delete');
			if(res == true){
//which method should i use
			}
}

**Comment by MaleehaYasvi** [comment]
using _this.editor.dispatch('connectionRemoved');
it goes into this event, but connection is still visible in the UI

**Comment by jerosoler** [comment]
View: https://github.com/jerosoler/Drawflow/issues/240

Closed for duplicate.
