### ISSUE TITLE
add method to redraw connection

### ISSUE THREAD

**Issue by taroongunessee** [jerosoler/Drawflow#3]
I'm calling the import method, but the connection lines are not appearing for some reason.   If I move the nodes slightly then the connections appear.  

Can we have a method to redraw the connection lines?

**Comment by jerosoler** [comment]
Hello

Try
```javascript
const editor = new Drawflow(id);
...
const key = 3;
editor.updateConnectionNodes('node-'+key);
```

This method is used for load.
Example load:
```javascript
for (var key in this.drawflow.drawflow[this.module].data) {
   this.updateConnectionNodes ('node -' + key);
}
```

**Comment by taroongunessee** [comment]
This is perfect, it works, thanks again.  The plugin is awesome.

**Comment by jerosoler** [comment]
Perfect! Thanks! 😍

If you like it, mark it with a star.
