### ISSUE TITLE
How can modify connection double click functionality

### ISSUE THREAD

**Issue by Yusufzai** [jerosoler/Drawflow#300]
Hello Jero,

I have modified the SVG connection previously ( Previous issue link - https://github.com/jerosoler/Drawflow/issues/255#issuecomment-920677512 ) with your help but I got an issue when I try to double click on the connection lines.  

I want to know how can I fix this SVG issue when the user double clicks on SVG -> https://prnt.sc/1zn2vw1

Below is the screenshot of the issue

https://prnt.sc/1zn3fsu

**Comment by jerosoler** [comment]
Hi @Yusufzai 

The link imatge not work:
https://prnt.sc/1zn3fsu

You can attach the image here.

**Comment by Yusufzai** [comment]
Below is the updated Image link 

![download](https://user-images.githubusercontent.com/22294055/141781307-34ed6bce-df00-408c-a177-b4ff172b7e8a.png)

**Comment by jerosoler** [comment]
There are 4 types of connections:
"Open", "Close" "Other" and "openclose".

In that case, only the default was modified: "openclose".

It would have to modify the others in the same way, which are the ones in charge of building the "reroute".

Open: From the ouput node to the first point.
Close: From the last point to the input node.
Other: From one point to another point. (In the middle)

You can also disable reroute.
```javascript
editor.reroute = false;
```
