### ISSUE TITLE
can't access vuex in a registered vue component

### ISSUE THREAD

**Issue by AnoOnion** [jerosoler/Drawflow#302]
i want to access the getters function in the component that i have registered, but i get an error like :

![error](https://user-images.githubusercontent.com/47703876/141979589-a58b4b26-a938-48b3-8828-eb4307dca02f.png)

do you have a solution? thanks

**Comment by jerosoler** [comment]
How are you mounting drawflow?

And the node?

**Comment by AnoOnion** [comment]
onMounted(() => {
                         let layout      = document.getElementById('tracking-flow')
                         let editor      = new Drawflow(layout, vue)
                         
                         editor.value    = new Drawflow(layout, vue, instance.appContext.app._context)
                         editor.reroute  = true
          
                         editor.start()
          
                         editor.registerNode('branchnode', BranchNode)

                         editor.addNode('main-address', 0, 1, 0, 190, 'branch-node', { 'data': 'test' }, 'branchnode', 'vue')
               })

is it correct to use dragflow ?
i use vue 3

**Comment by jerosoler** [comment]
I understand that vuex is added to the instance.

You can see an example of vue3
https://github.com/jerosoler/drawflow-vue3-example

View app component:
https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/drawflow.vue

And  Node component:
https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/nodes/node1.vue

Gettin the instance: 
```javascript
df = getCurrentInstance().appContext.config.globalProperties.$df.value;
```

**Comment by AnoOnion** [comment]
wow, it worked 💯 

ooh, one more thing, when I create a node with a height of 100px and when that node is selected then the height will change to 200px

but the connection position does not adjust, how so that when the height of the selected node changes, the connection position adjusts accordingly?

thanks for seeing this before

**Comment by jerosoler** [comment]
Force update connections with:
```javascript 
updateConnectionNodes('node-'+id);
```

**Comment by AnoOnion** [comment]
Thank you very much, i will try it tomorrow 👍
