### ISSUE TITLE
Is there a way to draw the Nodes within Drawflow canvas based on user preferred size and position?

### ISSUE THREAD

**Issue by Aravinda93** [jerosoler/Drawflow#305]
I am using the `Drawflow` within my `Vuejs/Nuxtjs` application and creating `Nodes` dynamically upon clicking on the `Add Node` button. During the addition of the `Node` within `addNode` method, I am passing the `posx` and `posy` due to which `Node` is always added to the same place in `Drawflow Canvas` and I have to drag it to the different place based on my wish. 

Is there any way for me to add it to the place I would like directly rather than adding it to the same `posx` and `posy`? Also, set the size (height and width) of the `Node` dynamically? Something like the `Drag-and-drop` with `Draw` approach after clicking on the `Add Node` button? 

I have added my code sample in [CodeSandbox](https://codesandbox.io/s/exciting-andras-uv1x3?file=/pages/index.vue).

I am really looking forward to some suggestions or work-around. I looking for some suggestions that would look something like this:
![CPT2111181107-1920x930](https://user-images.githubusercontent.com/29374160/142395286-b02c6666-cf14-4a8d-b379-201c7305ef1e.gif)

**Comment by jerosoler** [comment]
To add a node in the position look at you:

Vue3 Example
Repo: https://github.com/jerosoler/drawflow-vue3-example
Demo: https://jerosoler.github.io/drawflow-vue3-example/

Or with vanilla javascript:
Demo: https://jerosoler.github.io/Drawflow/
Repo: https://github.com/jerosoler/Drawflow/blob/master/docs/index.html

You have to use the drag methods (ondragstart, ondragover).

The issue of resizing a node is already more complicated. You will have to use some external library.

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for the links and example. I have been trying to achieve the same using the example mentioned [here](https://github.com/jerosoler/drawflow-vue3-example/blob/3a26f275907dc99121ed52a88bc72671f8293ba7/src/components/drawflow.vue). However, I am running into a few errors and unable to make it work.

I have posted my code in [CodeSandBox](https://codesandbox.io/s/exciting-andras-uv1x3?file=/pages/index.vue) for your reference.

I am getting the error within the `drag(event)` function and the error are due to the following line:
```

this.mobile_item_selec = event.target.closest('.drag-drawflow').getAttribute('data-node')
```

`event.target` has the `li` element and I am trying to read the `closest` on it and its throwing the error:
```
client.js:215 TypeError: Cannot read properties of null (reading 'getAttribute')
    at VueComponent.drag (index.js?!./node_modules/vue-loader/lib/index.js?!./pages/Test.vue?vue&type=script&lang=js&:102)
    at dragstart (templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./pages/Test.vue?vue&type=template&id=cde3d4aa&scoped=true&:32)
    at invokeWithErrorHandling (vue.runtime.esm.js:1862)
    at HTMLLIElement.invoker (vue.runtime.esm.js:2187)
    at HTMLLIElement.original._wrapper (vue.runtime.esm.js:6951)
```

Can you please suggest how to achieve the `drag-and-drop` function to draw the nodes whenever I want?

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for your response and example. 

I am trying to follow the [mentioned code](https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/drawflow.vue) and implement it similar within my application. 

I have a few doubts with regards to this code:
1. I am not understanding what is this significance of the parameter `mobile_last_move` and where is the value populated to it. Because if I remove the `if block` and keep only else then it's working within your sample code.

2. I am trying to follow the same logic and it's not working for me. I have added the code in [CodeSandbox](https://codesandbox.io/s/exciting-andras-uv1x3?file=/pages/index.vue)

Can you please help me out with this issue?

**Comment by jerosoler** [comment]
Fix! Is for support drag with mobile. 

View changes: https://github.com/jerosoler/drawflow-vue3-example/commit/dbd08ca8156a4aae7a8c5d4f9fe5f29a0f5b0a58

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for the response and correction. Since I am developing only for the desktop I have removed that part and made it work for the desktop.

I am trying to develop an application similar to what you have developed [here](https://jerosoler.github.io/drawflow-vue3-example/). I observe that you have used `element-plus` which works only with the `Vue 3 version`. Since I am using the `Nuxtjs` which is based on the `Vue 2 version` I am unable to use it. So the look and feel of my application are not as cool as yours.

Can you please let me know what alternative I can use to make my application look cool like yours? I tried the `CSS` styling but for some reason I am unable to make it look as similar as yours. I have posted my code on [CodeSandbox](https://codesandbox.io/s/exciting-andras-uv1x3?file=/pages/index.vue).

@jerosoler If you get a chance can you please have a look at my [code](https://codesandbox.io/s/exciting-andras-uv1x3?file=/pages/index.vue) and suggest me something so I can develop an application somewhat similar to [yours](https://jerosoler.github.io/drawflow-vue3-example/).

**Comment by jerosoler** [comment]
Element ui for vue2 https://element.eleme.io/#/en-US

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for providing the `Vue2 Element-ui`. I included it within my code and modified your `node1.vue` and `nodeHeader.vue` so I can adapt them within my `Vuejs/Nuxtjs` application. But still, for some reason, it does not appear the same.

As of now, I am trying to include only 1 node `node1`, and trying to make sure it would look as in your [sample](https://jerosoler.github.io/drawflow-vue3-example/). I have added the complete code sample similar to your code in [Codesandbox](https://codesandbox.io/s/blissful-wozniak-6voii?file=/pages/index.vue:3678-3715).

Can you please let me know what should I do within my `Nuxtjs` to ensure my front-end looks similar to yours?

Your code: https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/drawflow.vue
Your frontend: https://jerosoler.github.io/drawflow-vue3-example/
My code and frontend: https://codesandbox.io/s/blissful-wozniak-6voii?file=/pages/index.vue

**Comment by jerosoler** [comment]
The style css is only in files: 
https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/assets/style.css
https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/App.vue
https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/drawflow.vue

**Comment by jerosoler** [comment]
Try change this lines:

```css
@import "~/assets/css/drawflow.css";
@import "drawflow/dist/drawflow.min.css";
```

to 
```css
@import "drawflow/dist/drawflow.min.css";
@import "~/assets/css/drawflow.css";
```


And add css of the library theme: https://element.eleme.io/#/es/component/quickstart
```
import 'element-ui/lib/theme-chalk/index.css';
```

**Comment by jerosoler** [comment]
I just saw that the corresponding css was not being applied.
