### ISSUE TITLE
events execute N number of times when N is the size of nodes in the module, and data is overwritten in all components 

### ISSUE THREAD

**Issue by Siumauricio** [jerosoler/Drawflow#307]
###For example I have nodeA which have a property called name, when the node is created I want to assign a different name, but
for example, I add again the same component nodeA, the events run every N quantities, where N is the length of nodes that I have
in all container so if I have 3 nodesA the events will run 6 times. this happens in vue3
onMounted( () => {
 editor.on('nodeCreated',(idNode)=>{
console.log('Invocation Method NodeCreated, Node Id: ',idNode)
})
}):

![image](https://user-images.githubusercontent.com/47042324/142553945-e1a49896-26d5-4755-beec-bed8d9d6bb81.png)

**Comment by jerosoler** [comment]
Where are you putting that code?

It should be where it is `<div id ="drawflow"></div> `.

I would say that you are putting the code in a node.

**Comment by Siumauricio** [comment]
No I'm just using 

`               <div class="border" id="drawflow" @drop="drop($event)" @dragover="allowDrop($event)"></div>
`
but the question that I have is, the events just should be invoked after where editor makes editor.start()?
because I invoked the events in each node and the events gets duplicate, and when the event gets invoked they run all the duplicate events, so the data gets overwritting.

**Comment by jerosoler** [comment]
Yes! After editor.start()!

If you invoke the events on each node, they will be repeated, as you have subscribed more than once.

View demo with vue 3:
Repo: https://github.com/jerosoler/drawflow-vue3-example
Demo: https://jerosoler.github.io/drawflow-vue3-example/

**Comment by Siumauricio** [comment]
Ok but how I will pass data from 1 component to another and get renderized ?

**Comment by jerosoler** [comment]
What kind of data do you want to pass between components?
By components do you mean nodes? The library is not realtime, passing data from one node to another.
