### ISSUE TITLE
nodeMoved event is not being emitted

### ISSUE THREAD

**Issue by JDanP** [jerosoler/Drawflow#309]
Hi!

I am using the event `nodeMoved` to execute some code. The problem is that the event is not being emitted in a particular unfortunate situation:
While moving a node (left click button pressed), move the cursor out of the editor, release the left click button, comes back to editor to drop the node and click to drop it: the event is not emitted. It seems nothing, but sadly I have very important code that relies on this event and in my app it is very easy to get to this issue. Do you have any idea how to solve it or to force to emit this event somehow? 

Evidence with console.log() in https://jerosoler.github.io/Drawflow/:

Feature:
![image](https://user-images.githubusercontent.com/43183212/143366758-763e1511-4399-4302-bfd8-ce9452b8a8b5.png)

Issue:
![image](https://user-images.githubusercontent.com/43183212/143367985-a8c443df-5be4-4fdf-b46d-900b9cff3a9d.png)

Thanks in advance!

**Comment by jerosoler** [comment]
Hi @JDanP 

You can solve the problem with:

```javascript
editor.on('click', (e) => {
      if(editor.drag) {
        editor.dispatch('nodeMoved', editor.ele_selected.id.slice(5));
      }
})
```

Jero

**Comment by JDanP** [comment]
It worked perfectly! Thanks a lot!
