### ISSUE TITLE
About node shapes

### ISSUE THREAD

**Issue by mcesaro** [jerosoler/Drawflow#310]
Hi Jero,
I'd like to include different node shapes in my flows. The ideal would be able to use a limited flow chart-like range (like circles or rhombus) but rectangular would be good, maybe using internally a row or grid layout.
Can you please give us a quick rundown on the CSS hierarchy to use to achieve, if possible, this result?

Thank you,
Massimo

**Comment by jerosoler** [comment]
Hi

View  example of romb:
https://github.com/jerosoler/Drawflow/issues/20#issuecomment-679976512

Jero

**Comment by mcesaro** [comment]
I see,
actually I had something like this in mind:
![dfrect](https://user-images.githubusercontent.com/6418086/143402533-8cac4bbe-8ce6-4c37-b3ad-0aae405cbcf3.png)
where the elements A and B and their input elements (text or select) are in the same row.
I thought that changing the `display: flex` and `flex-direction` in the internal `box` class would be enough (I'm referring to the `beautiful.css` style;sheet in the demo), but they inherit from upper classes that makes the result quite messy.
That's why I was wondering if there is a CSS way to customize the shape, at least in the content layout.
Thank you for your support.

**Comment by jerosoler** [comment]
In the demo with beautiful.css

![image](https://user-images.githubusercontent.com/30957047/143405567-972d426f-88e3-4fd6-a664-5b5e067774f3.png)


Modify in css
```css
.drawflow-node .box {
display: flex;
}
```
And the result 

![image](https://user-images.githubusercontent.com/30957047/143405694-f559a016-7df2-4809-896f-212af7fdcebd.png)

You can also directly modify the source css, which is just this:
https://github.com/jerosoler/Drawflow/blob/master/src/drawflow.css

**Comment by mcesaro** [comment]
Thank you!
