### ISSUE TITLE
Add import button and export to file

### ISSUE THREAD

**Issue by ArFe** [jerosoler/Drawflow#313]
Hi @jerosoler,

I have these functions (import button and export to file) ready for my own use and could add to your lib, if you'd like to.

If so, which index.html should I change? Drawflow/index.html or Drawflow/docs/index.html?
Further, the former does not run straight from there, need to change this:
```<script src="dist/drawflow.min.js"></script>```
Not sure if it's on purpose or not. 

Please let me know, thanks.

**Comment by TomHermsen** [comment]
@ArFe Import and export is already available, see https://github.com/jerosoler/Drawflow#export--import

**Comment by ArFe** [comment]
> @ArFe Import and export is already available, see https://github.com/jerosoler/Drawflow#export--import

Hi @TomHermsen, I meant buttons on the demo, not the functions on Drawflow, which I know exists as I'm using them.
The export **button** today only displays the JSON, and do not export to file as I'm proposing.
As well as there's not import **button**, to import the file you just exported.
This is just to help people get started, not something related to the lib itself.

**Comment by jerosoler** [comment]
Hi @ArFe 

Thanks! 

I don't want to complicate the demo any more. There are many users who get lost.

But if you want you can add here the code to export to file.
And we add the label "Tricks". With tricks that the community develops.
