### ISSUE TITLE
Whaticket Integration

### ISSUE THREAD

**Issue by pgdigital** [jerosoler/Drawflow#315]
Hi friends, any help?

How can I integrate that in Whaticket?

Thanks a lot

**Comment by pgdigital** [comment]
Hi @jerosoler , tks for reply.

Here you have: https://github.com/canove/whaticket

**Comment by jerosoler** [comment]
The best thing would be to talk to @canove and have him do the integration. Open issue in project. 

I see that it is an application with react.

You can see an example of react https://github.com/jerosoler/Drawflow/issues/21#issuecomment-668255935

Or if someone from the community is interested in integrating it.

They also have the demo available to see how to integrate it.
https://github.com/jerosoler/Drawflow/blob/master/docs/index.html
