### ISSUE TITLE
Importing drawflow theme css breaks my appearance

### ISSUE THREAD

**Issue by MSoup** [jerosoler/Drawflow#319]
Sorry I wasn't sure where to post this question, I know it's not directly related to Drawflow...

This is what I designed:
![image](https://user-images.githubusercontent.com/19704779/145361250-82440621-a201-413c-8b36-6887f52933f1.png)

When I press export and copy the CSS, and reference it in App.vue like this

```js
<style>
    @import './assets/styles/newStyle.css';
</style>
```

It breaks my setup. Here is what my browser looks like

![image](https://user-images.githubusercontent.com/19704779/145361458-0dc0d584-1bc7-4765-8556-696196564ce4.png)

Do I need to do anything special for importing a theme?

**Comment by jerosoler** [comment]
You also have to import the minimal theme drawflow.min.css.

The theme does not replace the min file, it overwrites it.

If you don't have it added, try putting the style in head.

**Comment by MSoup** [comment]
Oh I see. Thank you so much! I didn't realize that I needed to import the theme alongside drawflow.min.css
