### ISSUE TITLE
Use custom directives whit Drawflow

### ISSUE THREAD

**Issue by dhanos23** [jerosoler/Drawflow#324]
Hi

I tried to use a custom directive in a node of Drawflow, I used vue 3 and composition api.
I used the official documentation of vue, but, when I tried to put the directive in the node I had an error:

`TypeError: Cannot read properties of undefined (reading 'deep')
    at withDirectives (app.js:10003)
    at app.js:26790
    at renderFnWithContext (app.js:7410)
    at renderSlot (app.js:12818)
    at Proxy.render (app.js:24862)
    at renderComponentRoot (app.js:7453)
    at ReactiveEffect.componentUpdateFn [as fn] (app.js:11200)
    at ReactiveEffect.run (app.js:5829)
    at setupRenderEffect (app.js:11326)
    at mountComponent (app.js:11109)`
    
   This is the directive example that I used
   
   `app.directive('highlight', {
  updated() {
    console.log('hola');
  },
});`

and my node is 
<template>
  <div>
    <textarea v-highlight/>
  </div>
</template>

Do you have some kind of example to use custom directives in nodes?

thank you

**Comment by jerosoler** [comment]
Hi! 

View example of vue3
https://jerosoler.github.io/drawflow-vue3-example/
Repo: https://github.com/jerosoler/drawflow-vue3-example

I think the problem may come from the instance.

View pass instance a drawflow https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/drawflow.vue
And get the instance on node: https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/nodes/node2.vue

Can this help you?

**Comment by dhanos23** [comment]
Hi 
This example solved all of my issues I had; the problem laid on the way that I had the instance setup.
thanks!
