### ISSUE TITLE
Making straight lines without curvature

### ISSUE THREAD

**Issue by olutmatkaijian** [jerosoler/Drawflow#325]
Hey,

great project! However, I'd like to be able to create straight lines by adding points through a series of clicks - and hiding these points if the View is not in edit mode.
So to clarify: I click on an output node, then click on a canvas. It creates a straight line between node and canvas, and creates a reroute point where I clicked on the canvas. I then click again, and it creates another reroute point, until I click on a node. At this point it finishes the connection. That way, I'd be able to make for example process schematics. 
Is there a way to do it? I cannot figure it out.

Thanks for your great work!

**Comment by jerosoler** [comment]
Hi @olutmatkaijian 

Exist possibility:
![image](https://user-images.githubusercontent.com/30957047/146508638-0e82dd66-2beb-41c7-88e2-583b1f4cc91f.png)

```javascript
    editor.reroute = true;
    editor.reroute_fix_curvature = true;
    editor.curvature = 0.1;
    editor.reroute_curvature = 0.1;
    editor.start();
```

What works differently.
First create a line and then you can create points by double clicking on the line.

Jero

**Comment by olutmatkaijian** [comment]
Awesome, thanks. It's not exactly what I wanted, but it is good enough :)
