### ISSUE TITLE
Connection lines are offset from nodes

### ISSUE THREAD

**Issue by tyzjames** [jerosoler/Drawflow#327]
Hi! Thanks for this library.

I'm trying to use this library in my angular project, but have hit a roadblock and I can't find the code that is causing this. The connection lines are offset in my graph. I can click on a connection point in the node and drag but the lines are all offset. Do you have an idea on which part of the code is causing this?
<img width="1189" alt="Screen Shot 2021-12-17 at 11 20 19 PM" src="https://user-images.githubusercontent.com/6988852/146567128-c4bd3460-e58c-4f04-9e12-313f3cd20b5d.png">

**Comment by jerosoler** [comment]
Hi! 

Thanks!!

View: https://github.com/jerosoler/Drawflow/issues/208 and  https://github.com/jerosoler/Drawflow/issues/123 and https://github.com/jerosoler/Drawflow/issues/34#issuecomment-779690035 and https://github.com/jerosoler/Drawflow/issues/37#issuecomment-716220711

**Comment by tyzjames** [comment]
Thanks for the links! I can confirm that this works:

```
#drawflow {
  text-align:initial;
  position: relative;
  width: 100%;
  height: 800px;
  border: 1px solid red;
}
```
