### ISSUE TITLE
Zoom pre-set and flow import

### ISSUE THREAD

**Issue by mcesaro** [jerosoler/Drawflow#329]
Hi,
I tried to preset the zoom level at draflow initialization using something like
```javascript
editor.zoom = 0.8;
```
because when loading flows I'd like to make them a little smaller than the default zoom level.
What happens is that the setting seem ignored and the first connections redraw looks like it is the only part reduced. If I move on the canvas, then the zoom set comes in to effect, but the connections are still not correct:

![Screenshot from 2021-12-20 14-42-57](https://user-images.githubusercontent.com/6418086/146777430-a347104d-0d29-4855-b73d-9f63be1dfe28.png)

Moreover, when switching modules it seems that the zoom setting is ignored altogether or reset to 1.
Is it possible to have a persistent, per session, zoom level applied to all the modules?

Thank,
Massimo

**Comment by jerosoler** [comment]
Hi @mcesaro 

On load 
```javascript
 editor.start();
    editor.zoom = 0.8;
    editor.zoom_refresh();
    editor.import(dataToImport);
```

Onchange module:
```javascript
editor.changeModule('Home'); 
editor.zoom = 0.8;
editor.zoom_refresh();
```

Jero

**Comment by mcesaro** [comment]
Hi Jero,
your suggestion works great!
Thanks
