### ISSUE TITLE
Test in vue 3 with $df

### ISSUE THREAD

**Issue by dhanos23** [jerosoler/Drawflow#331]
Hi

I used your example to how use drawflow with vue 3 (https://github.com/jerosoler/drawflow-vue3-example) and everithing its ok, but when I tried to test my components with vue-test-utils I had this problem
![image](https://user-images.githubusercontent.com/7193018/147048949-2c1845e2-36fa-40b4-9c62-771f9d89a2af.png)

Do you have any example to how needs to do the test?

thanks

**Comment by jerosoler** [comment]
Hello,

I can't help you with the tests. Little I have tested.
Maybe this can help you:
https://github.com/vuejs/vue-test-utils/issues/1655


But in any case that variable refers to:
```javascript
editor.value = new Drawflow(id, Vue, internalInstance.appContext.app._context);
```

Jero
