### ISSUE TITLE
output_2 converted to output_1 if no output_1

### ISSUE THREAD

**Issue by dearsina** [jerosoler/Drawflow#332]
First off, I just want to say thank you for creating a wonderful library. Now to the bug (or is it a feature?) that I think I found.

If you have assigned an output_2, but no output_1 to a node, the script converts the output_2 to an output_1.
The same doesn't apply to input_2s where there is no input_1. There, the input_2 remains input_2.

Have a [look](https://jsfiddle.net/f7epbryL/1/).

I'm I missing something? Is it supposed to behave like this? Can I keep output_2 as output_2 without an output_1?

**Comment by jerosoler** [comment]
Hi @dearsina 

You are importing the wrong content.

The nodes would have to be added using "addNode".

The outputs or inputs have to be relative: (Ex: output_1, output_2, ...)

Even the removeNodeInput and removeNodeOutput functions rearrange the outputs_

What you are trying to do cannot by default.

**Comment by dearsina** [comment]
I'm not sure if I follow. Are you saying I shouldn't use the `editor.import()` function? This is the key snippet from the JSfiddle. I have assigned both an input_2 and an output_2, but no input_1 and output_1. Only the output_2 is converted to output_1, the input_2 remains as is.

```
      var dataToImport = {

        "drawflow": {
          "Home": {
            "data": {
              
              "93c27a9c-8f5e-4b61-8330-35afe47cc4b7": {
                "html": "This node has an input_2 and an output_2. input_2 is treated as input_2, but output_2 is converted to output_1 somewhere.",
                "class": "timer",
                "id": "93c27a9c-8f5e-4b61-8330-35afe47cc4b7",
                "name": "93c08768-489d-4a0f-ae20-565540ccc9d2",
                "pos_x": "10",
                "pos_y": "10",
                "typenode": false,
                "data": [],
                "inputs": {
                  "input_2": {
                    "connections": []
                  }
                },
                "outputs": {
                  "output_2": {
                    "connections": []
                  }
                }
              },
            }
          }
        }
      }

      editor.start();
      editor.import(dataToImport);
```

**Comment by jerosoler** [comment]
If you can use "editor.import". But you should run it after you've done an "editor.export" first.

Now you are modifying the json manually and not generated by drawflow.

The inputs and outputs are assigned in drawflow continuously. There can be no jumps.

**Comment by dearsina** [comment]
Ok, good to know. I do a lot of that. 😃
