### ISSUE TITLE
The Vue3 unMounted event will not be triggered when using removeNodeId and clear

### ISSUE THREAD

**Issue by rni-l** [jerosoler/Drawflow#334]
Hi, I found a problem. The Vue3 unMounted event will not be triggered when using removeNodeId and clear.

[test demo](https://codesandbox.io/s/currying-silence-gp6yw?file=/src/App.vue)

App.vue:
```vue
<template>
  <div>
    <button @click="remove">remove</button>
    <div class="box"></div>
  </div>
</template>

<script>
import HelloWorldVue from "./components/HelloWorld.vue";
import { h, ref, render, defineComponent, onMounted } from "vue";
import Drawflow from "drawflow";
import "drawflow/dist/drawflow.min.css";

const Vue = { version: 3, h, render };
export default defineComponent({
  name: "App",
  components: {},
  setup() {
    const editor = ref();

    onMounted(() => {
      editor.value = new Drawflow(document.querySelector(".box"), Vue);
      editor.value.registerNode("hello", HelloWorldVue, {}, {});
      editor.value.start();
      editor.value.addNode("ddd", 1, 1, 200, 200, "ddd", {}, "hello", "vue");
    });

    const remove = () => {
      editor.value.removeNodeId("node-1");
    };

    return {
      remove,
    };
  },
});
</script>
```

HelloWorld.vue
```vue
<script>
export default {
  name: "HelloWorld",
  props: {
    msg: String,
  },

  mounted() {
    console.log("component mount");
  },

  unmounted() {
    console.log("component unmount");
  },
};
</script>
```

Look console, not show "component unmount" when clicking the remove button.

How to solve it? 

Thanks

**Comment by jerosoler** [comment]
Hi @rni-l 

I understand the problem.

The problem is that drawflow works with vanilla javascript and when deleting the node, it deletes it like this:
```javascript
this.container.querySelector(`#${id}`).remove();
 ```

Which Vue does not detect automatically.

I haven't found any way to force the unmounted event.

Maybe it can be achieved with:
```javascript 
document.querySelector(`#node-5 > .drawflow_content_node > div`).__vnode
Or:
document.querySelector(`#node-5 > .drawflow_content_node > div`).__vueParentComponent
```
Can you think of any way to force the event?

I haven't played much with vue3

**Comment by rni-l** [comment]
Thanks @jerosoler 

But I did not find a good way to solve it. I now use Eventbus to notify the components to be removed for processing.

**Comment by jerosoler** [comment]
If you want to know the elements that are removed, you can make use of the drawflow events. In this case the "nodeRemoved".

```javascript 
editor.on('nodeRemoved', function(id) {
  console.log("Node removed " + id);
})
```

**Comment by tomasp1189** [comment]
@rni-l @jerosoler Have you found a way around this? I'm having similar issue where event listeners from unmounted components still trigger.
@rni-l could you provide your approach with the event bus?

**Comment by rni-l** [comment]
> @rni-l @jerosoler Have you found a way around this? I'm having a similar issue where event listeners from components that should have been unmounted still trigger even though they are not visible on screen. @rni-l could you provide your approach with the event bus?

@tomasp1189 

[demo](https://codesandbox.io/s/busy-hypatia-lejenb)

In the demo, it will show the "unmount" text when clicking the "Remove component" in the console.

First, use the "EventBus" library. In the demo, I copied the sample code to implement the feature.

Second, use EventBus on your main page or component:

```javascript
import HelloWorldVue from "./components/HelloWorld.vue";
import { h, ref, render, defineComponent, onMounted } from "vue";
import Drawflow from "drawflow";
import "drawflow/dist/drawflow.min.css";
import eventBs from "./eventbus"; // import the EventBus

const Vue = { version: 3, h, render };
export default defineComponent({
  name: "App",
  components: {},
  setup() {
    const editor = ref();

    onMounted(() => {
      editor.value = new Drawflow(document.querySelector(".box"), Vue);
      editor.value.registerNode("hello", HelloWorldVue, {}, {});
      editor.value.start();
      editor.value.addNode("ddd", 1, 1, 200, 200, "ddd", {}, "hello", "vue");
    });

    const remove = () => {
      // notify using EventBus to component
      eventBs.emit("remove");
      editor.value.removeNodeId("node-1");
    };

    return {
      remove,
    };
  },
});
```
Third, add a listener event inside the component you want to insert:

```javascript
import eventBus from "../eventbus";

export default {
  name: "HelloWorld",
  mounted() {
   // listen
    eventBus.on("remove", () => {
      console.log("component will unmount by drawflow");
    });
    console.log("component mount");
  },
  unmounted() {
    eventBus.off("remove");
    console.log("component unmount");
  },
};
```

**Comment by tomasp1189** [comment]
@rni-l Thanks! Yeah, I have something similar. My issue is when I clear it programmatically or when navigating away. I can't get the unmount then.

**Comment by rni-l** [comment]
> @rni-l Thanks! Yeah, I have something similar. My issue is when I clear it programmatically or when navigating away. I can't get the unmount then.

@tomasp1189  

Sorry, I don't understand what you mean. Can't trigger unmount event in inserted component via Drawflow when you are using navigation?

Like this? It will trigger a remove event when the page changes navigation.

```javascript
// main page
export default {
  unmounted() {
    eventBs.emit("remove");
  }
}

// child component
export default {
  mounted() {
    // listen
    eventBus.on("remove", () => {
      // ...
    });
  }
}
```
