### ISSUE TITLE
An exception occurs when node data key has ',' or '|' and some areas cannot be dragged 

### ISSUE THREAD

**Issue by rni-l** [jerosoler/Drawflow#336]
Hi, I have two questions.

Version: 0.0.54.

First:

An exception occurs when the node data key has ',' or '|'.

code:
```javascript

editor.import(drawflow: {
          Home: {
            data: {
              1: {
                id: 1,
                name: "welcome",
                data: {
                  test: {
                    "aaa,a": "1",
                    "aaa|a": "1",
                  },
                },
                class: "welcome",
                html: '<div>test</div>',
                typenode: false,
                inputs: {},
                outputs: {},
                pos_x: 50,
                pos_y: 50,
              },
            },
          },
        },)

```

Second:

If the root dom has class, the outside of '.drawflow' cannot be dragged.

I think it was caused by here:

![image](https://user-images.githubusercontent.com/17063207/147739394-922f8696-c646-4403-9dfd-1f269e739afa.png)

In this [demo](https://codesandbox.io/s/crazy-shadow-0h6hz?file=/src/App.vue), it will be reproduced.

**Comment by jerosoler** [comment]
Hi @rni-l 

Thanks for issue and PR.

I see you are using vue.

Not only those characters are not allowed. If not many others too.

Affects all characters in html attributes. https://html.spec.whatwg.org/multipage/syntax.html#attributes-2
For example: "@#$...."

That for example students could conflict with vue ":", "@"
https://vuejs.org/v2/guide/syntax.html#Shorthands

We would have to get all the allowed characters and not just two.

For example chrome not support or show error:
![image](https://user-images.githubusercontent.com/30957047/147748734-076221cb-7070-4cba-bd11-ebddad4280db.png)


The attribute df  they are used to synchronize directly with the data. If it is badly formed or the browser does not support it, it could cause errors or problems. I think it is better not to allow strange characters.
![image](https://user-images.githubusercontent.com/30957047/147748827-cb6aa95e-ed46-43b8-a2f6-d0add399a6b5.png)

Jero

**Comment by rni-l** [comment]
Thanks @jerosoler 

But I need to save complex data in each node, it includes ',' and '|' characters, so do you have other ways to solve this problem? Can I only use an additional object to store the node data?

**Comment by jerosoler** [comment]
If you are not going to use the df attributes, you can use:
https://github.com/jerosoler/Drawflow/issues/97

If you can't convert the data before "import" and after "export".

**Comment by rni-l** [comment]
Thanks @jerosoler 

I solved the first question.

**Comment by jerosoler** [comment]
Can you elaborate on the second question?

**Comment by rni-l** [comment]
You can go to look at this [demo](https://codesandbox.io/s/crazy-shadow-0h6hz?file=/src/App.vue).

The blue area is the root node and the red area is the '.drawflow' node.  When I added the class to the root node, I can't drag the blue area, only the red area.

```javascript
// HTML
<div class="box"></div>

// js
editor= new Drawflow(document.querySelector(".box"));
```

I think it was caused by here:

![](https://user-images.githubusercontent.com/17063207/147739394-922f8696-c646-4403-9dfd-1f269e739afa.png)

Forgive my bad English...

**Comment by jerosoler** [comment]
It is an issue that is currently open. https://github.com/jerosoler/Drawflow/pull/141

Change: 
```html
<div class="box"></div>
```
For:

```html
<div class="parent-drawflow box"></div>
```

**Comment by rni-l** [comment]
Thanks.
