### ISSUE TITLE
Uncheck checkbox 

### ISSUE THREAD

**Issue by dhanos23** [jerosoler/Drawflow#339]
Hi!

I tried to import/export data from a checkbox, but when I unchecked the checkbox and exported the data; it is the same as if I had checked the checkbox, so there´s no changes.

My checkbox is a simple input
`<input type="checkbox" v-model="model">`

I used vue 3 for this proyect so by any chance do you have any examples for checkbox that you may share with me?

**Comment by mcesaro** [comment]
Hi, it happened to me also (without vue). My solution was to scan the flow after import and set again the checkbox status according to the saved data value. I'm not sure this is a shortcoming of Drawflow, though, rather the way you deal with the HTML rendering of the nodes.

**Comment by jerosoler** [comment]
Hi @dhanos23 

View a compelt example in vue3: https://github.com/jerosoler/drawflow-vue3-example
And demo: https://jerosoler.github.io/drawflow-vue3-example/

If you don't want to use the df- attributes you can use the getNodeDataFromId function as in this example:
https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/nodes/node1.vue
