### ISSUE TITLE
Use function vue in  components HTML

### ISSUE THREAD

**Issue by myshinjio** [jerosoler/Drawflow#34]
In vuejs  function I use Library function  **this.editor.addNode**  and i used  **"@click="Clicked"**  It's not working in vuejs
You can recommend for using in vuejs
 
 `card_devices: '
                 <div class="card-devices" > 
                    <div class="header"> 
                      <h1> Test </h1>
                    </div>
                    <div class="body" >
                      <span @click="Clicked"> Name :</span>
                    </div>
                    </div>
                  </div> 
        '`

**Comment by jerosoler** [comment]
Hello @myshinjio 

For vue you have to register the components.

Example: 
**App.vue**
```javascript
<template>
  <div id="app">
    <div id="drawflow"></div>
  </div>
</template>

<script>
import Vue from 'vue'
/*eslint-disable */
import NodeClick from './components/NodeClick.vue'
import Drawflow from 'drawflow'
import styleDrawflow from 'drawflow/dist/drawflow.min.css' // eslint-disable-line no-use-before-define
/*eslint-enable */


export default {
  name: 'App',
  data() {
    return {
      editor: null,
    }
  },
  mounted() {
    const id = document.getElementById("drawflow");
    this.editor = new Drawflow(id, Vue);
    this.editor.start();
    const props = {};
    const options = {};
    this.editor.registerNode('NodeClick', NodeClick, props, options);
    const data = {};
    this.editor.addNode('Name', 0, 1, 150, 300, 'Class', data, 'NodeClick', 'vue');

  },
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
#drawflow {
  width: 100%;
  height: 500px;
  border: 1px solid red;
}
</style>

```

**Component NodeClick**
```javascript
<template>
  <div class="card-devices" >
     <div class="header">
        <h1> Test </h1>
     </div>
    <div class="body" >
       <span @click="Clicked"> Name :</span>
     </div>
  </div>
</template>

<script>
export default {
  methods: {
    Clicked() {
      alert("hello-drawflow");
    }
  }
}
</script>

```

**Comment by myshinjio** [comment]
It's working Thank you very help full. 👍

**Comment by jerosoler** [comment]
Perfect! 🎉🎉

**Comment by namjals** [comment]
![image](https://user-images.githubusercontent.com/22319132/108040135-47f07d80-7080-11eb-9ca8-54599987a27d.png)
I tried applying the code as it is in vue.
When dragging the output, there is a line to the far right.
How do I fix it?

**Comment by jerosoler** [comment]
Hello @namjals 

view in https://github.com/jerosoler/Drawflow/issues/37#issuecomment-716220711

mmmm.. try 

```css
#app {
  text-align: initial;
}
```

or: 

```css
#drawflow {
  text-align:initial;
  position: relative;
  width: 100%;
  height: 800px;
  border: 1px solid red;
}
```

**Comment by AK3030** [comment]
How do i change the style of nodes in vue? I'm using the same example as above but nothing I do changes the background-color or style of the node.
