### ISSUE TITLE
Make begining of line stick to output not center of node

### ISSUE THREAD

**Issue by adamburczy** [jerosoler/Drawflow#341]
This node is connected to first output, but when I drag it , it seems like it is connected to the second output. Is there a way to prevent that behavior, for example  make begining of line stick to output not center of outputing node?

https://user-images.githubusercontent.com/73838040/148565888-2b6ce9ee-b535-45d8-8d4b-737822a0d2fd.mp4

**Comment by jerosoler** [comment]
I see you have modified the code. By default the modules are horizontal.

Can you indicate the modifications you have made? Put some example in codepen ...

It is not very clear to me where it is connected. The inputs are up and the outputs are down?

It seems to be connected to the input above with the node input below.

If you have not modified the javascript. View for vertical lines: https://github.com/jerosoler/Drawflow/issues/20#issuecomment-774637314

Jero

**Comment by adamburczy** [comment]
that was issue with my code, found it and solved it
