### ISSUE TITLE
Adding unique ids for outputs/inputs?

### ISSUE THREAD

**Issue by galanflorind** [jerosoler/Drawflow#343]
Hello,
To begin, I'd like to mention that this library is pretty cool, and I enjoy working with it. It has saved me a lot of time.

I've hit a problem that's pretty big for me, I need to add/remove outputs/inputs dynamically from an external panel, and having the ids of the outputs/inputs incremented causes a lot of problems and I'm not seeing any other way than finding a way to add unique ids to inputs/outputs.

Is there a way to add unique ids for outputs/inputs that won't change when I remove an output/input? (when i have output_1, output_2 and output_3, if i remove output_2, output_3 becomes output_2)

Thanks!

**Comment by jerosoler** [comment]
Hi @galanflorind 

Thanks! 

You can see this issue which deals with the same problem.
- https://github.com/jerosoler/Drawflow/issues/153

**Comment by galanflorind** [comment]
@jerosoler Thank you for your prompt answer!

I've seen that issue but at the same time I would need to pass an ID there (only having a number would be pretty hard on making all the logic we have behind), somehow I would need a unique id.

Is there a way to attach a unique ID or is it something that needs too much change and we need to find a workaround with `output_[number]` and see what we could do?

**Comment by galanflorind** [comment]
I see, thanks for the directions!
