### ISSUE TITLE
Ability to add data to the connection object

### ISSUE THREAD

**Issue by hkurma** [jerosoler/Drawflow#345]
I have read the documentation and haven't seen a way to add data to the connection. This is probably useful in few cases.

The use case I'm trying to solve here is where there is a node which has 2 connections for an ouput port. Now, this node is more like a decision making node and I would want to take only one of the connections.

 **How adding data property to the connection object would help this use case:**

Now if there was a data property in the connection object, I would use the data property on the connection object to evaluate against the decision made by it's node and take the connection that satisfies the evaluation.

**Comment by jerosoler** [comment]
What does it mean to add labels? Inconnections?

**Comment by hkurma** [comment]
@jerosoler I was hoping it to be 'connection'.

Also, a way to show some text on the connection. Something like below

![image](https://user-images.githubusercontent.com/36047647/149637077-29c0f1e9-0a34-43d9-8724-ef651f5d5ba0.png)

**Comment by jerosoler** [comment]
It is not implemented yet, but you can find solutions here:
- https://github.com/jerosoler/Drawflow/issues/18
