### ISSUE TITLE
[FEATURE REQUEST] - Add Conditional node and Loop node

### ISSUE THREAD

**Issue by sujit-baniya** [jerosoler/Drawflow#346]
Thank you for awesome library.

Adding Conditional node would be very helpful. 
Some days back, I built a library: https://github.com/sujit-baniya/flow in golang that would allow executing functions in flow.
I'm looking to integrate this library with Drawflow

Feature:
- Allow user to create UI to connect to another node based on condition
- Allow user to create UI to loop through each record and connect each record to another record

**Comment by jerosoler** [comment]
Hi,
Thanks

A conditional node is only a node with 1 input and 2 outputs.

```javascript
// editor.addNode(name, inputs, outputs, posx, posy, class, data, html);
editor.addNode('github', 1,2, 150, 300, 'github', data, html);
```
You can add as many inputs and outputs as you like.
- inputs: 1
- outputs: 2

**Comment by ariselseng** [comment]
@jerosoler Is it possible to get different styling on the connection line based on the condition? If the condition is true then the line is blue but if it false then it would be preferable to make it red?
If not, is it possible to mark the two outputs by text or styling some other way?

**Comment by jerosoler** [comment]
Not by default. 

but you could use this approach:
- https://github.com/jerosoler/Drawflow/issues/588
And
- https://github.com/jerosoler/Drawflow/issues/180

**Comment by ariselseng** [comment]
@jerosoler Thank you! You project seems great by the way.
