### ISSUE TITLE
[Bug] - Uncaught TypeError: Cannot read property 'connections' of undefined

### ISSUE THREAD

**Issue by sujit-baniya** [jerosoler/Drawflow#347]
Node A with 1 output
Node B with 1 input and 1 output

on page load event, I added both nodes and trying to add connection from NodeA to NodeB. Adding connection gave me error

```js
Uncaught TypeError: Cannot read property 'connections' of undefined
    at Drawflow.addConnection (drawflow.ts?t=1642773364754:624)
    at addConnection (editor.ts?t=1642773512469:68)
    at drop (editor.vue?t=1642773512469:33)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6737)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6746)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js:357)
```

It's complaining here

```js
if (exist === false) {
				...
				this.drawflow.drawflow[nodeOneModule].data[id_input].inputs[
					input_class
				].connections.push({
					node: id_output.toString(),
					input: output_class,
				})
}
```

because for NodeA it doesn't have `inputs` and thus no `connections`

**Comment by jerosoler** [comment]
How are you adding the connection?

With to the UI?

With JavaScript? With what method?

**Comment by sujit-baniya** [comment]
@jerosoler I'm trying to add with JavaScript with `addConnection`
https://github.com/jerosoler/Drawflow/blob/master/src/drawflow.js#L688

And error is thrown here
https://github.com/jerosoler/Drawflow/blob/master/src/drawflow.js#L705

**Comment by jerosoler** [comment]
As it is a Javascript thing, it is the responsibility of the developer. You can use the **getNodeFromId(id)** method to find out if the connection exists.

**Comment by sujit-baniya** [comment]
As I see, the bug appeared to be coming from the library on line I've mentioned. `getNodeFromId` will not in this case as I'm trying to call `addConnection` from nodeA (only output) to nodeB

**Comment by jerosoler** [comment]
The library is intended to be used by UI. Functions can be used by javascript. But in some cases you have to see if the object exists.

In this case it is as simple as this:

```javascript
    const nodeOut = editor.getNodeFromId(1);
    const nodeIn = editor.getNodeFromId(4);
    
    if(nodeOut.outputs['output_3'] !== undefined && nodeIn.inputs['input_1'] !== undefined) {
        editor.addConnection(1, 4, 'output_3', 'input_1');
    }
```

**Comment by sujit-baniya** [comment]
Thank you. After some change it works now.
