### ISSUE TITLE
[QUESTION] - How would I print node ID on the node I dragged and dropped on editor?

### ISSUE THREAD

**Issue by sujit-baniya** [jerosoler/Drawflow#348]
I'm using this library for vue 3 and I'm successfully implemented this library in my project. I was wondering on how can I print or use the NodeID on the node I dragged and dropped on editor.

![image](https://user-images.githubusercontent.com/4959215/150644467-454ddc2e-e439-430d-a4d0-cfafe88a9fd4.png)

**Comment by jerosoler** [comment]
You can access the parent element and get the id.

https://github.com/jerosoler/Drawflow/issues/271#issuecomment-944042114

You can also see an example of a vue3 demo:
Node example:
https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/nodes/node1.vue

Repo: https://github.com/jerosoler/drawflow-vue3-example

Demo: https://jerosoler.github.io/drawflow-vue3-example/

**Comment by sujit-baniya** [comment]
Thanks @jerosoler. IT's working
