### ISSUE TITLE
How to restrict the node to single input

### ISSUE THREAD

**Issue by freesix** [jerosoler/Drawflow#35]
I really like your project and willing to use it but I have a question according to my requirement.
Is it possible to **restrict the node to a single input** ?

Also, Can we customize it?

**Comment by jerosoler** [comment]
Hello @freesix 

Thanks! ❤️

An input could be restricted with functions and events. Or you can modify the library.

For example:
```javascript
editor.on("connectionCreated", function(info) {
  const nodeInfo = editor.getNodeFromId(info.input_id);
  if(nodeInfo.inputs[info.input_class].connections.length > 1) {
    const removeConnectionInfo = nodeInfo.inputs[info.input_class].connections[0];
    editor.removeSingleConnection(removeConnectionInfo.node, info.input_id, removeConnectionInfo.input, info.input_class);
  }
});
```

This example deletes the first connection and only keeps the last one.

**Comment by muratcim** [comment]
Thank you @jerosoler 

How can we do the same for output. Output only to bind to an input

**Comment by jerosoler** [comment]
Hello @muratcim 

Following the example above.

For example:
```javascript
editor.on("connectionCreated", function(info) {
  const nodeInfo = editor.getNodeFromId(info.output_id);
  if(nodeInfo.outputs[info.output_class].connections.length > 1) {
    const removeConnectionInfo = nodeInfo.outputs[info.output_class].connections[0];
    editor.removeSingleConnection(info.output_id, removeConnectionInfo.node, info.output_class, removeConnectionInfo.output);
  }
});
```

**Comment by muratcim** [comment]
Thank you @jerosoler 
it worked

Best Regards

**Comment by dotrungit91** [comment]
@jerosoler 
I'm so glad I found this tutorial.
But there is a problem as follows:
I want to catch delete event and call api( when use delete on keyboard and right click to connection)

`this.editor.on('connectionRemoved', (info) => {
     // call delete api
 })`
 
But according to the instructions above,
every times restrict the node, it will automatically call the api.

**Comment by jerosoler** [comment]
It is only called if a connection is deleted.

**Comment by dotrungit91** [comment]
> It is only called if a connection is deleted.

@jerosoler 
yes sir, i just want to call the api when delete key is pressed or when right click. But when have more than one connection on input, it will automatically call the method `removeSingleConnection`.

**Comment by jerosoler** [comment]
You can create something like this.

```javascript

let deleteConnectionAuto = false;

editor.on("connectionCreated", function(info) {
  const nodeInfo = editor.getNodeFromId(info.output_id);
  if(nodeInfo.outputs[info.output_class].connections.length > 1) {
    const removeConnectionInfo = nodeInfo.outputs[info.output_class].connections[0];
    deleteConnectionAuto = true;
    editor.removeSingleConnection(info.output_id, removeConnectionInfo.node, info.output_class, removeConnectionInfo.output);
  }
});

this.editor.on('connectionRemoved', (info) => { 
    if(!deleteConnectionAuto) {
        // call delete api
    } else {
        deleteConnectionAuto = false;
    }
})
```

**Comment by dotrungit91** [comment]
@jerosoler i loving you !!!!

**Comment by viniciusverasdossantos** [comment]
> ```js
> const nodeInfo = editor.getNodeFromId(info.output_id);
>   if(nodeInfo.outputs[info.output_class].connections.length > 1) {
>     const removeConnectionInfo = nodeInfo.outputs[info.output_class].connections[0];
>     editor.removeSingleConnection(info.output_id, removeConnectionInfo.node, info.output_class, removeConnectionInfo.output);
>   }
> ```

This code doesn't work for me. I'm using version .59 
Is there another way?
![image](https://github.com/jerosoler/Drawflow/assets/16549732/fd72000f-4f82-4fdd-9979-ad9de4a8cfbe)
