### ISSUE TITLE
UpdatedExported json with connection name,while trying to import the same  connection name is missing ;how can this be solved

### ISSUE THREAD

**Issue by 1989levinu** [jerosoler/Drawflow#351]
![drawflow1](https://user-images.githubusercontent.com/98806915/151939773-b7ddad19-ffd7-4850-aa4e-229993ce70ea.png)

here while exporting connnection name is added to connection object as shown in below
exported json
    "typenode": false,
                    "inputs": {},
                    "outputs": {
                        "output_1": {
                            "connections": [
                                {
                                    "node": "7d3c0fe5-5daf-4ad7-b7e9-61c87f329b87",
                                    "output": "input_1",
                                    "connection_name": "connection1"
                                },
                                {
                                    "node": "de0e2817-3122-46f5-8415-a3cfcc0030a2",
                                    "output": "input_1",
                                    "connection_name": "connection2"
                                }
                            ]
                        }
                    },

While importing the same how can i get the connection name back to editor

**Comment by jerosoler** [comment]
Hello,

Since connection_name has been created externally.
You can use the "import" event to create the connection label.

**Comment by 1989levinu** [comment]
Thanks jero , it worked
