### ISSUE TITLE
[QUESTION] - How can I access drawflow object in node?

### ISSUE THREAD

**Issue by sujit-baniya** [jerosoler/Drawflow#352]
I wanted to use multiple drawflow in same page but use same node on those drawflow instances. I was wondering on how I can access the drawflow object on child nodes?

**Comment by jerosoler** [comment]
You have two options or you can use different instances.
```javascript
var id = document.getElementById("drawflow");
const editor = new Drawflow(id);
editor.start();

var id2 = document.getElementById("drawflow2");
const editor2 = new Drawflow(id2);
editor2.start();
```

Or you can use modules.
https://github.com/jerosoler/Drawflow#modules

**Comment by sujit-baniya** [comment]
@jerosoler yes I could implement multiple instances but the issue I'm facing is this

```js
// Node.vue
<template>
    <div>Hi There</div>
</template>
```

I've added the `Node.vue` to editor as

```js
editor.addNode('node', 0, 1, pos_x, pos_y, 'node', {},  'node',  'vue')
```

Till here everything works.

Now on `Node.vue`, I wanted to access `editor` instance. For e.g.
```js
// Node.vue
<template>
    <div>Hi There</div>
</template>
<script setup lang="ts">
editor.removeConnection() // or any other functions
</script>
```

Hope above illustration clarifies my question

**Comment by jerosoler** [comment]
View example with vue3: 

https://github.com/jerosoler/drawflow-vue3-example

Editor: https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/drawflow.vue
Node: https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/nodes/node1.vue

Vue 2: Prototype method:

https://github.com/jerosoler/Drawflow/issues/271#issuecomment-944042114

Vue2 With event bus: or mitt library.
https://github.com/jerosoler/Drawflow/issues/37#issuecomment-717822302

**Comment by sujit-baniya** [comment]
Got it working using this
```js
editor.registerNode(operation.key, operation.component, {editor: editor})
```

Thanks for suggestions
