### ISSUE TITLE
90 degree lines and alignment

### ISSUE THREAD

**Issue by amergoat** [jerosoler/Drawflow#354]
We are working on a corporate app, and we are trying to see if we can make this work for our needs.  We have several things we are trying to accomplish, and were wondering if you could help us figure them out.

1) We want the lines to show they are connecting to the input/outputs only. Right now the lines hide behind the nodes when the lines change. (see screenshot). Is there a clean way to make the lines clearly visible?

2) With the 90 degree lines, is it possible to make it cleanly split? If you see my screenshot with the 90 degree lines, the lines don't look like they come from the same output, nor is in clean to make the tree.  Is it possible to make the connections look like the mockup provided?

3) Is there a simple way to add a button that will auto align and auto space the nodes to make the flow look clean?

4) When I add additional metadata to the export, I get a console warning about that additional data when I import it. Is there a way to make this work well to remove this console warning?

Thank you for your help.

![Screenshot (304)](https://user-images.githubusercontent.com/96874240/152722313-1fee29ee-edc1-44ae-9913-31795bfde210.png)
![Screenshot 2022-02-06 215719](https://user-images.githubusercontent.com/96874240/152722317-ef477ecb-7a6a-40dd-aaff-542ae823986f.png)
![Screenshot 2022-02-02 100944](https://user-images.githubusercontent.com/96874240/152722319-dcb63cf5-a73b-4e10-a88b-db3ddd487d07.png)
![Screenshot (305)](https://user-images.githubusercontent.com/96874240/152722320-ffd26dd7-f958-4900-b92b-7c050682de1c.png)

**Comment by jerosoler** [comment]
Hi @amergoat 

1. View 
- #20 
- https://github.com/jerosoler/Drawflow/issues/20#issuecomment-801265399

2. Related 1

3. You could create a button by looping through the data from the export function. And doing an update of the position of the node. See how to update the position:
- https://github.com/jerosoler/Drawflow/issues/112

4. We would need to see the error or what data you are passing.
