### ISSUE TITLE
[QUESTION] - How can I restrict to create duplicate node?

### ISSUE THREAD

**Issue by sujit-baniya** [jerosoler/Drawflow#357]
I wanted to limit users to select one node per flow. Some nodes allowed only once whereas some nodes could be allowed multiple times. How would I do that?

**Comment by jerosoler** [comment]
Before doing an addNode, you can always loop through the export to see if the node is already in the module.
You could search by node name.

**Comment by sujit-baniya** [comment]
Thanks! working
