### ISSUE TITLE
How to Import back the Exported file with Drawflow information.

### ISSUE THREAD

**Issue by Aravinda93** [jerosoler/Drawflow#359]
I am creating the `Drawflow` Nodes and Connection dynamically and Exporting the data in Drawflow. Is there any way to import back the Exported data? Looking for some suggestions.

I have added the code sample [here](https://codesandbox.io/s/blissful-wozniak-6voii?file=/components/DrawflowSample.vue).

Link: https://codesandbox.io/s/blissful-wozniak-6voii?file=/components/DrawflowSample.vue

**Comment by jerosoler** [comment]
View your generated json:

```javascript
```

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for the response. I am really sorry I was working on another critical requirement so missed this.

You are correct the generated JSON has the structure that you have provided. However, when I try to import the exported drawflow structure then nothing happens and I get the error:
```
drawflow.min.js:218 Uncaught TypeError: Cannot read properties of undefined (reading 'Home')
    at i.load (drawflow.min.js:218:47)
    at i._import (drawflow.min.js:1295:77)
    at FileReader.reader.onload (index.js?!./node_modules/vue-loader/lib/index.js?!./components/fileName.vue?vue&type=script&lang=js&:404:26)
```

I am following the process that you have mentioned above not sure why am I getting the error. I have provided the sample code in [Codesandbox](https://codesandbox.io/s/blissful-wozniak-6voii?file=/components/DrawflowSample.vue) for your reference: https://codesandbox.io/s/blissful-wozniak-6voii?file=/components/DrawflowSample.vue

If you get a chance can you please have a look and provide some workaround or suggestions?  All I want to do is import the same diagram into my Drawflow canvas that I exported:

**Comment by jerosoler** [comment]
When you read the file you are not parsing to JSON.

Try:

```javascript
this.$df.import(res.target.result);
```
To
```javascript
this.$df.import(JSON.parse(res.target.result));
```

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for the response. Now I am able to get the import and the diagram. 

I am facing one small issue related to some of the data that I am importing. During the Export I am also appending the data that the user has provided for each of my Node along with the Drawflow diagram info so that during the import I can populate my Arrays with the data that the user provided during the creation the Nodes. 

However, some of the data will not be pre-populated during the import of the info although they are populated in the respective Array.

For example:
1. Create 2 Nodes within the Drawflow canvas.
2. Populate the Syntax for the first Node as URN and second as WebURI
3. Now export the data using the Export feature. This file will have the Drawflow information along with the information provided for each Node.
4. Now import the same file data using the Import feature. During the import, I am populating my Vuex Store with the information of the respective Nodes and then creating the Drawflow diagram.
5. Now if you observe the Nodes will not have the information that I provided although the data are present within my Vuex Store. 

@jerosoler Is there any possibility to populate the data as well along with the Drawflow info? I have provided the code sample in [CodeSandbox](https://codesandbox.io/s/blissful-wozniak-6voii?file=/components/IdentifiersNode.vue). Looking for some suggestions on how to assign value to the Nodes which are present within the Vuex Store.

Creation and Export:
![Example-1](https://user-images.githubusercontent.com/29374160/156746262-79a40b49-1633-427c-aa43-f4ffd64f26bc.gif)

Import where only the last Node will have the value of all other Nodes without the value:
![CPT2203041125-1920x1096](https://user-images.githubusercontent.com/29374160/156746425-f6ac41df-b1c3-4bf8-8f3b-2921347d8e1a.gif)

**Comment by jerosoler** [comment]
Why don't you save the data directly to drawflow node with the "df-*" attributes?

```javascript
 "5": {
                        "id": 5,
                        "name": "Identifiers",
                        "data": {
                            "ID": 5,
                            "nodeId": 5,
                            "eventType": "Identifiers"
                        },
                        "class": "Identifiers",
                        "html": "Identifiers",
                        "typenode": "vue",
```

I see that it saves data to node. But save the id, you already have it. It's a little weird.

Why don't you save like this:

```javascript
 "data": {
                    "5": {
                        "id": 5,
                        "name": "Identifiers",
                        "data": {
                            "identifierSyntax": "URN",
                        },
                        "class": "Identifiers",
                        "html": "Identifiers",
                        "typenode": "vue",
                        "inputs": {},
                        "outputs": {
                            "output_1": {
                                "connections": []
                            }
                        },
                        "pos_x": null,
                        "pos_y": 27
                    },
                    "6": {
                        "id": 6,
                        "name": "Identifiers",
                        "data": {
                           "identifierSyntax": "WebURI",
                        },
                        "class": "Identifiers",
                        "html": "Identifiers",
                        "typenode": "vue",
                        "inputs": {},
                        "outputs": {
                            "output_1": {
                                "connections": []
                            }
                        },
                        "pos_x": 229,
                        "pos_y": 197
                    }
                }
```

And here you will receive the data:

```javascript
const data = this.$df.getNodeFromId(id.slice(5));
```
I don't see the error in your code.

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for the response and workaround.

Actually, I am creating different types of Nodes by registering them. Identifiers are one of the types of Node.
The information associated with these Nodes is not simple rather complex and they are stored within the different Vuex stores. So if I would like to save them into the data of the respective node during the export then it would require a lot of processes also I have to follow a similar process during the import again. 

Currently, I am using the Drawflow for the visual representation within my application and storing all the information within my Vuex store array.

@jerosoler Is there any other alternative approach that I can use to fix the issue and obtain the value within my Drawflow Node during the import? Looking for some suggestions. Thanks in advance.

**Comment by jerosoler** [comment]
I think you have it half solved, what you have is some error in your code, I would try to find that error.

I try to fork codesandbox but it gives me an error when loading the application.

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for looking into the code. 

I have modified my code within CodeSandbox based on your previous comment for storing the value within data of Drawflow. If you get a chance please have a look or else if you have forked my code already then you can provide me some workaround or suggestion based on that as well.

Based on your previous suggestion I tried to store only the `IdentifierSyntax` value within my `IdentifiersNode` as that's the only information that I show within the Drawflow Node and the rest everything I can take care of within my `Vuex Store`.

After this I will have the Drawflow information something like this:
```
"2": {
                        "id": 2,
                        "name": "Identifiers",
                        "data": {
                            "ID": 2,
                            "nodeId": 2,
                            "eventType": "Identifiers",
                            "identifierSyntax": "WebURI"
                        },
                        "class": "Identifiers",
                        "html": "Identifiers",
                        "typenode": "vue",
                        "inputs": {},
                        "outputs": {
                            "output_1": {
                                "connections": []
                            }
                        },
                        "pos_x": 453,
                        "pos_y": 188
                    },
```

Now during the import, only some Identifiers Nodes i.e particularly only with WebURI will be default selected.  For `URN` value it wont be selected but gets selected if the last node is URN.  Please refer the code in [Codesandbox](https://codesandbox.io/s/blissful-wozniak-6voii?file=/components/IdentifiersNode.vue).

**Comment by jerosoler** [comment]
I have been checking and it has a problem in the improtation:
```javascript
 importDesignInfo() {
      const reader = new FileReader();
      this.file = this.$refs.readDrawflowInfo.files[0];
      this.$refs.readDrawflowInfo.value = null;
      reader.onload = (res) => {
        const importData = JSON.parse(res.target.result);

        this.$store.commit(
          "modules/ConfigureIdentifiersInfoStore/populateIdentifiersArray",
          importData.identifiersNodeInfo
        );

        this.$df.start();
        this.$df.registerNode("Identifiers", Identifiers, {}, {});
        this.$df.import(importData.drawflowInfo);
      };
```

Change to:
```javascript
 importDesignInfo() {
      const reader = new FileReader();
      this.file = this.$refs.readDrawflowInfo.files[0];
      this.$refs.readDrawflowInfo.value = null;
      reader.onload = (res) => {
        const importData = JSON.parse(res.target.result);

        this.$store.commit(
          "modules/ConfigureIdentifiersInfoStore/populateIdentifiersArray",
          importData.identifiersNodeInfo
        );

        this.$df.import(importData.drawflowInfo);
      };
```

Remove "Start and Register", since it is already calling it in the mounted method.

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for the response. It worked. 

I also removed the default value that I provided in the `IdentifiersNode.vue : identifierSyntax: "",`. 
Thanks a lot for looking into the help and for the really nice library. Have a great weekend ahead :)
