### ISSUE TITLE
How to transfer/sync data between nodes

### ISSUE THREAD

**Issue by aisenarge** [jerosoler/Drawflow#364]
Hello

I have a problem to transfer data between nodes. I can check the values with that function (I also can change values from other nodes with that code in comment):

`editor.on('nodeDataChanged', function(id) {
      console.log("Node Changed " + id);
      console.log("Node Data:   " + Object.values(editor.getNodeFromId(id)['data']));
      // document.getElementById("df-text").innerHTML = Object.values(editor.getNodeFromId(id)['data']);
    })`

But i can't transfer data with using connections. And i couldn't find any solution. 
Thanks for your help

**Comment by jerosoler** [comment]
You can update data from another node with the function:
updateNodeDataFromId

Example:
```javascript
editor.updateNodeDataFromId(5,{ name: 'Drawflow' });
```

**Comment by aisenarge** [comment]
Thank you, now i can change data from another node with your function. But now i can't change html parameter from node data. Is it possible to change html (for example image source) from node data?

**Comment by jerosoler** [comment]
df- attriubtes only update, input, select, textarea.

For update html view: https://github.com/jerosoler/Drawflow/issues/40

**Comment by jerosoler** [comment]
@RaviGuggilam Please do not use other issues to comment on other problems. 

Use event import 
```javascript
editor.on('import', () => {
 // For earch all elements 
})
```
