### ISSUE TITLE
Clicking on connection ask for  it properties and right click on connection delete

### ISSUE THREAD

**Issue by 1989levinu** [jerosoler/Drawflow#365]
now i have called one method on
 editor.on('connectionSelected', function (connection) {
setproperties();
}
but i have to delete the connection on right click  as normal.

how can i do this.. since connectinSelected event is get invoked both on right click and normal click

**Comment by jerosoler** [comment]
Hello,

You can detect the right click like so:
```javascript
    editor.on('clickEnd', function(event) {
      if(editor.connection_selected !== null && event.button === 2) {
          alert("Right Click connection");
      }
    })
```

**Comment by 1989levinu** [comment]
can i get this event inside  connectionSelected event. My need is if it is regular click show connectionProperties and if it is rightclick invoke delete..[right click delete i'm using the current built-in functionality of drawflow.js].but my concern is when the connection is selected.inisde that event(connectionSelected event) ,i need to check whether it is normal click or right click.

**Comment by 1989levinu** [comment]
Thanks:-)
