### ISSUE TITLE
How to get current position of node?

### ISSUE THREAD

**Issue by jf19742016** [jerosoler/Drawflow#367]
Hello, firstly - a fantastic library thank you.  I'm trying to store all of my data in a database, so on I can build a flow and then load it back.  If I move a node, how do I get it's current position so I can update the database so next time it loads it is in the same place?

Thanks

**Comment by jerosoler** [comment]
Hi! Thanks!

You can use the export and import method to save to the database.
```javascript
var exportdata = editor.export();
editor.import(exportdata);
```

If you just want the position each time a node is modified you can use events. In this case the nodeMoved event
```javascript
    editor.on('nodeMoved', function(id) {
      console.log("Node Moved " + id);
      const data = editor.getNodeFromId(id);
      console.log(`Position x:${data.pos_x} y:${data.pos_y}`);
    });
```

**Comment by jf19742016** [comment]
Perfect, exactly what I needed - thank you.

**Comment by Co-Maheshh** [comment]
How to restrict moving node inside editor.once we dropped node in editor  i need to restrict it to moving another position?
