### ISSUE TITLE
Clickable nodes when editor locked

### ISSUE THREAD

**Issue by jf19742016** [jerosoler/Drawflow#368]
Hello,

Is it possible to lock the editor for "editing" but still have the nodes clickable?  I'm trying to create a mechanism where someone can build a flow and then associate information with the nodes.  I then want to lock the flow but the nodes be clickable so the viewer can see the additional information.

Thanks

**Comment by jerosoler** [comment]
View editor mode.
```javascript
editor.editor_mode = 'edit';
```

Support three values: edit, fixed, view

**Comment by jf19742016** [comment]
Thank you for responding so quickly and on the weekend.  I did miss that - doh.  However putting it into view mode, nodes are still not clickable?

**Comment by jerosoler** [comment]
Try fixed method. 

Explain methods:
edit for edit, fixed for nodes fixed but their input fields available, view for view only

**Comment by jf19742016** [comment]
I used your example and it's in fixed mode.  The nodes are not clickable?

**Comment by jerosoler** [comment]
View similar questions: 
- https://github.com/jerosoler/Drawflow/issues/266
- https://github.com/jerosoler/Drawflow/issues/140

**Comment by jf19742016** [comment]
Perfect, thank you.

**Comment by jf19742016** [comment]
Perfect thank you.
