### ISSUE TITLE
[REQUEST] Do a tutorial series on this tool + Create forum

### ISSUE THREAD

**Issue by moseskamau338** [jerosoler/Drawflow#370]
Hi @jerosoler , your tool can do wonders! I did not realize that until I hit the issues page. I would like to request you to do a full coverage of the capabilities of this tool in a tutorial series and also create a community where we can help each other on related issues.

Thank you, just my two-sense.

**Comment by jerosoler** [comment]
Hello,
Thanks.

I don't have the necessary time.
I already spend time responding to issues, emails, maintaining, creating other libraries.
On the other hand I think it's a small library and you don't need it.

Of the node editor libs, I think it's one of the simplest to use and easiest.

There are also no sponsors.

Jero
