### ISSUE TITLE
Import exported drawflow data

### ISSUE THREAD

**Issue by RoyaghRamo** [jerosoler/Drawflow#371]
Hello, I have set up an Angular app using drawflow and I'm tried to import a drawflow data that I exported before and saved it in a database, but I don't see to get the connections right.

`{
  "drawflow": {
    "Home": {
      "data": {
        "1": {
          "id": 1,
          "name": "job1",
          "data": {},
          "class": "",
          "html": "<div>job1</div>",
          "typenode": false,
          "inputs": {},
          "outputs": {
            "output_1": {
              "connections": [
                {
                  "node": "2",
                  "output": "input_1"
                }
              ]
            }
          },
          "pos_x": 65.42498779296875,
          "pos_y": 175.28749084472656
        },
        "2": {
          "id": 2,
          "name": "job2",
          "data": {},
          "class": "",
          "html": "<div>job2</div>",
          "typenode": false,
          "inputs": {
            "input_1": {
              "connections": [
                {
                  "node": "1",
                  "input": "output_1"
                }
              ]
            }
          },
          "outputs": {},
          "pos_x": 464.42498779296875,
          "pos_y": 135.28749084472656
        }
      }
    }
  }
}
`
And this is the result I get when I launch `editor.import(exportedData)`.
![image](https://user-images.githubusercontent.com/57964781/157128320-ed30768f-0d0a-4c8b-87d3-2a970191bebd.png)

**Comment by jerosoler** [comment]
the start function is before?

```javascript
editor.start();
    editor.import({ "drawflow": { "Home": { "data": { "1": { "id": 1, "name": "job1", "data": {}, "class": "", "html": "<div>job1</div>", "typenode": false, "inputs": {}, "outputs": { "output_1": { "connections": [ { "node": "2", "output": "input_1" } ] } }, "pos_x": 65.42498779296875, "pos_y": 175.28749084472656 }, "2": { "id": 2, "name": "job2", "data": {}, "class": "", "html": "<div>job2</div>", "typenode": false, "inputs": { "input_1": { "connections": [ { "node": "1", "input": "output_1" } ] } }, "outputs": {}, "pos_x": 464.42498779296875, "pos_y": 135.28749084472656 } } } } })
```

The css is loaded before importing?
I have tried it and the export is correct.
![image](https://user-images.githubusercontent.com/30957047/157190577-d7338301-d1c8-4934-bcab-e8249600baf9.png)


Complete example html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css"/>
  <script src="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.js"></script>
</head>
<body>
<div id="drawflow"></div>
  <style>
    #drawflow { 
      position: relative;
      text-align:initial;
      width: 100%;
      height: 800px;
      border: 1px solid red;
    }

    .drawflow .drawflow-node2 {
    display: flex;
    align-items: center;
    position: absolute;
    background: #0ff;
    width: 160px;
    min-height: 40px;
    border-radius: 4px;
    border: 2px solid #000;
    color: #000;
    z-index: 2;
    padding: 15px;
}
</style>
<script>
    var id = document.getElementById("drawflow");
    const editor = new Drawflow(id);
    editor.line_path = 1;
    
    editor.reroute = true;
    editor.reroute_fix_curvature = true;
    editor.curvature = 0.1;
    editor.reroute_curvature = 0.1;
    editor.start();
    editor.import({ "drawflow": { "Home": { "data": { "1": { "id": 1, "name": "job1", "data": {}, "class": "", "html": "<div>job1</div>", "typenode": false, "inputs": {}, "outputs": { "output_1": { "connections": [ { "node": "2", "output": "input_1" } ] } }, "pos_x": 65.42498779296875, "pos_y": 175.28749084472656 }, "2": { "id": 2, "name": "job2", "data": {}, "class": "", "html": "<div>job2</div>", "typenode": false, "inputs": { "input_1": { "connections": [ { "node": "1", "input": "output_1" } ] } }, "outputs": {}, "pos_x": 464.42498779296875, "pos_y": 135.28749084472656 } } } } })
 


</script>
</body>
</html>
```



Other similars isues:
- https://github.com/jerosoler/Drawflow/issues/267
- https://github.com/jerosoler/Drawflow/issues/349
-

**Comment by RoyaghRamo** [comment]
> the start function is before?
> 
> ```js
> editor.start();
>     editor.import({ "drawflow": { "Home": { "data": { "1": { "id": 1, "name": "job1", "data": {}, "class": "", "html": "<div>job1</div>", "typenode": false, "inputs": {}, "outputs": { "output_1": { "connections": [ { "node": "2", "output": "input_1" } ] } }, "pos_x": 65.42498779296875, "pos_y": 175.28749084472656 }, "2": { "id": 2, "name": "job2", "data": {}, "class": "", "html": "<div>job2</div>", "typenode": false, "inputs": { "input_1": { "connections": [ { "node": "1", "input": "output_1" } ] } }, "outputs": {}, "pos_x": 464.42498779296875, "pos_y": 135.28749084472656 } } } } })
> ```
> 
> The css is loaded before importing? I have tried it and the export is correct. ![image](https://user-images.githubusercontent.com/30957047/157190577-d7338301-d1c8-4934-bcab-e8249600baf9.png)
> 
> Complete example html:
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>   <meta charset="UTF-8">
>   <meta name="viewport" content="width=device-width, initial-scale=1.0">
>   <meta http-equiv="X-UA-Compatible" content="ie=edge">
>   <title>Document</title>
>   <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css"/>
>   <script src="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.js"></script>
> </head>
> <body>
> <div id="drawflow"></div>
>   <style>
>     #drawflow { 
>       position: relative;
>       text-align:initial;
>       width: 100%;
>       height: 800px;
>       border: 1px solid red;
>     }
> 
>     .drawflow .drawflow-node2 {
>     display: flex;
>     align-items: center;
>     position: absolute;
>     background: #0ff;
>     width: 160px;
>     min-height: 40px;
>     border-radius: 4px;
>     border: 2px solid #000;
>     color: #000;
>     z-index: 2;
>     padding: 15px;
> }
> </style>
> <script>
>     var id = document.getElementById("drawflow");
>     const editor = new Drawflow(id);
>     editor.line_path = 1;
>     
>     editor.reroute = true;
>     editor.reroute_fix_curvature = true;
>     editor.curvature = 0.1;
>     editor.reroute_curvature = 0.1;
>     editor.start();
>     editor.import({ "drawflow": { "Home": { "data": { "1": { "id": 1, "name": "job1", "data": {}, "class": "", "html": "<div>job1</div>", "typenode": false, "inputs": {}, "outputs": { "output_1": { "connections": [ { "node": "2", "output": "input_1" } ] } }, "pos_x": 65.42498779296875, "pos_y": 175.28749084472656 }, "2": { "id": 2, "name": "job2", "data": {}, "class": "", "html": "<div>job2</div>", "typenode": false, "inputs": { "input_1": { "connections": [ { "node": "1", "input": "output_1" } ] } }, "outputs": {}, "pos_x": 464.42498779296875, "pos_y": 135.28749084472656 } } } } })
>  
> 
> 
> </script>
> </body>
> </html>
> ```
> 
> Other similars isues:
> 
> * [Arrow not showing on import data #267](https://github.com/jerosoler/Drawflow/issues/267)
> * [Import Failed: The connections doesn't show correctly #349](https://github.com/jerosoler/Drawflow/issues/349)

Yes, I have the css on global, and I saw in the other issues that you can update the connections from the event `import`.
I don't see it anywhere inside the the library.

**Comment by jerosoler** [comment]
Try:
- https://github.com/jerosoler/Drawflow/issues/267

Basically they are to listen to the events and update the connection of the nodes.

**Comment by RoyaghRamo** [comment]
> Try:
> 
> * [Arrow not showing on import data #267](https://github.com/jerosoler/Drawflow/issues/267)
> 
> Basically they are to listen to the events and update the connection of the nodes.

I've tried that, it seems that it didn't work.
But I found an interesting thing in HTML, the `path` inside the `svg` was filled with 0 

This is the image after creating a draw
![Screenshot 2022-03-08 100043](https://user-images.githubusercontent.com/57964781/157204238-9f35efd1-5003-4741-9a99-e555a58c8337.png)

This is the image after importing an existing draw
![Screenshot 2022-03-08 100219](https://user-images.githubusercontent.com/57964781/157204282-a2ccb88c-59f0-40d5-aafe-bcfbb3bc3246.png)

**Comment by jerosoler** [comment]
If you move a node with the mouse, does the connection appear?

**Comment by jerosoler** [comment]
The same problem
- https://github.com/jerosoler/Drawflow/issues/270

**Comment by RoyaghRamo** [comment]
> If you move a node with the mouse, does the connection appear?

Yes, it does appear after I mode a node.

**Comment by jerosoler** [comment]
Try settimeout for discard. 
```javascript
setTimeout(function(){ editor.import(YOUR DATA); }, 1000);
```

**Comment by RoyaghRamo** [comment]
Yes, it works now.
Thank you @jerosoler. I'm working on the implementation of your amazing library with Angular.
