### ISSUE TITLE
Is it possible to add Editicon in btw the connection path  as soon as it is created

### ISSUE THREAD

**Issue by 1989levinu** [jerosoler/Drawflow#372]

**Comment by jerosoler** [comment]
Can you elaborate more on your question?

You can detect a connection when it is created with the events in this case the connectionCreated
https://github.com/jerosoler/Drawflow#events

**Comment by 1989levinu** [comment]
I need to add connection name and properties for each connection..Right now a pop with connection properties will appear when we click on connection.But user do'nt understand now whether that connection is editable..can we place some edit button or small icon along with connection.i,e inbetween the  svg 
![connection](https://user-images.githubusercontent.com/98806915/157409997-1a5d1784-af54-47d2-9d0d-149018cec2b0.png)
path.

**Comment by jerosoler** [comment]
View:
- https://github.com/jerosoler/Drawflow/issues/18#issuecomment-991167477

**Comment by 1989levinu** [comment]
Thanks Jero..Thanks for the reply,great work keep going:-)
