### ISSUE TITLE
Add click event for newly added input/output

### ISSUE THREAD

**Issue by 1989levinu** [jerosoler/Drawflow#373]
How can we add click event on newly added input/ output  of a node

![newdbt](https://user-images.githubusercontent.com/98806915/157802214-2a20a617-49bc-4e7e-8b3f-db0ac00e4dce.png)

**Comment by jerosoler** [comment]
You can use the click event

```javascript
editor.on('click', (e) => {
      if(e.target.classList[0] === "output" || e.target.classList[0] === "input") {
        console.log("click Input / Output");
      }
    })
```

For add node on click output a simple example:
```javascript
editor.on('click', (e) => {
      if(e.target.classList[0] === "output") {
        const nodeClick = e.target.closest(".drawflow-node").id.slice(5);
        const nodeNew = editor.addNode("test", 1,1, 300,  300, "test", {}, `<div>New Node</div>`);
        editor.addConnection(nodeClick, nodeNew, e.target.classList[1] , 'input_1');
      }
    })
```

**Comment by 1989levinu** [comment]
What is the easiest way to remove input/output.Just like connection and node removal do we need to show delete icon on right click.. can u pls help me,do u have any idea?

**Comment by jerosoler** [comment]
See this to create a contextmenu and use the "removeNodeInput" and "removeNodeOutput" functions.
- https://github.com/jerosoler/Drawflow/issues/187

**Comment by 1989levinu** [comment]
Thanks Jero ,Will try in that way

**Comment by 1989levinu** [comment]
It worked thanks
