### ISSUE TITLE
connection line issue

### ISSUE THREAD

**Issue by vinodjaunjalkar** [jerosoler/Drawflow#378]
Hello jerosoler,

I am using your plugin and thank you for making such wonderful plugin.

I am facing small issue with connection line, when I drag any node to top or down the connection line leave his position from input (input_1)  and same for output (output_1) 

Please check my screenshot to get better idea of my query

**Without drag top or down** 
![without drag top or down effect](https://user-images.githubusercontent.com/102278225/159849816-3cf0d8e2-2170-4dea-83d5-d2e6a21877b5.png)

**Drag top side**
![top-side drag effect](https://user-images.githubusercontent.com/102278225/159849832-161127cb-c876-4207-8412-7afdbdc7dc84.png)

**Drag down side**
![down-side drag effect](https://user-images.githubusercontent.com/102278225/159850103-a86cb97f-b82d-46fe-917e-ee0384a67514.png)

Please help me out for this issue.

**Comment by jerosoler** [comment]
Uhmm... It looks like a css problem.

Try disabling your css layer to rule out the problem.
Persiste el problema?

Another option:
If it only happens at the end, try the "nodeMoved" event
https://github.com/jerosoler/Drawflow#events

And force an update of the node with the method "updateConnectionNodes('node-5')"
https://github.com/jerosoler/Drawflow#methods

**Comment by vinodjaunjalkar** [comment]
Hello jerosoler,,

Thank you for your reply and I tried to make changes as per your suggestions but was not fixed it.

Mentioned issue already exists in the default plugin but I don't know how to fix it.

When we move node extremally up or down then this issue arises.

Please check attached screenshot of default plugin.

 extremally up
![original-plugin-top](https://user-images.githubusercontent.com/102278225/160060408-bc496d9f-9ece-46b6-9d76-9d362397da97.png)

 extremally down
![original-plugin-down](https://user-images.githubusercontent.com/102278225/160060435-f427cd49-3b7a-45ce-b302-3759afd66c16.png)

**Comment by jerosoler** [comment]
The default view would be this:
![image](https://user-images.githubusercontent.com/30957047/160073791-421974b1-48c9-46bb-962a-6c16cee45911.png)

This would be with the extra layer of the demo: (https://jerosoler.github.io/Drawflow/)
![image](https://user-images.githubusercontent.com/30957047/160073825-c2923f07-d16d-43ac-9d79-4b0a8e627ae8.png)

In both cases it behaves correctly.

What browser are you using, in this case I am using chrome with the version: 99.0.4844.51

**Comment by vinodjaunjalkar** [comment]
Hi,

Thank you for your reply.

I am not facing the same issue in the Firefox browser however the issue is occurring in the chrome (Version 99.0.4844.82).

**Comment by jerosoler** [comment]
I have tried with the latest version of chrome.

Are you using Zoom in the browser?
- https://github.com/jerosoler/Drawflow/issues/292
- https://github.com/jerosoler/Drawflow/issues/218

Are you loading the latest version of the css? 
The demo is not using the latest version of the css.

**Comment by vinodjaunjalkar** [comment]
Hi,

I have modified the #drawflow css class and added zoom 80% and now its working perfectly.

Thanks for your support.
