### ISSUE TITLE
[FEATURE REQUEST] - Allow moving of input or output point to side or up and down

### ISSUE THREAD

**Issue by sujit-baniya** [jerosoler/Drawflow#382]
Currently the points for input and output are restricted to left or right of the node. Is it possible to make the points move to different edges of a node?

![image](https://user-images.githubusercontent.com/4959215/161314513-48614eb4-d903-4e34-b077-88d3748bfbac.png)

**Comment by sujit-baniya** [comment]
I'm able to switch the points but the curvature of connection seems odd.
Any idea to move the curve of curvature accordingly (move the curve along side of node being moved)

![image](https://user-images.githubusercontent.com/4959215/161324681-b1c94f1a-08e6-4eb2-8469-5d76bf63dc70.png)

**Comment by jerosoler** [comment]
View 
- #20

**Comment by sujit-baniya** [comment]
@jerosoler Thanks got it working. I made the points to shift on doubleclick on node

**Comment by sujit-baniya** [comment]
Only problem with the UI is the end of the connection remains unchanged until I drag the related node

![image](https://user-images.githubusercontent.com/4959215/161378061-9c23643e-22a7-4d14-ab12-d742460cea93.png)
