### ISSUE TITLE
Arrange layout

### ISSUE THREAD

**Issue by DomenicoFormoso** [jerosoler/Drawflow#383]
After importing Nodes and Connections is it possible to rearrange the layout? 
(At the time of import I do not know the size of the node)
Thank you for your work.

**Comment by jerosoler** [comment]
You could listen to the import event and iterate through the nodes to move them like so:
 - https://github.com/jerosoler/Drawflow/issues/112

Event import:
```javascript
editor.on('import', function(import) {
  console.log(import);
})
```
