### ISSUE TITLE
How do you remove a node ?

### ISSUE THREAD

**Issue by pkasson** [jerosoler/Drawflow#389]
If a user adds the Legend (the short keys and 'how to' node), it should not be saved with the flow.  Iterating through all the modules and then nodes, one can get the node id, but when calling:

```
 for (var key in modules)
 {
  var nodes = modules[key].data;

  for (var key2 in nodes)
  {
   var node =  nodes[key2];

   console.log(nodes[key2].id + ", " + nodes[key2].name + ", " + nodes[key2].inputs);

   if(nodes[key2].name == 'Legend')
   {
    var id = nodes[key2].id;

    editor.removeNodeId(id);
   }
  }
 }
```

it throws an error:

`e.slice is not a function. (In 'e.slice(5)', 'e.slice' is undefined)`

in removeNodeId function.

**Comment by jerosoler** [comment]
RemovenodeId function is:

**Correct**
```javascript
removeNodeId('node-5');
```

**Incorrect**
```javascript
removeNodeId(5);
```

**Comment by pkasson** [comment]
That worked - just to confirm, if you are doing this programmatically, as I showed above, the id will always be the same as that of the div, i.e.:

    editor.removeNodeId("node-" + id);

if the div id is 4, then node-4 will always be correct.

**Comment by jerosoler** [comment]
Yes!
