### ISSUE TITLE
data does not change if input value is changed using javascript or jquery

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#39]
Hi @jerosoler , hope you are doing well.
I have changed the input value of one of the nodes and later on when i console log the editor.export, the input value is not changed there...
how can i solve this? i want to change the input value using javascript and also want to reflect the change in node data.
thanks

**Comment by jerosoler** [comment]
Hi @MehbubRashid 

You have tried to add the new html in the node.
```javascript 
editor.drawflow.drawflow.Home.data[5].html = "...."
```

**Comment by jerosoler** [comment]
Hi @MehbubRashid 

The javascript change not fire events. 
You can send the input event this way when changing the data.

```javascript
document.querySelector("#node-1 > div.drawflow_content_node > div > input[type=text]").value = "hey MehbubRashid";
var evt = document.createEvent("HTMLEvents");
evt.initEvent("input", true, true);
document.querySelector("#node-1 > div.drawflow_content_node > div > input[type=text]").dispatchEvent(evt);
```

**Comment by MehbubRashid** [comment]
thanks @jerosoler , i will try it soon

**Comment by jerosoler** [comment]
You can also call it like this

```javascript 
document.querySelector("#node-1 > div.drawflow_content_node > div > input[type=text]").value = "hey MehbubRashid";
var event = new Event('input', {
    bubbles: true,
    cancelable: true,
});
document.querySelector("#node-1 > div.drawflow_content_node > div > input[type=text]").dispatchEvent(event);
```

**Comment by MehbubRashid** [comment]
works! thanks

**Comment by MehbubRashid** [comment]
> You can also call it like this
> 
> ```js
> document.querySelector("#node-1 > div.drawflow_content_node > div > input[type=text]").value = "hey MehbubRashid";
> var event = new Event('input', {
>     bubbles: true,
>     cancelable: true,
> });
> document.querySelector("#node-1 > div.drawflow_content_node > div > input[type=text]").dispatchEvent(event);
> ```

Hi, @jerosoler , i am just curious..can you provide a jquery implementation of this event fire code? because the jquery trigger() method is not working here..only the vanilla javascript dispatch is working.

**Comment by MehbubRashid** [comment]
Okay i have found the issue, wordpress uses pretty old version of jquery(1.12..) that version does not bubble up while using trigger() method..that might be causing the issue.

**Comment by jerosoler** [comment]
Mmmm... 

Try https://api.jquery.com/category/events/event-object/

Also with jquery you can mix javascript.

**Comment by MehbubRashid** [comment]
> Mmmm...
> 
> Try https://api.jquery.com/category/events/event-object/
> 
> Also with jquery you can mix javascript.

Yeah, i have mixed up js with jquery..but i was curious why jquery trigger was not working..then i came to find that my jquery version is very old and does not bubble up event
