### ISSUE TITLE
Delete context menu on connection selection

### ISSUE THREAD

**Issue by tomasp1189** [jerosoler/Drawflow#390]
Hey @jerosoler !! First of all, thanks for the awesome library! 

I was wondering if it is possible to include the Delete context menu for connections upon a connection selection. I have looked at the source code and the documentation and haven't found any options for this.

Thanks!

**Comment by jerosoler** [comment]
Second button on mouse, show contextmenu on connection. 

![image](https://user-images.githubusercontent.com/30957047/162977090-d754671d-dabe-4517-9b6c-40b3daaf0b09.png)

**Comment by tomasp1189** [comment]
@jerosoler Yeah! I noticed, but me and my team would like to show it everytime we select a connection to make it more intuitive for the users.

**Comment by jerosoler** [comment]
You can try this.

```javascript
    editor.on("clickEnd", function(e) {
      if(e.target.classList[0] === "main-path") {
          editor.contextmenu(e);
      }
    });
```
Seen in this issue:
- https://github.com/jerosoler/Drawflow/issues/47#issuecomment-708518414

**Comment by tomasp1189** [comment]
This worked!! Thanks, @jerosoler ! You are a rockstar!
