### ISSUE TITLE
Dark Mode / mode switching - is there a list of attributes and their relation ?

### ISSUE THREAD

**Issue by pkasson** [jerosoler/Drawflow#392]
Dark mode switching, based on the article you shared works great.

But, trying to understand the exact CSS values for a given attribute is hit and miss.

For example, I am using this:

```
 --dfLineStroke         : hsla(203, 96%, 60%, 0.914);   /*  line color  */


.drawflow .connection .main-path                          /*  line connectors  */
{
 stroke            : var(--dfLineStroke);
 stroke-width      : 2px;
}
  
```

But ... it is difficult to find things like line stroke / line hover.

**Comment by jerosoler** [comment]
You can see in the file all the css https://github.com/jerosoler/Drawflow/blob/master/src/drawflow.css, which is very little, in this case the lines:

```javascript
.drawflow .connection .main-path {
  fill: none;
  stroke-width: 5px;
  stroke: steelblue;
  pointer-events: all;
}
.drawflow .connection .main-path:hover {
  stroke: #1266ab;
  cursor: pointer;
}

.drawflow .connection .main-path.selected {
  stroke: #43b993;
}
```

**Comment by pkasson** [comment]
Great - thanks!
