### ISSUE TITLE
Text node

### ISSUE THREAD

**Issue by pkasson** [jerosoler/Drawflow#393]
How hard would it be to do a text node only text shows like an annotation in Vizio or just putting clear text next to notes for descriptions.

**Comment by jerosoler** [comment]
I could make a node with a textarea. And class transparent or color of note.

You might have a problem with the height of the node. You can see a solution here:
- https://github.com/jerosoler/Drawflow/issues/250

**Comment by pkasson** [comment]
Is it possible to have a different type of object for text and not a node ?  There is a line object - is that not different ?

It could be a small div with a transparent BG ... does that fit into this architecture ?

**Comment by jerosoler** [comment]
They are different yes, but they are in the core of the library.

There is no easy way to add a new element.

But a node is still a div. It can be made transparent with classes and without inputs and outputs.

You can see in the demo how there is a node without inputs and outputs. And another node with another type of color.
![image](https://user-images.githubusercontent.com/30957047/164616626-4929afe8-b998-4a50-bc5e-f4d1c0b3286b.png)

**Comment by pkasson** [comment]
Yep - I created a simple node that has a transparent BG with no connectors ... just need to eliminate the border and it will do the job.

Thanks !
