### ISSUE TITLE
Changing node name after rendering

### ISSUE THREAD

**Issue by pkasson** [jerosoler/Drawflow#394]
I am adding the ability to change the name of a node using a property grid - it works, but it loses the class:

$('#node-' + nodeId + " .title-box").text(updatedName);

It appears that when a node is created ... as you do dynamically in 'addNode', there is nothing that provides easy access to the title-box text - could you either add an id to that that title-box or provide a way to rename the text in the title box once rendered ?

**Comment by jerosoler** [comment]
> but it loses the class

Can you explain?
I do not understand that the class loses?

**Comment by pkasson** [comment]
Using the jQuery snippet above, I am attempting to only change the text in the title-box - but it clearly wipes out all children elements as well (could be a jQuery issue).  

1st screen shot shows the dialog where you can change aspects of the node - in this case, the display text.  Here you see the icon preceding the text:
 
![Screen Shot 2022-04-22 at 11 58 53 AM](https://user-images.githubusercontent.com/3072247/164752116-0441648a-9e65-46d1-8f81-acc216c6f194.png)

Here is the HTML markup before applying the text change (you can see the svg class, which was created from the font awesome css):

![Screen Shot 2022-04-22 at 11 59 54 AM](https://user-images.githubusercontent.com/3072247/164752247-9f798d87-5078-4d18-8d2f-fd0cb16620ad.png)

After the update - you can see visually the icon is gone from title-box:

![Screen Shot 2022-04-22 at 12 00 21 PM](https://user-images.githubusercontent.com/3072247/164752332-f934bc37-70f2-413f-b2b0-ad3969eaa25f.png)

... which matches the HTML:

![Screen Shot 2022-04-22 at 12 00 59 PM](https://user-images.githubusercontent.com/3072247/164752359-284d8943-981d-481c-848d-14db7190f8ba.png)

**Comment by jerosoler** [comment]
Use a span and save yourself the trouble.

```html
<div  class="title-box">
     <svg ....></svg>
     <span>Send Email</span>
</div>
```

and 

```javascript
$('#node-' + nodeId + " .title-box span").text(updatedName);
```

**Comment by pkasson** [comment]
Yep - that worked - thanks !
