### ISSUE TITLE
How to add icons to title-box

### ISSUE THREAD

**Issue by pkasson** [jerosoler/Drawflow#395]
Related to #80 , I have created a context / right click for the nodes where a menu pops for edit/delete.

I could not get the icons to show properly as shown in #80 ... any ideas on how to inline font-awesome or other icons on same line as text for the title-box ?

**Comment by jerosoler** [comment]
In the template:

```javascript
 var template = `
          <div>
            <div class="title-box">Title <div class="icons"><i class="fab fa-edit "><i class="fab fa-delete "></div></div>
            <div class="box">
              ...
            </div>
          </div>
          `;
          editor.addNode('node', 0, 1, pos_x, pos_y, 'node', { "name": ''}, template );
```

**Comment by shehab-01** [comment]
I wrote exactly as you showed but couldn't get desired result. 
<img width="119" alt="1" src="https://github.com/jerosoler/Drawflow/assets/78807929/02fca28f-09d8-4e2f-8ae0-22413bf06046">

**Comment by jerosoler** [comment]
@shehab-01  revise your css or add an image instead of an icon
