### ISSUE TITLE
Is there a way to print the flow diagram ?

### ISSUE THREAD

**Issue by pkasson** [jerosoler/Drawflow#397]
Is there a way today, or a plan to print out the flow to a file (jpeg, etc.) or printer ?

**Comment by pkasson** [comment]
This shows promise, and maybe I am not doing it right - but took the example in #67 and got an error:

[Node.CloneNode() not a function -dom-to-image.js](https://stackoverflow.com/questions/60238179/node-clonenode-not-a-function-dom-to-image-js)

It seems that it expects a single div and no children elements ?   (https://stackoverflow.com/questions/60238179/node-clonenode-not-a-function-dom-to-image-js)

**Comment by jerosoler** [comment]
It seems that more than one element is selected.

How is the element (code) selected?

**Comment by pkasson** [comment]
` function printFlow()
 {
  var node = document.getElementById('drawflow');

  domtoimage.toBlob(node).then(function (blob) 
  {
   window.saveAs(blob, 'drawflow.png');
  //  var img = new Image();
  //  img.src = dataUrl;
  //  document.body.appendChild(img);
  })
  .catch(function (error) 
  {
   alert('Oops, something went wrong !');
  });`

**Comment by jerosoler** [comment]
It seems to be correct, unless you have more than one "drawflow" node.

Ask in the developer library. https://github.com/tsayen/dom-to-image

**Comment by nbar10** [comment]
The domToImage will only print the items currently on viewable. If there are items hidden which you would have to scroll to, then it won't print them.
