### ISSUE TITLE
Multiple snap points destabilizes drawflow

### ISSUE THREAD

**Issue by CelticRugger** [jerosoler/Drawflow#401]
Clicking on line to create multiple points (more than 2) causes problems where it draws from other points not between the two points you are splitting.

Saving and reloading with several multiple points becomes very unstable to the point all the flow lines disappear. Especially as you attach lines between other nodes and start snapping those with in points. 

![image](https://user-images.githubusercontent.com/12037252/165727843-bf4b3580-3d34-40c8-bf77-b6142b98146b.png)

**Comment by jerosoler** [comment]
Add in your code to fix click point.
```javascript
editor.reroute_fix_curvature = true;
```

**Comment by jerosoler** [comment]
Try new version 0.0.56 fix addreroutepoint and removereroutepoint.
