### ISSUE TITLE
Re-centre the grid and panning to particular nodes on the grid 

### ISSUE THREAD

**Issue by gpack** [jerosoler/Drawflow#403]
Hi, 

These are relating more towards the canvas/grid area. 
And there are a couple of questions below:

QUESTION 1:
Is it possible to re-centre the canvas back to x:0, y:0. Since the canvas begins at 0,0 and nodes are dropped from that point, I think it's logical and a good idea to have a button where if the user hits it, it "re-centres" the map in the middle again. 
Because at the moment in the demo, if you pan away and get lost, the middle "search icon" doesn't do this, it just resets the zoom.  
How would I go about achieving this?

QUESTION 2:
I am keeping a list of nodes that I add to the gird in a list separately, and I would like to be able to click on any of these nodes in the list and would like the grid to centre itself to where the node is sitting on the grid. So almost like it's finding the node on the grid and moving to that position so that the node selected is seen in the middle.
How would I achieve something like this?

Thank you, any guidance would be very helpful.

Great work on the script by the way.

**Comment by jerosoler** [comment]
Question 1 view:
- https://github.com/jerosoler/Drawflow/issues/88

Question 2: 
Use the method described in question 1.
You can get the x,y coordinates of a node with the method: getNodeFromId 
https://github.com/jerosoler/Drawflow#methods

**Comment by gpack** [comment]
Amazing! Thanks so much for the super fast reply Jero. 
Even finding the previous answers that matched my questions so quickly was impressive.
