### ISSUE TITLE
Drawflow Nodes Input/Output port position changes but connector remains in same position when texts are added on the Node dynamically.

### ISSUE THREAD

**Issue by Aravinda93** [jerosoler/Drawflow#405]
@jerosoler Hi, I am trying to design some nodes and add some dynamic text on the Node. The problem I am facing is that if I have 2 nodes and a connection is established between the nodes, now if I try to add some text dynamically on the Drawflow Nodes then the Input & Output port position changes but the connector position remain the same due to which it looks something like this:

<img width="778" alt="Screenshot 2022-04-30 at 10 01 06" src="https://user-images.githubusercontent.com/29374160/166097306-07092230-f0fd-43e0-829c-e8869c3743c6.png">

As we can see ports and connectors are not aligned properly. Is there any way we can make the port position fixed? or based on port movement move the connector also accordingly?

I have added my code here for your reference: https://codesandbox.io/s/cocky-matan-kvqnu?file=/assets/css/drawflow.css
Sample play area: https://kvqnu.sse.codesandbox.io/

Steps to reproduce:
1. Add `Identifiers1` and `Identifiers2` into the Drawflow.
2. Build the connection between `Identifiers1` output port to `Identifiers2` input port.
3. Now change the URN to WebURI on `Identifiers1` and in `Identifier2`. We can observe that ports are moved on the Drawflow Node but the connection remains fixed.

**Comment by jerosoler** [comment]
Onchange option Force update connection nodes. 
Example:
```javascript
editor.updateConnectionNodes('node-4');	
```

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for your quick response. But I am unable to follow a bit. Can you please let me know which onChange you are referring to? I am unable to find any onChange method in `Drawflow documentation`.

If you are referring to onChange of the value then it's being imported from another component.

**Comment by jerosoler** [comment]
In your case you could call it from the function `instanceIdentifiersSyntaxChang` and in funcion call:
```
this.$df.updateConnectionNodes(id)
```

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot. I tried adding it within the function as well as within mounted but still, it seems like the port is moving a bit, and connections are not updated. Can you please let me know what am I missing here?

Following is the simple code I have: https://codesandbox.io/s/cocky-matan-kvqnu?file=/components/IdentifiersNode.vue

**Comment by jerosoler** [comment]
Updateconnectipn function parameter is `node-5` no a number of id

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot this is working as expected :)

**Comment by Aravinda93** [comment]
Without Scoped:

![Without Scoped](https://user-images.githubusercontent.com/29374160/168595607-700c099f-5adf-4d6c-86ab-ac9885f2e659.gif)


Scoped:
![With Scoped](https://user-images.githubusercontent.com/29374160/168595645-60edfb85-c409-40f0-8483-39e2d60bb4a7.gif)

**Comment by jerosoler** [comment]
Without scope.

You have to have a minimum of css out of scope.

Inside the node you can have whatever scope you want, but always inside the `drawflow_content_node` container.

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for your response.

Sorry but I am unable to understand completely. Do you mean to say that I must use it without `scoped`?

**Comment by jerosoler** [comment]
All css in draflow: https://github.com/jerosoler/Drawflow/blob/master/src/drawflow.css
Always bring classes ahead: `.parent-drawflow` or `.drawflow`

It would not have to reach another component.

**Comment by Aravinda93** [comment]
@jerosoler Thanks a lot for the response.

As you mentioned I have updated my `Drawflow.css` and now the classes are at the top than other styles I have added `scoped` but still for some reason some styles are not applied.

Please find the stylesheets here: https://codesandbox.io/s/cocky-matan-kvqnu?file=/assets/css/drawflow.css

Following is the code for importing the styles:
```
<style scoped src="@/assets/css/drawflow.css">
</style>
```

Am I doing anything wrong here or missing something? Can you please once have a look and provide your suggestion?

**Comment by jerosoler** [comment]
Use without scoped

```
<style src="@/assets/css/drawflow.css">
</style>
```

**Comment by Aravinda93** [comment]
Thanks a lot its working as expected :)
