### ISSUE TITLE
Exemple with nuxt

### ISSUE THREAD

**Issue by capoia** [jerosoler/Drawflow#409]
Hi, Does anyone have an example in NUXT, I can't seem to get it to work.

**Comment by jerosoler** [comment]
What is the problem?

**Comment by capoia** [comment]
A similar example of VUE in nuxt would be amazing, I think it would add a lot!
But my problem is: I'm following the documentation, I've already added transpile in nuxt.config, and my page looks like this:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/21159928/166470866-081e40a4-a0f3-4663-8fd5-03b09f4dc3c6.png">

O que ta me retornando é:

<img width="1661" alt="image" src="https://user-images.githubusercontent.com/21159928/166471033-0316fbef-bf04-4e2f-95ef-f6d0b387b04f.png">

If, I try to add a node, using this code:
var html = `
<div><input type="text" df-name></div>
`
var data = { name: '' }

this.editor.addNode('github', 0, 1, 150, 300, 'github', data, html)

it returns me: Cannot read properties of null (reading 'appendChild')

**Comment by jerosoler** [comment]
editor.start() is missing.

```javascript
this.editor = new Drawflow(id,Vue, this);
this.editor.start();
```

**Comment by capoia** [comment]
I added the line and the problem persists

**Comment by capoia** [comment]
I managed to progress.
I'm looking at this example: https://github.com/jerosoler/drawflow-vue3-example and trying to adapt to NUXT.

I'm having problems in node1.vue, on mounted you set EL.value.....
but right above you define it as NULL, like him. ai access el.value and el is null ?
Which is exactly the error you're giving me! (annot read properties of null (reading 'value'))
Here's the code:
![n1](https://user-images.githubusercontent.com/21159928/166567968-3c5136ef-a276-4a76-9e25-77a40bde6e59.png)

**Comment by jerosoler** [comment]
The sidebar to drag the nodes, you have to do it yourself you can follow the example of vue3.
