### ISSUE TITLE
input text cannot be selected by dragging mouse

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#41]
Hi, its a major problem i think...if you have any input or textarea inside a node, you cannot select the texts inside it by dragging your cursor...because the node itself gets moved instead of the texts being selected..

is there any way to  prevent the node drag mechanism while inside in any input or textarea?

**Comment by MehbubRashid** [comment]
okay, i have fixed that by overwriting the click (mousedown) handler by adding this:
`
// Only drag if element parent is not the wrapper
                        if(e.target.closest(".drawflow-body-wrapper") == null) {
                            this.drag = true;
                        }
`

then i have added an extra wrapper (drawflow-body-wrapper) in my node html...

it works pretty great..but will it cause any extra side effect? @jerosoler

**Comment by jerosoler** [comment]
The solution you propose I think works without a problem. But I found it interesting and I have added it.

Added in version 0.0.24  `draggable_inputs`

```javascript
editor.draggable_inputs = false;
```
Affects inputs, textarea and contenteditable.

**Comment by MehbubRashid** [comment]
Awesome! Thanks :D
