### ISSUE TITLE
[Bug] Right click when creating a connection.

### ISSUE THREAD

**Issue by xaimepardal** [jerosoler/Drawflow#411]
Right-clicking while creating a new connection in the "editor" allows you to access the delete connection option. The browser returns an unhandled error.

A possible improvement would be to listen to the "create connection" event and as long as this connection is not created or canceled, the option to delete connection with right click will be disabled.

The error in console.

> Uncaught TypeError: Cannot read properties of undefined (reading 'slice') at i.click (drawflow.min.js:1:7493)

**Comment by jerosoler** [comment]
Thanks @xaimepardal 

I look to fix it.

**Comment by jerosoler** [comment]
Fix in version 0.0.58 ;)
