### ISSUE TITLE
Auto-selecting the most recently added node

### ISSUE THREAD

**Issue by gpack** [jerosoler/Drawflow#415]
Is it possible to auto-select the most recently added node?
So basically, once you drag it on the canvas it is auto-selected (highlighted) automatically. 

How would I go about doing this? 

thanks.

**Comment by jerosoler** [comment]
View:
- https://github.com/jerosoler/Drawflow/issues/360#issuecomment-1041230729

**Comment by gpack** [comment]
thanks. 
The #360 comment does work, but it doesn't actually highlight the node as a normal click would.
Example: when you click on a node, it selects and highlights it.
I need to replicate this exact behaviour.

**Comment by gpack** [comment]
Thanks Jero! That did it, it works well.
