### ISSUE TITLE
how to change the node size at synchronous time

### ISSUE THREAD

**Issue by zhizhico** [jerosoler/Drawflow#418]
**while using such as method, how to change the node size at synchronous time**

addNodeInput (id)
addNodeOutput (id)
removeNodeInput (id, input_class)
removeNodeOutput (id, output_class)

**Comment by jerosoler** [comment]
By default the size is changed
![image](https://user-images.githubusercontent.com/30957047/168004127-73df6e38-cc3a-4ad8-96fb-8670000096b7.png)

Adding `editor.addNodeInput(7)` in demo.
![image](https://user-images.githubusercontent.com/30957047/168004250-9eb2480f-8438-42e0-b22c-db7e8336f85f.png)

**Comment by zhizhico** [comment]
Thanks,jero !
It is wrok finely.
