### ISSUE TITLE
Some 'df-values' not getting exported or imported

### ISSUE THREAD

**Issue by rudrak23** [jerosoler/Drawflow#421]
Am using editor.export() and saving the JSON to mysql (JSON datatype) when you click on the 'save' button and retrieving the mysql data onPageLoad and import it to drawflow using editor.start() and editor.import(responseObj) . 

For the element below, df-condition (select element) data gets populated but df-condition-value does not. Help please?

`<div>
            <div class="title-box"><i class="fab fa-telegram-plane"></i> Condition </div>
            <div class="box">
              <p>Select condition</p>
              <select df-condition>
                <option value="notequal">Equals</option>
                <option value="equal">Not Equal</option>
              </select>
              <p>Compare with</p>
              <input df-condition-value value="" type="text" placeholder="Enter value"/>
            </div>
          </div>`

**Comment by jerosoler** [comment]
Use:
```javascript
editor.addNode('aaa', 1, 3, 300, 200, 'aaa', { condition: { select: 'equal', value: 'test'}}, `<div> <div class="title-box"><i class="fab fa-telegram-plane"></i> Condition </div> <div class="box"> <p>Select condition</p> <select df-condition-select> <option value="notequal">Equals</option> <option value="equal">Not Equal</option> </select> <p>Compare with</p> <input df-condition-value value="" type="text" placeholder="Enter value"/> </div> </div>` );
```

Change select  to:
```html
<select df-condition-select>
```

And the addnode function:
```javascript
 { condition: { select: 'equal', value: 'test'}}
```

**Comment by rudrak23** [comment]
Works. Can you please help me understand what ` select: 'equal', value: 'test'}` does?

**Comment by jerosoler** [comment]
It is the data passed in the creation of the node.

They are the data that can be modified with the df-* attributes.

It will be the data that will be exported.
