### ISSUE TITLE
Add Custom function for image

### ISSUE THREAD

**Issue by RaviGuggilam** [jerosoler/Drawflow#422]
in below image, I want to add function for click on image icon. Is it possible

![image](https://user-images.githubusercontent.com/66006795/168532829-ceec7e97-e1cf-43c4-ba79-85366ffff4f2.png)

**Comment by jerosoler** [comment]
You have many options. Some are:
```javascript
editor.addNode('bbb', 1, 0, 850, 200, 'bbb', {}, `<img src="https://avatars.githubusercontent.com/u/66006795?s=88&v=4" width="20px" onclick="console.log('test')">` );
```

Other option:
```javascript
editor.addNode('ccc', 1, 1, 850, 370, 'ccc', {}, `<img src="https://avatars.githubusercontent.com/u/66006795?s=88&v=4"  width="20px" class="button-edit">`);

editor.on("clickEnd", (e)=> {
      if(e.target.classList[0] === "button-edit") {
        console.log("ClICKBUTTON");
      }
    })
```

**Comment by RaviGuggilam** [comment]
I tried below example and getting following error

**Error:Uncaught ReferenceError: clickFunction is not defined**

editor.addNode('bbb', 1, 0, 850, 200, 'bbb', {}, `<img src="https://avatars.githubusercontent.com/u/66006795?s=88&v=4" width="20px" onclick="customFunction('test')">` );

const customFunction = (name)=>{
    console.log(name);
}

**Comment by jerosoler** [comment]
Are you using another name?

clickFunction != customFunction

**Comment by RaviGuggilam** [comment]
function name is propertyDetails().

**Comment by RaviGuggilam** [comment]
its my typo error...modified the above comment.

html: `<div style="text-align:right"><i style="cursor:pointer" onClick="propertyDetails()" class="fa-solid fa-pen-to-square"></i></div>`

propertyDetails() {
      alert('hi');
}

**Comment by RaviGuggilam** [comment]
ng-click for angular-js but for Angular 2+ it is (click)

ng-click is replaced with (click)
