### ISSUE TITLE
How can i disable some event - (createConnection, deleteConnection) ?

### ISSUE THREAD

**Issue by dotrungit91** [jerosoler/Drawflow#429]
I'm making an example that has 2 modes: read-only and editable
Read-only mode: can show and hover on connection. Along with that, it is not possible to create and delete (connection, nodes) as well as move nodes.
Is it possible? 
Thank you very much!

**Comment by jerosoler** [comment]
There are three types of view, none solve it?

```javascript
editor.editor_mode = 'edit'; // Default
editor.editor_mode = 'fixed'; // Only scroll
editor.editor_mode = 'view'; //
```
I don't quite understand your "read-only" module

**Comment by dotrungit91** [comment]
@jerosoler thank you that is` editor.editor_mode = 'edit';`
