### ISSUE TITLE
connection line is not properly synced with output or inputs

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#43]
![error](https://user-images.githubusercontent.com/34944930/93900251-fa612600-fd16-11ea-9a15-a2e769348627.gif)
Hi, @jerosoler , when the node height gets changed, the connection line does not sync with it and stays in the same place. when i move the node, then it syncs...what can be the solution for it?

**Comment by jerosoler** [comment]
Hello @MehbubRashid 

Wow!! nice design!!! 

Force update connections with: 

Mehtod | Description
--- | ---
`updateConnectionNodes(id)` | Update connections position from Node Ex id: node-x

**Comment by MehbubRashid** [comment]
@jerosoler works great, thanks!

**Comment by shailesh345** [comment]
> ![error](https://user-images.githubusercontent.com/34944930/93900251-fa612600-fd16-11ea-9a15-a2e769348627.gif)
> Hi, @jerosoler , when the node height gets changed, the connection line does not sync with it and stays in the same place. when i move the node, then it syncs...what can be the solution for it?

Nice design

**Comment by dina-setiana** [comment]
Hi ,
I tried to use `updateConnectionNodes ` but the connection line still won't sync properly.
I tried to use updateConnectionNodes after `addConnection`, on `connectionCreated` but none of them works.
Could you tell me where should I put the updateConnectionNodes code??

**Comment by jerosoler** [comment]
Hi @dina-setiana 

The nodes are shown to you correctly? 
View commun problem: https://github.com/jerosoler/Drawflow/issues/123#issuecomment-784149366

When you create the connection from one node to another does it work correctly?

Are you loading the data from an external source? Maybe with a settimeout? https://github.com/jerosoler/Drawflow/issues/286



Jero

**Comment by dina-setiana** [comment]
@jerosoler 
Thank you for the reply.

I'm loading data from external source and settimeout solved my problem.
Works like a charm. Thank you once again
