### ISSUE TITLE
Entering text into textarea throws readonly error

### ISSUE THREAD

**Issue by pkasson** [jerosoler/Drawflow#430]
I have a component that has a textarea element.  When I enter data into it, I get the following html error:

<img width="328" alt="Screen Shot 2022-05-19 at 8 28 48 AM" src="https://user-images.githubusercontent.com/3072247/169293519-929848a0-054d-443c-b34d-7bd1a1560a74.png">

<img width="1221" alt="Screen Shot 2022-05-19 at 8 27 44 AM" src="https://user-images.githubusercontent.com/3072247/169293501-841165ff-b15a-4fe7-aa2d-cbec7d400cc4.png">

**Comment by jerosoler** [comment]
I've tried this and it works fine:
```javascript
    editor.addNode('aaa', 1, 3, 300, 200, 'aaa', { textarea: 'hii'}, `aaa<textarea df-textarea></textarea>` );
```

How do you add the node?
 
Are you using any framework?

**Comment by pkasson** [comment]
Not using any frameworks - here is the add function:

`
editor.addNode(name, leftConnector, rightConnectors, posX, posY, classOverride, data, componentHTML);
`

The html is simply a node with a textarea.

**Comment by jerosoler** [comment]
It does not produce any error.

You can try yourself, look at the example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css"/>
  <script src="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.js"></script>
</head>
<body>
<div id="drawflow"></div>
  <style>
    #drawflow { 
      position: relative;
      text-align:initial;
      width: 100%;
      height: 800px;
      border: 1px solid red;
    }
</style>
<script>
    var id = document.getElementById("drawflow");
    const editor = new Drawflow(id);
    editor.start();    
    editor.addNode('aaa', 1, 3, 300, 200, 'aaa', { template: 'hii'}, `<div><div class=title-box><i class=fas fa-database></i> Data</div><div class=box>Enter text to send<textarea id=data df-template></textarea></div></div>` );
</script>
</body>
</html>
```

**Comment by pkasson** [comment]
I see that ... must be something in my code, but it is odd.  Thanks for looking.
