### ISSUE TITLE
How do I set node id ahead of time or add a connection based on a different property?

### ISSUE THREAD

**Issue by AK3030** [jerosoler/Drawflow#431]
I am iterating through a list of nodes to add them to the editor. I also have a list of all the connections between nodes (based on the names of nodes). I am migrating from a different editor so this information is pre-existing. The 'addConnection' method seems to only work with ids but I have no way of knowing the mapping between node names and ids.

`
nodes.forEach((node) => {
     this.editor.addNode(node.name, 1, 1, left, top, 'job-node', {}, 'NodeClick', 'vue')
}

connections.forEach((connection) => {
    this.addConnection(??, ??, ??, ??)
}

`

I also can't get a basic example to work where I do 

`
this.editor.addConnection(1, 2, 'ouput', 'input')
`

The docs also don't specify what 'output_class' and 'input_class' are? Is that the class of the node or the input and output circles? It would be helpful to have a more detailed example in the docs.

**Comment by jerosoler** [comment]
Get id of node create with:
```javascript
const idNode = editor.addNode('bbb', 1, 0, 900, 200, 'bbb', {},  `ddd` );
```
`idNode` return of id of node.

For conection:
example: 
```
editor.addConnection(15,16,'output_1','input_1');
```
15 and  16 id's of nodes. 
and ouputs and inputs:
![image](https://user-images.githubusercontent.com/30957047/169469595-2a727148-8b20-484f-9dba-9cb504dc200c.png)

**Comment by AK3030** [comment]
Thanks.

Is there a way to get the output class in a similar way? It doesn't appear that the addNodeOutput and input methods return anything.

**Comment by jerosoler** [comment]
They don't return anything, but the last input or output is always added.
You can know before or after adding, getting the node information with `getNodeFromId`.
