### ISSUE TITLE
Element Ordering in JSON

### ISSUE THREAD

**Issue by rudrak23** [jerosoler/Drawflow#432]
Is there any documentation on how to traverse the export json manually in ASC or DESC order based on the linked connections?

Tried accessing the ['data'] node of the json, the element ordering is based on when the elements are added to the canvas and not the linkages. Help?

**Comment by jerosoler** [comment]
The connections do not have a creation date or any identifying id.
So you can't sort by ASC or DESC for connection.

It could listen to the `connectionCreated` event and add the date of the connection created. So I could sort the export by creation date.

**Comment by jerosoler** [comment]
For that you only have to filter the exported data.

Go through the export looking for the nodes that do not have any input, only outputs and from here you already know the connections that each node has.
