### ISSUE TITLE
Cool library, thanks for making it!

### ISSUE THREAD

**Issue by danielcasler** [jerosoler/Drawflow#433]
I've been playing around with Drawflow/Vue 3 and I must say, it's a pretty darn cool! Thanks for making it!

**Comment by jerosoler** [comment]
Thanks!  ❤

If it's.
Here is an example from vue3.
https://github.com/jerosoler/drawflow-vue3-example
And the vue3 demo: https://jerosoler.github.io/drawflow-vue3-example/

You can also contribute with a donation: https://paypal.me/jerosoler
