### ISSUE TITLE
Connecting line by dragging onto node

### ISSUE THREAD

**Issue by gpack** [jerosoler/Drawflow#436]
I would like to connect the connection to a node by simply dragging the line onto a node (instead of trying to match to the input circle). 
Is this possible?

Because in my case I will only ever have 1 input circle for all my nodes, so instead of always trying to drop the connection line exactly onto the input circle, I'd like to be able to drop the connection line onto the node. So once it hovers over the node, it will connect.

This makes it a bit more user-friendly, because sometimes it gets a bit tricky trying to drop the line onto the output circle.

**Comment by jerosoler** [comment]
Use:
```javascript
editor.force_first_input = true;
```

**Comment by gpack** [comment]
Great, that works well.

Is there a way to detect that the user has dragged the line onto a node? I would like to add some CSS styling or highlight the node when user is dragging a line on top of the node.

**Comment by jerosoler** [comment]
I could do something like this, add the css class "hover-drop"

```css
    .drawflow .drawflow-node.hover-drop {
        background: pink;
    }
```

```javascript
    let dragElementHover = null;
    let last_x = 0;
    let last_y = 0;
    editor.on("mouseMove", ({x,y}) => {
        if(conStat) {
            console.log("test");
            const eles = document.elementsFromPoint(x,y);
            const ele = eles.filter( ele => ele.classList[0] === "drawflow-node");
            if(ele.length > 0 && ele[0].id.slice(5) !== conStatId) {
                dragElementHover = ele[0];
                dragElementHover.classList.add("hover-drop");
            } else {
                if(dragElementHover != null) {
                    dragElementHover.classList.remove("hover-drop");
                    dragElementHover = null;
                }
            }
        }
        last_x = x;
        last_y = y;
    })

    let conStat = false;
    let conStatId = null;
    editor.on("connectionStart", (out) => {
        conStatId = out.output_id;
        conStat = true;
    })

    editor.on("connectionCancel", () => {
        conStat = false;
        conStatId = false;
        const ele = document.querySelector(".hover-drop");
        ele.classList.remove("hover-drop");
    })

    editor.on("connectionCreated", () => {
        conStat = false;
        conStatId = false;
        const ele = document.querySelector(".hover-drop");
        ele.classList.remove("hover-drop");
    })
```

**Comment by gpack** [comment]
Thanks for the code Jero. It works, but there's a small bug with below code.

If you drag a connection line and never drop it on a node, the below code breaks:

editor.on("connectionCancel", () => {
        conStat = false;
        conStatId = false;
        const ele = document.querySelector(".hover-drop");
        ele.classList.remove("hover-drop");      <------------------------------ **this line breaks**
 })

**Error**: Cannot read properties of null (reading 'classList')  

Also, if you have 2 nodes overlapping on top of each other, and you drag the connection line across both the nodes, it only removes the "hover-drop" class from one of the nodes, the other node stays selected.

**Comment by jerosoler** [comment]
It was a quick example.
Use a querySelectorAll and loop to remove the class.

**Comment by gpack** [comment]
Yep will do that. 
And thanks again for the quick (but accurate) example.
