### ISSUE TITLE
Why is are the nodes not properly connecting by dragging input to output?

### ISSUE THREAD

**Issue by cacious7** [jerosoler/Drawflow#437]
When I try to connect a node's input to another node's output, the line is not displayed correctly, it is displayed on top of both nodes instead of between them. I have added a screenshot for clarity. I am using Vue2. The grid isn't showing either after copying the CSS from your theme builder.
![image](https://user-images.githubusercontent.com/17464196/170295560-d87933c1-2b81-4054-bb09-53bb8f6dc9fc.png)

**Comment by jerosoler** [comment]
Is it loading the css before starting?

Try to add the css in the head

If you try without the theme generator, only with the minimum css configuration, the line also happens?

Are you using any third party css library?

Have you tried this:

- https://github.com/jerosoler/Drawflow/issues/123#issuecomment-784149366
Other similar issues:
- https://github.com/jerosoler/Drawflow/issues/208
- https://github.com/jerosoler/Drawflow/issues/327

If not fixed, can you provide a demo?

**Comment by cacious7** [comment]
Actually, I have just realized that the values I set, were for the ".parent-drawflow" (main container). The width and height for the child .drawflow were not set by me to 100% each. This must be an existing problem on your side. Please check it.
![image](https://user-images.githubusercontent.com/17464196/170307208-68ba6502-1495-4189-8fdc-9ed3f141b456.png)
If the height is set to vh, it fixes the problem, however, the grid is still not visible even after setting it in the theme builder. What could be the issue with that?

**Comment by cacious7** [comment]
The grid is still not displaying, I can't figure out why. I have followed your guidelines but it isn't working. I have also tried adding the body CSS you've given me to the .drawflow container parent element but there is no visible change. Please advise.

**Comment by jerosoler** [comment]
Create a codepen or similar to display your code,

**Comment by jerosoler** [comment]
View example with vue2:
- https://github.com/jerosoler/Drawflow/issues/263#issuecomment-930449781
