### ISSUE TITLE
Is it possible to disable editor dragging?

### ISSUE THREAD

**Issue by xaimepardal** [jerosoler/Drawflow#438]
Is it possible to disable editor dragging? Reading the source code, I see that the editor_selected variable controls this. Is it possible that it never be true without rewriting the editor.click() function?

Thanks for your project. I love it.

**Comment by jerosoler** [comment]
Thanks

Try:
```javascript
editor.on('clickEnd', () => {
      editor.editor_selected = null;
    })
```

**Comment by xaimepardal** [comment]
Thanks!
It's right.
