### ISSUE TITLE
Can we have 'unselect node' events?

### ISSUE THREAD

**Issue by douglas-s3nd** [jerosoler/Drawflow#44]
So, considering we may want to bind any kind of function to the nodeSelected event, it would be very usefull to have an event to bind functions when the user clicks on any empty space between nodes.

**Comment by jerosoler** [comment]
Hello @douglas-s3nd 

oh it would be interesting.
 
I am looking to add a new event or the nodeSelected event that returns a null value.

**Comment by douglas-s3nd** [comment]
Hmmm...Not sure if a nodeSelected event returning null would be triggered in the same `conditions
I would suggest introducing it along these lines within the click(e) funcion, precisely after the "switch (this.ele_selected.classList[0])", since it's when the node is actually been unselected

![image](https://user-images.githubusercontent.com/68653212/93918902-632eab00-fce3-11ea-8041-ba14f4bd7ac4.png)

At a glance seemes to me it wouldn't imply any collateral damage in other features, but I'm not sure

**Comment by jerosoler** [comment]
A new event has been added so as not to create breaking changes

New version 0.0.25

Added new events: 

- click event
- keydown event
- export event
- **nodeUnselected event**
- contextmenu event 

Update info, view new events: https://github.com/jerosoler/Drawflow#events

**Comment by douglas-s3nd** [comment]
Nice work man!
Pretty useful 👍
