### ISSUE TITLE
on method question

### ISSUE THREAD

**Issue by danielcasler** [jerosoler/Drawflow#441]
Hello,

As part of my evaluation of Drawflow I noticed the **on** method, which registers events. dispatch uses the events object to call events. Where are events actually registered? What I mean is, **on** does not appear to be called anywhere?

Thanks!

**Comment by jerosoler** [comment]
It is to listen for events in your code.

See in the documentation: https://github.com/jerosoler/Drawflow#events

For example, when you delete a node, save to the database...

**Comment by danielcasler** [comment]
Ah, I understand now. on is not used by Drawflow and is there as an API method that allows users to add listeners. All of the dispatch calls are "in-case" the user has added listeners. 

Thanks for the expeditious response!

**Comment by jerosoler** [comment]
So you can extend the functionalities without modifying the library.

Example simple:
- https://github.com/jerosoler/Drawflow/issues/438

Example complex: 
- https://github.com/jerosoler/Drawflow/issues/423
