### ISSUE TITLE
Is it possible to modify only the connection while fixing the position of the node?

### ISSUE THREAD

**Issue by cer718** [jerosoler/Drawflow#444]
Hi,

I want the user to be able to modify only the connections of nodes.
I tried changing the editor mode, but couldn't find that function.
can you give me some advice?

Thanks in advance for your help.

**Comment by jerosoler** [comment]
Using events to prevent drag nodes. 

Try:
```javascript
    editor.on("clickEnd", function(event) {
        if(editor.node_selected != null) {
            editor.drag = false;
        }
    });
```

**Comment by cer718** [comment]
> Using events to prevent drag nodes.
> 
> Try:
> 
> ```js
>     editor.on("clickEnd", function(event) {
>         if(editor.node_selected != null) {
>             editor.drag = false;
>         }
>     });
> ```

It works well :)

Thanks for your help
