### ISSUE TITLE
Overlapping nodes issue. Rearranging the entire flow when a node changes position

### ISSUE THREAD

**Issue by LozanCorina** [jerosoler/Drawflow#452]
I searched through your forum and did not find a clear answer if the problem with overlapping nodes can be solved. 
Another problem is: when I change the connection to 2 nodes, the whole scheme is rearranged;.
When ordering, create large spaces between nodes
![quiz-flow-error](https://user-images.githubusercontent.com/61292431/172643173-9193af68-cffd-4463-b341-364a8e2ba598.png)

I attach my code below:

```
Object.keys(nodes).forEach(function(key) {
                        _this._graph.setNode(key,{width: 118, height: 62});

                        Object.keys(nodes[key].inputs.input_1.connections).forEach(function(key2) {
                            _this._graph.setEdge(nodes[key].inputs.input_1.connections[key2].node, key);
                        });
                    });

                    dagre.layout(this._graph);

                    this._graph.nodes().map(id => {
                        const node = this._graph.node(id);

                        if (nodes[id] && nodes[id].pos_x === '' && nodes[id].pos_y === '') {
                            nodes[id].pos_x = node.x;
                            nodes[id].pos_y = node.y;
                        }
                    })

                    this.editor.import({drawflow: {Home: {data: nodes}}});
```

**Comment by LozanCorina** [comment]
> do you re-import?

right, after changing connections I re-import flow.
I search answer for the problem with overlapping nodes can be solved?

**Comment by jerosoler** [comment]
Overlapping nodes on import?
Or 
Overlapping nodes with mouse movement?
