### ISSUE TITLE
How do I access a node component from outside that component?

### ISSUE THREAD

**Issue by cacious7** [jerosoler/Drawflow#453]
I have a master component where all the nodes are being created. I want to access the Vue instance of an active node, such as on created, removed, or selected where the node id is provided.

In short, how do I match the id with a corresponding Vue component instance so that I can access the component properties?

**Comment by jerosoler** [comment]
I don't understand you.

Do you want to get the id?
- https://github.com/jerosoler/Drawflow/issues/271#issuecomment-944042114

View al issues vue:
- https://github.com/jerosoler/Drawflow/issues?q=label%3AVue

**Comment by cacious7** [comment]
no, not the id of the node. I want to get the actual Vue component instance associated with the node.

**Comment by jerosoler** [comment]
The component is mountend in `drawflow_content_node` for vue2 can be accessed by the variable __vue__.

View example: 
- https://github.com/jerosoler/Drawflow/issues/306#issuecomment-973864382

For vue3 I don't know.
