### ISSUE TITLE
How to identify all ports are connected or not

### ISSUE THREAD

**Issue by sethupsanil** [jerosoler/Drawflow#455]
- I want to show an error if the nodes are not connected 
![image](https://user-images.githubusercontent.com/22883917/174135250-32c082b0-ddac-49d0-a31c-267453567b0e.png)

is it possible?

**Comment by jerosoler** [comment]
It is possible.

You can get the information of the nodes. With: `getNodeFromId(id) ` here you can see if there are connections or not.

It could also help you detect when there are new connections or they are deleted with the events: `connectionCreated` and `connectionRemoved`
