### ISSUE TITLE
Node's component is not getting updated [Vue 2]

### ISSUE THREAD

**Issue by shrey7070** [jerosoler/Drawflow#457]
Hi @jerosoler,
Thanks for making our life easy. 🥇 
I am working on Vue 2 and Made the flow as per my requirement.
For updating the Node data I am using `this.editor.updateNodeDataFromId(id,data)` . which is updating the draw flow object. but the issue is that I am unable to update the content in the Node's component.
For example
before update: 

![image](https://user-images.githubusercontent.com/41335030/174284699-24ab09ba-589b-413d-bde9-b37c647b9825.png)
after update: - **Drawflow object updated but node component is not**

![image](https://user-images.githubusercontent.com/41335030/174284724-4dda6f35-b874-4566-8c98-b9311c134eb2.png)

Thanks in advance :)

**Comment by jerosoler** [comment]
Hello! Thanks! 

`updateNodeDataFromId` not refresh component. 

View:
https://github.com/jerosoler/Drawflow/issues/37#issuecomment-717822302

**Comment by shrey7070** [comment]
And It worked! :)
Thanks again Jerosoler

I do have the following question,
After importing the Nodes connectors and lines are not coming into alignment, could you please help me with that.
![image](https://user-images.githubusercontent.com/41335030/174473985-97027cb4-0203-43da-8877-1032a5e4ccc8.png)

Thanks Again :)

**Comment by jerosoler** [comment]
View: 
- https://github.com/jerosoler/Drawflow/issues/349#issuecomment-1021931919
Or: 
- https://github.com/jerosoler/Drawflow/issues/267

**Comment by shrey7070** [comment]
hi @jerosoler,

Thanks for the quick response.

I tried with using **this.editor.updateNodesConnection('node-2')**, but it is not doing anything.
then I tried to console **this.editor.updateNodesConnection()**, but it is showing as undefined.

**Comment by jerosoler** [comment]
Is 
editor.updateConnectionNodes('node-2') without this

**Comment by shrey7070** [comment]
As I am using Vue js, I am getting an error called "editor is not defined" without using **this**

**Comment by shrey7070** [comment]
Hi @jerosoler,
I used the **setTimeout** function to **updateConnecttionNodes** and it is working fine

Thanks for your help.

**Comment by Samandar0021305** [comment]
> Hi [@jerosoler](https://github.com/jerosoler), I used the **setTimeout** function to **updateConnecttionNodes** and it is working fine
> 
> Thanks for your help.


I also had this problem, if you do it with settimeOut it might work fine, but it doesn't work in places with very fast internet, I have the same problem right now
