### ISSUE TITLE
'onConnectionRemoved' called before 'onConnectionCreated'

### ISSUE THREAD

**Issue by MyIsaak** [jerosoler/Drawflow#459]
For some reason, my code emits the 'onConnectionRemoved' before 'onConnectionCreated' when I try to delete a connection after it is made.

Steps to reproduce below: (See [codepen.io](https://codepen.io/MyIsaak/pen/VwQNLqp?editors=1111))
```js
let editor = new Drawflow(document.querySelector("#drawflow"));
editor.start();

editor.addNode("Home", 0, 1, 10, 10, "node-test", {}, "Drag from here =>", false);
editor.addNode("Home", 1, 0, 300, 10, "node-test", {}, "<= Connect to here", false);

// Issue: When we delete just after creating a connection, the events
// below get fired incorrently. First "connectionRemoved", then "connectionCreated"
editor.on("connectionCreated", deleteCreatedConnection)

editor.on("connectionCreated", () => console.log("connectionCreated"));
editor.on("connectionRemoved", () => console.log("connectionRemoved"));

// Registering the listener after fixes the problem somehow?
// editor.on("connectionCreated", deleteCreatedConnection)


function deleteCreatedConnection({input_id, output_id, input_class, output_class}) {
  editor.removeSingleConnection(output_id, input_id, output_class, input_class);
}
```

**Comment by jerosoler** [comment]
Have you modified the library?
Have you overridden any method?

Can you show your code?

**Comment by MyIsaak** [comment]
Hi, @jerosoler thanks for the swift reply. I've not modified, nor overrode any methods. I've edited my issue including a [codepen example](https://codepen.io/MyIsaak/pen/VwQNLqp?editors=1111)

**Comment by jerosoler** [comment]
Hello!

I see what the problem is.
It's not really a problem. It's the way it runs. It runs synchronously.

Callbacks in events are executed on the moment.

The events are fired one by one.

Example: 
## 1
```javascript
  editor.on("connectionCreated", () => console.log("connectionCreated1"));
    editor.on("connectionCreated", () => console.log("connectionCreated2"));
    editor.on("connectionCreated", () => console.log("connectionCreated3"));
```
Return:
```
connectionCreated1
connectionCreated2
connectionCreated3
```

In this case execute 1, 2, 3.  How the events were recorded in order of creation. 

## 2
If we now execute this other:
```javascript
editor.on("connectionCreated", (info) => {
        console.log("connectionCreated1")
        deleteCreatedConnection(info);
    });
editor.on("connectionCreated", () => console.log("connectionCreated2"));
editor.on("connectionCreated", () => console.log("connectionCreated3"));
editor.on("connectionRemoved", () => console.log("connectionRemoved"));
```
Return:
```
connectionCreated1
connectionRemoved
connectionCreated2
connectionCreated3
```

Until one event is finished, the next one is not executed.

Explanation in a diagram.

![image](https://user-images.githubusercontent.com/30957047/174447121-6dea8e84-2e9c-415b-b833-6166d5c16bd1.png)

The flow follows the red numbers.

The question is why are you using the same event twice?

**Comment by MyIsaak** [comment]
Thanks for the thorough explanation, and yes internally events are handled in a synchronous fashion, however logically could sort the scheduled events to avoid this. 

> The question is why are you using the same event twice?

I wrote a wrapper class that makes instantiates Drawflow and make internal changes, like modifying the curves and listening to `connectionCreated` to delete specified connections. After instantiating my wrapper class, one might want to use the same event twice. In this case, I add a listener to `connectionCreated`, and `connectionRemove`, to update the state of the connected nodes, but events aren't played in order.
