### ISSUE TITLE
Fit to Screen Option

### ISSUE THREAD

**Issue by nexline** [jerosoler/Drawflow#460]
Hi @jerosoler,

Thanks man, great project, congratulations. 🥇

Is there any way to resize and center align all drawflow? Fit to screen option

Example:

![image](https://user-images.githubusercontent.com/47707975/174429606-22a86482-32fc-4e65-85a4-d9f035f2b2b9.png)

**Comment by jerosoler** [comment]
Hi! Thanks!

The red box. You can make it any size you want. It's css.

If you mean moving the canvas view:
- #88
