### ISSUE TITLE
Create node in position where connection line is released

### ISSUE THREAD

**Issue by my-nd** [jerosoler/Drawflow#461]
First of all thank you for developing this awesome tool. I am using it in an internship and I'm really enjoying it.

So, is there a way to draw a node when the connection line is released in the position it's released? Just like shown in the image below? It would be useful but I can't find a way to get that position to draw a new node.

<img width="402" alt="Screenshot_2" src="https://user-images.githubusercontent.com/81083405/174828795-fea6e2a8-c463-4c03-b417-daa42657be15.png">

**Comment by jerosoler** [comment]
You can use the **connectionCancel** and **mouseMove** events.

connectionCancel: To see when the connection was canceled.
mouseMove: To determine the position of the mouse.

**Comment by my-nd** [comment]
@jerosoler Makes sense. Thanks!

**Comment by MyIsaak** [comment]
Any pointers on how to calculate the mouse position given **offset** and **zoom**?

**Comment by jerosoler** [comment]
View demo in folder docs in repo.

**Comment by MyIsaak** [comment]
Thanks, but is this a bug or really intended? Can we just multiply `pos_x` by `1 / editor.zoom` instead of `editor.precanvas.clientWidth / (editor.precanvas.clientWidth * editor.zoom)` or is it a typo?
```
pos_x = pos_x * ( editor.precanvas.clientWidth / (editor.precanvas.clientWidth * editor.zoom)) - (editor.precanvas.getBoundingClientRect().x * ( editor.precanvas.clientWidth / (editor.precanvas.clientWidth * editor.zoom)));
```

**Comment by MyIsaak** [comment]
Nevermind. It works btw. Thanks!
