### ISSUE TITLE
Remove Node does not work

### ISSUE THREAD

**Issue by RoyaghRamo** [jerosoler/Drawflow#463]
Hello, I've tried removing a node using `removeNodeId`, but it gives me this error 

![image](https://user-images.githubusercontent.com/57964781/175327507-2aca3359-5217-40b3-840f-29b97cf6336a.png)

I've checked the repo, and this is what I found

![image](https://user-images.githubusercontent.com/57964781/175327603-5e67c825-3f35-4b63-a2f8-ab0007e0713e.png)

Seems that slicing a number is the problem.

Did I misunderstand something?

**Comment by jerosoler** [comment]
Paramter is `node-x` not a number. View in readme.

For older versions. 
- #442

**Comment by RoyaghRamo** [comment]
> Paramter is `node-x` not a number. View in readme.
> 
> For older versions.
> 
> * [node-id v. integer inconsistency? #442](https://github.com/jerosoler/Drawflow/issues/442)

Ohh I see, thanks
