### ISSUE TITLE
Restrict node overlap while dragging existing node and new node 

### ISSUE THREAD

**Issue by Sri-5555** [jerosoler/Drawflow#465]
How to restrict overlap of node while dragging existing or  adding new node over other node 
![overlap node](https://user-images.githubusercontent.com/108112427/175485242-75c4f9f5-9b41-47ee-913f-cd0d8ecdbfb8.PNG)

**Comment by jerosoler** [comment]
By default there is nothing implemented.
But what would have to be done is to detect the collisions.

https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection


You could use the events of "nodeCreated", "nodeMoved". To detect when a node is created or moved.

Once this is done, detect if there is a collision and if there is, move the node.

Move node with javascript:
- https://github.com/jerosoler/Drawflow/issues/112

**Comment by codeandcore** [comment]
Hi @jerosoler 
can you please help me that how can i get position of any node in drawflow when i move using (nodeMoved event)
so i can manage collision detaction

Thanks

**Comment by jerosoler** [comment]
Use  `editor.export()` to gell all info. 

Or `document.querySelectorAll(".drawflow-node ");` and get left and top position

**Comment by vnomohan** [comment]
is there any sample code for this? could you please share it here
