### ISSUE TITLE
How can I render an array of data taken from database?

### ISSUE THREAD

**Issue by it2468** [jerosoler/Drawflow#467]
Hi @jerosoler ,
First of all, I really like your project!
I'm learning and planning to use the Drawflow library in my vue 2 project.
But I am wondering is there a way to calculate and render the positions of nodes of an array of data retrieved from the DB.
Example:
![image](https://user-images.githubusercontent.com/46559502/176086706-f291cc22-101e-4378-aca9-ac48957fa295.png)

**Comment by jerosoler** [comment]
Hello,

All nodes are added with an X,Y position.

If you know the child nodes and the parent nodes, I think you will be able to calculate the distance well. And the size of the nodes.

There is currently no automatic way to do this.

Another way is to move the node via javascript once it is mounted:
- https://github.com/jerosoler/Drawflow/issues/112

**Comment by it2468** [comment]
Thank you,

So is there a way to get data from that array to assign to component then pass that component to node?

I don't know how to pass a react component to node.

Can you tell me how to do that?

**Comment by jerosoler** [comment]
> So is there a way to get data from that array to assign to component then pass that component to node?

That is depends on how you extract the data from your DB

> I don't know how to pass a react component to node.

There is no react wrapper for now.
But you can see examples of react.
- #290 
- #21

**Comment by it2468** [comment]
Thank you so much!
