### ISSUE TITLE
Get export code with inputs

### ISSUE THREAD

**Issue by nishanshashintha1996** [jerosoler/Drawflow#468]
I have tested your demo, But if I change GitHub starts node input value, the export option doesn't include that changed text. How can I solve this issue? Is there any way to get updated JSON?

**Comment by jerosoler** [comment]
The change appears in the "data" of the node.
Not in the html of the node, that html is not modified.

![image](https://user-images.githubusercontent.com/30957047/176365403-3ce0138f-8827-49ba-9d66-972776a5e094.png)

The data you want to modify from inputs, textareareas, selects. You can use the df-* attributes 
https://github.com/jerosoler/Drawflow#node-example

```javascript
var html = `
<div><input type="text" df-name></div>
`;
var data = { "name": '' };

editor.addNode('github', 0, 1, 150, 300, 'github', data, html);
```

df-name  it updates automatically.
