### ISSUE TITLE
Dragging node without selecting the node

### ISSUE THREAD

**Issue by gpack** [jerosoler/Drawflow#481]
Is it possible to drag a node, but don't select it?
I would like the user to be able to select a node only when they click on the node (single click), but not while they are dragging it.

Currently I am detecting "dragging" of node using below code:
`	if(editor.node_selected && editor.drag) {	// dragging node
	}
`
But if I unselect the node when they start dragging, the "nodeSelected" event  still executes. So I can't place any code in that function because it will always fire when user is dragging the node.

**Comment by jerosoler** [comment]
Either you create a variable for nodeselect to skip or you can move nodes via javascript.
- https://github.com/jerosoler/Drawflow/issues/112

**Comment by gpack** [comment]
Ok thanks.
