### ISSUE TITLE
Importing data in a string format causes output to be 'undefined'

### ISSUE THREAD

**Issue by dinukapj** [jerosoler/Drawflow#482]
Love the library. I have an issue with the import, however. My Exported JSON looks like this:

```
var test = '{ "drawflow": { "Home": { "data": { "1": { "id": 1, "name": "begin", "data": {}, "class": "begin", "html": "\n<div>\n<div class=\"title-box\"><i class=\"fas fa-forward\"></i> Begin</div>\n</div>\n", "typenode": false, "inputs": {}, "outputs": { "output_1": { "connections": [] } }, "pos_x": 50, "pos_y": 50 } } }, "Other": { "data": {} } }}'

editor.import(test);
```

When I try to run the app, it ends up with this message:

```
drawflow.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'Home')
    at i.load (drawflow.min.js:1:4152)
    at i.import (drawflow.min.js:1:45397)
    at reader.onload (automation.html:658:38)
```

But if I remove the quotation marks from the sample JSON, it works:

```
var test = { "drawflow": { "Home": { "data": { "1": { "id": 1, "name": "begin", "data": {}, "class": "begin", "html": "\n<div>\n<div class=\"title-box\"><i class=\"fas fa-forward\"></i> Begin</div>\n</div>\n", "typenode": false, "inputs": {}, "outputs": { "output_1": { "connections": [] } }, "pos_x": 50, "pos_y": 50 } } }, "Other": { "data": {} } }}
```

However, since I'm trying to load the JSON from a file on the computer (from a file selector), the output format will most likely be in string format. How can I resolve this?

**Comment by jerosoler** [comment]
Thanks

Use JSON.parse to convert to object. 

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

```javascript 
var test = JSON.parse(YOUR_STRING_TEXT);
```

**Comment by dinukapj** [comment]
> Thanks
> 
> Use JSON.parse to convert to object.
> 
> https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
> 
> ```js
> var test = JSON.parse(YOUR_STRING_TEXT);
> ```

Thank you very much! That worked. I'll close this issue.
