### ISSUE TITLE
Is there a way to change the input?

### ISSUE THREAD

**Issue by fajardokarl** [jerosoler/Drawflow#483]
Hi, been using this for a project and it's been good. But a requirement was added on our side of the project. Is there a way to change the input? In our case, we need to make the connection detached when we draw the input on a node that has a connection.

**Comment by jerosoler** [comment]
Hi @fajardokarl 

You mean this?
- https://github.com/jerosoler/Drawflow/issues/35

Using the connectionCreated event we remove the previous connection. And we leave the new one.

**Comment by fajardokarl** [comment]
Thank you for the reply @jerosoler.
What I meant was like resetting the connection when you drag an input with the connection, It will detach.
![image](https://user-images.githubusercontent.com/49085510/178431303-4b30a656-00b1-421b-90dc-e85bf9449640.png)

Then the output connection will remain and other end will make the mouse pointer its end position again, like this.
![image](https://user-images.githubusercontent.com/49085510/178431652-4e0017c7-7982-4906-8af6-daa7bdcfbcbb.png)

**Comment by jerosoler** [comment]
I think this could work.

```javascript 
    editor.on("clickEnd", (e) => {
        if(e.target.classList[0] === "input") {
            const nodeId = e.target.closest(".drawflow-node").id.slice(5);
            const nodeInfo = editor.getNodeFromId(nodeId);
            if(nodeInfo.inputs[e.target.classList[1]].connections.length > 0) {
                const removeConnectionInfo = nodeInfo.inputs[e.target.classList[1]].connections[0];
            
                editor.removeSingleConnection(removeConnectionInfo.node, nodeInfo.id, removeConnectionInfo.input, e.target.classList[1]);
                
                var evt = new MouseEvent("mousedown", {
                    view: window,
                    bubbles: true,
                    cancelable: false,
                });
                editor.container.querySelector(`#node-${removeConnectionInfo.node} .outputs .output.${removeConnectionInfo.input}`).dispatchEvent(evt);
            }
        }
    });
```

**Comment by AbhayUpadhyay96** [comment]
Hi @jerosoler 
I am using this Library in my Project So My Requirement is I need to connect the Nodes from Node Left, Right, Top, and Bottom(User can connect node from any side he can give input from any side) but as of now we can connect the node only to node Left Side So is there any way to do this?
Thanks in Advance Your Support will Highly appreciated.
