### ISSUE TITLE
Df-* value not getting exported

### ISSUE THREAD

**Issue by rudrak23** [jerosoler/Drawflow#490]
I have an inputbox and using autofill suggestions. 

Problem is when i normally type into the text input field, that value is properly exported in json. But if i set the input value using javascript as element.value = "test", this value is not exported in javascript.

document.getElementById("assign").value = "test"; //does not export this input box value

<input id="assign" df-assigned-role type="text" onkeyup="searchName(this);" placeholder="Start typing"/>

**Comment by jerosoler** [comment]
Not automatically change with javascript. Use **updateNodeDaraFromId**

```javascript
document.getElementById("recommendations").value = "test"; 
editor.updateNodeDataFromId(5, { name: 'test' });
```
