### ISSUE TITLE
Half connector

### ISSUE THREAD

**Issue by tanishq1398** [jerosoler/Drawflow#491]
Hi @jerosoler ,
Is it possible to have half connections, where connectors can be drawn from any node and can be left at anywhere without attaching it to any other node. Also is it possible to have text over the connectors just as shown in image
![sample](https://user-images.githubusercontent.com/110106426/181252741-dd51ffb7-16f8-457a-a213-e8bd822013d8.png)

**Comment by jerosoler** [comment]
It's not possible.
Still an invisible node could be created using this method.
- https://github.com/jerosoler/Drawflow/issues/461

For label text view: 
- https://github.com/jerosoler/Drawflow/issues/18#issuecomment-991167477
