### ISSUE TITLE
Error when creating a connection

### ISSUE THREAD

**Issue by TimKeitany** [jerosoler/Drawflow#493]
I get this error when I make a connection between two nodes.

drawflow.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'connections')
    at i.dragEnd (drawflow.min.js:1:12791)

I am using the UI.

What might be the issue here?

Thanks

**Comment by jerosoler** [comment]
How are you adding the nodes?

It seems that it does not find the connection id in the stat.

**Comment by TimKeitany** [comment]
I am importing all the nodes first. Below is my json:

{
  "drawflow": {
    "Home": {
      "data": {
        "26": {
          "id": 26,
          "name": "database",
          "data": {},
          "class": "database",
          "html": "<div><div class=\"title-box\"><i class=\"fas fa-database\"></i> Database</div></div>",
          "typenode": false,
          "inputs": {
            "input_9": {
              "connections": []
            }
          },
          "outputs": {
            "output_21": {
              "connections": []
            }
          },
          "pos_x": 585,
          "pos_y": 87
        },
        "29": {
          "id": 29,
          "name": "questionnaire",
          "data": {},
          "class": "questionnaire",
          "html": "<div><div class=\"title-box\"><i class=\"fas fa-clipboard-list\"></i> Questionnaire</div></div>",
          "typenode": false,
          "inputs": {},
          "outputs": {
            "output_24": {
              "connections": []
            }
          },
          "pos_x": 84,
          "pos_y": 148
        }
      }
    }
  }
}

I suspect the issue emanates from this json but I cant seem to spot it.

**Comment by jerosoler** [comment]
The default inputs and outputs start in 1 in all nodes. Order is correlative. 
```json
"inputs": {
                        "input_1": {
                            "connections": []
                        },
                        "input_2": {
                            "connections": []
                        }
                    },
                    "outputs": {
                        "output_1": {
                            "connections": []
                        },
                        "output_2": {
                            "connections": []
                        }
                    },
```

**Comment by TimKeitany** [comment]
Hi @jerosoler .
Thanks for the feedback. 
The issue is now resolved after I implemented your instructions.
