### ISSUE TITLE
webpack fails to run

### ISSUE THREAD

**Issue by yaswanth-git** [jerosoler/Drawflow#494]
![Screenshot from 2022-08-05 11-12-29](https://user-images.githubusercontent.com/70765767/183009457-33723735-d46b-4bce-97c4-a8781b6d4659.png)

**Comment by jerosoler** [comment]
View:
https://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b

**Comment by yaswanth-git** [comment]
babel-loader is already configured, still the error is showing up 
![Screenshot from 2022-08-07 15-07-17](https://user-images.githubusercontent.com/70765767/183284801-fb0ce0d9-0bed-4471-86f0-c301b57440e5.png)

**Comment by jerosoler** [comment]
Try with babel preset es2015
