### ISSUE TITLE
Click event of the canvas

### ISSUE THREAD

**Issue by nishanshashintha1996** [jerosoler/Drawflow#500]
Hi devs, Thank you for the quick responses to my previous issues. So right now I need to know, Is there any way to catch the canvas mouse click event? Once the user clicks out of the nodes, I need to catch it. But I can not use the nodeUnSelect event. Because if I click another node, it is executing. So I need to catch the canvas click or select. 

Thanks

**Comment by jerosoler** [comment]
Hi! @nishanshashintha1996 

Try event "click" or "clickEnd":
```javascript
editor.on("click", (e) => {
        if(e.target.classList[0] === 'parent-drawflow' || e.target.classList[0] === 'drawflow') {
            console.log("Click on Canvas");
        }
    })
```
