### ISSUE TITLE
Dynamically added input text values not updating after import

### ISSUE THREAD

**Issue by rudrak23** [jerosoler/Drawflow#501]
I have a button which dynamically adds a new input text box to the node when you click it (class elemAddBtn). 

The issue is when you generate this new node and dynamically add input text boxes, then click on the 'save' button, the new text boxes are exported and imported just fine. But after importing the saved export, when you add the new input text box by clicking the button of class elemAddBtn and clicking on 'save' again, the newly added element doesn't show up and are not exported and imported properly.

`$(document).on("click",".elemAddBtn",function() {
       var dom_element = $(this)[0];
      var element = "<div class='box'><input df-element" + count + " type='text' class='form-control' placeholder='Enter Option'></div>";
      parent.innerHTML += element;

      editor.drawflow.drawflow.Home.data[nodeID].html = dom_element.parentNode.parentNode.innerHTML;
});`

Help?

**Comment by jerosoler** [comment]
The first OK.
The second KO.

What is the value of exporting before and after?

Take a look at this example of how to add images.
- https://github.com/jerosoler/Drawflow/issues/252

This is also about the same:
- #40

**Comment by rudrak23** [comment]
My jquery function which adds new input box to node

`$(document).on("click",". elemAddBtn",function() {
      var dom_element = $(this)[0];   //Jquery to Javascript
      var idStr = dom_element.parentNode.parentNode.parentNode.parentNode.id;
      console.log(dom_element.parentNode.parentNode.innerHTML);
      var idArr = idStr.split("-");
      var nodeID = idArr[1];
      var parent = dom_element.parentNode.parentNode.children[4];
      var optionsCount = parent.children.length;

      var element = "<div class='box'><input df-option" + optionsCount + " type='text' class='form-control' placeholder='Enter Option'></div>";
      parent.innerHTML += element;

      console.log(dom_element.parentNode.parentNode.innerHTML);

      editor.drawflow.drawflow.Home.data[nodeID].html = dom_element.parentNode.parentNode.innerHTML;
    });`

> Step 1: Create new node
> Step 2: Add new dynamic input box and enter value as '1'
> Step 3: Add new dynamic input box and enter value as '2'
> Step 4: Add new dynamic input box and enter value as '3'

**Export Data:**
`{
	"drawflow": {
		"Home": {
			"data": {
				"9": {
					"id": 9,
					"data": {
						"select": "dropdown",
						"option0": "1",
						"option1": "2",
						"option2": "3",
						"option3": "",
						"option4": "",
						"option5": "",
						"option6": "",
						"option7": "",
						"option8": "",
						"option9": "",
						"assigned": "",
						"option10": "",
						"option11": "",
						"option12": "",
						"option13": "",
						"option14": "",
						"option15": "",
						"option16": "",
						"option17": "",
						"option18": "",
						"option19": "",
						"option20": "",
						"option21": "",
						"option22": "",
						"option23": "",
						"option24": "",
						"option25": "",
						"option26": "",
						"option27": "",
						"option28": "",
						"option29": "",
						"option30": "",
						"option31": "",
						"option32": "",
						"option33": "",
						"option34": "",
						"option35": "",
						"option36": "",
						"option37": "",
						"option38": "",
						"option39": "",
						"option40": "",
						"option41": "",
						"option42": "",
						"option43": "",
						"option44": "",
						"option45": "",
						"option46": "",
						"option47": "",
						"option48": "",
						"option49": "",
						"option50": "",
						"option51": "",
						"option52": "",
						"condition": {
							"value": ""
						}
					},
					"html": "\n            <div class=\"title-box\"><i class=\"fab fa-userinput \"></i> Ask for User Input</div>\n            <div class=\"box\">\n                <input df-assigned=\"\" class=\"assigned assignedinput\" type=\"text\" onkeyup=\"searchAssignedKeyup(this);\" placeholder=\"Type name(s)\">\n                <div class=\"recommendations\"></div>\n            </div>\n            <div class=\"box\">\n              <label style=\"color:white;\" for=\"cars\">Input Type</label>\n                <select df-select=\"\" name=\"userInput\" id=\"userInput\" class=\"userInputList\">\n                  <option value=\"decision\">Approve / Reject</option>\n                  <option value=\"excel\">Upload Excel File</option>\n                  <option value=\"text\">Text</option>\n                  <option value=\"number\">Number</option>\n                  <option value=\"date\">Date</option>\n                  <option value=\"dropdown\">Dropdown</option>\n                  <option value=\"checkbox\">Checkbox</option>\n                  \n                </select>\n            </div>\n            <hr style=\"display: block;\">\n            <div class=\"listElements\" style=\"display: block;\"><div class=\"box\"><input df-option0=\"\" type=\"text\" class=\"form-control\" placeholder=\"Enter Option\"></div><div class=\"box\"><input df-option1=\"\" type=\"text\" class=\"form-control\" placeholder=\"Enter Option\"></div><div class=\"box\"><input df-option2=\"\" type=\"text\" class=\"form-control\" placeholder=\"Enter Option\"></div></div>\n            <hr style=\"display: block;\">\n            <div class=\"box\" style=\"color: white; display: block;\">\n              <button style=\"width: 10rem; color:white;\" type=\"button\" class=\"btn btn-primary optionsBtn\"><i class=\"fa fa-plus\"></i>&nbsp;&nbsp;&nbsp;Add Option</button>\n            </div>\n            <div class=\"box\" style=\"color:white;\">\n              <p style=\"color:white;\">Enter Instruction</p>\n              <textarea df-userinput-value=\"\"></textarea>\n            </div>\n          ",
					"name": "userinput",
					"class": "userinput",
					"pos_x": 190,
					"pos_y": 30,
					"inputs": {
						"input_1": {
							"connections": []
						}
					},
					"outputs": {
						"output_1": {
							"connections": []
						}
					},
					"typenode": false
				}
			}
		}
	}
}`

> Step 5: Click Save button (Exports into mysql)
> Step 6: Refresh page (Imports from mysql)
> Step 7: Add new dynamic input box for node and enter value as '4'
> Step 8: Click Save button (Exports into mysql)
> Step 9: Refresh page (Imports from mysql) (THIS SHOWS ONLY 3 INPUT BOXES ADDED IN STEPS 2,3,4 AND DOES NOT SHOW THE NEW INPUT BOX ADDED in Step 7)

**Export Data:**
`{"drawflow": {"Home": {"data": {"9": {"id": 9, "data": {"select": "dropdown", "option0": "1", "option1": "2", "option2": "3", "option3": "4", "option4": "", "option5": "", "option6": "", "option7": "", "option8": "", "option9": "", "assigned": "", "option10": "", "option11": "", "option12": "", "option13": "", "option14": "", "option15": "", "option16": "", "option17": "", "option18": "", "option19": "", "option20": "", "option21": "", "option22": "", "option23": "", "option24": "", "option25": "", "option26": "", "option27": "", "option28": "", "option29": "", "option30": "", "option31": "", "option32": "", "option33": "", "option34": "", "option35": "", "option36": "", "option37": "", "option38": "", "option39": "", "option40": "", "option41": "", "option42": "", "option43": "", "option44": "", "option45": "", "option46": "", "option47": "", "option48": "", "option49": "", "option50": "", "option51": "", "option52": "", "condition": {"value": ""}}, "html": "\n            <div class=\"title-box\"><i class=\"fab fa-userinput \"></i> Ask for User Input</div>\n            <div class=\"box\">\n                <input df-assigned=\"\" class=\"assigned assignedinput\" type=\"text\" onkeyup=\"searchAssignedKeyup(this);\" placeholder=\"Type name(s)\">\n                <div class=\"recommendations\"></div>\n            </div>\n            <div class=\"box\">\n              <label style=\"color:white;\" for=\"cars\">Input Type</label>\n                <select df-select=\"\" name=\"userInput\" id=\"userInput\" class=\"userInputList\">\n                  <option value=\"decision\">Approve / Reject</option>\n                  <option value=\"excel\">Upload Excel File</option>\n                  <option value=\"text\">Text</option>\n                  <option value=\"number\">Number</option>\n                  <option value=\"date\">Date</option>\n                  <option value=\"dropdown\">Dropdown</option>\n                  <option value=\"checkbox\">Checkbox</option>\n                  <!--<option value=\"camera\">Camera</option>\n                  <option value=\"gallery\">Camera / Gallery</option>\n                  <option value=\"sound\">Sound Recording</option>-->\n                </select>\n            </div>\n            <hr style=\"display: block;\">\n            <div class=\"listElements\" style=\"display: block;\"><div class=\"box\"><input df-option0=\"\" type=\"text\" class=\"form-control\" placeholder=\"Enter Option\"></div><div class=\"box\"><input df-option1=\"\" type=\"text\" class=\"form-control\" placeholder=\"Enter Option\"></div><div class=\"box\"><input df-option2=\"\" type=\"text\" class=\"form-control\" placeholder=\"Enter Option\"></div></div>\n            <hr style=\"display: block;\">\n            <div class=\"box\" style=\"color: white; display: block;\">\n              <button style=\"width: 10rem; color:white;\" type=\"button\" class=\"btn btn-primary optionsBtn\"><i class=\"fa fa-plus\"></i>&nbsp;&nbsp;&nbsp;Add Option</button>\n            </div>\n            <div class=\"box\" style=\"color:white;\">\n              <p style=\"color:white;\">Enter Instruction</p>\n              <textarea df-userinput-value=\"\"></textarea>\n            </div>\n          ", "name": "userinput", "class": "userinput", "pos_x": 190, "pos_y": 30, "inputs": {"input_1": {"connections": []}}, "outputs": {"output_1": {"connections": []}}, "typenode": false}}}}}`

**Comment by jerosoler** [comment]
In step number 8 is it being saved? It is safe?
In step number 7 the export shows you the input?
In the last export I only see 3 entries until df-option2.

**Comment by rudrak23** [comment]
Fixed the issue! It was the way I was fetching the node id, after reimporting the dom structure changed and idStr was being returned as undefined.

```
//var idStr = dom_element.parentNode.parentNode.parentNode.parentNode.id;
var idStr = dom_element.closest(".drawflow_content_node").parentNode.id;
```
