### ISSUE TITLE
Node Drag by Icon or Similar

### ISSUE THREAD

**Issue by jf19742016** [jerosoler/Drawflow#502]
Hello,

I am creating flow items with title and detail as per the image.  I want the user to be able to edit them by clicking on them. This is clashing when clicking the node, as the node then becomes draggable or the text is selected and treated as a new node.  Is it possible to add say a small box or icon in the bottom right hand corner that can be used to drag the node around instead and not make the whole node selectable?  

![image](https://user-images.githubusercontent.com/24268325/186222567-1f688f28-c7ca-45ce-aa7f-1acef6ea903e.png)

Thanks

**Comment by jerosoler** [comment]
You could reverse the solution of this comment. Or adapt-it with some kind of css class.
- https://github.com/jerosoler/Drawflow/issues/423#issuecomment-1134886506

**Comment by jf19742016** [comment]
Thank you as ever, I can do something with that.
