### ISSUE TITLE
Connection from input to output

### ISSUE THREAD

**Issue by urveerendra** [jerosoler/Drawflow#503]
Hi @jerosoler , 
was trying to customize the plugin for getting the connections from input to outputs.

Most things working as expected, 
 1. draw connections from input, 
 2. continue drawConnection when dragged,
 **3.** but in the end "mouseUp" or "dragEnd(e)" is not identifying the output class and node-id, when drag is ended.
 Tried setting it from the "mouseMove" and even from the mouselastPosition.
Failing to get output-id when drag-ended.

any light on this issue?

**Comment by jerosoler** [comment]
Hello

In the click function, you should have an "input" option on the switch.
I would create a new variable connectionStart = "input or output".

I would duplicate the drawConnection to drawConnectionInput function.

I dragEnd will do the reverse function of creating connection.

You can get the output id and the output_class from the event itself. It would have to be in the variable "ele_last".

**Comment by urveerendra** [comment]
Perfect!.
I implemented the same approach for achieving it,
1. created switch for "input" click and starting "drawConnection"
2. drawConnectionInput, which draws the svg(main-path) till it encounters "dragEnd".
3. But only in DragEnd, **I am always getting "ele_last" as "svg(main-path)" .**
       **issue->I am not gettin "ele-last" as "output" element for completing the connection.**

**Comment by jerosoler** [comment]
Try to modify the z-index of the outputs. Perhaps the connection that is being created is above. I is the last element it detects.

Even with the connections, they should have an event pointer none AND a z-index 0.

**Comment by urveerendra** [comment]
Hi @jerosoler, 
Thanks a lot for all your suggestions, "pointer-events":none. Worked! :)

So finally, we can connect from Inputs to outputs points.
