### ISSUE TITLE
get input value inside modal

### ISSUE THREAD

**Issue by maxkaoppp** [jerosoler/Drawflow#505]
Hello @jerosoler ,

Firstly great library!!

I make a modal that contain input.Now I want to get input value and pass to another label inside the drawflow node by save button click.How can I do that

![image](https://user-images.githubusercontent.com/58621821/186615701-846fa929-e38b-4c94-8ccf-610c4d4f1659.png)

Thanks

**Comment by jerosoler** [comment]
Using method `updateNodeDataFromId`

View: 
https://github.com/jerosoler/Drawflow#methods

**Comment by maxkaoppp** [comment]
Is there an example?I still can't update label inside the data-node

**Comment by jerosoler** [comment]
In label update the html with javascript. 

View example: 
- https://github.com/jerosoler/Drawflow/issues/252
