### ISSUE TITLE
Distinction between user created events and programmatically created events

### ISSUE THREAD

**Issue by dsoiM** [jerosoler/Drawflow#51]
I am using JS to modify node connections from external sources during editing. 
Then user also has possibility to manually create node connections.
The event is fired for both when using `editor.on('connectionCreated', function(conn) {`
Do you think there is a way or a trick to catch only user created connections? Maybe combining somehow to click event?
I tried to use Promises `var prom1 = new Promise(function(resolve, reject){
    	editor.on('connectionCreated',resolve);
	});
	var prom2 = new Promise(function(resolve, reject){
		editor.on('click',resolve);
	});
	Promise.all([prom1, prom2]).then(function(){
    	alert('click + connection create');
	});`
But that's not quite achieving this..

**Comment by jerosoler** [comment]
Hello,
I could do something like that right?

```javascript 
let ConnectionProg = false;
    function addConnectionProg(id_output, id_input, output_class, input_class) {
      ConnectionProg = true;
      editor.addConnection(id_output, id_input, output_class, input_class);
    }

    editor.on("connectionCreated", function(info) {
      if(ConnectionProg === true) {
        ConnectionProg = false;
      } else {
        console.log(info);
      }
    });

    addConnectionProg(1,5,'output_1','input_1');
```
It's useful?

**Comment by dsoiM** [comment]
Thank you @jerosoler! That seems great. I was also devising another solution in the meanwhile, which might work as well but yours is better:
```javascript
editor.on('click', function(conn) {
    	connectionfromClick = true;
	});
    
    
editor.on('connectionCreated', function(conn) {
		if (connectionfromClick) {
			console.log('User created connection');	
		}
		connectionfromClick = false;
});
```
And then i must set connectionfromClick =false every time I create a connection programmatically
