### ISSUE TITLE
Create guid on every

### ISSUE THREAD

**Issue by maxkaoppp** [jerosoler/Drawflow#510]
Hello @jerosoler ,
Thanks again for a cool tool and I need your advice.

I need every node has UUID as the primary ID for each node of each flow is unique. Additionally,  I need every modal has UUID as the primary ID.How can I do that in javascript var?
![image](https://user-images.githubusercontent.com/58621821/187303045-9ee8faaf-e1ec-4d9b-96ac-11a98c8c7e73.png)

**Comment by jerosoler** [comment]
Use `useuuid` to generate a UUID for node. 

```javascript
editor.useuuid = true;
```


It's tricky to pass the uuid to the node content.

You would have to detect with the created node and modify with a uuid.

Or before assigning the html generate a unique uuid and insert it. 

Something like that:

```javascript 
const number = ' YOUR FUNCTION NUMBER';
var dbclick = ` <div id="${number}">...</div>` 
```

**Comment by maxkaoppp** [comment]
thanks @jerosoler , I'll try it later.
Additionally,there is another problem.I save my drawflow data with button click,but drawflow will be cleared after page load.How could I save data without page load?

**Comment by jerosoler** [comment]
Save data withouth page reload with ajax petition.
