### ISSUE TITLE
Create node with both drag and click

### ISSUE THREAD

**Issue by maxkaoppp** [jerosoler/Drawflow#521]
hello @jerosoler ,I want to create the nodes with both click and drag.Is it possible?

**Comment by jerosoler** [comment]
Click and drag is the natural behavior of moving the canvas. Do you want to remove this function?

**Comment by maxkaoppp** [comment]
no,I mean i want to addNode with both click and drag,not just drag.

**Comment by maxkaoppp** [comment]
![image (1)](https://user-images.githubusercontent.com/58621821/189181507-a1d22dc1-6f74-4f1d-be9e-7541d4a968a2.png)
now addnode to drawflow using drag.How can I addnode to drawflow using click?

**Comment by jerosoler** [comment]
You can use the click event, to detect the position. I add the node as when dragging with the addNode function.

**Comment by maxkaoppp** [comment]
OK.I'll try it. Thanks a lot.

**Comment by maxkaoppp** [comment]
Thanks @jerosoler , it works very successful.
What a great project!
🙏
