### ISSUE TITLE
Create mouse selection box

### ISSUE THREAD

**Issue by maxkaoppp** [jerosoler/Drawflow#522]
hello @jerosoler ,I want to create the rectangle box with mouse drag and copy selected node.How can I do that?
Just like the image below.
![image](https://user-images.githubusercontent.com/58621821/189578755-ec9badca-0e7b-474e-b0e4-1f9b913dd0fa.png)

**Comment by jerosoler** [comment]
For default library not support multiple select. 
You can see here some solutions:
- https://github.com/jerosoler/Drawflow/issues/322
- https://github.com/jerosoler/Drawflow/issues/50

To be able to do it you need to detect the collisions, it can be achieved with this method:
https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

You just have to have the sizes of the drawn box and the size of your nodes.
