### ISSUE TITLE
drawflow removeNodeOutput QuerySelector Issue

### ISSUE THREAD

**Issue by cheesama** [jerosoler/Drawflow#528]
Hi, before reporting issue, I appreciate you about this great library development.

When I try to use drawflow editor.removeNodeoutput Function, It seems to set wrong query selection in code.

Here is actual DOM elements.

![image](https://user-images.githubusercontent.com/23301850/190946709-15ec082f-d573-4122-b98a-5ac38f378769.png)

But, there is wrong part in lib code.

![image](https://user-images.githubusercontent.com/23301850/190946811-21c1d970-9195-49d0-bc96-68aed9dfc7b7.png)

following this code, wrong reference dom element is searched and not found finally.

![image](https://user-images.githubusercontent.com/23301850/190946900-38288b09-841e-4192-a2e9-9c9b9273ff54.png)

When I modified querySelector slightly like below, it works

![image](https://user-images.githubusercontent.com/23301850/190947029-70824361-11ee-4435-916c-7fdb0d671abb.png)

So, how about it? Can you fix it or may I do pull request for it?

Thank you~

**Comment by jerosoler** [comment]
Hi! @cheesama 

The second value has to be the complete class and not the id of the output. 
Exemple: 
"output_2"  not "2"


In docs:  https://github.com/jerosoler/Drawflow#methods

Mehtod | Description
-- | --
removeNodeOutput(id, output_class) | Remove output to node. Ex id: 5, output_2


The code is example in demo:
```javascript
editor.removeNodeOutput(12, 'output_2');
```
![image](https://user-images.githubusercontent.com/30957047/190961486-ae796961-f351-445b-a43e-56302119617c.png)

**Comment by cheesama** [comment]
Thank you for reply.

Following your guide, it works well. Sorry for misuse of lib.

I close this issue myself ^^
