### ISSUE TITLE
Using Stylesheet in Nodes for katex/mathjax support

### ISSUE THREAD

**Issue by martinpflaum** [jerosoler/Drawflow#536]
Hi i am trying to visualize some math with katex or mathjax in the nodes. It seems like the stylsheet is not working or loaded correctly in the Node. 

 It works outside the nodes 100%. Also i checked the html code inside the node, which is correct. I am sadly not a knowledgeable css wizard🧙. 

Where do i need to include the line  ` <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.css">` ?

Or is there away to force overwrite of css styles to ensure that there is no style cheating the css cascade?

Your programm is looking fantastic btw :) 
![Screenshot (5)](https://user-images.githubusercontent.com/63510484/193478744-b236f214-aa45-4b14-9927-ff728d2a8cb9.png)
Any help would be deeply appreciated!

**Comment by martinpflaum** [comment]
oke i think i got the issue Node is LitElement and its styles are completely different then of the normal webpage https://lit.dev/docs/components/styles/

**Comment by martinpflaum** [comment]
Oke i have solved my issue. If anyone who looks at this has a similar issue this is what i came up with

`

<script>
  function convert_display(input){
    return katex.renderToString(input,{ displayMode: true ,throwOnError: false});
  }
  function update_katex(){
    var math_inline = document.getElementsByClassName('inline');
      for (var i = 0; i < math_inline.length; i++) {
        try {
          if (math_inline[i].classList.contains("katex")){
            continue;
          }
          
          katex.render(math_inline[i].textContent, math_inline[i],{throwOnError: false});
          math_inline[i].setAttribute("class","rendered")
        }catch (e) {
        }
      }

    var math_display = document.getElementsByClassName('display_katex');
      for (var i = 0; i < math_display.length; i++) {
        try {
          if (math_display[i].classList.contains("katex")){
            continue;
          }

        katex.render(math_display[i].textContent, math_display[i],{ displayMode: true ,throwOnError: false});
        math_display[i].setAttribute("class","rendered")
        
        }catch (e) {
        }
      }
  }
</script>

<script type="module">
  import {LitElement, html} from 'https://unpkg.com/@polymer/lit-element@latest/lit-element.js?module';

  class MyElement extends LitElement {

   
  render() {
    return html`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.css"><slot></slot>`;
  }
}
  customElements.define('my-element', MyElement);
</script>

`

and then when you want to add something you need to have something like this

`  var facebook = `
   
        <div>
          <div class="title-box"> Theorem on Alternatives</div>
     <my-element class="display_katex">{\\lim \\sup}_{n\\rightarrow \\infty} a_n = {\\lim \\sup}_{n\\rightarrow \\infty} \\{ a_n , a_{n+1} , a_{n+2} , \\ldots \\}</my-element>          
</div>
        `;
        var newNodeId=editor.addNode('facebook', 0,  1, pos_x, pos_y, '', {}, facebook );
        var node = document.getElementById("node-"+newNodeId);
       
        update_katex();
        update_katex();
      `
it s a bit messy but i think one can get the important stuff out of the code

**Comment by martinpflaum** [comment]
oke i solved my issue in the attachement is my solution, its a bit messi right now but i think one can get the import stuff out of the file easily

```html


<script>
  function convert_display(input){
    return katex.renderToString(input,{ displayMode: true ,throwOnError: false});
  }
  function update_katex(){
    var math_inline = document.getElementsByClassName('inline');
      for (var i = 0; i < math_inline.length; i++) {
        try {
          if (math_inline[i].classList.contains("katex")){
            continue;
          }
          
          katex.render(math_inline[i].textContent, math_inline[i],{throwOnError: false});
          math_inline[i].setAttribute("class","rendered")
        }catch (e) {
        }
      }

    var math_display = document.getElementsByClassName('display_katex');
      for (var i = 0; i < math_display.length; i++) {
        try {
          if (math_display[i].classList.contains("katex")){
            continue;
          }

        katex.render(math_display[i].textContent, math_display[i],{ displayMode: true ,throwOnError: false});
        math_display[i].setAttribute("class","rendered")
        
        }catch (e) {
        }
      }
  }
</script>

<script type="module">
  import {LitElement, html} from 'https://unpkg.com/@polymer/lit-element@latest/lit-element.js?module';

  class MyElement extends LitElement {

   
  render() {
    return html`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.css"><slot></slot>`;
  }
}
  customElements.define('my-element', MyElement);
</script>


```
 and then some where else where you add the element do something like this:

```html
var facebook = `
   
        <div>
          <div class="title-box"> Theorem on Alternatives</div>
     <my-element class="display_katex">{\\lim \\sup}_{n\\rightarrow \\infty} a_n = {\\lim \\sup}_{n\\rightarrow \\infty} \\{ a_n , a_{n+1} , a_{n+2} , \\ldots \\}</my-element>          
</div>
        `;
        var newNodeId=editor.addNode('facebook', 0,  1, pos_x, pos_y, '', {}, facebook );
        var node = document.getElementById("node-"+newNodeId);
       
        update_katex();
        update_katex();

```

**Comment by martinpflaum** [comment]
basicly the lit-element protects the katex style from any css style outside and prevents any bugs this way.

**Comment by jerosoler** [comment]
Hi! 

It is the first time I try Latex.
Here I have made a small example of how you can load it.


![image](https://user-images.githubusercontent.com/30957047/193621041-947c5892-7190-4160-ba57-661aa474ac1e.png)

Code:
```javascript
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css"
    />
    <script src="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.css" integrity="sha384-IKOookmJ6jaAbJnGdgrLG5MDmzxJmjkIm6XCFqxnhzuMbfkEhGQalwVq2sYnGyZM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.js" integrity="sha384-kSBEBJfG5+zZAKID5uvi6avDXnnOGLnbknFv6VMnVBrknlFw67TwFsY9PaD33zBI" crossorigin="anonymous"></script>
    <style>
      #drawflow {
        position: relative;
        width: 100%;
        height: 800px;
        border: 1px solid red;
      }

      </style>
  </head>
  <body>
    <div>
        <div id="drawflow"></div>  
    </div>
    <script>

    var id = document.getElementById("drawflow");

    const editor = new Drawflow(id);
    editor.start();
    editor.on("nodeCreated", (id) => {
        const infoNode = editor.getNodeFromId(id);
        if(infoNode.class === 'katex') {
            const form = infoNode.html;
            const element = document.querySelector(`#node-${id} .drawflow_content_node`);
            katex.render(form,element, {throwOnError: false});
        }
    })

    const form  = "c = \\pm\\sqrt{a^2 + b^2}";
    editor.addNode('katex name', 1, 1, 0, 0, 'katex', {}, form);
    
    const form2 = "f(a,b,c) = (a^2+b^2+c^2)^3";
    editor.addNode('katex name2', 1, 1, 200, 300, 'katex', {}, form2);

</script> 
  </body>
</html>
```

**Comment by martinpflaum** [comment]
Hey thank you very much🙂. This is way more clean than what i came up with!
