### ISSUE TITLE
line of overlapping connections is not displayed when selecting

### ISSUE THREAD

**Issue by quentingosset** [jerosoler/Drawflow#538]
Hello, I have a small problem visible in the attached screen,
I have overlapping links and when I select a specific link, I would like the whole link to be visible but here a part of the link is missing. Do you have an idea how to fix this? I have tried a Z-index but it doesn't seem to work on a svg.

![image](https://user-images.githubusercontent.com/6824137/194030708-c8236bf6-ddbc-4919-a29c-e2d14c209270.png)

**Comment by jerosoler** [comment]
This is a problem of straight lines, which overlap.

You can try with this css:

```css
.connection:has(.selected) {
    z-index: 3;
}
```

**Comment by quentingosset** [comment]
Perfect ! Work correctly :)
