### ISSUE TITLE
What would a fixing mode be like that would only prevent the nodes from changing their positions?

### ISSUE THREAD

**Issue by mcantonbul** [jerosoler/Drawflow#54]
For example, let my editor run in fixed mode, but I want the selection events of the nodes in the editor to be triggered. All I want is that their location can't be updated. When `editor.editor_mode = 'fixed';` , node select events are not triggered.

**Comment by jerosoler** [comment]
Hello

In version 0.0.27 I added the "clickEnd" event function.

If you use edit mode.

You can prevent drag with it.

```javascript 
editor.on("clickEnd", function() {
      editor.drag = false;
 });
```

Is this what you want?

**Comment by mcantonbul** [comment]
Yes, it is exactly that :) It worked exactly as I wanted it. Thanks.
