### ISSUE TITLE
Place new nodes in a path between two nodes

### ISSUE THREAD

**Issue by amalas9506** [jerosoler/Drawflow#540]
Hi @jerosoler 
Firstly great library!!

I am using this library in a project but now I am facing this problem.
 
 There is any solution for add  nodes in a  connection(path) between two nodes?
I have already done with ondragover on the svg path. But it doesn't work properly. Path width is 4px so not user friendly. I can not increase the width more than 4px.

Can you please guide how can we achieve this with Draw flow?

Thanks & Regards,
Amala

**Comment by jerosoler** [comment]
Hello,
Thanks!

I think the best option is to use a collision detector
https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

Use with node. And the points of the paths of the connections.
https://stackoverflow.com/questions/22633718/get-points-y-coordinate-on-svg-path

**Comment by jerosoler** [comment]
Two paths options:

Another option would be to modify the library so that it would have the connection to another larger transparent path.

**Comment by amalas9506** [comment]
Hello!
Thanks for the quick reply. Will try it.
