### ISSUE TITLE
Center diagram based on Nodeid

### ISSUE THREAD

**Issue by converseKarl** [jerosoler/Drawflow#541]
If i have a popup list of nodes, and choose one, how can i use this to centre the diagram with this node in the middle.  Has anyone tried this because in a large diagram this scroll to or position centre feature would be very useful.

Any thoughts how to do this

**Comment by jerosoler** [comment]
You can get the coordinates of the node with getNodeFromId and use the following method.
- https://github.com/jerosoler/Drawflow/issues/88
