### ISSUE TITLE
need to display a pop up window while clicking on the node , and export the content which is entered in the popup window

### ISSUE THREAD

**Issue by Ashvi213** [jerosoler/Drawflow#542]
I need to add a new popup window while clicking the node. For example pop up window contain a text box to enter some data. while exporting the data the json also include the data given in the popup window

**Comment by jerosoler** [comment]
Use `updateNodeDataFromId	` to save data on export. 

Example: 
```javascript 
editor.updateNodeDataFromId(5, { name: 'Drawflow' });
```

Update object data in node (7 position): 
```
editor.addNode('github', 0, 1, 150, 300, 'github', data, html);
```

**Comment by Ashvi213** [comment]
That works. Thank you so much
