### ISSUE TITLE
A simple example showing execution of the flow created using drawflow

### ISSUE THREAD

**Issue by chansdad** [jerosoler/Drawflow#543]
Hello Folks 
First - This is one GREAT project . I was on the lookout for someting like this for a while and only came across this project. So going through the docs and live demo i see it is pretty straightforward to create draw flows. I am looking for a simple example on how to execute the flow created using Drawflow. If there is a simple example showcasing how we can execute a simple flow  , that will be great .

Thanks

**Comment by jerosoler** [comment]
Hello,

It depends a lot on the content of the nodes. Also the programming language. Normally the streams run on the backend.

Here are two examples of projects that use drawflow and execute flow:
- PHP https://github.com/42coders/workflows
- JS https://github.com/AutomaApp/automa

You can find more projects using drawflow:
https://github.com/jerosoler/Drawflow/network/dependents

I put the label "Help Wanted" in case someone can help you.
