### ISSUE TITLE
Pré-visualização

### ISSUE THREAD

**Issue by krefects** [jerosoler/Drawflow#544]
O Drawflow é ótimo, mas quando trabalhos com fluxos muito grandes, sentimos falta de uma mapa de "Pre-visualização". 
Alguem ja estaria tralhando em uma função deste tipo ?
Conforme é feito no "MySQL Workbench", onde temos uma caixa de visualização do fluxo total.
![Sem título](https://user-images.githubusercontent.com/17180773/196704808-a06fa048-6c36-473c-a4bb-32aeed433b61.png)

**Comment by jerosoler** [comment]
View:
- https://github.com/jerosoler/drawflow-minimap-example
- https://github.com/jerosoler/Drawflow/issues/94
