### ISSUE TITLE
How can I copy text in the node?

### ISSUE THREAD

**Issue by it2468** [jerosoler/Drawflow#546]
First of all, thank you for creating a great library.
I want to ask you how to copy text in a node by clicking and hovering.
Currently I see the post mouse move event being caught to move the position of node.
I don't want to use double click. Is there a way to copy like I usually do?
Thank you!

**Comment by jerosoler** [comment]
Hi! 

For example only the text of the content of the node.

Add CSS:
```css
      .drawflow_content_node {
          user-select: text;
      }
```

And javascript to prevent drag:
```javascript
    editor.on("clickEnd", (e) =>  {
        if(e.target.classList[0] === "drawflow_content_node") {
            editor.drag = false;
        }
    })
```

**Comment by it2468** [comment]
Thanks for answer.
But it doesn't seem to work.
I'm in editor mode view. 
I did as you instructed but When I click and move the mouse to do text copy but it is still doing drag&drop all the way to move all nodes.
It seems when I drag to copy it is receiving the drag event to move all nodes.
Do you have a way to disable drag event in all nodes in view mode?

**Comment by jerosoler** [comment]
Prevent drag:
```javascript
   editor.on("clickEnd", (e) =>  {
            editor.drag = false;
    })
```

**Comment by it2468** [comment]
Thank you!
