### ISSUE TITLE
Import with multiple Jsons

### ISSUE THREAD

**Issue by reshmakarunan** [jerosoler/Drawflow#549]
Hi,

I am using the Drawflow library and thank you for such a wonderful Library :)

I have a query related with Editor.Import functionality. Is there any way to import multiple jsons to the same editor? The Jsons which are already saved before.

**Comment by jerosoler** [comment]
Hello,

Thank you!

Only one json can be imported at a time.
You can import it as many times as you want.

If you want to import several json, you can transform-them before importing into one.

For this, I would use the uuid, since otherwise the id of the nodes is consecutive.
```javascript
editor.useuuid = true;
```

**Comment by reshmakarunan** [comment]
Thank you for the response.  
I have already tried the option you suggested. I am using uuid and transforming the Json before importing. It is working as expected. 

Thank you once again
