### ISSUE TITLE
Getting mouse coordinates on canvas, not screen

### ISSUE THREAD

**Issue by dsoiM** [jerosoler/Drawflow#55]
I'm doing a context menu that enables adding nodes to drawflow canvas right where the contextmenu is, but I'm having problems positioning the context menu correctly with scaling
Below code works perfectly when locating mouse coordinates when zoom is not used within drawflow, but after using zoom it does not work. I've been trying to fiddle with the editorZoom multiplier to client values and the rect values, without success. Any ideas on how to implement this thing?
```javascript
	editor.on('zoom', function(zoom) {
	  editorZoom = zoom;
	})

  	editor.on('translate', function(position) {
	  translateX = position.x;
	  translateY = position.y;
	})
	
    editor.on('contextmenu', function(event) {
    	var rect = document.getElementById('drawflow').getBoundingClientRect();
    	var contextmenux = event.clientX - translateX / editorZoom - rect.left ;
    	var contextmenuy = event.clientY - translateY / editorZoom - rect.top ;
   }
```

It seems none of the coordinate events return coordinates relative to the canvas, but instead relative to the viewport. Could some canvas related coordinate events would be nice as well? So that it returns negative coordinates if that is where the event happens on canvas. This is because addNode takes coordinates relative to canvas, not relative to screen.

**Comment by dsoiM** [comment]
Actually I found code from the example:
```javascript
      pos_x = pos_x * ( editor.precanvas.clientWidth / (editor.precanvas.clientWidth * editor.zoom)) - (editor.precanvas.getBoundingClientRect().x * ( editor.precanvas.clientWidth / (editor.precanvas.clientWidth * editor.zoom)));
      pos_y = pos_y * ( editor.precanvas.clientHeight / (editor.precanvas.clientHeight * editor.zoom)) - (editor.precanvas.getBoundingClientRect().y * ( editor.precanvas.clientHeight / (editor.precanvas.clientHeight * editor.zoom)));

```
I'll try with that one and close this question if succeed :-)

**Comment by dsoiM** [comment]
Yep that works

**Comment by jerosoler** [comment]
> Actually I found code from the example:
> 
> ```js
>       pos_x = pos_x * ( editor.precanvas.clientWidth / (editor.precanvas.clientWidth * editor.zoom)) - (editor.precanvas.getBoundingClientRect().x * ( editor.precanvas.clientWidth / (editor.precanvas.clientWidth * editor.zoom)));
>       pos_y = pos_y * ( editor.precanvas.clientHeight / (editor.precanvas.clientHeight * editor.zoom)) - (editor.precanvas.getBoundingClientRect().y * ( editor.precanvas.clientHeight / (editor.precanvas.clientHeight * editor.zoom)));
> ```
> 
> I'll try with that one and close this question if succeed :-)

Perfect! 🎉
