### ISSUE TITLE
Different length of connection line have different position for delete [x]

### ISSUE THREAD

**Issue by ArG97** [jerosoler/Drawflow#550]
hi, different length of connection line have different position for X
![image](https://user-images.githubusercontent.com/69562680/199424941-2052a1ff-d0ab-4591-987a-272ce7ab4ce7.png)
![image](https://user-images.githubusercontent.com/69562680/199424995-83602ec9-5fb9-4b04-9b0e-97626d29b5b5.png)
![image](https://user-images.githubusercontent.com/69562680/199425143-41c86695-73d0-493d-b988-8d09abd9b9d2.png)

how to make it fixed even the length changes?

_Originally posted by @ArG97 in https://github.com/jerosoler/Drawflow/issues/407#issuecomment-1299685121_

**Comment by jerosoler** [comment]
I would have to modify the contextmenu function.

https://github.com/jerosoler/Drawflow/blob/300c9efda3bf8820131b3e93ea50cd9b76c892d3/src/drawflow.js#L521

You can override the function:
```javascript
editor.contextmenu = function(e)  {
 ...
}
```

I would have to modify these lines:

```javascript
 if(this.connection_selected && (this.connection_selected.parentElement.classList.length > 1)) {
        deletebox.style.top = e.clientY * ( this.precanvas.clientHeight / (this.precanvas.clientHeight * this.zoom)) - (this.precanvas.getBoundingClientRect().y *  ( this.precanvas.clientHeight / (this.precanvas.clientHeight * this.zoom)) ) + "px";
        deletebox.style.left = e.clientX * ( this.precanvas.clientWidth / (this.precanvas.clientWidth * this.zoom)) - (this.precanvas.getBoundingClientRect().x *  ( this.precanvas.clientWidth / (this.precanvas.clientWidth * this.zoom)) ) + "px";

        this.precanvas.appendChild(deletebox);

      }
```

**Comment by ArG97** [comment]
> I would have to modify the contextmenu function.
> 
> https://github.com/jerosoler/Drawflow/blob/300c9efda3bf8820131b3e93ea50cd9b76c892d3/src/drawflow.js#L521
> 
> You can override the function:
> 
> ```js
> editor.contextmenu = function(e)  {
>  ...
> }
> ```
> 
> I would have to modify these lines:
> 
> ```js
>  if(this.connection_selected && (this.connection_selected.parentElement.classList.length > 1)) {
>         deletebox.style.top = e.clientY * ( this.precanvas.clientHeight / (this.precanvas.clientHeight * this.zoom)) - (this.precanvas.getBoundingClientRect().y *  ( this.precanvas.clientHeight / (this.precanvas.clientHeight * this.zoom)) ) + "px";
>         deletebox.style.left = e.clientX * ( this.precanvas.clientWidth / (this.precanvas.clientWidth * this.zoom)) - (this.precanvas.getBoundingClientRect().x *  ( this.precanvas.clientWidth / (this.precanvas.clientWidth * this.zoom)) ) + "px";
> 
>         this.precanvas.appendChild(deletebox);
> 
>       }
> ```

Thank you, Jero !
