### ISSUE TITLE
Dynamically change ID

### ISSUE THREAD

**Issue by cewebdesigner** [jerosoler/Drawflow#555]
If I have a Node, and I put another one before the one that was already there

the Node that was already there, goes with ID = 1, when I add a new Node it goes with ID = 2, but this new node I put before Node 1

that is, you would have to change the order in the IDs automatically

Is there a way to do this?

**Comment by jerosoler** [comment]
What do you mean add it before?

The order is correlative.

If you want you can generate the id's with UUID. Adding:
```javascript
editor.useuuid = true;
```
