### ISSUE TITLE
Deselect all nodes

### ISSUE THREAD

**Issue by nexline** [jerosoler/Drawflow#556]
How to deselect all nodes

**Comment by jerosoler** [comment]
Only one node can be selected.

But it's as simple as clicking on the background.
You can simulate this click with javascript too.

**Comment by nexline** [comment]
when I have any node selected, how do I deselect them all?

**Comment by nexline** [comment]
I try to simulate a click on the background with javascript, no success, doesn't remove the selection

**Comment by jerosoler** [comment]
Try:
```javascript
var evt = new MouseEvent("mousedown", {
            view: window,
            bubbles: true,
            cancelable: false,
        });
document.querySelector(`#drawflow`).dispatchEvent(evt);
```

**Comment by nexline** [comment]
Nice, it worked, the only thing missing was to trigger mouseup because only mousedown triggers the translate event
