### ISSUE TITLE
Start dragging on "parent-drawflow" div only possible if no custom class is set before initialisation

### ISSUE THREAD

**Issue by DeeFuse** [jerosoler/Drawflow#559]
If you want to set a custom class to the main drawflow div like this:
```html
...
<section class="content" style="position:absolute; width:100%; height:100%">
    <div class="container-fluid" id="drawflow" ondrop="dropEvent(event)" ondragover="allowDrop(event)"></div>
</section>
...
```

the `click(e)` handler can't detect the "parent-drawflow" class and does not set the correct flags [here](https://github.com/jerosoler/Drawflow/blob/300c9efda3bf8820131b3e93ea50cd9b76c892d3/src/drawflow.js#L244) to enable dragging outside of the generated `class="drawflow"` parent div.
That is caused by switchting the first classList item only.
The [initialisation ](https://github.com/jerosoler/Drawflow/blob/300c9efda3bf8820131b3e93ea50cd9b76c892d3/src/drawflow.js#L55) code appends the `parent-drawflow` class at the end of the classList resulting in following class: `class="container-fluid parent-drawflow"`

One solution would be to use `if(element.classList.contains(className))` instead of the `switch` statement
https://github.com/jerosoler/Drawflow/blob/300c9efda3bf8820131b3e93ea50cd9b76c892d3/src/drawflow.js#L202-L203

**Comment by jerosoler** [comment]
View solution:
- https://github.com/jerosoler/Drawflow/issues/469

**Comment by jerosoler** [comment]
Close duplicate issue
