### ISSUE TITLE
Manually assign nodes for group node.

### ISSUE THREAD

**Issue by nishanshashintha1996** [jerosoler/Drawflow#560]
Hi team. First of all, thank you for this great script. Is there any possibility to add nodes programmatically to a group node?
Appreciate your valuable response.

Tnanks

**Comment by jerosoler** [comment]
View:
 - https://github.com/jerosoler/Drawflow/issues/423

**Comment by nishanshashintha1996** [comment]
Here I have attached loop video for a great understanding. Can you please check that? Thanks

https://www.loom.com/share/919807af068c4addadcada530c28d810

**Comment by jerosoler** [comment]
I understand that you are not adding the node to the group until you move the node.
