### ISSUE TITLE
Replace node HTML on load

### ISSUE THREAD

**Issue by gitgitwhat** [jerosoler/Drawflow#561]
When the graph is exported the node HTML is saved however in cases where the HTML data is dynamic (such as a changing list of options in a select input) loading a past snapshot leads to stale data.  Is there a way to update the node html when importing an exported graph.

Great library by the way.  Thanks for building this.

**Comment by jerosoler** [comment]
Hello

Usign df-attributes
Example: 
- https://github.com/jerosoler/Drawflow/issues/421

Or editing html:
- https://github.com/jerosoler/Drawflow/issues/40
