### ISSUE TITLE
When moving node on editor how to get new  pos_x and pos_y  updated values

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#563]
I have added node on workspace but when i am moving into another position that time how to get updated  values of pos_x and pos_y.

**Comment by jerosoler** [comment]
Try:
```javascript
    editor.on("nodeMoved", (id) => {
        const nodeInfo = editor.getNodeFromId(id);
        console.log(nodeInfo);
        console.log(nodeInfo.pos_x);
        console.log(nodeInfo.pos_y);
    });
```

**Comment by Co-Maheshh** [comment]
great.it will get new position values of x and y but after how to update it on directly in addnodetodrawflow () method.
