### ISSUE TITLE
can we add dynamically  any new variables in json data structure .

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#565]
is there any way to change variables or add new variables in json. 
we have variables like pos_x and pos_y in json. so how we can change it to top and left like this.

**Comment by jerosoler** [comment]
View: 
- https://github.com/jerosoler/Drawflow/issues/40

**Comment by Co-Maheshh** [comment]
i want to  add new variables as a key in json structure

**Comment by jerosoler** [comment]
editor.drawflow.drawflow.Home.data[5].test = "YOUR DATA"
