### ISSUE TITLE
How to use dblclick() on html node  for opening model ?

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#566]
i tride like this 

                    <div class="row"  dblclick="openModel (e)">
			           <i class="material-icons dp48 col-12">email</i>
		   </div>
		    <div class="col-12">
		                  <span>Email</span>
                    </div>

   openModel (e)
{
   console.log("model open");
}

but its not working.

**Comment by jerosoler** [comment]
View demo node "DBclick"
https://jerosoler.github.io/Drawflow/

And code of demo:  
https://github.com/jerosoler/Drawflow/blob/master/docs/index.html

Or view: 
- https://github.com/jerosoler/Drawflow/issues/224
