### ISSUE TITLE
How to import drawflow graph after postback

### ISSUE THREAD

**Issue by maxkaoppp** [jerosoler/Drawflow#567]
hello @jerosoler, When button been clicked will trigger page postback,then the drawflow graph will lost. How can I rebind drawflow graph after postback?

**Comment by jerosoler** [comment]
Hello

With import method to lo load data. 

```javascript
editor.import(exportdata);
```

Why is the graph lost?

**Comment by maxkaoppp** [comment]
I write editor.import(exportdata) in document.ready method but after postback 
Drawflow graph get lost.

**Comment by jerosoler** [comment]
Show your code to review
