### ISSUE TITLE
Vertical Connection from nodes (like a Flow Chart)

### ISSUE THREAD

**Issue by Soumi95** [jerosoler/Drawflow#568]
Hi @jerosoler,

First of all, Thank you for this amazing library. 
I am using input/output point at the top/bottom of nodes and trying to make a flow chart with vertical connection as shown in below image.
![image](https://user-images.githubusercontent.com/118988780/203808078-52fa791a-d11b-43f6-b0f5-d2c171fa27a2.png)
I have overwritten the createCurvature() function by taking the reference from #20. But it is not resolving my problem. now the flow is showing like this
![image](https://user-images.githubusercontent.com/118988780/203807846-b0247750-8db4-487b-9988-49900cc2e93d.png)

Could you please suggest any solution so that vertical connection can be used?

Thanks in Advance.

**Comment by jerosoler** [comment]
It's in comment: https://github.com/jerosoler/Drawflow/issues/20#issuecomment-801265399

```javascript
    editor.createCurvature = function(start_pos_x, start_pos_y, end_pos_x, end_pos_y, curvature_value) {
        var center_y = ((end_pos_y - start_pos_y)/2)+start_pos_y;
      return ' M ' + start_pos_x + ' ' + start_pos_y + ' L '+ start_pos_x +' ' +  center_y  + ' L ' + end_pos_x + ' ' +  center_y  + ' L ' + end_pos_x + ' ' + end_pos_y;
    }

```

**Comment by Soumi95** [comment]
Thanks a lot @jerosoler. This function solved my problem.
