### ISSUE TITLE
Arrows and connections are not aligned properly

### ISSUE THREAD

**Issue by Soumi95** [jerosoler/Drawflow#569]
Hi @jerosoler 
I am using this library to create flow chart that has vertical connection and input/output point on top/bottom of the node. When connection will be made between nodes, the input point (circle in shape by default) will be changed to arrow shape. So, I am changing input class to arrow-input inside connectionCreated event and the input point is changing to arrow shape. But after making connection when I am selecting the node and dragging it, the connection is shifting to the left as shown in the image
![image](https://user-images.githubusercontent.com/118988780/203928665-29b8b187-7c08-4cf5-950a-ad7806169b69.png)

CSS for arrow input is
.drawflow .drawflow-node.arrow-input .input {
  left: 90px;
  top: -53px;
  background: transparent;
  position: relative;
  transform: rotate(90deg);
  border-style: solid;
  border-width: 12px 0 12px 12px ;
  border-color: transparent transparent transparent #007bff ;
  border-radius: 0px ;
}
and I am overriding the createCurvature() function as you suggested on #568 

Could you please give me any suggestion to solve this issue?

Thanks in Advance.

**Comment by jerosoler** [comment]
You will probably have to modify the css left property.

**Comment by Soumi95** [comment]
Thank you, it worked. I modified some css property and now arrow and connection coming as expected.
