### ISSUE TITLE
Remove Clear Button

### ISSUE THREAD

**Issue by mithunsidd** [jerosoler/Drawflow#571]
hi jerosoler, pls tell me how can I remove clear button only from "other"

**Comment by jerosoler** [comment]
What do you mean by "other"? And "clear button"????

**Comment by mithunsidd** [comment]
![draw](https://user-images.githubusercontent.com/64886058/204440913-d6719297-aca1-4c03-94a8-53f84ac6507c.png)
hi, you can see from image, i need to clear button from other module only.
\

**Comment by jerosoler** [comment]
Use events to detect module and hide/show button

```javascript
editor.on("moduleChanged", function(name) {
  if(name === "other") {
  // Hide button clear
  } else {
  // Show button now
  }
});
```
