### ISSUE TITLE
can we export json structure below format

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#572]
{
  "drawflow": {
    "Home": {
      "data": {
        "0": {
          "reference": 1,
          "title": "Start",
          "config": {},
          "class": "",
          "html": " "
          "inputs": {},
          "outputs": {
            "output_1": {
              "connections": [
                {
                  "node": "2",
                  "output": "input_1"
                }
              ]
            }
          },
          "pos_x": 120,
          "pos_y": 150
        }
		}
		"links":{
		"1":{
		 "node": "2",
         "output": "input_1"
		},
		"2":{
		}
		}}}

**Comment by jerosoler** [comment]
There is only one export method.
Once exported you can modify it to your liking.

**Comment by Co-Maheshh** [comment]
But if am modify the json structure and after i am try to initialize drawflow based on that json.is it work ?

**Comment by jerosoler** [comment]
If you keep the main structure it should work. The rest of the code will ignore it.
But it's usually not a good idea.
