### ISSUE TITLE
can we start node id from 0. right now its start from 1.but can we change it into from 0.

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#573]

**Comment by jerosoler** [comment]
Try:
```javascript
editor.nodeId = 0;
```

**Comment by Co-Maheshh** [comment]
yes.          
editor.nodeId = 0;

it assign 0 value for first node but for second node it directly assign 2 value. it not assign 1.
I have scenerio like operator id shoud starts from 0 instead of 1.

**Comment by jerosoler** [comment]
I have tested it and it returns correctly.

```javascript
    editor.start();
    editor.nodeId = 0;
    editor.on("nodeCreated", (id) => {
      console.log(id);
    });
    editor.addNode('test1', 1, 1, 200, 300, 'test1', {}, 'Hello World');
    editor.addNode('test1', 1, 1, 400, 300, 'test1', {}, 'Hello World2');
    editor.addNode('test1', 1, 1, 500, 300, 'test1', {}, 'Hello World3');
```

Return:
![image](https://user-images.githubusercontent.com/30957047/204735005-fc86f0d0-6388-4f22-9dfe-85b9e938f363.png)
