### ISSUE TITLE
nodeCreated problem

### ISSUE THREAD

**Issue by linguist89** [jerosoler/Drawflow#578]
Hi there, 
Firstly, DrawFlow is awesome, thanks for the hard work you've put in to create it!

My question is that with the following code:

```
editor.on('nodeCreated', function(id) {
        console.log("Node created " + id);
      })
```

For some reason it doesn't output the first node. It only starts outputting from node-2. Otherwise it works fine. Any ideas why this might be?

**Comment by jerosoler** [comment]
In this example, only B will be notified.
Since the event listener has not been initialized before A.

I recommend putting the event after start.

```javascript
editor.addNode(...A)
editor.on('nodeCreated', function(id) {
        console.log("Node created " + id);
      })
editor.addNode(...B)
```

The addNode event is not fired on imports either.

**Comment by linguist89** [comment]
That fixes it! Thank you!
