### ISSUE TITLE
Use of nodeUnselected event

### ISSUE THREAD

**Issue by Soumi95** [jerosoler/Drawflow#580]
Hi @jerosoler,

I want to use the node unselected event of drawflow. My requirement is - On nodeSelected event, after completing the required task, that node should be unselect. So I am trying with nodeUnselected event but it is not happening. What I am doing is, in nodeSelected event, I use dispatch to call the nodeUnselected event, it is going to nodeUnselected event but however the node is not unselected, it still remains selected.
Could you please help me to figure out this problem?

Thank you in Advance.

**Comment by jerosoler** [comment]
The event does not deselect, it only notifies when it is deselected.
View:

- https://github.com/jerosoler/Drawflow/issues/456
Or:
- https://github.com/jerosoler/Drawflow/issues/556
