### ISSUE TITLE
how to dynamically increases output ?

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#581]
My scenerio is that i have a  one node in editor when i click on that node one popup is opened. in that pop up we are given number like 2 or 3. if i am added 3 then.it will be immediately add 3 output on that node. how we can do like this. 

Thank you in advance.

**Comment by jerosoler** [comment]
Please read documentation in readme: (Opened 9 issues.)

https://github.com/jerosoler/Drawflow#methods

Method - addNodeOutput - To increase outputs.

**Comment by HeoYoungHyun** [comment]
Can't I dynamically generate output?

**Comment by jerosoler** [comment]
Example: 
```javascript
editor.addNodeOutput(5);	
```

**Comment by jerosoler** [comment]
Before asking please try searching the issues.
- https://github.com/jerosoler/Drawflow/issues/35

**Comment by Co-Maheshh** [comment]
i used this method.but after that we need to initialize editor again or directly it added 5 outputs.

editor.addNodeOutput(5);

i am used this but it does not worked for me.

**Comment by jerosoler** [comment]
Number 5 it's id of node to add ouput.

**Comment by Co-Maheshh** [comment]
can you provide one sample example ?
