### ISSUE TITLE
How to initialize canvas position?

### ISSUE THREAD

**Issue by rhl88** [jerosoler/Drawflow#583]
After moving the canvas, ajax loads a new one. The canvas is not initialized.

After dragging, the coordinates before ajax loading.

**Comment by rhl88** [comment]
video https://youtu.be/Aazl6p0ItVQ

**Comment by jerosoler** [comment]
For default not saved in export canvas position. 

Save canvas position. 
Load data.
Load data position. 

Use method:
- https://github.com/jerosoler/Drawflow/issues/88
View example:
- https://github.com/jerosoler/Drawflow/issues/387
