### ISSUE TITLE
How do I lock and unlock the canvas? 

### ISSUE THREAD

**Issue by rhl88** [jerosoler/Drawflow#584]
You can control dragging or not.

**Comment by jerosoler** [comment]
```javascript
editor.editor_mode = 'view'; 
```

**edit** for edit, **fixed** for nodes fixed but their input fields available, **view** for view only

Only block nodes.  Not canvas.  

For draggin canvas block view:
- https://github.com/jerosoler/Drawflow/issues/321

**Comment by rhl88** [comment]
Instead of locking nodes, I want the entire canvas to be immovable.

**Comment by jerosoler** [comment]
...
Combine editor mode view edit with #321

**Comment by rhl88** [comment]
yes! o(*￣▽￣*)ブ
