### ISSUE TITLE
4 directions

### ISSUE THREAD

**Issue by HeoYoungHyun** [jerosoler/Drawflow#587]
안녕하세요 Drawflow 잘 사용하고 있습니다.
4방향으로 설정하고 싶은데 어떻게 설정하는지 알려주실 수 있나요?
![image](https://user-images.githubusercontent.com/70512460/205181717-b7ee8de9-331a-4d18-8d26-3fbea341b197.png)

**Comment by rhl88** [comment]
把入口与出口放在中间。

**Comment by jerosoler** [comment]
view: 
- https://github.com/jerosoler/Drawflow/issues/20#issuecomment-679976512
