### ISSUE TITLE
Cannot read property 'classList' of null"

### ISSUE THREAD

**Issue by chastoedov** [jerosoler/Drawflow#59]
Hi!
Thank you for the great library!😍🤗

I ran a test file on my server - work!👍 

Now I'm trying to run this example using the VueJS components.
![image](https://user-images.githubusercontent.com/56137952/97346442-7f060d80-189c-11eb-9d8d-91afed8cb4b1.png)

Here is the result of this component
![image](https://user-images.githubusercontent.com/56137952/97346829-02bffa00-189d-11eb-964f-43ae4046f8c1.png)

But on the editor.start(); get the error "Cannot read property 'classList' of null"
![image](https://user-images.githubusercontent.com/56137952/97347088-5cc0bf80-189d-11eb-99e3-25a074767d39.png)

Please tell me what the error may be and how to fix it?

**Comment by chastoedov** [comment]
Found a solution :)

Replaced created () with mounted ()

**Comment by jerosoler** [comment]
Hello @chastoedov 

> Thank you for the great library!heart_eyeshugs

Thanks!! 🎉

> Found a solution :)

Perfect!

If you are using vue you can see these examples https://github.com/jerosoler/Drawflow/issues/37 and https://github.com/jerosoler/Drawflow/issues/34
