### ISSUE TITLE
how to exclude node which is not connected into any other node ?

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#590]

**Comment by jerosoler** [comment]
get the information of the node and check if it has inputs and outputs.

```javascript
const data = editor.getNodeFromId(id)	
console.log(data);
```

**Comment by Co-Maheshh** [comment]
But i want to exclude node which is not connected at the time of saving json structure ?

**Comment by jerosoler** [comment]
In the export is the same information. You will have to go through the export and remove the empty nodes.
