### ISSUE TITLE
Limit drag and drop useage

### ISSUE THREAD

**Issue by mithunsidd** [jerosoler/Drawflow#591]
Hi, I have a drag and drop issue, I want to set the to limit  number of time able to drag and drop facebook to once

**Comment by jerosoler** [comment]
Hi!  @mithunsidd 

Following the example of the demo. The addNodeToDrawflow function, we can modify it like this:
Link code demo: https://github.com/jerosoler/Drawflow/blob/master/docs/index.html

```javascript
  function addNodeToDrawFlow(name, pos_x, pos_y) {
      const drawflowModule = editor.module;
      const nodes = editor.drawflow.drawflow[drawflowModule].data;
      let nodeExist = false;
      for (var key in nodes) {
        if(editor.drawflow.drawflow[drawflowModule].data[key].name === name) {
            nodeExist = true;
        }
      };

      alert(nodeExist);
      ....
}
```
We can see if there is any module with the same name in the module. Depending on whether or not it exists, you can decide what to do.
