### ISSUE TITLE
[question] How can I use the drawflow.js instead of the minified version?

### ISSUE THREAD

**Issue by Joerideman** [jerosoler/Drawflow#595]
Hi, I am playing around with your work.

I tried to understand how it works and make some variations. I tried to use the drawflow.js instead of the drawflow.min.js, but this gives errors. 

Did I make a wrong assumption about the files? 

```
drawflow.js:1 Uncaught SyntaxError: Unexpected token 'export' (at drawflow.js:1:1)
index.html:98 Uncaught ReferenceError: Drawflow is not defined
    at index.html:98:20
(anonymous) @ index.html:98
```

Also You are awesome for sharing your work.

**Comment by jerosoler** [comment]
Simple. Remove 'export' from drawflow.js

**Comment by Joerideman** [comment]
awesome. That was such a quick and easy answer. Thank you.
