### ISSUE TITLE
getting error when importing json ?

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#601]

**Comment by Co-Maheshh** [comment]
![image](https://user-images.githubusercontent.com/118881887/206744243-600107c3-aa45-4875-817e-d9e64b752dec.png)

**Comment by Co-Maheshh** [comment]
when importing json position of properties is matter or not...means if i am add id at 3 rd position placing name at 1st position.and then importing that time getting error ?
how to import without posotion matters?

**Comment by Co-Maheshh** [comment]
Sequence of parameters like name , id , pos_x, pos_ y so on. is ot required in sequencing?

**Comment by jerosoler** [comment]
The export json does not have to be modified. If you need another type of import, you can fork the library and modify it to your liking.

**Comment by jerosoler** [comment]
Show you json

**Comment by Co-Maheshh** [comment]
this is my json .

{
    "drawflow": {
        "Home": {
            "data": {
                "0": {                
                    "name": "Start",
                    "id": "0",
                    "html": "Start",
                    "class": "",                
                    "typenode": false,
                    "inputs": {},
                    "outputs": {
                        "output_1": {
                            "connections": [{
                                "node": 1,
                                "output": "input_1"
                            }]
                        }
                    },
                    "pos_x": 40,
                    "pos_y": 40
                },
  "1": {
                    "id": "1",
                    "name": "SFTP",
                    "data": {
                    },
                    "class": "",
                    "html": "SFTP",
                    "typenode": false,
                    "inputs": {
                        "input_1": {
                            "connections": [{
                                "input": "output_1",
                                "node": "0"
                            }]
                        }
                    },
                    "outputs": {
                        "output_1": {
                            "connections": [{
                                "node": "2",
                                "output": "input_1"
                            }]
                        }
                    },
                    "pos_x": 40,
                    "pos_y": 220
                }
 }}}}

**Comment by jerosoler** [comment]
In the nodes it is necessary to add the data.

Node 0 without data. 

```javascript
"data": {},
```
