### ISSUE TITLE
Getting error for updateconnectionNodes ?

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#605]
![image](https://user-images.githubusercontent.com/118881887/207019417-b40a141c-16b8-42fd-9261-a4f420512e96.png)

**Comment by Co-Maheshh** [comment]
i am trying to increase the no of outputs using passing number like this.

        this.editor.addNodeOutput(this.selectedNodeId);
        this.editor.updateConnectionNodes(outputnode);

here,    
         this.selectedNodeId    is the id of selected node.
         outputnode                 is the number of outputs for example 3 like this.


SO what happen  outputnode initial value is 2 means node has by default 2 output added. but when i am updating outpunode value using above code then it will increase only by 1 value. for example.  suppose i am passing value 4 so i need to create 4 output for node.but it created 3.


thanks in advance.

**Comment by jerosoler** [comment]
The correct value: ✔
```javascript
updateConnectionNodes('node-5');
```

Incorrect:  ⛔
```javascript
updateConnectionNodes('5');
```
