### ISSUE TITLE
More comfortable zooming on big canvas

### ISSUE THREAD

**Issue by dsoiM** [jerosoler/Drawflow#61]
I have a very big canvas where items can be located at "top: 6305px; left: 400px;" and even more, sometimes even 20 000 px. When items are so far off the 0,0, then zooming around is not very comfortable is items on canvas do not remain in view and zooming does not work intuitively. I tried to overwrite the zoom functions with trickery to manipulate the translate coordinates, such as:
```javascript
editor.zoom_out = function(){
    if(this.zoom > this.zoom_min) {
      this.zoom-=0.1;
      this.canvas_y =this.canvas_y - (this.canvas_y/7/this.zoom); //That 7 is just a test
      this.zoom_refresh();
    }
  }
```

but no success. It requires some kind transformation of canvas coordinates based on zoom multiplier as well as current canvas location but i cannot figure out how. Any ideas on this?

**Comment by jerosoler** [comment]
Hello 

What you want is to move the canvas while you zoom right?

If it is correct, you have to use:
```javascript 
this.precanvas.style.transform = "translate("+x+"px, "+y+"px) scale("+this.zoom+")";
```

**Comment by dsoiM** [comment]
That is not quite what i meant. You will see if you try it yourself on your demo:
First move on canvas wayyy down, then drop something on it:
![image](https://user-images.githubusercontent.com/26181887/98234315-8db98800-1f60-11eb-8fae-5bf6697870cc.png)



Then zoom out twice:
![image](https://user-images.githubusercontent.com/26181887/98234375-a2961b80-1f60-11eb-9981-63cfc3abee4f.png)

The actual location where I was on canvas has moved far away, including the item that was visible

**Comment by jerosoler** [comment]
The demo does not produce any strange movements for me.

Are you using a touch screen or touchpad?

**Comment by jerosoler** [comment]
mmmm .. now I see what you say, I had tried with a small distance when testing with a distance of 4000px I see what happens.

**Comment by dsoiM** [comment]
Yep it occurs only on big canvases where items are far off 0px, 0px

**Comment by jerosoler** [comment]
Hello @dsoiM 

Try this code please, if it is correct I will add it to the library.

```javascript 
  editor.last_zoom = 1;
      editor.zoom_refresh = function (){
        this.dispatch('zoom', this.zoom);
        this.canvas_x = (this.canvas_x / this.last_zoom) * this.zoom;
        this.canvas_y = (this.canvas_y / this.last_zoom) * this.zoom; 
        editor.last_zoom = this.zoom;
        this.precanvas.style.transform = "translate("+this.canvas_x+"px, "+this.canvas_y+"px) scale("+this.zoom+")";
      }
```
Thanks!

**Comment by dsoiM** [comment]
Hey @jerosoler, works absolutely perfect, good job 👍

**Comment by jerosoler** [comment]
Update version to 0.0.30

Fix! ;) 

And add a zoom_value  https://github.com/jerosoler/Drawflow#editor
Thanks!
