### ISSUE TITLE
Any function called in drawflow library when canvas creation is finished with existing data.

### ISSUE THREAD

**Issue by AnirudhWT** [jerosoler/Drawflow#612]

**Comment by jerosoler** [comment]
You can use events to detect.

For example when an import data: 
```javascript
editor.on('import', (import) => {
....
});
```

**Comment by AnirudhWT** [comment]
@jerosoler  Getting data : Array of objects from some api in angular and using them to map with drawflow.

**Comment by jerosoler** [comment]
The question is very open.

What kind of data? What do you want to map?
If the node already exists?
Create more nodes?
Modify the nodes?
....

**Comment by surihoney** [comment]
Hi @jerosoler , what could be wrong if this event not triggered at all ?

editor.on('import', function () {
 console.log("Successfully import");
});

**Comment by jerosoler** [comment]
@surihoney Is that code before importing?

**Comment by surihoney** [comment]
i put it after,  i tried put it before import also not working, what's the correct order?

`   
editor.start();

editor.import(data);

 editor.on('import', function () {
    console.log("Successfully import");
  });
`

**Comment by jerosoler** [comment]
1 start
2 on import event
3 import data

**Comment by surihoney** [comment]
Still not working, I think maybe because it's inside React component's useEffect maybe it has something to do with that. 
Thank you for this awesome library .

**Comment by surihoney** [comment]
Hi this is silly , but what causing the issue I mention above (the import event not triggered) , is because I used the older version of this code. After upgraded, now works flawlessly . @jerosoler
