### ISSUE TITLE
Does this library support automatic layout?

### ISSUE THREAD

**Issue by yyy33** [jerosoler/Drawflow#613]
Very nice design, does it support automatic layout algorithms like dagre?

**Comment by jerosoler** [comment]
It doesn't have an automatic layout, but surely you mean doing this:
- https://github.com/jerosoler/Drawflow/issues/529

**Comment by yyy33** [comment]
> It doesn't have an automatic layout, but surely you mean doing this:
> 
> * [Auto positioning #529](https://github.com/jerosoler/Drawflow/issues/529)

thank you
