### ISSUE TITLE
Link to the output in Connection line 

### ISSUE THREAD

**Issue by maxkaoppp** [jerosoler/Drawflow#615]
Hi @jerosoler ,
I want to link to the output in Connection line.
How can I do?
Just like the image below.

![image](https://user-images.githubusercontent.com/58621821/208334115-d471468f-4009-47bb-b419-f861e3cb52ae.png)
![image](https://user-images.githubusercontent.com/58621821/208334209-bad1ae6e-79d8-4c9d-9a27-d25a8583c435.png)

**Comment by jerosoler** [comment]
Connections only go from node to node.

You could use this method to create a new connection with the 'addConnection' function.
- https://github.com/jerosoler/Drawflow/issues/461

You could also be guided by these methods as well.
- https://github.com/jerosoler/Drawflow/issues/424
- https://github.com/jerosoler/Drawflow/issues/436
