### ISSUE TITLE
Check currently how many nodes are there in the canvas

### ISSUE THREAD

**Issue by Ashvi213** [jerosoler/Drawflow#616]
I have dynamic popup on each nodes. So I need to drag one node and on double click need to fill the pop up. If I don't fill the popup the dragging of next node must be restricted. If there any provision to check how many nodes are there in the canvas before I am dragging the next node.

**Comment by paulohenriquesg** [comment]
I'm not sure if this is the definitive answer, but you can use the following to get a nodeList:
```
document.querySelectorAll(".drawflow-node ");
```

**Comment by jerosoler** [comment]
Hi! 

Other alternative to get nodes from module.
```javascript
console.log(editor.drawflow.drawflow[editor.module].data);
```
