### ISSUE TITLE
Allow drop is not defined

### ISSUE THREAD

**Issue by mithunsidd** [jerosoler/Drawflow#619]
Hi, I have JSON value which added to variable and assigned to dataTOImport. I am able to retrieve the data but unable to drag and drop event  and modify it.
thanks
[message.txt](https://github.com/jerosoler/Drawflow/files/10286584/message.txt)

**Comment by jerosoler** [comment]
The code of your example is not complete.

What I see is wrong is this:

Change
```javascript
  editor.import(JSON.parse(dataToImport));
```
To:
```javascript
    editor.import(dataToImport);
```
