### ISSUE TITLE
Save zoom value on editor.export

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#62]
Hi, @jerosoler hope you are doing well..i think you should consider saving the zoom value on editor.export...because if anyone zoom out, move the nodes to left and save the flow,then when the editor.import happens, it resets to the default zoom size, for this reason, some nodes get outside of the monitor.
![flowzoom](https://user-images.githubusercontent.com/34944930/98339920-b1e79880-2036-11eb-90c9-501f2ea41ac4.gif)

**Comment by jerosoler** [comment]
Hello @MehbubRashid 

I understand the problem you have.

I don't know whether or not to include it in the export. I will study it.

But it has an easy solution.
Example:
```javascript
var position_x = 0;
    var position_y = 0;
    var zoom = 0;

    editor.on("import", function() {
      editor.canvas_x = position_x;
      editor.canvas_y = position_y;
      editor.zoom = zoom;
      editor.zoom_refresh();
    })


    editor.on("export", function() {
      position_x = editor.canvas_x;
      position_y = editor.canvas_y;
      zoom = editor.zoom;
    })
```

You could save the data at the same time it is exported. Or you could even add them to the json when you export them.

**Comment by MehbubRashid** [comment]
Thanks..this is solved!
