### ISSUE TITLE
Links are disorganized

### ISSUE THREAD

**Issue by cewebdesigner** [jerosoler/Drawflow#624]
when I import the links it is wrong, how can I fix this at the time of import

![Screenshot (65)](https://user-images.githubusercontent.com/118427344/209881272-8f2ec55f-d39a-4d92-8a56-351b3c45f9bc.png)

`const dataToImport =  {"drawflow":{"Home":{"data":........}}}`
`editor.start();`
`editor.import(dataToImport);`

I import via JSON

**Comment by jerosoler** [comment]
I assume you are using the link system.

What surely you do not have added the event import.

Look at this issue:
- https://github.com/jerosoler/Drawflow/issues/608

**Comment by cewebdesigner** [comment]
> I assume you are using the link system.
> 
> What surely you do not have added the event import.
> 
> Look at this issue:
> 
> * [Outputs being disarranged after switching to another tab #608](https://github.com/jerosoler/Drawflow/issues/608)

So I implemented it here and when text doesn't appear on the screen, maybe I'm not getting the JSON with this type of import?


![importacao](https://user-images.githubusercontent.com/118427344/209962771-62b77537-9858-42ab-aeab-a1ea130b2f2b.png)

**Comment by jerosoler** [comment]
You are not calling `editor.import("YOUR_DATA");`

They have to call the function at the end of the script.

**Comment by cewebdesigner** [comment]
ahhh, thank you very much it worked.
