### ISSUE TITLE
Cannot read property 'connections' of undefined

### ISSUE THREAD

**Issue by MehbubRashid** [jerosoler/Drawflow#63]
Hi @jerosoler, I have noticed that while trying connecting to a node with 0 input while editor.force_first_input set to true, it causes a fatal error..its a bug i think... a check should be placed to confirm if that node has at least one input.
![forcefirst](https://user-images.githubusercontent.com/34944930/98444336-4b986e00-213b-11eb-99ad-fc991a5bc14a.gif)

**Comment by jerosoler** [comment]
Hello @MehbubRashid 

Fix in 0.0.29 ;) 

Thanks for your work!

**Comment by MehbubRashid** [comment]
Awesome! Thanks for your hard work <3 <3
