### ISSUE TITLE
Remover Node Output

### ISSUE THREAD

**Issue by cewebdesigner** [jerosoler/Drawflow#630]
How can I remove Node Output, without having to remove it in sequence

Eg: I have [output_1, output_2, output_3]
if i remove it in sequence it works

if by chance I want to remove output_2 and then output_3
gives error

![erro](https://user-images.githubusercontent.com/118427344/210629715-1a4eb1c1-91fa-4e8a-b182-78a1907e8274.png)

**Comment by jerosoler** [comment]
By removing output_2. Output 3 becomes 2.

Remove output_2 and remove output_2.

```javascript
editor.removeNodeOutput(1, 'output_2');	
editor.removeNodeOutput(1, 'output_2');	
```
