### ISSUE TITLE
Curvature design  

### ISSUE THREAD

**Issue by nasimcoderex** [jerosoler/Drawflow#632]
What should I do if want to implement this following design 
<img width="979" alt="Screenshot 2023-01-11 at 5 18 32 PM" src="https://user-images.githubusercontent.com/77294147/211793794-32d16d21-b1bd-4472-a2c4-a8cc71b0e899.png">

`var hx1 = line_x + Math.abs(x - line_x) * curvature
  var hx2 = x - Math.abs(x - line_x) * curvature
 return ( ' M ' + line_x + ' ' + line_y + ' C ' + hx1 + ' ' + line_y + ' ' + hx2 + ' ' + y + ' ' + x + '  ' + y + ' M ' + (x - 1) + ' ' + y + ' L' + (x - 10) + ' ' + (y - 5) + '  L' + (x - 10) + ' ' + (y + 5) + ' Z' + ' M ' + (x - 1) + ' ' + y + ' L' + (x - 10) + ' ' + (y - 3) + '  L' + (x - 10) + ' ' + (y + 3) + ' Z' + ' M ' + (x - 1) + ' ' + y + ' L' + (x - 10) + ' ' + (y - 1) + '  L' + (x - 10) + ' ' + (y + 1) + ' Z' )`

I have used this calculation and the output is - 

<img width="508" alt="Screenshot 2023-01-11 at 5 24 19 PM" src="https://user-images.githubusercontent.com/77294147/211794337-95e30d07-b057-4a86-868d-6fb065baf1ab.png">

So please give me a solution

**Comment by jerosoler** [comment]
You can find curvatures here:
- https://github.com/jerosoler/Drawflow/issues/20

**Comment by nasimcoderex** [comment]
<img width="390" alt="Screenshot 2023-01-11 at 5 44 34 PM" src="https://user-images.githubusercontent.com/77294147/211798186-c7c74551-4c00-42c9-b496-1a51706db7b8.png">


 var center_y = ((end_pos_y - start_pos_y)/2)+start_pos_y;

 return ' M ' + start_pos_x + ' ' + start_pos_y + ' L '+ start_pos_x +' ' +  center_y  + ' L ' + end_pos_x + ' ' +  center_y  + ' L ' + end_pos_x + ' ' + end_pos_y;


I don't want link this

**Comment by jerosoler** [comment]
I recover an old code. I would say what you want:

```javascript
    editor.createCurvature = function(start_pos_x, start_pos_y, end_pos_x, end_pos_y, curvature_value, type) {
        let angle = 15;
        const stroke = 2; // === stroke CSS. 
        const input_distance = 10;
        const fix_arrow_distance = 10;
        const min_x_distance = 45;

        const x = start_pos_x + input_distance;
        const y = start_pos_y;
        const end_x = end_pos_x - fix_arrow_distance;
        const end_y = end_pos_y;
        const center_x = ((end_x - x)/2)+x;
        const center_y =  ((end_y - y)/2)+y;
        const distance_x = end_x - x;
        const distance_y = end_y - y;
        let minX = false;
        
        let line = '';
        
        if(distance_x <= min_x_distance) {
            minX = true;
        }
        
        if(end_y > y) {
            //Down Lines
            if(distance_y <= angle*2) {
                angle = distance_y/2;
            }
            if(minX) {
                if(distance_y <= angle*4) {
                    angle = distance_y/4;
                }
                line += `
                M ${x} ${y} 
                L ${x+min_x_distance-angle} ${y} 
                A ${angle} ${angle} 1 0 1 ${x+min_x_distance} ${y+angle}
                L ${x+min_x_distance} ${center_y-angle}
                A ${angle} ${angle} 1 0 1 ${x+min_x_distance-angle} ${center_y}
                L ${end_x-min_x_distance} ${center_y}
                A ${angle} ${angle} 1 0 0 ${end_x-min_x_distance-angle} ${center_y+angle}
                L ${end_x-min_x_distance-angle} ${end_y-angle}
                A ${angle} ${angle} 1 0 0 ${end_x-min_x_distance} ${end_y}
                L ${end_x} ${end_y}
                `;
            } else {
                line += `
                M ${x} ${y} 
                L ${center_x-angle} ${y} 
                A ${angle} ${angle} 1 0 1 ${center_x} ${y+angle}
                L ${center_x} ${center_y} 
                L ${center_x} ${end_y-angle} 
                A ${angle} ${angle} 1 0 0 ${center_x+angle} ${end_y}
                L ${end_x} ${end_y}
                `;    
            }
            
        } else {
            // UP Lines
            if(distance_y*-1 <= angle*2) {
                angle = distance_y*-1/2;
            }
            if(minX) {
                if(distance_y*-1 <= angle*4) {
                    angle = distance_y*-1/4;
                }
                line += `
                M ${x} ${y} 
                L ${x+min_x_distance-angle} ${y} 
                A ${angle} ${angle} 1 0 0 ${x+min_x_distance} ${y-angle}
                L ${x+min_x_distance} ${center_y+angle}
                A ${angle} ${angle} 1 0 0 ${x+min_x_distance-angle} ${center_y}
                L ${end_x-min_x_distance} ${center_y}
                A ${angle} ${angle} 1 0 1 ${end_x-min_x_distance-angle} ${center_y-angle}
                L ${end_x-min_x_distance-angle} ${end_y+angle}
                A ${angle} ${angle} 1 0 1 ${end_x-min_x_distance} ${end_y}
                L ${end_x} ${end_y}
                `;
            } else {
                line += `
                M ${x} ${y} 
                L ${center_x-angle} ${y} 
                A ${angle} ${angle} 1 0 0 ${center_x} ${y-angle}
                L ${center_x} ${center_y} 
                L ${center_x} ${end_y+angle} 
                A ${angle} ${angle} 1 0 1 ${center_x+angle} ${end_y}
                L ${end_x} ${end_y}
                `;
            }
        }

        let arrow = `M ${end_x+0.5} ${end_y+0.5} L ${end_x-10} ${end_y-10}  M ${end_x+0.5} ${end_y-0.5} L ${end_x-10} ${end_y+10} `;

        switch(type) {
            case 'open': 
                return  line;
                break
            case 'close': 
                return  line + arrow;
                break
            case 'other': 
                return  line;
                break
            default:
                return line + arrow;
                
        }
        return  line + arrow;
    }
```

**Comment by NahumG10** [comment]
Hi, I'm using this solution for arrows on lines but is there a way to flip the arrow to be on the left side instead of right side?

**Comment by jerosoler** [comment]
Hi @NahumG10 

You would have to modify this part of the function.

Arrow for triangle.
And switch to indicate position of svg.

```javascript
        let arrow = `M ${end_x+0.5} ${end_y+0.5} L ${end_x-10} ${end_y-10}  M ${end_x+0.5} ${end_y-0.5} L ${end_x-10} ${end_y+10} `;

        switch(type) {
            case 'open': 
                return  line;
                break
            case 'close': 
                return  line + arrow;
                break
            case 'other': 
                return  line;
                break
            default:
                return line + arrow;
                
        }
        return  line + arrow;
```

**Comment by mushzak** [comment]
> I recover an old code. I would say what you want:
> 
> ```js
>     editor.createCurvature = function(start_pos_x, start_pos_y, end_pos_x, end_pos_y, curvature_value, type) {
>         let angle = 15;
>         const stroke = 2; // === stroke CSS. 
>         const input_distance = 10;
>         const fix_arrow_distance = 10;
>         const min_x_distance = 45;
> 
>         const x = start_pos_x + input_distance;
>         const y = start_pos_y;
>         const end_x = end_pos_x - fix_arrow_distance;
>         const end_y = end_pos_y;
>         const center_x = ((end_x - x)/2)+x;
>         const center_y =  ((end_y - y)/2)+y;
>         const distance_x = end_x - x;
>         const distance_y = end_y - y;
>         let minX = false;
>         
>         let line = '';
>         
>         if(distance_x <= min_x_distance) {
>             minX = true;
>         }
>         
>         if(end_y > y) {
>             //Down Lines
>             if(distance_y <= angle*2) {
>                 angle = distance_y/2;
>             }
>             if(minX) {
>                 if(distance_y <= angle*4) {
>                     angle = distance_y/4;
>                 }
>                 line += `
>                 M ${x} ${y} 
>                 L ${x+min_x_distance-angle} ${y} 
>                 A ${angle} ${angle} 1 0 1 ${x+min_x_distance} ${y+angle}
>                 L ${x+min_x_distance} ${center_y-angle}
>                 A ${angle} ${angle} 1 0 1 ${x+min_x_distance-angle} ${center_y}
>                 L ${end_x-min_x_distance} ${center_y}
>                 A ${angle} ${angle} 1 0 0 ${end_x-min_x_distance-angle} ${center_y+angle}
>                 L ${end_x-min_x_distance-angle} ${end_y-angle}
>                 A ${angle} ${angle} 1 0 0 ${end_x-min_x_distance} ${end_y}
>                 L ${end_x} ${end_y}
>                 `;
>             } else {
>                 line += `
>                 M ${x} ${y} 
>                 L ${center_x-angle} ${y} 
>                 A ${angle} ${angle} 1 0 1 ${center_x} ${y+angle}
>                 L ${center_x} ${center_y} 
>                 L ${center_x} ${end_y-angle} 
>                 A ${angle} ${angle} 1 0 0 ${center_x+angle} ${end_y}
>                 L ${end_x} ${end_y}
>                 `;    
>             }
>             
>         } else {
>             // UP Lines
>             if(distance_y*-1 <= angle*2) {
>                 angle = distance_y*-1/2;
>             }
>             if(minX) {
>                 if(distance_y*-1 <= angle*4) {
>                     angle = distance_y*-1/4;
>                 }
>                 line += `
>                 M ${x} ${y} 
>                 L ${x+min_x_distance-angle} ${y} 
>                 A ${angle} ${angle} 1 0 0 ${x+min_x_distance} ${y-angle}
>                 L ${x+min_x_distance} ${center_y+angle}
>                 A ${angle} ${angle} 1 0 0 ${x+min_x_distance-angle} ${center_y}
>                 L ${end_x-min_x_distance} ${center_y}
>                 A ${angle} ${angle} 1 0 1 ${end_x-min_x_distance-angle} ${center_y-angle}
>                 L ${end_x-min_x_distance-angle} ${end_y+angle}
>                 A ${angle} ${angle} 1 0 1 ${end_x-min_x_distance} ${end_y}
>                 L ${end_x} ${end_y}
>                 `;
>             } else {
>                 line += `
>                 M ${x} ${y} 
>                 L ${center_x-angle} ${y} 
>                 A ${angle} ${angle} 1 0 0 ${center_x} ${y-angle}
>                 L ${center_x} ${center_y} 
>                 L ${center_x} ${end_y+angle} 
>                 A ${angle} ${angle} 1 0 1 ${center_x+angle} ${end_y}
>                 L ${end_x} ${end_y}
>                 `;
>             }
>         }
> 
>         let arrow = `M ${end_x+0.5} ${end_y+0.5} L ${end_x-10} ${end_y-10}  M ${end_x+0.5} ${end_y-0.5} L ${end_x-10} ${end_y+10} `;
> 
>         switch(type) {
>             case 'open': 
>                 return  line;
>                 break
>             case 'close': 
>                 return  line + arrow;
>                 break
>             case 'other': 
>                 return  line;
>                 break
>             default:
>                 return line + arrow;
>                 
>         }
>         return  line + arrow;
>     }
> ```

Can you write the same for vertical?

**Comment by TungRuddy** [comment]
> > I recover an old code. I would say what you want:
> > ```js
> >     editor.createCurvature = function(start_pos_x, start_pos_y, end_pos_x, end_pos_y, curvature_value, type) {
> >         let angle = 15;
> >         const stroke = 2; // === stroke CSS. 
> >         const input_distance = 10;
> >         const fix_arrow_distance = 10;
> >         const min_x_distance = 45;
> > 
> >         const x = start_pos_x + input_distance;
> >         const y = start_pos_y;
> >         const end_x = end_pos_x - fix_arrow_distance;
> >         const end_y = end_pos_y;
> >         const center_x = ((end_x - x)/2)+x;
> >         const center_y =  ((end_y - y)/2)+y;
> >         const distance_x = end_x - x;
> >         const distance_y = end_y - y;
> >         let minX = false;
> >         
> >         let line = '';
> >         
> >         if(distance_x <= min_x_distance) {
> >             minX = true;
> >         }
> >         
> >         if(end_y > y) {
> >             //Down Lines
> >             if(distance_y <= angle*2) {
> >                 angle = distance_y/2;
> >             }
> >             if(minX) {
> >                 if(distance_y <= angle*4) {
> >                     angle = distance_y/4;
> >                 }
> >                 line += `
> >                 M ${x} ${y} 
> >                 L ${x+min_x_distance-angle} ${y} 
> >                 A ${angle} ${angle} 1 0 1 ${x+min_x_distance} ${y+angle}
> >                 L ${x+min_x_distance} ${center_y-angle}
> >                 A ${angle} ${angle} 1 0 1 ${x+min_x_distance-angle} ${center_y}
> >                 L ${end_x-min_x_distance} ${center_y}
> >                 A ${angle} ${angle} 1 0 0 ${end_x-min_x_distance-angle} ${center_y+angle}
> >                 L ${end_x-min_x_distance-angle} ${end_y-angle}
> >                 A ${angle} ${angle} 1 0 0 ${end_x-min_x_distance} ${end_y}
> >                 L ${end_x} ${end_y}
> >                 `;
> >             } else {
> >                 line += `
> >                 M ${x} ${y} 
> >                 L ${center_x-angle} ${y} 
> >                 A ${angle} ${angle} 1 0 1 ${center_x} ${y+angle}
> >                 L ${center_x} ${center_y} 
> >                 L ${center_x} ${end_y-angle} 
> >                 A ${angle} ${angle} 1 0 0 ${center_x+angle} ${end_y}
> >                 L ${end_x} ${end_y}
> >                 `;    
> >             }
> >             
> >         } else {
> >             // UP Lines
> >             if(distance_y*-1 <= angle*2) {
> >                 angle = distance_y*-1/2;
> >             }
> >             if(minX) {
> >                 if(distance_y*-1 <= angle*4) {
> >                     angle = distance_y*-1/4;
> >                 }
> >                 line += `
> >                 M ${x} ${y} 
> >                 L ${x+min_x_distance-angle} ${y} 
> >                 A ${angle} ${angle} 1 0 0 ${x+min_x_distance} ${y-angle}
> >                 L ${x+min_x_distance} ${center_y+angle}
> >                 A ${angle} ${angle} 1 0 0 ${x+min_x_distance-angle} ${center_y}
> >                 L ${end_x-min_x_distance} ${center_y}
> >                 A ${angle} ${angle} 1 0 1 ${end_x-min_x_distance-angle} ${center_y-angle}
> >                 L ${end_x-min_x_distance-angle} ${end_y+angle}
> >                 A ${angle} ${angle} 1 0 1 ${end_x-min_x_distance} ${end_y}
> >                 L ${end_x} ${end_y}
> >                 `;
> >             } else {
> >                 line += `
> >                 M ${x} ${y} 
> >                 L ${center_x-angle} ${y} 
> >                 A ${angle} ${angle} 1 0 0 ${center_x} ${y-angle}
> >                 L ${center_x} ${center_y} 
> >                 L ${center_x} ${end_y+angle} 
> >                 A ${angle} ${angle} 1 0 1 ${center_x+angle} ${end_y}
> >                 L ${end_x} ${end_y}
> >                 `;
> >             }
> >         }
> > 
> >         let arrow = `M ${end_x+0.5} ${end_y+0.5} L ${end_x-10} ${end_y-10}  M ${end_x+0.5} ${end_y-0.5} L ${end_x-10} ${end_y+10} `;
> > 
> >         switch(type) {
> >             case 'open': 
> >                 return  line;
> >                 break
> >             case 'close': 
> >                 return  line + arrow;
> >                 break
> >             case 'other': 
> >                 return  line;
> >                 break
> >             default:
> >                 return line + arrow;
> >                 
> >         }
> >         return  line + arrow;
> >     }
> > ```
> 
> Can you write the same for vertical?

`editor.createCurvature = function (start_x, start_y, end_x, end_y, curvature_value, type) {
        var center_y = ((end_y - start_y) / 2) + start_y;
        var default_round_radius = 10;
        var round_radius = Math.min(default_round_radius, Math.abs(start_x - end_x), Math.abs(start_y - end_y));

        var isRight = end_x > start_x;
        var isDown = end_y > start_y;
        //// ARROW

        const fix_arrow_distance = 11;
        var x = end_x;
        var y = end_y - fix_arrow_distance;
        let arrow;
        if(isDown){
          arrow = ` M ${x} ${y} L ${x-5} ${y-8} L ${x+5} ${y-8} L ${x} ${y} Z` + 
          ` M ${x} ${y - 2} L ${x-2} ${y-5} L ${x+2} ${y-5} L ${x} ${y - 2} Z`
        } else {
          arrow = ` M ${x - 5} ${end_y + fix_arrow_distance * 2} L ${x} ${end_y + fix_arrow_distance} L ${x+5} ${end_y + fix_arrow_distance * 2} Z` + 
          ` M ${x - 3} ${end_y + 19} L ${x + 4} ${end_y + 19}`
        }
        return  `M ${start_x} ${start_y}
        L ${start_x} ${isDown ? center_y - round_radius : center_y + round_radius}
        A ${round_radius} ${round_radius} 0 0 ${isRight !== !isDown ? 0 : 1} ${isRight ? start_x + round_radius : start_x - round_radius} ${center_y}
        L ${isRight ? end_x - round_radius : end_x + round_radius} ${center_y}
        A ${round_radius} ${round_radius} 0 0 ${isRight !== !isDown ? 1 : 0} ${end_x} ${isDown ? center_y + round_radius : center_y - round_radius}
        L ${end_x} ${end_y}` + arrow;
      }`
