### ISSUE TITLE
drag and drop multiple node connected 

### ISSUE THREAD

**Issue by Sri-5555** [jerosoler/Drawflow#633]
Hi @jerosoler,

how to create multiple connected node in a canvas  while drag and dropping a single node 

like need the below example while draging and droping a node from the list 

![drawflow](https://user-images.githubusercontent.com/108112427/212034718-d7de6e53-c7eb-4d50-8ec5-919c251632b1.PNG)

**Comment by Sri-5555** [comment]
Thanks @jerosoler  It works

**Comment by Sri-5555** [comment]
can we group the above nodes. move all the group nodes while dragging and delete all the grouped nodes while delete

**Comment by jerosoler** [comment]
You will need to implement a layout similar to this.

- https://github.com/jerosoler/Drawflow/issues/322
