### ISSUE TITLE
How to customize the Node?

### ISSUE THREAD

**Issue by liuyinze** [jerosoler/Drawflow#634]
Hi Jero,

I have a question regarding the module customization. 

 
![image](https://user-images.githubusercontent.com/47323422/212049904-5828fa08-4b4a-46eb-bcbb-3407a2b4868b.png)

How can I use your addnode() method to customize such kind of node? What I want is the editable text displayed. 

Is that possible that you can show me the code behind this node?

Thanks!

**Comment by jerosoler** [comment]
I do not understand your question.

You can see this example here: https://github.com/jerosoler/Drawflow/blob/master/docs/index.html

**Comment by liuyinze** [comment]
> I do not understand your question.
> 
> You can see this example here: https://github.com/jerosoler/Drawflow/blob/master/docs/index.html

That's helpful!
