### ISSUE TITLE
Position connectors relatively to the content within a node

### ISSUE THREAD

**Issue by auxdesigner** [jerosoler/Drawflow#635]
Is there a way to position connectors relatively to the HTML content in the node? E.g. align the connector to a DIV (see screenshot). These DIVs / connectors are dynamically generated, so I can't hardcode the css.

Thanks!

<img width="276" alt="img 278" src="https://user-images.githubusercontent.com/1220314/212180639-349dab6e-077d-480b-8239-123985a9e938.png">

**Comment by jerosoler** [comment]
View this method: 
- https://github.com/jerosoler/Drawflow/issues/628#event-8152915194

**Comment by auxdesigner** [comment]
That works. Thank you!
