### ISSUE TITLE
Designated Inputs and Outputs

### ISSUE THREAD

**Issue by AfroYetty** [jerosoler/Drawflow#636]
Is there anything on the cards to be able to link inputs to labels or objects inside the node.

Functionality:
- Linking inputs to specific labels represented as objects in the node for both input and output 
- Rearange line links when input objects change position

Before rearange
![image](https://user-images.githubusercontent.com/31693987/212484498-e5655ad9-9bf8-4913-9657-aa4bb7a4969c.png)

After rearange
![image](https://user-images.githubusercontent.com/31693987/212485206-5c7c0661-67f1-4b9a-8792-e030bda0b202.png)

This is likely possible by hacking the system and physically moving a node into another node and just piggybacking off the base functionality, but if it's natively supported, that would be nice

**Comment by jerosoler** [comment]
1: Here is an example of how to align output to element.

- https://github.com/jerosoler/Drawflow/issues/363#issuecomment-1050699201

2: I don't understand.
But you can detect node movements using the `nodeMoved` event

**Comment by AfroYetty** [comment]
Interesting, ok that will work for what I need, thanks :)

Point to is then not important.

On a side not in relation to this, Is it possible to give connection ports custom name?

For example, connection ports are currently labeled input_<no>, output_<no> so when it's exported it exports as

`json
{
    "inputs":{
        "input_1":{
            "connections":[
                 {
                     "node":"2",
                     "input":"output_1"
                 }
            ]
        }
    }
}
`

Assigning a custom name value like "input_username"

The expected export
`json
{
    "inputs":{
        "input_username":{
            "connections":[
                 {
                     "node":"2",
                     "input":"output_1"
                 }
            ]
        }
    }
}
`

**Comment by jerosoler** [comment]
Cannot currently be assigned a name. They need to have a number.

But you could add information like this:

```javascript
editor.drawflow.drawflow.Home.data[1].outputs["output_1"].name = "output_username";
```
Another way would be saving the data in the information

```javascript
editor.addNode('NodeA', 1, 1, 440, 300, 'NodeA', { outputsname: { 1: "output_username "}}, 'NodeA');
```

**Comment by AfroYetty** [comment]
Very cool, ok I'll play around with that, thanks for the assistance.

Steller project, can't wait to see where it goes.
