### ISSUE TITLE
Get input and Output

### ISSUE THREAD

**Issue by LauritzOffe** [jerosoler/Drawflow#641]
I'm sorry if this is a stupid question. 
I want to generate my own json file from the diagram. It should look something like this:

`data = [
{
id: 0,
text: "Exsample",
inputs: [1, 4, 6],
outputs: [2, 9, 7]
},
 {.....}
]`

How can I get the Id's of the input and output for each element?

**Comment by jerosoler** [comment]
Have you tried exporting?

```javascript
const data = editor.export();
```

**Comment by LauritzOffe** [comment]
Of course, that would be a possibility.
I'm probably just missing a point in the documentation, but it should be possible to get data via the input, such as all id's from a node's input. This could of course also be a string or any other data.

**Comment by jerosoler** [comment]
But when do you want to get that information when clicked? In the input or output?

You can get the information of a node like this:

```javascript
const id = 5;
const nodeInfo = editor.getNodeFromId(id);
```

**Comment by LauritzOffe** [comment]
I was looking for a list of all the information I can get from a node. 
`editor.getNodeFromId(id);`
This shows all the info I need.
Thanks for the support
