### ISSUE TITLE
Group node while initial drag and drop 

### ISSUE THREAD

**Issue by Sri-5555** [jerosoler/Drawflow#644]
Hi @jerosoler,

I was trying to group some node while drag and drop, which I can drag and move or delete all at once. 

I tried with the below example of yours(https://github.com/jerosoler/Drawflow/issues/423#issuecomment-1131533142) here grouping happens on draging into the box. Is there any way to implement this while initial drag and drop itself 

![image](https://user-images.githubusercontent.com/108112427/214217805-93625122-f254-4b6b-af91-5a465820d7aa.png)

**Comment by jerosoler** [comment]
You could listen for the nodeCreated event and do the same thing that is done in the nodeMoved event.

I think that could work with that.

**Comment by Sri-5555** [comment]
Thanks @jerosoler. Its works
