### ISSUE TITLE
How I can update html and data? when I click to node I need to fill data and then update

### ISSUE THREAD

**Issue by mushzak** [jerosoler/Drawflow#645]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/14214670/214306311-9fab048e-5c40-4cc1-8f8d-c0dcc9155c4b.png">

**Comment by mushzak** [comment]
I know that I can use editor.updateNodeFromId and send {data}, but how I can use it for updating existing nodes? can I use data ? and if yes how?

**Comment by jerosoler** [comment]
View:

- https://github.com/jerosoler/Drawflow/issues/561

or: 

- https://github.com/jerosoler/Drawflow/issues/490

**Comment by mushzak** [comment]
df-* this is working but it is for form elements, but as you can see in my screenshot there are no inputs, name and description

**Comment by jerosoler** [comment]
You can use df attributes without form, only for save information. 

If you only want to modify the html you will have to update the template and the html.

Example adding input to node: in html and save for export.

https://github.com/jerosoler/Drawflow/issues/226#issuecomment-901025520

**Comment by mushzak** [comment]
can I do something like <span df-NAME></span>?

**Comment by jerosoler** [comment]
No, the html is not updated automaticaly. It would have to be forced as i specified before.

Maybe you could try an input type disabled.

**Comment by mushzak** [comment]
will try thanks
