### ISSUE TITLE
Can I disable deleting for node? but not for alll, editor_mode = 'view' but for ONLY ONE NODE

### ISSUE THREAD

**Issue by mushzak** [jerosoler/Drawflow#647]

**Comment by jerosoler** [comment]
You can use any of these methods:
- #10
- #70

**Comment by jerosoler** [comment]
Add before `editor.start()`

```javascript
editor.contextmenu = function(e) { e.preventDefault() }
```

**Comment by mushzak** [comment]
Thank you @jerosoler for you example, but this will stop for all nodes, is there is a way to disable for custom node you want?

**Comment by eviltik** [comment]
@mushzak the "e" parameter if the event. So you can probably check what is "target" attribute and preventDefault or not, depending of your needs.

**Comment by jerosoler** [comment]
Perhaps in this case it would be better to use an event. Example with idNode 1.

```javascript
    editor.on("contextmenu", (e) =>  {
        const idNode = 1 // Example with nodeId ===  1
        if(editor.node_selected !== null)  {
            if(editor.node_selected.id === `node-${idNode}`) {
                editor.node_selected = null;
            }
        }
    })
```

**Comment by mushzak** [comment]
thank you very much
