### ISSUE TITLE
[FEATURE-REQUEST] Detect line cross when moving an unlinked node

### ISSUE THREAD

**Issue by eviltik** [jerosoler/Drawflow#649]
Like in Blender (3D software), when you are moving a unlinked node and if it cross an existing line (link) between 2 other nodes (let's say node A and node B), then, if some condition matches (i.e input/output integrity check), then i can release the mouse button and the new node is automatically linked with the node A for inputs, node B for outputs, removing the initial link between node A & node B. This is a challenge :)

Btw:
* this library is really cool, the code is clear, congrats and THANK YOU to make it opensource.
* can you enable sponsors stuff or provide a way to give you money, because @jerosoler you made a fantastic job
  *  oups, already enabled !
* are you looking for a secondary maintainer (no commit since 7 months, 7 PR waiting ..)

Have a good day

**Comment by jerosoler** [comment]
Hello!! 

Thanks for donation! 🎉❤️

What you ask can be done.

I have created this example for you.

It is a simple html file.
You can try dragging the "CCC" node between the "AAA" node connection to "BBB".

Complete code:

```javascript
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css"
    />
    <script src="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.js"></script>
    <style>
      #drawflow {
        position: relative;
        width: 100%;
        height: 800px;
        border: 1px solid red;
      }

      .drawflow .connection .main-path.hover-drop {
        stroke: pink;
       }
      </style>
  </head>
  <body>
    <div>
        <div id="drawflow"></div>  
    </div>

    <script>

    const id = document.getElementById("drawflow");
    const editor = new Drawflow(id);
    
    editor.start();

    /* CODE FOR EXAMPLE */

    let dragElementHover = null;
    let last_x = 0;
    let last_y = 0;
    editor.on("mouseMove", ({x,y}) => {
        if(editor.node_selected && editor.drag) {
            const nodeID = editor.node_selected.id.slice(5);
            const nodeInfo = editor.getNodeFromId(nodeID);
            const nodeConnected = (nodeInfo.inputs.input_1.connections.length === 0 && nodeInfo.outputs.output_1.connections.length  === 0 ? true : false); 
            
            const eles = document.elementsFromPoint(x,y);
            const ele = eles.filter( ele => ele.classList[0] === "main-path");
            if(ele.length > 0 && nodeConnected) {
                dragElementHover = ele[0];
                dragElementHover.classList.add("hover-drop");
            } else {
                if(dragElementHover != null) {
                    dragElementHover.classList.remove("hover-drop");
                    dragElementHover = null;
                }
            }
        } 
        last_x = x;
        last_y = y;
    })

    editor.on("nodeMoved", (id) => {
        
        if(dragElementHover !== null) {
            const nodeDragId = id;
            const connection = dragElementHover.parentElement;
            
            const inputNode = connection.classList[1].slice(13);
            const outputNode = connection.classList[2].slice(14);
            const outputClass = connection.classList[3];
            const inputClass = connection.classList[4];

            editor.removeSingleConnection(outputNode,inputNode, outputClass, inputClass);

            editor.addConnection(outputNode, nodeDragId ,outputClass, 'input_1');
            editor.addConnection(nodeDragId, inputNode ,'output_1', inputClass);
            
            dragElementHover.classList.remove("hover-drop");
            dragElementHover = null;
        } 
    })
    /* END  CODE FOR EXAMPLE */

    const nodeA = editor.addNode('aaa', 1, 1, 100, 300, 'aaa', {}, 'aaa' );
    const nodeB = editor.addNode('bbb', 1, 1, 800, 300, 'bbb', {}, 'bbb' );
    const nodeC =  editor.addNode('ccc', 1, 1, 300, 200, 'ccc', {}, 'ccc' );
    const nodeD =  editor.addNode('ddd', 1, 1, 500, 500, 'ddd', {}, 'ddd' );
    const nodeE =  editor.addNode('eee', 1, 1, 800, 500, 'eee', {}, 'eee' );
    editor.addConnection(nodeA, nodeB, 'output_1', 'input_1');
    editor.addConnection(nodeD, nodeE, 'output_1', 'input_1');
   
</script> 
  </body>
</html>
```

The only problem that exists in this code is that it only detects it in the mouse pointer. And not with the width and height of the node.

It is difficult to do a detection in an SVG line.
You could help with this guide:
https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

I answer:
- this library is really cool, the code is clear, congrats and THANK YOU to make it opensource.
> Thanks!
- can you enable sponsors stuff or provide a way to give you money, because @jerosoler you made a fantastic job
-  oups, already enabled ! 
> Yes, Only paypal.  In the future I will consider github sponsor account. 
- are you looking for a secondary maintainer (no commit since 7 months, 7 PR waiting ..)
> Currently I am only maintaining the library. I'm working on a new library with many more features.
  (Undo, redo, multiselect, keys configuration, prevent events...)
  There are also many features PR that are case-specific.
  And better programmed.

**Comment by eviltik** [comment]
Really great 👍
