### ISSUE TITLE
Alignment of text within a title box to the node connectors

### ISSUE THREAD

**Issue by CloudUX-AU** [jerosoler/Drawflow#651]
Hi all - Im trying to figure out if it is possible to align title box markup to the node connector 'circles'. Has anyone found a way to ensure text can be positioned alongside specific node connectors?  

For example - I have a title box with 10 output connectors. How might I structure the title box markup so I can place 10 text labels alongside each of the output connectors?

**Comment by jerosoler** [comment]
View: 
- #363 
- #623

**Comment by CloudUX-AU** [comment]
Thanks for that - most helpful!
