### ISSUE TITLE
Vue3 and TS implementation example

### ISSUE THREAD

**Issue by theJavaWolf** [jerosoler/Drawflow#653]
Hello, I have been trying to implement your example from https://github.com/jerosoler/Drawflow/issues/100 .

I get the following error:
![image](https://user-images.githubusercontent.com/73689661/217129694-066ee2c5-ee15-4d20-a3d1-0b2e755d0c1b.png)

Has there been any breaking changes since that issue?
If yes could you please upload an updated version of the simple example from https://github.com/jerosoler/Drawflow/issues/100 please?

**Comment by jerosoler** [comment]
Hello,

The problem I see is that you are using "script setup" with an export, remove the word setup.

According to what marks the error.

You can see a complete example with vue3.
Demo: https://jerosoler.github.io/drawflow-vue3-example/
Repo: https://github.com/jerosoler/drawflow-vue3-example

jero

**Comment by theJavaWolf** [comment]
Thank you very much!
