### ISSUE TITLE
Connection Reroute

### ISSUE THREAD

**Issue by AfroYetty** [jerosoler/Drawflow#657]
**Problem:**

Strange behavior when adding a retoute point on a connection.

The reroute point seems to be placed incorrectly but can't seem to see any obvious reasons why that would happen

**Expected Behavior** 

Taken from Drawflow example site: https://jerosoler.github.io/Drawflow/

![image](https://user-images.githubusercontent.com/31693987/218202471-eacbef85-6a98-4ecb-8f69-1af1301e8a0e.png)

**Experienced Behavior**

On my app

![image](https://user-images.githubusercontent.com/31693987/218202914-583ff528-d582-4c21-b1de-74b1c2ac6a8d.png)

This behavior can also be replicated on the CodePen example site: https://codepen.io/KikePuma/pen/OJXXXdb

![image](https://user-images.githubusercontent.com/31693987/218203105-2de70b07-a2fe-4117-be1c-8132be4aa666.png)

Version:
Css: 0.0.59
JS: 0.0.59

Environment:
Babel
JSX
React
TailwindCss
Jquery

**Comment by jerosoler** [comment]
Hello,

It seems to be a css problem.
Surely some class is interfering.

Example with the minimum of operation.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css"
    />
    <script src="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.js"></script>
    <style>
      #drawflow {
        position: relative;
        width: 100%;
        height: 800px;
        border: 1px solid red;
      }
      </style>
  </head>
  <body>
    <div>
        <div id="drawflow"></div>  
    </div>
    <script>

    var id = document.getElementById("drawflow");

    const editor = new Drawflow(id);
    editor.reroute  =  true;
   
    editor.start();
    


    editor.addNode('test1', 1, 1, 440, 300, 'test1', {}, '<textarea></textarea><div id="content"></div>');
    editor.addNode('test1', 1, 1, 200, 300, 'test1', {}, '<textarea></textarea><div id="content"></div>');
    
    const nodeA = editor.addNode('NodeA', 1, 1, 440, 300, 'NodeA', {}, 'NodeA');
    const nodeB = editor.addNode('NodeB', 1, 1, 840, 300, 'NodeB', {}, 'NodeB');
    const nodeC = editor.addNode('NodeC', 1, 1, 840, 500, 'NodeC', {}, 'NodeC');
    editor.addConnection(nodeA, nodeB, "output_1", "input_1");	
    editor.addConnection(nodeA, nodeC, "output_1", "input_1");
   
</script> 
  </body>
</html>
```

It reminds me of one of these issues, see if any of them solve the problem.

- https://github.com/jerosoler/Drawflow/issues/378
- https://github.com/jerosoler/Drawflow/issues/292
- https://github.com/jerosoler/Drawflow/issues/379

**Comment by AfroYetty** [comment]
Hi,

Thanks, will give those a look and see if I can find what's causing the conflict

**Comment by AfroYetty** [comment]
I my goodness I am so dumb, I completely forgot that I actually copied my drawflow style sheet from that code pen site, when I disable that sheet it works as expected 

Vanilla style with all my all other style sheets enabled (Working)
![image](https://user-images.githubusercontent.com/31693987/218302253-f7e8f8a6-bdff-40dc-8101-52fdb763adb3.png)


So that works, I found another issue with the adding of reroutes, it seems that when you add a reroute point it adds the point in the right place but the incorrect segment of the svg path is adjusted

![image](https://user-images.githubusercontent.com/31693987/218305999-d49e24c8-cba5-4646-adeb-7ad1637b9e12.png)

I will go through the open issues and see if there is already an issue logged for that, if not I'll make a new one

**Comment by jerosoler** [comment]
Use for fix adding points:

```javascript
editor.reroute_fix_curvature = true;
```

**Comment by AfroYetty** [comment]
Shot, thanks

Keep up the good work :)
