### ISSUE TITLE
Get all nodes connected to one root node 

### ISSUE THREAD

**Issue by urre** [jerosoler/Drawflow#658]
Hi, 

Is it possible to find all nodes that connects to a "base/root" node. I have this scenario:

![CleanShot 2023-02-14 at 19 08 41@2x](https://user-images.githubusercontent.com/307676/218821385-f8b7442c-bdb3-4521-a984-9ce579e66c66.jpg)

In this case I'd like to color the top connectors in the same color, giving all those nodes a certain class/color etc

**Comment by jerosoler** [comment]
Hello,

You can get the information of a node.
```javascript
const infoNode = editor.getNodeFromId(id);
console.log(infoNode);
```
In the information you will find the inputs and outputs. And you can search again with the method.

**Comment by urre** [comment]
Thanks, yes.
