### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by flamendless** [jerosoler/Drawflow#66]
Hi, im looking forna node graph libraries for the web (if possible with support for vue). Are the node and wire/connector customizable? My plan is to use this as similar to unreal blueprint (not full scope but just the basics) like multiple input fields in the node.

**Comment by jerosoler** [comment]
Hi @flamendless 

The library supports the vue components, view examples: https://github.com/jerosoler/Drawflow/issues?q=is%3Aissue+label%3AVue+is%3Aclosed

You can customize the node and the connector (the connector more or less). You can see the theme editor or use its css: https://jerosoler.github.io/drawflow-theme-generator/

The library allows multiple inputs to nodes and multiple outputs.

Jero

**Comment by flamendless** [comment]
@jerosoler thank you.

Another question though, can the data be saved or serialized?

**Comment by jerosoler** [comment]
Hello @flamendless 

Yes and yes!

View demo: https://jerosoler.github.io/Drawflow/

Button export and view a AWS node. 

For export import data view: https://github.com/jerosoler/Drawflow#export--import

Jero
