### ISSUE TITLE
Get data by Mysql (RESOLVED)

### ISSUE THREAD

**Issue by maxivane** [jerosoler/Drawflow#673]
I'm Brazilian and I'm using a translator,
What is the easiest or best way to get the data from mysql??
I tried using the example below, but I don't know how to put the id in the node, so it didn't work
var data = { "name": '' ,"id":2};

#667

**Comment by maxivane** [comment]
**RESOLVED.**
**Method Save data:**
+++++++++++++++
`var dados = {
	dadosJson: JSON.stringify(editor.export())
};
$.post("addons/sysup/mapa/save_node",dados).done(function(data){
	if (data == "success"){
		alert("Salvo com Sucesso");
	}else{
		alert(data);
	}
});`

**Method Get Data**
`$.ajax({
	type: "POST",
	url: "addons/sysup/mapa/get_all_nodes",
	dataType: "JSON",
	success: function(data) {
		for(var i=0;data.length>i;i++){
			const dataImport = JSON.parse(data[i].data);
			editor.import(dataImport);
		};
	}
});`

**Comment by fullsendai** [comment]
Hey Maxivane, just curious how far did you go with integrating this project with php/mysql?

**Comment by maxivane** [comment]
> Hey Maxivane, just curious how far did you go with integrating this project with php/mysql?

Hi... I was able to save and receive the data from the db

**Comment by fullsendai** [comment]
Awesome! I'm actually trying to do this right now. Do you think this project is good enough for a production app?

**Comment by fullsendai** [comment]
Do you mind sharing your method Maxi?
