### ISSUE TITLE
how to store the created connection label text

### ISSUE THREAD

**Issue by Gsmraaj** [jerosoler/Drawflow#678]
hi sir, thank you so much for you to creating this wonderful library which is very useful to do my college project
    , i found a way to use the connection label text , 
    but i dont know how to store it like below , 
     
          outputs: {
            output_1: {
              connections: [
                {
                  node: "2",
                  output: "input_1",
                  conLabelTxt: "something"
                },
                {
                  node: "3",
                  output: "input_1",
                  conLabelTxt: "something"
                },
              ],
            },
          },
          
          for (let nodeId in dataToImport.drawflow.Home.data) {
         let node = dataToImport.drawflow.Home.data[nodeId];
         let outputKeys = Object.keys(node.outputs);
           for (let i = 0; i < outputKeys.length; i++) {
            let outputKey = outputKeys[i];
           let connections = node.outputs[outputKey].connections;
           for (let j = 0; j < connections.length; j++) {
            let connection = connections[j];

      let conLabel = document.querySelector(
        `.connection.node_in_node-${connection.node}.node_out_node-${node.id}.output_1.input_1`
      );

      if (connection.conLabelTxt !== undefined) {
        addLabelText(conLabel, `${connection.conLabelTxt}`);
      }
    }
  }
}

**Comment by jerosoler** [comment]
You can save to the drawflow's JSON by following the example below

- https://github.com/jerosoler/Drawflow/issues/40#issuecomment-692820035

**Comment by Gsmraaj** [comment]
editor.drawflow.drawflow.Home.data[
      conOpId
    ].outputs.output_1.connections.find(
      (connection) => connection.node === conIpId
    ).conLabelTxt = `"${successMsg.value}"`;
    
    thanks sir it worked
