### ISSUE TITLE
Create connection on drop over node

### ISSUE THREAD

**Issue by vartakshreyas** [jerosoler/Drawflow#679]
Hi 

I am using your package in angular and i must say that its a very good packge. 
Currentlly i got a requirement from client side and i am asking your help for same.

The requirement is:
Can we create a connection between two node after drop anywhere on node destination node?

I go through github conversations on same but i didn't get any reference.
Could you please give me any reference to achive that?

**Comment by jerosoler** [comment]
View this issues:

- https://github.com/jerosoler/Drawflow/issues/175
- https://github.com/jerosoler/Drawflow/issues/419
- https://github.com/jerosoler/Drawflow/issues/326

**Comment by vartakshreyas** [comment]
Thanks for the quick reply.
But i am not looking for this kind of solution.

My scenario is:
I have two nodes in editor and i am starting connection from output of first node.
but instead of drop on input of second node, i am dropping it in middle of node area.
In this case, is it possible to create connection between those nodes?

or can i get id of that node on which i have droped connection string?

here is the reference video for my query
https://user-images.githubusercontent.com/42171629/231441849-69e2f1fd-fdaa-4f74-8449-761b072d7203.mp4

**Comment by jerosoler** [comment]
Just apply this option

Use:
```javascript
editor.force_first_input = true;
```

**Comment by vartakshreyas** [comment]
Thats work like a magic...Thank you very much
