### ISSUE TITLE
How to work with Vue component events

### ISSUE THREAD

**Issue by chastoedov** [jerosoler/Drawflow#68]
Hi!

I Create blocks using the vue component, but I can't find on the Internet how to work with events that I return from this component.

Below is an example of rendering a component.

![image](https://user-images.githubusercontent.com/56137952/99287984-06b3bc00-284c-11eb-9457-8e8191398da0.png)

I create events inside the component, but I can't catch them outside of this component.

![image](https://user-images.githubusercontent.com/56137952/99288263-64480880-284c-11eb-9bbd-05499fb8f796.png)

Have you solved this problem? Can you help?

**Comment by jerosoler** [comment]
Hello @chastoedov 

View example with events
https://github.com/jerosoler/Drawflow/issues/37#issuecomment-717822302

It was useful to you?

Jero

**Comment by chastoedov** [comment]
Thank you, I did everything in a couple of minutes and it worked!

I saw this ticket before, I understood it, but for some reason I decided that this would not work for me....)))
