### ISSUE TITLE
Misalign node connection after change in browser zoom 

### ISSUE THREAD

**Issue by vartakshreyas** [jerosoler/Drawflow#686]
Hi 

I am using your package and i am getting proper support from your side to fullfill my requirements.
Now i got stuck at one point, where connection alignments got mismatched with connection point when i reduce browser zoom. 

Please look at attached picture where i set my browser zoom to 75%.
I have gone through issues posted on github but didn't get any help. Is there any way that you can suggest to tackle this situation?
![Mystique](https://user-images.githubusercontent.com/42171629/235621134-4c55b71c-637c-4f1d-a5d3-dc6d19d386ba.png)

**Comment by jerosoler** [comment]
View: 
- https://github.com/jerosoler/Drawflow/issues/684#event-9127169207

Try by default, without extra style.

**Comment by vartakshreyas** [comment]
I have tried that solution but still i am facing same issue.
At 80% its working fine but misaligned connection at 75%

**Comment by jerosoler** [comment]
Have you tried the blank example that appears in the previous issue?

In that case you get an error?

Have you tried deactivating all your css?

**Comment by vartakshreyas** [comment]
Hi..Thanks for proper suggetion.
By removing css added by me and using package css resolved my issue.

I am using this package in angular so i have to added css file path in angular.json file to reflect package css.

Thanks @jerosoler to be there with proper guidance.
