### ISSUE TITLE
Dynamic Select don't work !

### ISSUE THREAD

**Issue by Chaymae-Elmoueden** [jerosoler/Drawflow#689]
After selecting the files list from the database , it fails to remember the value of 'df-mytemplate

![dynsele](https://user-images.githubusercontent.com/113434646/236830447-2b1ce403-9b8b-4104-9543-cdb4cd575d53.JPG)

**Comment by jerosoler** [comment]
View example of vue:
https://github.com/jerosoler/drawflow-vue3-example/blob/master/src/components/nodes/node1.vue

**Comment by Chaymae-Elmoueden** [comment]
It's working fine now. I tried applying it to v-select as well. I can retrieve its value, but I can't pass it through the output to the node. Thank you. 
![v-select](https://github.com/jerosoler/Drawflow/assets/113434646/65874144-897d-40e8-af83-197404fe231b)

**Comment by Chaymae-Elmoueden** [comment]
I tried to this 
![essai](https://github.com/jerosoler/Drawflow/assets/113434646/29870c2b-4ff2-4c99-b733-c15897821627)
