### ISSUE TITLE
Add a method to get a node from id

### ISSUE THREAD

**Issue by icabbi-joegarlick** [jerosoler/Drawflow#7]
Hello!

First of all, love this script!

I was wondering if it would be possible to add a function to be able to get the node object from the node is. 

The reason i want this is because I don't want multiple connections from an output. My idea is to register the connection event which passes the node ID, use that id to see how many connections the output it currently has. 

Thanks,
Joe

**Comment by jerosoler** [comment]
Hello

I love that you like it!

A function for example ???

```javascript
getNodeInfoId(id).
```

It returns the same information as this:
```javascript
editor.drawflow.drawflow.Home.data[3]
```
In the example:

```javascript
{
  "id": 3,
  "name": "telegram",
  "data": {
    "channel": "channel_2"
  },
  "class": "telegram",
  "html": "\n          <div>\n            <div class=\"title-box\"><i class=\"fab fa-telegram-plane\"></i> Telegram bot</div>\n            <div class=\"box\">\n              <p>Send to telegram</p>\n              <p>select channel</p>\n              <select df-channel>\n                <option value=\"channel_1\">Channel 1</option>\n                <option value=\"channel_2\">Channel 2</option>\n                <option value=\"channel_3\">Channel 3</option>\n                <option value=\"channel_4\">Channel 4</option>\n              </select>\n            </div>\n          </div>\n          ",
  "typenode": false,
  "inputs": {
    "input_1": {
      "connections": [{
        "node": "7",
        "input": "output_1"
      }]
    }
  },
  "outputs": {},
  "pos_x": 1032,
  "pos_y": 184
}
```

With this would be solved?



Jero

**Comment by icabbi-joegarlick** [comment]
Hey @jerosoler !

Yes thats exactly it, I have been using:

`getNodeFromId: function (id) {
    return this.editor.drawflow.drawflow.Home.data[id];
},`

A addConnection function would be good too, however I dont mind making a PR for this if that helps you?

Also I would like to note that the event for connectionCreated and connectionRemoved has a typo, ouput_id should be output_id

Thanks,
Joe!

**Comment by icabbi-joegarlick** [comment]
Would also like to mention that deleting a node that has connections doesn't trigger connectionRemoved for the connections that were destroyed because of this

**Comment by jerosoler** [comment]
Hello

Thank you! 👏👏

I just implemented your changes.
I also noticed another mistake. But it has already been corrected.
You will see a new function `getModuleFromNodeId`.

You can see the changes in the last commits.

The `getNodeFromId` function has also been implemented.

Anything else?

**Comment by icabbi-joegarlick** [comment]
Hey @jerosoler 

Thank you so much for implementing my changes 🎉🎉 Im sure others will find these useful!

I have just created a function to create connections programatically, see: https://github.com/icabbi-joegarlick/Drawflow/commit/ed8263c277b9c2459298c7d6f8798517378d0910

Im not sure if this function is 100% correct and you will probably be able to tell me if it is however it seems to be working in my use case (custom loading using addNode and addConnection)

Thanks again!
Joe

**Comment by jerosoler** [comment]
WoW!!! 👀👀 

I would say it is not correct.

The connection to node i is added directly not to the general flow. If you change modules you will see why. I think that it would not be exported correctly either.

You should also take into account what module you are on!

Jero

**Comment by jcbjoe** [comment]
Thanks for the feedback @jerosoler !

I mean its working for me so far, ill keep testing it tomorrow. Do you think you would be able to make a similar function that is correct?

Thanks,
Joe

**Comment by icabbi-joegarlick** [comment]
Thanks for the feedback @jerosoler !

I mean its working for me so far, ill keep testing it tomorrow. Do you think you would be able to make a similar function that is correct?

Thanks,
Joe

**Comment by jerosoler** [comment]
I'll look at it tomorrow.

I just added some modifications and fixes

**Comment by jerosoler** [comment]
Hi! 👋

Method added `addConnection`
Commit: https://github.com/jerosoler/Drawflow/commit/de99a4e2d42bfbaf2a0ed49cd064721f7c0840b6

Use:
`addConnection(id_output, id_input, output_class, input_class)`

Example:
 `addConnection(15,16,'output_1','input_1')`

And other fixes and features ;)

**Comment by icabbi-joegarlick** [comment]
Hey @jerosoler!

Thank you so much for looking into this for me! I really appreciate it. This will make development so much easier.

We can now close this issue now.

I will add another issue if I come across anything else!

Thanks again,
Joe
