### ISSUE TITLE
How to customize such a nested combination

### ISSUE THREAD

**Issue by MikeNo007** [jerosoler/Drawflow#703]
example：
<div>
        <el-select></el-select>
        <el-select></el-select>
 </div>
or:
     <div>
        <el-select></el-select>
        <el-input></el-input>
        <el-input></el-input>
     </div>
Drag the prepared elements into the div.

**Comment by jerosoler** [comment]
Not example added???

View for groups elements: 
- https://github.com/jerosoler/Drawflow/issues/423#issuecomment-1131533142

**Comment by MikeNo007** [comment]
> Not example added???
> 
> View for groups elements:
> 
> * [How to group nodes #423 (comment)](https://github.com/jerosoler/Drawflow/issues/423#issuecomment-1131533142)

**Comment by MikeNo007** [comment]
Thank you for your help. It's very useful for me!
