### ISSUE TITLE
DOMException: Failed to execute 'querySelectorAll' on 'Element': '[df-excelData-0-Full Name]'

### ISSUE THREAD

**Issue by Chaymae-Elmoueden** [jerosoler/Drawflow#706]
I receive this error and I'm not sure what the exact solution is. I have tried doing const updatedColumnName: string = columnName.replace(/\s/g, "_"); but the issue persists. Thank you in advance for your assistance. 
![issu1](https://github.com/jerosoler/Drawflow/assets/113434646/1f289ed8-f7a5-4d47-9c58-80b3e4e848a8)
![issu2](https://github.com/jerosoler/Drawflow/assets/113434646/75510730-c72e-46ef-9759-8ed695982845)

**Comment by jerosoler** [comment]
Try without spaces and without capital letters.

**Comment by Chaymae-Elmoueden** [comment]
thank you it works without capital letters
