### ISSUE TITLE
Node connectors issue

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#708]
Hi Jerosoler,
Facing issue for node connectors  while updating it shows the saved connections but not connectors if I move the node then only it shows their connectors so I need to every node again.
I am importing the data like this.editor.import(forValues);
Kindly suggest me solution

With connectors
![image](https://github.com/jerosoler/Drawflow/assets/118881887/6167f678-7e68-49fa-be00-4bd139b6a2ab)

Without connectors
![image](https://github.com/jerosoler/Drawflow/assets/118881887/1f612fdc-9942-41cd-8d0a-3f3887ce80a3)

**Comment by jerosoler** [comment]
Duplicate:
View: 
- https://github.com/jerosoler/Drawflow/issues/2
- https://github.com/jerosoler/Drawflow/issues/270
- https://github.com/jerosoler/Drawflow/issues/371
- https://github.com/jerosoler/Drawflow/issues/267
- https://github.com/jerosoler/Drawflow/issues/349
....

**Comment by roniemartinez** [comment]
FYI: Not related to import but I guess it's the same issue.

I have been creating nodes and connections using `editor.addNode()` and `editor.addConnection()`.
- On first load, the connections are visible (sometime it is not).
- Succeeding loads/refresh, the connections are hidden.
- If the connections are not visible, moving the nodes will render them.

The only solution I found is using a `setTimeout(function() {}, 200)` taken from https://github.com/jerosoler/Drawflow/issues/371#issuecomment-1061686102
