### ISSUE TITLE
How add a bottom bar with id to box ?

### ISSUE THREAD

**Issue by Ludov1234** [jerosoler/Drawflow#709]
![image](https://github.com/jerosoler/Drawflow/assets/123162852/1b040971-89b4-4dbc-a155-16aad6d0be24)

**Comment by jerosoler** [comment]
Hello,

You can get the ID in two ways:
```javascript
const idNode = addNode(...)
```
Or by the DOM.  
The node always embeds the ID of the node.
```html
<div id="node-1" class="drawflow-node welcome selected" style="top: 50px; left: 50px;"><div class="inputs"></div><div class="drawflow_content_node" >
```

You could also override the addNode and addNodeImport functions to include the id.

**Comment by Ludov1234** [comment]
thanks you
