### ISSUE TITLE
 how to add a footer in the box with information ?

### ISSUE THREAD

**Issue by Ludov1234** [jerosoler/Drawflow#710]
![Capture d'écran 2023-06-07 091819](https://github.com/jerosoler/Drawflow/assets/123162852/73c38d03-91b1-4fe9-baa4-a4563f867132)

**Comment by Ludov1234** [comment]
I don't know if the first answer suits me. I just wanted to integrate a footer into the box. Should I do the same?

**Comment by jerosoler** [comment]
In  `addNode` in html field add your html bottom. 

For example in demo: https://jerosoler.github.io/Drawflow/

You can see nodes with header and without header.

Everything is added in the html field.
![image](https://github.com/jerosoler/Drawflow/assets/30957047/44fcb1c8-10d1-4321-9e42-4d5490a66ad6)
