### ISSUE TITLE
Node connection wire issue

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#711]
Hi ,

While updating the connection am getting the saved data on UI but node connection wire or connectors are not visible initially.
If we move any node then only get the connection wire related to that node help me to get out of this issue.

Without moving node
![image](https://github.com/jerosoler/Drawflow/assets/118881887/b5954fd3-e471-47f5-a4cd-63ec61f95092)

After moving the node
![image](https://github.com/jerosoler/Drawflow/assets/118881887/16214956-c6e9-435d-96fe-9cf6f970fb27)

Thanks in advance.

**Comment by jerosoler** [comment]
Duplicate: 
- https://github.com/jerosoler/Drawflow/issues/708
