### ISSUE TITLE
how to fix the problem of the position when i type in searchbar for a view on the search

### ISSUE THREAD

**Issue by Ludov1234** [jerosoler/Drawflow#718]
editor.translate_to = function(x, y) {
  var pos_x = x * (this.precanvas.clientWidth / (this.precanvas.clientWidth * this.zoom)) - (this.precanvas.getBoundingClientRect().x * (this.precanvas.clientWidth / (this.precanvas.clientWidth * this.zoom)));
  var pos_y = y * (this.precanvas.clientHeight / (this.precanvas.clientHeight * this.zoom)) - (this.precanvas.getBoundingClientRect().y * (this.precanvas.clientHeight / (this.precanvas.clientHeight * this.zoom)));

  this.canvas_x = pos_x;
  this.canvas_y = pos_y;
  let storedZoom = this.zoom;
  this.zoom = 1;
  this.precanvas.style.transform = "translate(" + pos_x + "px, " + pos_y + "px) scale(" + this.zoom + ")";
  this.zoom = storedZoom;
  this.zoom_last_value = 1;
  this.zoom_refresh();
}

var infonode = '';

$("#search").on('keyup', function(e) {
  e.preventDefault();
  var value = $(this).val().toLowerCase();
  $(".drawflow-node").filter(function() {
    var isFind = $(this).text().toLowerCase().indexOf(value) > -1;
    if (isFind) {
      $(this).addClass("isFind");
      var idnode = $(this).attr('id').replace('node-', '');
      infonode = editor.getNodeFromId(idnode);
    } else {
      $(this).removeClass("isFind");
    }
    if (value == '') {
      infonode = '';
      $(this).removeClass("isFind");
    }
  });

  if (infonode != '') {
    console.log('infonode -----');
    console.log(infonode.pos_x + ' / ' + infonode.pos_y);
    editor.translate_to(infonode.pos_x, infonode.pos_y);
  }
});

**Comment by Ludov1234** [comment]
a problem because the position is not the good when i write in search bar

**Comment by jerosoler** [comment]
Can you detail your problem more?

What is that search? Where is?
You are moving the canvas. Where do you want to move it exactly?

Can you provide an example?

**Comment by Ludov1234** [comment]
![image](https://github.com/jerosoler/Drawflow/assets/123162852/60fd522f-86d5-4e8b-8479-6471fa176d00)
The search bar in yellow find and fix the camera on the box but when i write
![image](https://github.com/jerosoler/Drawflow/assets/123162852/cbf631bd-ce62-406a-80ba-57bdf8680fbb)
the box in border red is not finds in the good positions

**Comment by jerosoler** [comment]
Have you tried the function here: 
- https://github.com/jerosoler/Drawflow/issues/88

I see that it is similar but different

**Comment by Ludov1234** [comment]
for the contested menu
![image](https://github.com/jerosoler/Drawflow/assets/123162852/aead6663-e4fa-4966-920d-2247f4c414e3)


1: I retrieve the x and y positions of the box

2: there is a column on the left

3: so what is the formula with trick 88 to arrive at the result of the capture

**Comment by jerosoler** [comment]
Tested on the demo:

```javascript
editor.translate_to = function(x,y){
	this.canvas_x = x;
	this.canvas_y = y;
	let storedZoom = this.zoom;
	this.zoom = 1;
	this.precanvas.style.transform = "translate("+this.canvas_x+"px, "+this.canvas_y+"px) scale("+this.zoom+")";
	this.zoom = storedZoom;
	this.zoom_last_value = 1;
	this.zoom_refresh();
}

const nodeInfo = editor.getNodeFromId(5);

editor.translate_to(-1*nodeInfo.pos_x,-1*nodeInfo.pos_y);
```

Works with zoom is 1.

![image](https://github.com/jerosoler/Drawflow/assets/30957047/0672b99c-8a60-42f8-9aec-09f1ed5dfb52)
