### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by muratcim** [jerosoler/Drawflow#72]
After selecting more than one node, I want to copy and paste it into a different module.I need a roadmap on how to do it

**Comment by jerosoler** [comment]
Hi @muratcim 

Are multiple nodes selected at the same time? How?

Who wants to copy only the node or the node and the connections?

**Comment by aalmeida314** [comment]
Hi, I would like to know if is posible to copy one or more nodes (without connections) and paste in the same board.

**Comment by jerosoler** [comment]
@aalmeida314  use method: `editor.getNodeFromId(id)` and remove connections and create a new node.

**Comment by mushzak** [comment]
is there any update about copy and paste? can I select or for example right-click on node and select copy and the same node will be added to the editor?

**Comment by rndffc** [comment]
any updates? @jerosoler
