### ISSUE TITLE
Connection Orientations

### ISSUE THREAD

**Issue by rogereyes86** [jerosoler/Drawflow#725]
I see that the connections between nodes are made from Left to Right or vise versa, how can I make these connections example from Top to bottom Etc?

Example:

In the below image, the left side is our plugin, and on the right is another plugin from another author but far from the power of ours:

![image](https://github.com/jerosoler/Drawflow/assets/39953923/e9b2c8f7-5954-4c52-a23f-92fd1adff0a0)

**Comment by rogereyes86** [comment]
I manipulated the Top, Left position in the Css and Set the Position as Absolute and kind of does the trick:

.drawflow .drawflow-node .input {
  position: absolute;
  top: -20px;
  left: 45%;
  transform: translate(0, 45%);
}
.drawflow .drawflow-node .output {
  position: absolute;
  top: 82%;
  right: 52%;
  transform: translate(82%, 52%);
}

![image](https://github.com/jerosoler/Drawflow/assets/39953923/ff8ae811-7a7b-4ff0-aae1-9edf6f9fefbc)


But still have issues with the connection line always trying to go right:

![image](https://github.com/jerosoler/Drawflow/assets/39953923/4e37e9eb-548a-4a39-8294-9813e2ab1967)

**Comment by jerosoler** [comment]
View 
- #20
