### ISSUE TITLE
How Do I Assign Values to HTML Content (this.editor.addNode)    <select>            <option value="aZ">aZ</option>             <option value="bZ">bZ</option>  </select> Customized select

### ISSUE THREAD

**Issue by MikeNo007** [jerosoler/Drawflow#727]
How Do I Assign Values to HTML Content (this.editor.addNode)

  <select>
           <option value="aZ">aZ</option>
            <option value="bZ">bZ</option>
 </select>
Customized select

**Comment by jerosoler** [comment]
Use df-atrributes.

Example:
- https://github.com/jerosoler/Drawflow/issues/421#issuecomment-1126882170
