### ISSUE TITLE
Re-render after Import

### ISSUE THREAD

**Issue by rogereyes86** [jerosoler/Drawflow#729]
Hi, following other questions I was able to implement 2 changes that are working fine:

1- Adjust the connection to be used horizontally.
2- Add and remove a class to the input dot when a connection is successfully made.

So far so good, the problem is when I save the JSON code and then imported it, the following issues occur:

1- The curvature line is a little off the Dots:

![image](https://github.com/jerosoler/Drawflow/assets/39953923/cd2c6d2e-c410-46c2-9637-ac1aaa54656c)

Moving the Node it fixes it:

![image](https://github.com/jerosoler/Drawflow/assets/39953923/7722bcb5-34b6-45cd-8f88-c3f856d22f44)

Is there any way to re-render all curvatures after editor.import(dataToImport)?

Maybe calling this function but not sure how to call it from the edit.drawflow:

![image](https://github.com/jerosoler/Drawflow/assets/39953923/2c125de7-6cc8-4c5d-91b1-3ca8998dba53)

2- When importing, the class I applied to the input dots is rolled back, any idea how can I reapply this class to each input dot that has a valid connection?:

Before the Import:

![image](https://github.com/jerosoler/Drawflow/assets/39953923/12c62ce0-86b7-42d5-86a6-85b1d2e15b46)

After the Import (rolled back to his default class):

![image](https://github.com/jerosoler/Drawflow/assets/39953923/dfc22534-610b-44c7-89cf-bcfb84f70ea5)

**Comment by jerosoler** [comment]
1. Try this comment: https://github.com/jerosoler/Drawflow/issues/371#issuecomment-1061686102 
2. You have to add the class again. You can parse the json file you import to add them back.

**Comment by rogereyes86** [comment]
-1 Worked using that comment.
- Will try to loop all available inputs and check who has a connection.

Thanks for your help. Amazing~!

**Comment by rogereyes86** [comment]
-2 Working like a charm after Import:

setTimeout(function(){ 
	
editor.import(dataToImport);

for (var i = 1, b = Object.keys(dataToImport["drawflow"]["Home"]["data"]).length; i <= b; i++) 
{
	for (var x = 1, c = Object.keys(dataToImport["drawflow"]["Home"]["data"][i]["inputs"]).length; x <= c; x++) 
	{	
		if ( Object.keys(dataToImport["drawflow"]["Home"]["data"][i]["inputs"]["input_"+x]["connections"]).length > 0 )
			{		
				document.querySelector('#node-'+i+' .input_'+x).classList.add("filled");		
			}	
	}
}

}, 1000);


![image](https://github.com/jerosoler/Drawflow/assets/39953923/c6b6aa3e-7953-40be-85a3-c53b771b7ff1)
