### ISSUE TITLE
How to find if user is moving the selected node around

### ISSUE THREAD

**Issue by capoia** [jerosoler/Drawflow#737]
Hello, first thanks for the package, it has helped me a lot!

I wanted to know if there is a way to identify when a node is being moved, because I would like that when clicking on the node a config menu opens, but if the user clicks and then starts moving I would like this menu not to be opened.

**Comment by jerosoler** [comment]
Hi @capoia 

With event `mousemove`

View example:  
```javascript
    editor.on("mouseMove", ({x,y}) => {
        if(editor.node_selected && editor.drag) {
          console.log("Movenode");
        }
    });
```

**Comment by capoia** [comment]
Thanks!
