### ISSUE TITLE
how can update node inner label or name 

### ISSUE THREAD

**Issue by linpan** [jerosoler/Drawflow#74]
each node have unique tag name , so allow user can modified tag name by one. 

![image](https://user-images.githubusercontent.com/6077601/100085571-2881f400-2e87-11eb-94f0-b291f1de57fa.png)

**Comment by jerosoler** [comment]
Hello @linpan 

You can use the attribute `df-*` in **inputs, textarea or select** to synchronize with the node data.

Atrributs multiples parents support `df-*-*...`

### Node example
```javascript
var html = `
<div><input type="text" df-name></div>
`;
var data = { "name": '' };

editor.addNode('github', 0, 1, 150, 300, 'github', data, html);
```
