### ISSUE TITLE
How to disable the creation of connections by dragging?

### ISSUE THREAD

**Issue by matheusfnl** [jerosoler/Drawflow#740]
I want to disable this feature, i tried `editor.editor_mode = 'fixed'`, but this disables the node drag-and-drop

![disablepls](https://github.com/jerosoler/Drawflow/assets/96300475/368a02c0-328c-436a-8c0e-f2c90e36f28c)

**Comment by jerosoler** [comment]
Hi,

Disable drawconnection function:
```javascript
editor.drawConnection = function() {
  return false;
}

```

**Comment by jerosoler** [comment]
More simple and not errors in console javascript:
 ```javascript
editor.on("mouseMove", ({x,y}) => {
  editor.connection = false;
});
```
