### ISSUE TITLE
Is there a way to link nodes with connection directly by selecting options in dropdown menu & the options are the nodes defined in the chatflow?

### ISSUE THREAD

**Issue by VK-Devloper** [jerosoler/Drawflow#76]

**Comment by VK-Devloper** [comment]
connect message node by selecting message option. If you know how to implement please give refrence.
![MENU](https://user-images.githubusercontent.com/63523860/100314247-372def80-2fdc-11eb-88c9-dfbac5ad7f62.png)

**Comment by jerosoler** [comment]
Hello @VK-Devloper 

Yes!! use method `addConnection`.

Mehtod | Description
--- | ---
`addNodeOutput(id)` | Add output to node. Ex id: `5`
`addConnection(id_output, id_input, output_class, input_class)` | Add connection. Ex: `15,16,'output_1','input_1'`

From what I see in the image, perhaps the `addNodeOutput` method is also interesting.

**Comment by VK-Devloper** [comment]
Thanks @jerosoler 
Is there a way to add message node on dashboard if it doesn't exists after selecting message option?

**Comment by jerosoler** [comment]
If you just add a node.

What would have to export the content and go through the object in search of if the message node is there

More or less so:
```javascript
var exportdata = editor.export();
/*** Search in exportada ***/
if(exist === false)  {
editor.addNode(...)
}

```

**Comment by VK-Devloper** [comment]
@jerosoler  Thank you so much. I got that
