### ISSUE TITLE
Is there any way to disable node movement when you are inside an input or text area, to edit and select the content?

### ISSUE THREAD

**Issue by 0x66616C6C656E** [jerosoler/Drawflow#760]
![20230830-0249-47 6855016-_1_](https://github.com/jerosoler/Drawflow/assets/136522570/51787a62-a3c3-4c92-81e3-70fbb976b7b2)

Hey! Is there any way to disable node movement when you are in an input or text area to select content, when you try to select, the node moves.

Thanks in advance!

**Comment by jerosoler** [comment]
Try:

```javascript
editor.draggable_inputs = false;
```
