### ISSUE TITLE
I'm able to move flow only from black box

### ISSUE THREAD

**Issue by mushzak** [jerosoler/Drawflow#764]
<img width="1404" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/82f393cc-9219-4656-a490-840e304eed97">

When I hold click into box I'm able to move flow, but out of that I'm not able moving doesn't work

**Comment by jerosoler** [comment]
Have you added a css class in the parent element of drawflow or style?

View other possible problems:

- https://github.com/jerosoler/Drawflow/issues/469
- https://github.com/jerosoler/Drawflow/issues/443

**Comment by mushzak** [comment]
<img width="829" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/a0bc2c9e-c3b1-4036-bb8a-87e3b23c08ed">

**Comment by mushzak** [comment]
how I can share video with you? all videos are more then 10 mb, I'm not able to share here

**Comment by mushzak** [comment]
https://streamable.com/afjuyq

please check it here

**Comment by mushzak** [comment]
[https://streamable.com/afjuyq?src=player-page-share(url)

**Comment by jerosoler** [comment]
Try adding css: 
```
<style>
    #drawflow { 
      position: relative;
      text-align:initial;
....
}
```

If it doesn't work try removing your CSS. It may be causing some problem. If sun css works, check if the parent container is modified.

For example problem with boostrap:
- https://github.com/jerosoler/Drawflow/issues/194

**Comment by mushzak** [comment]
also translate event doesn't work out of that area
 
<img width="634" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/b2dc7633-db84-4726-b76c-5a87f77f8d29">

**Comment by mushzak** [comment]
<img width="1707" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/a344dbef-7c06-4f34-abd4-e0a98ad4666e">
Also as you can see it is working only for div.class.drawflow

**Comment by jerosoler** [comment]
Your drawflow div contain a class:
![image](https://github.com/jerosoler/Drawflow/assets/30957047/daf686c6-572d-40c3-9014-f77c41bb7964)
Review:
 - https://github.com/jerosoler/Drawflow/issues/469

Your class ng-*** in second position.

**Comment by mushzak** [comment]
is it fixed? because when using in Angular that classes adding automatically

**Comment by jerosoler** [comment]
Try changing the div to: 
```html
<div id="drawflow" class="parent-drawflow">
```

This solution is in last comments.

**Comment by mushzak** [comment]
Thank you very much for your fast answers, this solution is fixed my problem, and thank you very much for this library

**Comment by mushzak** [comment]
the last issue that I have in my flow it is related to having big flows, and I'm not able to center them
