### ISSUE TITLE
Accessing properties globally in Vue.js with prototypes ?

### ISSUE THREAD

**Issue by linpan** [jerosoler/Drawflow#77]
for example:
 Vue.prototype.$df = 'drawflow '

**Comment by jerosoler** [comment]
Basic example with vue cli.


Example: 
App.vue
```vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <Drawflow />
  </div>
</template>

<script>
/*import HelloWorld from './components/HelloWorld.vue'*/
import Drawflow from './components/Drawflow.vue'

export default {
  name: 'App',
  components: {
    Drawflow
  },
  mounted() {
    this.$df.addNode('github', 0, 1, 250, 400, 'github', {}, 'text2');
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

Component Drawflow
components/Drawflow.vue
```vue
<template>
  <div id="drawflow">
  </div>
</template>
<script>
import Drawflow from 'drawflow'
// eslint-disable-next-line
import styleDrawflow from 'drawflow/dist/drawflow.min.css'
import Vue from 'vue'



export default {
  name: 'Drawflow',
  mounted() {
    var id = document.getElementById("drawflow");
    Vue.prototype.$df = new Drawflow(id, Vue);
    this.$df.start();
    this.$df.addNode('github', 0, 1, 150, 300, 'github', {}, 'text');
  }
}
</script>

<style scoped>
 #drawflow {
   width: 800px;
   height: 800px;
   border: 1px solid red;
   display: block;
 }

</style>

```

**Comment by linpan** [comment]
thks



At 2020-11-26 16:30:46, "Jero Soler" <notifications@github.com> wrote:

Basic example with vue cli.

Example:
App.vue

<template>
  <divid="app">
    <imgalt="Vue logo"src="./assets/logo.png">
    <Drawflow />
  </div>
</template>

<script>/*import HelloWorld from './components/HelloWorld.vue'*/importDrawflowfrom'./components/Drawflow.vue'exportdefault {  name:'App',  components: {    Drawflow  },mounted() {this.$df.addNode('github', 0, 1, 250, 400, 'github', {}, 'text2');  }}</script><style>#app {font-family: Avenir, Helvetica, Arial, sans-serif;-webkit-font-smoothing: antialiased;-moz-osx-font-smoothing: grayscale;text-align: center;color: #2c3e50;margin-top: 60px;}</style>

Component Drawflow
components/Drawflow.vue

<template>
  <divid="drawflow">
  </div>
</template>
<script>importDrawflowfrom'drawflow'// eslint-disable-next-lineimportstyleDrawflowfrom'drawflow/dist/drawflow.min.css'importVuefrom'vue'exportdefault {  name:'Drawflow',mounted() {var id =document.getElementById("drawflow");Vue.prototype.$df=newDrawflow(id, Vue);this.$df.start();this.$df.addNode('github', 0, 1, 150, 300, 'github', {}, 'text');  }}</script><stylescoped>#drawflow {width: 800px;height: 800px;border: 1pxsolidred;display: block; }</style>
