### ISSUE TITLE
Remove the input of the first node

### ISSUE THREAD

**Issue by JCPreethi** [jerosoler/Drawflow#771]
Hey jerosoler,

I want to remove the the input icon of the very first node when its dropped from the sidebar.
    this.drawflow.start();
    this.drawflow.force_first_input = true;

This is what i have tried but it must've missed something since its not working.
How do i achieve this?

**Comment by jerosoler** [comment]
Hello,

The force_first_input variable is to be able to create the connection by leaving the mouse over the node i, not the input.

If you want the first node to not have an "input".

When creating the node, pass the input parameter to 0.
```
editor.addNode(name, inputs, outputs, posx, posy, class, data, html);
```

**Comment by JCPreethi** [comment]
Thanks @jerosoler
