### ISSUE TITLE
createCurvature calculation options based on node input/output

### ISSUE THREAD

**Issue by DannyV14** [jerosoler/Drawflow#773]
I have read through this issue multiple times:
https://github.com/jerosoler/Drawflow/issues/20
I have implemented a switch case very similar to code found in that issue.

I have three different options of curvature.
1. No center calculation
2. Center_X calculation 
3. Center_Y calculation

**The problem I am facing is** that the optimal route of the curve depends heavily on the input/output port being used.
As I have four ports that are input/output ambiguous (stacked on top of each with x-index changing).
Sometimes the horizontal port connecting to a top port should have no curve as the best line.
Or a port across from another would be best with a center_x approach.

I have attached a very poorly drawn guide trying to demonstrate the issue.
Where the curve line runs along the side of the node.
<img width="417" alt="DrawflowConnecitonNodeLogic" src="https://github.com/jerosoler/Drawflow/assets/26718654/59fd3750-ed29-4364-a506-8734ea2688bb">

All of this to say, what do you think the best approach is here?
I have looked into connection start/connection end/node moved events to try to determine the ports in use.
But the createCurvature function only uses (start_x, start_y, end_x, end_y) so there are null reference possibilities by using variables existing outside of the curve function.

**It is possible this is an unsolvable request.** But just wanted to reach out for any potential advice!

Thanks!

**Comment by DannyV14** [comment]
Looks like that should work! I’ll give it a try.
As always thank you so much for the quick response!

**Comment by DannyV14** [comment]
The changes in this PR, can I override the drawflow default functions with these changes in my implementation?

**Comment by jerosoler** [comment]
My recommendation is that you directly copy the file https://github.com/jerosoler/Drawflow/blob/master/src/drawflow.js 

And add changes manualy. 

You can add it to your project like this:
https://github.com/jerosoler/Drawflow/issues/526#issuecomment-1250828930
