### ISSUE TITLE
Single output connected with 2 input.

### ISSUE THREAD

**Issue by Co-Maheshh** [jerosoler/Drawflow#777]
@jerosoler  i have to create node which has 1 output but that output has 2 inputs .

**Comment by jerosoler** [comment]
By default library connect one output to multiple inputs.  


View demo: 
https://jerosoler.github.io/Drawflow/

![image](https://github.com/jerosoler/Drawflow/assets/30957047/91d545af-4acb-4af0-b6a0-4a3d18be4e1b)

**Comment by Co-Maheshh** [comment]
@jerosoler , can we restrict like only AWS name  input node can be connected to multiple nodes.
