### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Home') while importing

### ISSUE THREAD

**Issue by JCPreethi** [jerosoler/Drawflow#782]
Hello @jerosoler 

I'm trying to import the json that i have exported to sql server database, but i keep getting the - TypeError: Cannot read properties of undefined (reading 'Home') while importing error.

This is the data i'm sending on button click to the database

const dataExport = this.editor.export();  
dataExport = JSON.stringify(dataExport);

and this is how i am trying to import it in vue 2 using watch

const container = this.$refs.drawflowContainer;
  this.editor = new Drawflow(container);
  this.editor.start();
  try {
    this.editor.import(JSON.parse(JSON.stringify(this.activedetails['flow']['header']['htmlData'])));
  }
  catch (err) {
    console.log('Invalid Data',err)
  }   
  
  P.S  - tried to import just with JSON.parse() but it threw the below error
  
Invalid Data SyntaxError: Bad control character in string literal in JSON at position 813 (line 1 column 81).

What am i doing wrong here?

**Comment by jerosoler** [comment]
Compare "dataExport" with you "this.activedetails['flow']['header']['htmlData']" 

Or `console.log(this.activedetails['flow']['header']['htmlData'])`

The "Home" module is required. You cannot modify the name of the first module.

Solution is your first module is not "Home":
- https://github.com/jerosoler/Drawflow/issues/222

**Comment by JCPreethi** [comment]
It does have a Home module

**Comment by JCPreethi** [comment]
I am using vue2 and the html template template has no issues. 
when i try to import it manually like below:

const container = this.$refs.drawflowContainer;
          this.editor = new Drawflow(container);
          const toImport = {
            "drawflow": {
              "Home": {
                "data": {
                  "1": {
                    "id": 1,
                    "name": "OriginalRepo",
                    "data": {},
                    "class": "personalized",
                    "html": "<div>Content</div>",
                    "typenode": false,
                    "inputs": {},
                    "outputs": {
                      "output_1": {
                        "connections": []
                      }
                    },
                    "pos_x": 259,
                    "pos_y": 174
                  }
                }
              }
            }
          }
          this.editor.start();

          this.editor.import(toImport); 

this works, the issue arises only when im trying to import the data received from a get request.

For reference, i'm creating a new drawflow on mount and im trying to import it on a button click which triggers the watch variable
```
mounted(){
        const container = this.$refs.drawflowContainer;
        if (container) {
          this.editor = new Drawflow(container);
          var elements = document.getElementsByClassName('drag-drawflow');
            for (var i = 0; i < elements.length; i++) {
              elements[i].addEventListener('touchend', this.drop, false);
              elements[i].addEventListener('touchmove', this.positionMobile, false);
              elements[i].addEventListener('touchstart', this.drag, false );
            }
           }
}
```
watch:{
      async activeWf(){
        if(this.activeWf!= '-1'){
          const data = await this.$http.$get('workflow/' + this.activeWf);
          this.activeDetails = data;      
          const container = this.$refs.drawflowContainer;
          this.editor = new Drawflow(container);
          const toImport = {
            "drawflow": {
              "Home": {
                "data": {
                  "1": {
                    "id": 1,
                    "name": "OriginalRepo",
                    "data": {},
                    "class": "personalized",
                    "html": "<div>Content</div>",
                    "typenode": false,
                    "inputs": {},
                    "outputs": {
                      "output_1": {
                        "connections": []
                      }
                    },
                    "pos_x": 259,
                    "pos_y": 174
                  }
                }
              }
            }
          }
          this.editor.start()
          this.editor.import(toImport); 
        }
      }
    },

**Comment by jerosoler** [comment]
In the "Watch" you don't have to do the "this.editor = new Drawflow(container);"

Try this:

```javascript
watch:{
      async activeWf(){
        if(this.activeWf!= '-1'){
          const data = await this.$http.$get('workflow/' + this.activeWf);
          this.activeDetails = data;      
          //const container = this.$refs.drawflowContainer;
          //this.editor = new Drawflow(container);
          const toImport = {
            "drawflow": {
              "Home": {
                "data": {
                  "1": {
                    "id": 1,
                    "name": "OriginalRepo",
                    "data": {},
                    "class": "personalized",
                    "html": "<div>Content</div>",
                    "typenode": false,
                    "inputs": {},
                    "outputs": {
                      "output_1": {
                        "connections": []
                      }
                    },
                    "pos_x": 259,
                    "pos_y": 174
                  }
                }
              }
            }
          }
          //this.editor.start()
          this.editor.import(toImport); 
        }
      }
    },
```

**Comment by jerosoler** [comment]
Can you provide a codepen or somewhere to test your code?

When you do a 'const data = editor.export();' Try also doing an 'editor.import(data)';

Does it show an error?

**Comment by JCPreethi** [comment]
No error when i do - When you do a 'const data = editor.export();' Try also doing an 'editor.import(data)';
The error only occurs when import using the data saved in database.

I'm setting up my code online, will post it here once done

**Comment by JCPreethi** [comment]
Hello @jerosoler, i found the issue, its because the object i saved in the sql server is in the front "{"drawflow":"Home":{}}". It is working with this - '{"drawflow":"Home":{}}' format.
