### ISSUE TITLE
Connection breaking when node moved.

### ISSUE THREAD

**Issue by Mohammed-Rasik** [jerosoler/Drawflow#787]
Hi there,

Thank you so much for this library.

I am using Drawflow with my Angular project. Node creation and creating connections are working as we expected.  

<img width="518" alt="image" src="https://github.com/jerosoler/Drawflow/assets/70363130/ac40c8c1-d80f-4d0b-8e9e-fdf9197451d7">

After connection creation when I tried to move any node which is connected with any other node, the connection getting broken. This break is facing before the `onMoved ` event triggering.

<img width="517" alt="image" src="https://github.com/jerosoler/Drawflow/assets/70363130/51a31d4e-9874-49a9-8319-b7dfe968938f">

Could you please help me with any solution..?

**Comment by jerosoler** [comment]
In the image output not found on node source, review output.  What output???

**Comment by Mohammed-Rasik** [comment]
Hi @jerosoler ,

Thanks for the reply. As you mentioned the issue was with input/output . As part of node style customisation, input/output was not visible when a node is selected by using css property of `display: none`. That was the cause of breaking the connection while dragging. I achieved the same by setting `opacity ` property to make input/output not visible.

Thanks for the support.
