### ISSUE TITLE
nodeRemoved triggers before connectionRemoved

### ISSUE THREAD

**Issue by icabbi-joegarlick** [jerosoler/Drawflow#8]
Hey again,

Sorry for another issue!

Inside of removeNodeId(id), this.removeConnectionNodeId is called at the bottom which means that nodeRemoved is triggered before connectionRemoved. This is a problem because if you need data from the node that was deleted inside the connectionRemoved event this is not possible because it is already deleted.

In my instance, I need some data from the data object inside of the node which relates to the connection.

However I cannot see this being an issue for many others. In my development version I have moved the removeConnectionNodeId to the top of removeNodeId just so the connection is always removed first, which makes sense anyways.

You can see what I have done here: https://github.com/icabbi-joegarlick/Drawflow/commit/ad98179506395323e650b39776040021cd703913
In this commit also I have added a param to addNode to allow me to specify the nodeId for my loading system - Not sure this is the best solution for this issue but works for what I need at the moment. If i figure out a better solution i will tell you unless you have any ideas?

Let me know what you think.

Thanks,
Joe

**Comment by jerosoler** [comment]
Hello! 

About removeConnection you are right maybe I should go earlier.

Annotated.

About nodeID.
The node already has an id.

That could generate a problem from duplicate ids.

How do you load the data?

Jero

**Comment by icabbi-joegarlick** [comment]
Hey @jerosoler,

Thanks for the removeConnection reply.

I store the nodes in the database with the same ids as inside of drawflow.
Now lets say I have node ids: 1, 2, 3, 4, 5 and I delete node 3. When I load in the nodes from the database using addNode the node ids become 1, 2, 3, 4 because addNode works in an increment fashion. This means a connection between node 4 and 5 will be broken.

You are correct about the duplicatedIds - maybe to resolve this we could throw an exception if the ID already exists.

Thanks,
Joe

**Comment by jerosoler** [comment]
Have you thought about saving export method in one table?

To know if the node exists, maybe it could be used.
getNodeFromId(id)

Or create a checkNodeExist (id) method

**Comment by icabbi-joegarlick** [comment]
Yes, I have thought about using the export method however it contains a lot of data I do not need like HTML as my nodes follow the same HTML anyways.

**Comment by jerosoler** [comment]
Do you know that you can register nodes for reuse?

Example:
```javascript
var data = { "name": '' };
var html = document.createElement("div");
html.innerHTML= '<div><input type="text" df-name></div>';
editor.registerNode('test', html);
editor.addNode('github', 0, 1, 150, 300, 'github', data, 'test', true);
```

When exporting the html does not appear, only the essential:
```javascript
{
  "drawflow": {
    "Home": {
      "data": {
        "1": {
          "id": 1,
          "name": "github",
          "data": {
            "name": "holaaa111"
          },
          "class": "github",
          "html": "test",
          "typenode": true,
          "inputs": {},
          "outputs": {
            "output_1": {
              "connections": []
            }
          },
          "pos_x": 150,
          "pos_y": 300
        }
      }
    }
  }
}
```

**Comment by icabbi-joegarlick** [comment]
Ah right, That makes sense. The reason im doing it a custom way is just because of how I am storing the routing between modules. 

The best way for me is to be able to specify a nodeid on the addNode and throwing an exception or have a function that allows me to change the node id once created. 

However I understand this is not ideal and can continue using my own function for now.

**Comment by jerosoler** [comment]
Fix remove connections in commit: https://github.com/jerosoler/Drawflow/commit/dc4aff572eefcc6c82f3452ac160ecfe3162c703

**Comment by icabbi-joegarlick** [comment]
Thanks @jerosoler !

Maybe for now we close this and If I figure out a better solution for the whole setting the node id  I will let you know.
