### ISSUE TITLE
Issue with dynamically adding then removing output_1, output_2

### ISSUE THREAD

**Issue by mushzak** [jerosoler/Drawflow#807]
<img width="526" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/20e1edac-b19e-4ed8-a61f-60219b3da7f5">

I have flow like this, and adding outputs dynamically,  when trying to remove last output it is working, but 
for example when I have output_1 output_2 output_3 

when deleting output_2 having an issue offsetWidth, and suggestion how I can do this? 

also need to remove from child node inputs

**Comment by mushzak** [comment]
for example when I remove node output_3 from condition_desc, it works, but when trying to remove   2nd it gives issue,

For adding new output I'm using this: 
<img width="1011" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/9db1f513-1397-4a50-9c7a-c7f145884183">

**Comment by jerosoler** [comment]
In drawflow outputs and inputs as sequential number. 

Example: 
If you have 3 outputs.
And eliminate number 2.
Outputs 1 and 2 will remain available.

You are using the functions: `removeNodeOutput(id, output_class)` and `addNodeOutput(id)`?

**Comment by mushzak** [comment]
<img width="809" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/c63d0fa5-9595-4af4-bdb7-fd34227a2039">
I'm adding node output like this

**Comment by jerosoler** [comment]
Use 
```javascript
editor.addNodeOutput(idOfNode);
```

**Comment by mushzak** [comment]
if I use like this, how I can add lables? 
<img width="602" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/bf7c4f7e-18a6-4a80-8493-021b3b2bd264">

**Comment by mushzak** [comment]
id there any function that I can check output exists or not?

**Comment by jerosoler** [comment]
I don't know how you are adding the labels.

But once the connection is added you can always access the node information or add the label to the created connection.

You can get the node information with the function:
```javascript
const dataNode = editor.getNodeFromId(idOfNode);
```
Here you can see the outputs and inputs of the nodes.

**Comment by mushzak** [comment]
is there any function that I can check if output exists or not?

**Comment by jerosoler** [comment]
There is no function.
But you can use what was shown in the comment above to see if the output exists.

**Comment by mushzak** [comment]
tthis will remove "removeNodeOutput(id, output_class)" from child node inputs?

**Comment by jerosoler** [comment]
Yes

**Comment by mushzak** [comment]
<img width="615" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/55681b7b-10c1-4d3f-a8a0-e4c88eff3567">
having issues like this when using "removeNodeOutput(id, output_class)"

**Comment by mushzak** [comment]
<img width="592" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/a47572d6-dd95-484c-aafb-0804563adadf">

**Comment by mushzak** [comment]
<img width="576" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/aa221597-cd6b-47de-86c8-e1909bd8cced">
My problem is that I can have 3 outputs in the condition node, and then I can remove the second one, or the first one, and in this image, you can see what looks like. I don't have output_2 because I removed it. and after that, I'm having this issue. 
<img width="566" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/732a8c47-483b-4997-86c0-dfdb8d4e9b6e">

**Comment by jerosoler** [comment]
> In drawflow outputs and inputs are sequential number.

There can be no jump in them.

**Comment by mushzak** [comment]
<img width="1303" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/e2f30017-8289-4869-9ec6-228afe517a23">


when I try to "removeNodeOutput(id, output_class)". I'm getting this issue, do you know why?

**Comment by mushzak** [comment]
<img width="792" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/a40da745-f588-425d-acaa-c1ba66cfcd26">

**Comment by mushzak** [comment]
<img width="671" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/62581839-0430-47c9-96b0-32651a7f064a">
<img width="1228" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/57d21eee-c3cb-4d6f-ab3e-a8695cdbdeae">

**Comment by mushzak** [comment]
> <img alt="image" width="671" src="https://private-user-images.githubusercontent.com/14214670/294715737-62581839-0430-47c9-96b0-32651a7f064a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzI0NjMsIm5iZiI6MTcwNDU3MjE2MywicGF0aCI6Ii8xNDIxNDY3MC8yOTQ3MTU3MzctNjI1ODE4MzktMDQzMC00N2M5LTk2YjAtMzI2NTFhN2YwNjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIwMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMzAyODNhYjFlZDdlZTJhMjM2ZGQ1NDkwZTBhZDU3MDcxMWMwMzJkMDNjMGQyODE1YWY0NjA3MTgxNmE3NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MHj2H7QSMXgYoVTpIDNivvaoUN8UhLTlCw7CNHQBZNE"> <img alt="image" width="1228" src="https://private-user-images.githubusercontent.com/14214670/294715748-57d21eee-c3cb-4d6f-ab3e-a8695cdbdeae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzI0NjMsIm5iZiI6MTcwNDU3MjE2MywicGF0aCI6Ii8xNDIxNDY3MC8yOTQ3MTU3NDgtNTdkMjFlZWUtYzNjYi00ZDZmLWFiM2UtYTg2OTVjZGJkZWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIwMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzM5YTg4MDJmNWRlYWE3MGIzZTM4MmQ5MTY2ZGZiOWQ1ZmI3ZTEzZjc0ZDg5YTM0YWFkM2I1N2Q3MDQwYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vrTwsucXgWJy0C0V1XfD4qQ1-UUXsKt4VNA-d8Vhkhs">

@jerosoler I'm using .removeNodeOutput() function wrongly?

**Comment by mushzak** [comment]
as I understand the problem is when node has any outputs + connection  removeNodeOutput() gives error.

<img width="590" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/6d6a025c-95a0-4cf6-82f8-485d84037c18">

**Comment by mushzak** [comment]
When I try to remove first output which has a connection I see this error

<img width="526" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/311bb552-01ca-4e46-a93f-7ea37ff6aba5">



when removing output_2 or output_3 it gives this error

<img width="978" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/f2580941-c13a-4890-b231-4e363675ccbb">


<img width="629" alt="image" src="https://github.com/jerosoler/Drawflow/assets/14214670/2ef545f7-0f51-4341-a81f-70330842c21e">

**Comment by jerosoler** [comment]
Please create a codepen to reproduce this problem.

**Comment by mushzak** [comment]
I'm not able to copy json from my working place, I can send  screenshots

**Comment by mushzak** [comment]
I found the problem, closing the ticket, thanks.
