### ISSUE TITLE
any way to generate array checkboxes?

### ISSUE THREAD

**Issue by samankarbasi** [jerosoler/Drawflow#81]
hi. tnx for your awesome tool.
i have a problem. i want to save block data as an array.
my case is a table selector, then i want to list table fields as an array of checkbox inputs.
in a raw html we can handle this by brackets. ex: name=fields[]

i created a method to generate a list by click on table.
data holds like this: <input type='checkbox' class='block-checkbox' df-fields[" + field + "]>
i can select them, and they will save in data. but problem is that i can not uncheck them.
when i uncheck them, they still on in data saved by node.

i show you by a screen capture.
tnx again.

[2020-11-30_10-35-52.zip](https://github.com/jerosoler/Drawflow/files/5614268/2020-11-30_10-35-52.zip)

**Comment by jerosoler** [comment]
Hello @samankarbasi 

Thanks! 🎉

You can pass the code of the checkbox node.

To test.

Jero

**Comment by samankarbasi** [comment]
> Hello @samankarbasi
> 
> Thanks! 🎉
> 
> You can pass the code of the checkbox node.
> 
> To test.
> 
> Jero

here is the complete clone mix.
[Drawflow-master.zip](https://github.com/jerosoler/Drawflow/files/5615534/Drawflow-master.zip)
tnx.

**Comment by jerosoler** [comment]
Hello @samankarbasi 

Try override function `updateNodeValue`. Add function before `editor.start()`

Change value to false on unchecked. 


```javascript

  editor.drawflow = {
        "drawflow": {
            "Home": {
                "data":
                    {}
            }, "Other": {
                "data": {}
            }
        }
    }

    editor.updateNodeValue = function(event) {
      console.log("yeah");
      if(event.target.type === "checkbox") {
        if(event.target.checked === false) {
          event.target.value = false;
        }
      }
      var attr = event.target.attributes
      for(var i= 0; i < attr.length; i++) {
        if(attr[i].nodeName.startsWith('df-')) {
          this.drawflow.drawflow[this.module].data[event.target.closest(".drawflow_content_node").parentElement.id.slice(5)].data[attr[i].nodeName.slice(3)] = event.target.value;
        }

      }


    }
    editor.start();

```

Example: 
![image](https://user-images.githubusercontent.com/30957047/100606905-67da9580-330a-11eb-903a-c9c65809b810.png)

Other option  is override the data of node using `updateNodeDataFromId`

The checkbox always return the value "on". 

Try and tell us

**Comment by samankarbasi** [comment]
tnx very much.
yea it would work in this way, but when you export, then import it got an error about fields.
i mean there is a need to parse input variables as array.
df-field is very ok in single variable. but it could not cover arrays
name='post' => df-name='post'
name='posts[]' => there is no way to handle this by drawflow.

`function blockCheckboxChanged(e, nodeId) {
        let node = editor.getNodeFromId(nodeId)
        let fieldValue = e.target.value;
        let selectedFields = node.data.fields;
        if (e.target.checked) {
            //checkbox is checked and must be in DATA
            if (!selectedFields.includes(fieldValue)) {
                selectedFields.push(fieldValue)
            }
        }
        else {
            //checkbox is unchecked and must not be in DATA
            if (selectedFields.includes(fieldValue)) {
                let indexToDelete = selectedFields.indexOf(fieldValue);
                selectedFields.splice(indexToDelete, 1)
            }
        }

        //update fields
        editor.drawflow.drawflow['Home'].data[nodeId].data.fields = selectedFields;
    }`

i created this method when ever any generated checkbox checked. and directly update node data from root.
`updateNodeDataFromId` not working. actually there is not such method named this, or i cant find.
tnx very much for answering.

**Comment by jerosoler** [comment]
`updateNodeDataFromId` is added in 0.0.31. (Yesterday). Try download new version.

**Comment by jerosoler** [comment]
Are you solved? 
It's possible close?
