### ISSUE TITLE
[Question] What is the proper way to make sure the editor canvas will translate on all directions with no limit?

### ISSUE THREAD

**Issue by ElvisAns** [jerosoler/Drawflow#833]
I have everything working except the case when i want to drag the editor in unused zone, it translate to a certain distance then it stop, i feel like there is a maximum width while i did not set one....

https://github.com/jerosoler/Drawflow/assets/35831811/2f3cc08f-3db8-42e9-b41e-7f8c7bf17a90

**Comment by jerosoler** [comment]
That shouldn't be like that.
Look at the demo. This does not happen.
Make sure the drawflow container does not have any CSS classes.
It could be because of that:
- https://github.com/jerosoler/Drawflow/issues/469
-

**Comment by ElvisAns** [comment]
Nice, it worked when i set the first class to be `parent-drawflow`
