### ISSUE TITLE
addConnection method do not edit connection data.

### ISSUE THREAD

**Issue by darioillusorium** [jerosoler/Drawflow#836]
Hi! I'm not sure if it is a known issue or i'm doing something wrong.

When I use de _addConnection_ method, connection event "connectionCreated" occurs, I can catch the event and the connection data is correct but the **drawflow node connection data is not updated**. The connection is not added to the graph. However, if I connect it via interface (drag and drop output to input), all is correct: connectionCreated event occurs and node connection data is updated.

I use `editor.value.addConnection(out_id, in_id, 'output_1', 'input_1')` and seems to be correct, event occurs. But node connection data is not updated.

Thanks!

Darío :)

**Comment by jerosoler** [comment]
It seems that the function is correct.
Maybe the values no out_id and in_id are not correct.

Try forcing node connections to refresh:
```javascript
editor.updateConnectionNodes('node-5');
```

Remember that the use of the function is like this and the nodes must be created.
```javascript
editor.addConnection(1, 2, 'output_1', 'input_1');
```

**Comment by darioillusorium** [comment]
Thanks for the quick response, it seems that everything is correct and I also tried to force it. But I don't get it. I'll keep researching to see if I find anything I might be doing wrong. If I find the reason I'll show you. Thank you so much.

**Comment by darioillusorium** [comment]
Sorry for the confusion, there was a procedure that was deleting my connections.

Thanks
