### ISSUE TITLE
vue3 - this.render is not a function.

### ISSUE THREAD

**Issue by jdchmiel** [jerosoler/Drawflow#86]
This article describes the scenario quite well:
https://medium.com/js-dojo/vue-3-new-features-breaking-changes-a-migration-path-e075a9b3d3d5

I think the issue is that calling render on the vue object is only good for vue2. I am just beginning to explore this, and am curious if anyone else has already worked around it, or if a fix is already in the queue?

**Comment by jerosoler** [comment]
Hello @jdchmiel 

I'll take a look at it.

Jero

**Comment by jerosoler** [comment]
Hello @jdchmiel 

Try new version 0.0.32

Only change import to:
```javascript 
import * as Vue from 'vue'
```

Test please! ;)

**Comment by jdchmiel** [comment]
Hello @jerosoler - NPM does not seem to have 0.0.32 yet so I copied the raw file down, disabled eslint for the file, and verified it works with Vue3 set up with Typescript.  I will get things back 'correct' once NPM catches up. Thanks so much!

**Comment by jerosoler** [comment]
Hello 🎉

Close the issue! 

Try download:
```
npm install drawflow@0.0.32
```

In the page the last version is 0.0.32 ;)
