### ISSUE TITLE
newest npm package

### ISSUE THREAD

**Issue by viniciusverasdossantos** [jerosoler/Drawflow#862]
Where can I get the newest npm package?

**Comment by jerosoler** [comment]
Try:
`npm install drawflow@latest`

**Comment by viniciusverasdossantos** [comment]
> Try: `npm install drawflow@latest`


Sorry, I just found it strange because npm install drawflow@latest is installing version 0.0.59 and here it says it is from 2022. Is this date correct?

**Comment by jerosoler** [comment]
Yes it's correct.

**Comment by viniciusverasdossantos** [comment]
Sorry, but changes from 2022 to today is there any reason why new npm packages are not being generated?

**Comment by jerosoler** [comment]
No changes
