### ISSUE TITLE
Programmatically translating to coordinates

### ISSUE THREAD

**Issue by dsoiM** [jerosoler/Drawflow#88]
I wanted to programmatically go to certain coordinates on the canvas. Here is the code I used in case anyone needs it. The trickery to keep it simple is to reset zoom to 1 for the duration of canvas transform.

Also I will probably try to animate the transition in the future

```
editor.translate_to = function(x,y){
	this.canvas_x = x;
	this.canvas_y = y;
	let storedZoom = this.zoom;
	this.zoom = 1;
	this.precanvas.style.transform = "translate("+this.canvas_x+"px, "+this.canvas_y+"px) scale("+this.zoom+")";
	this.zoom = storedZoom;
	this.zoom_last_value = 1;
	this.zoom_refresh();
}
```

**Comment by jerosoler** [comment]
Good Job! @dsoiM

**Comment by icabbi-joegarlick** [comment]
@jerosoler @dsoiM 

Is there a way to get the current position then use that position with this function?

Im wanting to save the current X, Y and Zoom in a database and when the page is loaded back up the "viewport" is in the same place.

Im really struggling with this and any help would be greatly appreciated!

Thanks,
Joe

**Comment by jerosoler** [comment]
Hi!

Get position with:
```javascript
const x = editor.canvas_x;
const y = editor.canvas_y;
const zoom = editor.zoom; 
```

**Comment by icabbi-joegarlick** [comment]
Hey again!

Thanks for the reply.

 I have just tried this again. Saving all the values you mentioned above.

When running: this.editor.translate_to(x, y);
the position is different to what it was before i refreshed the page.

Also how would I factor in zoom into this function?

It would be really useful if the following functions were implemented:
GetTranslate
SetTranslate
GetZoom
SetZoom

Thanks again!
Joe

**Comment by icabbi-joegarlick** [comment]
> Hey again @jerosoler!
> 
> Thanks for the reply.
> 
> I have just tried this again. Saving all the values you mentioned above.
> 
> When running: this.editor.translate_to(x, y);
> the position is different to what it was before i refreshed the page.
> 
> Also how would I factor in zoom into this function?
> 
> It would be really useful if the following functions were implemented:
> GetTranslate
> SetTranslate
> GetZoom
> SetZoom
> 
> Thanks again!
> Joe

Any updates on this @jerosoler ?

Thanks!

**Comment by jerosoler** [comment]
Hi @icabbi-joegarlick 

```javascript
// GetZoom 
const zoom = editor.zoom;

// Get Translate:
const x = editor.canvas_x;
const y = editor.canvas_y;

// Set Translate the function in after comment. 

// Add zoom to function // Not tested
editor.translate_to = function(x,y, zoom){
	this.canvas_x = x;
	this.canvas_y = y;
	let storedZoom = zoom;
	this.zoom = 1;
	this.precanvas.style.transform = "translate("+this.canvas_x+"px, "+this.canvas_y+"px) scale("+this.zoom+")";
	this.zoom = storedZoom;
	this.zoom_last_value = 1;
	this.zoom_refresh();
}


```
