### ISSUE TITLE
drawflow nodes pos_x and pox_y issue

### ISSUE THREAD

**Issue by heziosight** [jerosoler/Drawflow#882]
Hello,  
when i switch between components or save my drawflow ,   nodes positions are reset to default and lost they x , y positions. 
i found the issue happen just after json is import
        if (json1.drawflow) {
          this.editor.import(json1);
          this.isStartNodeAdded = Object.values(json1.drawflow.Home.data).some((node: any) => node.name === 'start');

i attached sample video  
![chrome-capture-2024-6-17](https://github.com/user-attachments/assets/96119286-2829-4d11-9cb6-6e43956ea08d)

how i can solve it? 
thanks

**Comment by jerosoler** [comment]
Try settimeout on import method.

**Comment by heziosight** [comment]
I tried but it didn't fix the problem :(

**Comment by heziosight** [comment]
@jerosoler  issue has been solved by set   saveDrawflowState() {
    if (this.editor) {
      this.process.json = JSON.stringify(this.editor.export());
    }
method in drawflow component and called it by (click)="workflowComponent?.saveDrawflowState(); of selected tab , 
ensuring the current state of the drawflow is saved

thanks anyway!
