### ISSUE TITLE
Bugs in Demo application

### ISSUE THREAD

**Issue by skanga** [jerosoler/Drawflow#884]
I am evaluating this library for my project and found a couple of issues that were confusing. Wondering if they are bugs or my understanding is incorrect?

1) The lock/unlock button seems to be reversed?

2) When I double click on the "DB click" widget, I cannot edit the text to change the variable name, as prompted to do. This is same whether lock or unlock is on.

**Comment by jerosoler** [comment]
Its only demo

**Comment by skanga** [comment]
I understand that it is only a demo but is that supposed to be the correct behavior or not? Just for my understanding. 

Also - any suggestions on how to fix those if they are indeed bugs?

**Comment by skanga** [comment]
For Bug #2 you can change the last line of 	
      function showpopup(e) 
from:
      editor.editor_mode = "fixed";
to:
      editor.editor_mode = "edit";
