### ISSUE TITLE
make addConnection to asynchronous function

### ISSUE THREAD

**Issue by souplim** [jerosoler/Drawflow#887]
Hello, thank you for the great libarary. It's so useful. Love it!

I want to know there is a way to make addConnection func to asynchronous function.
I want to apply Async/Await concept to this function.
Is it possible?

Thank you.

**Comment by jerosoler** [comment]
Why do you need the async function? What do you need to do?

**Comment by souplim** [comment]
I want to show all the flows I made together at the same time.
If I made too many flows and reloaded, sometimes there are a few seconds during which I can see just the nodes without any links because of my logic.
So I want to hide the flows until they are perfectly connected.
Could I override the addConnection or something for that?

**Comment by jerosoler** [comment]
You can use the "import" event to detect when everything is loaded.

```javascript
editor.on("import", () => {
    // YOUR CODE
});
```

If you want to override the methods, you can override the methods like this.
Look in this comment how the removenodeId function is overridden:
- https://github.com/jerosoler/Drawflow/issues/10#issuecomment-1160543557

**Comment by souplim** [comment]
I used the code that you mentioned before to override function, thanks!
