### ISSUE TITLE
How to bind editor move to only the left mouse button? [Question]

### ISSUE THREAD

**Issue by VladikVT** [jerosoler/Drawflow#898]
Hello Jerosoler,

I noticed that the editor moves when you press any mouse button, how can I bind this only to the left one. 
I want to implement the functionality of selecting several nodes and then moving them, but this is stopping me.

Thanks in advance for your help!

**Comment by jerosoler** [comment]
Example code to disabling second button mouse, drag. 

```javascript
    var id = document.getElementById("drawflow");
    const editor = new Drawflow(id);
    editor.on("clickEnd", (e) => {
      if(e.button === 2) {
        editor.editor_selected = false;
      }
    })
    editor.start();
    editor.addNode("item", 1, 1, 700, 400, "", {}, '<input type="text"></input>');
    editor.addNode("item", 1, 1, 900, 700, "", {}, '<textarea></textarea>');
    editor.addNode("item", 1, 1, 500, 550, "", {}, 'C');
```

View for multiple nodes moving with shift key! 
- https://github.com/jerosoler/Drawflow/issues/322
