### ISSUE TITLE
Typescript version

### ISSUE THREAD

**Issue by ngunhaSO** [jerosoler/Drawflow#9]
Hi,
First, I'd like to say this is a great library!
I am wondering if you are planning on creating a type version for the library since i’d like to add this to my angular app

**Comment by jerosoler** [comment]
Hello

Thank you ;) 🎉
 
I don't plan to add typescript, for three reasons:
1. Vanilla javascript no dependency.
2. I haven't played much with typescript.
3. I am still adding features and fixes.

Maybe in the future.

The project started in April, maybe it will be too soon to refactor

**Comment by florianeichin** [comment]
Hi @jerosoler are there any updates to this topic, or no typed plans so far?

**Comment by jerosoler** [comment]
Hello @florianeichin, there are no plans at the moment.
