### ISSUE TITLE
custom method

### ISSUE THREAD

**Issue by linpan** [jerosoler/Drawflow#90]
proposal: add method
  1.get input or out node

**Comment by jerosoler** [comment]
Hello @linpan 

You can access that information with:
```javascript
getNodeFromId(id)
```

**Comment by creyeschaponan** [comment]
Hello @jerosoler 

I would like to know how I can dynamically store the id when I do the event: nodeRemoved, since there I get the id, but how can I store that id inside a vue variable,

I send what I want to do


```
this.$df.on('nodeRemoved', function(id){
          console.log(id);
          vue var = id; //  I want to do this so that when I delete store in a variable or in an array with the id of nodes removed
      });
```

**Comment by jerosoler** [comment]
Hello @creyeschaponan 

Save in data component (https://vuejs.org/v2/guide/components.html#Base-Example) or vuex. 

Use arrow function to store in data: https://github.com/jerosoler/Drawflow/issues/65#issuecomment-726160493
