### ISSUE TITLE
Is it possible to adjust the font size according to the resolution?

### ISSUE THREAD

**Issue by DooPal2000** [jerosoler/Drawflow#911]
Hello, I am using the library well. Is there a way to change the font size according to the resolution? Or if the browser itself is enlarged, the text looks too big as shown in picture 2, and I would like to change it flexibly. Any advice would be appreciated

![issue 1](https://github.com/user-attachments/assets/2f8f8e37-ffbe-4d8b-8f42-244a00b33d00)
![issue 2](https://github.com/user-attachments/assets/bc725415-bdc5-4960-a596-c40570fd0520)

**Comment by jerosoler** [comment]
You can get the zoom of the cancas this way in a css variable.
- https://github.com/jerosoler/Drawflow/issues/746#issuecomment-1662016223

If it is the browser zoom you will have to get it another way.
