### ISSUE TITLE
Remove connection with click and del key not working on page load

### ISSUE THREAD

**Issue by next-direction** [jerosoler/Drawflow#915]
Hi there,

so far I really enjoy using this library, it is very flexible and provides all the hooks to overwrite the behavior I want to change.

There is one issue that I can't figure out. When my page loads, an existing configuration is imported, and everything is rendered correctly.

I then try to click a connection an press the "delete" key, but nothing happens. I can reproduce the same behavior on the example page.
Only after clicking somewhere else in the editor area outside of any node or connection, I'm able to delete a connection by pressing "delete" after re-selecting it.

So the question is, what is different, when I click the drawflow area and then the connection instead of just the connection. The only thing I found is the following code (at the end of the click function, line 333) and if I would overwrite the complete function and leave out the `main-path` class, it would work as expected. But I don't know if anything else won't be working as expected afterwards.

```js
if (['input','output','main-path'].includes(this.ele_selected.classList[0])) {
   e.preventDefault();
}
```

Would appreciate any help I can get

**Comment by jerosoler** [comment]
View this:
- https://github.com/jerosoler/Drawflow/issues/446

**Comment by next-direction** [comment]
Ah, thank you, didn't find this yesterday.

Works as expected now,
