### ISSUE TITLE
Node Position Not Changes After Dragging and Reloading

### ISSUE THREAD

**Issue by azimsyncross** [jerosoler/Drawflow#916]
There is an inconsistency in how node positions are updated in Drawflow.js under different dragging scenarios:

Single Node Dragging:

When a single node is dragged, its position is saved correctly.
After reloading the page, the position of the dragged node changes expectedly.

Full Flow Dragging:

When the entire flow is dragged, the positions of all nodes are not updated.
After reloading the page, all nodes revert to their original positions instead of reflecting the changes from the flow drag.

Here is my code
`<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/drawflow/dist/drawflow.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/drawflow/dist/drawflow.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Drawflow Example</title>
  </head>
  <body class="flex">
    
    <div class="bg-gray-200 w-[20%] h-[100vh] p-4 flex flex-col items-center">
      
      <button
        class="bg-blue-500 text-white p-2 rounded-md mb-4 w-full"
        onclick="addCustomNode(2, 1, 'Two Inputs Node')"
      >
        2 inputs node
      </button>
      <button
        class="bg-blue-500 text-white p-2 rounded-md mb-4 w-full"
        onclick="addCustomNode(0, 2, 'Starting Node')"
      >
        Starting node
      </button>
      <button
        class="bg-green-500 text-white p-2 rounded-md mb-4 w-full"
        onclick="addCustomNode(1, 2, 'Processing Node')"
      >
        Processing node (1in, 2out)
      </button>
      <button
        class="bg-purple-500 text-white p-2 rounded-md mb-4 w-full"
        onclick="addCustomNode(2, 2, 'Multi Node')"
      >
        Multi node (2in, 2out)
      </button>

      
      <div class="mt-4 w-full">
        <label class="block text-gray-700 text-sm font-bold mb-2">
          Import JSON
        </label>
        <input
          type="file"
          id="jsonFileInput"
          accept=".json"
          class="hidden"
          onchange="handleFileSelect(event)"
        />
        <button
          onclick="document.getElementById('jsonFileInput').click()"
          class="bg-yellow-600 text-white p-2 rounded-md w-full mb-4"
        >
          Choose JSON File
        </button>
      </div>

      
      <div class="mt-4 flex flex-col gap-2 w-full">
        <button
          class="bg-green-600 text-white p-2 rounded-md w-full"
          onclick="saveToLocalStorage()"
        >
          Save to Local Storage
        </button>
        <button
          class="bg-blue-600 text-white p-2 rounded-md w-full"
          onclick="exportToJson()"
        >
          Export as JSON
        </button>
      </div>

      
      <div class="mt-4 flex flex-col gap-2 w-full">
        <button
          class="bg-gray-700 text-white p-2 rounded-md w-full"
          onclick="zoomIn()"
        >
          Zoom In (+)
        </button>
        <button
          class="bg-gray-700 text-white p-2 rounded-md w-full"
          onclick="zoomOut()"
        >
          Zoom Out (-)
        </button>
        <button
          class="bg-gray-700 text-white p-2 rounded-md w-full"
          onclick="resetZoom()"
        >
          Reset Zoom (R)
        </button>
      </div>
    </div>

    
    <div class="w-[80%] h-[100vh]">
      <div id="drawflow" class="w-full h-full"></div>
    </div>

    <script>
      // Previous variables remain the same
      let editor;
      let selectedNodeId = null;
      let copiedNodeData = null;
      const ZOOM_STEP = 0.1;
      const MIN_ZOOM = 0.1;
      const MAX_ZOOM = 2;
      const STORAGE_KEY = "drawflow-data";

      // New function to handle file import
      function handleFileSelect(event) {
        const file = event.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = function (e) {
          try {
            const jsonData = JSON.parse(e.target.result);
            editor.clear(); // Clear existing diagram
            editor.import(jsonData);
            alert("Flow imported successfully!");
          } catch (error) {
            console.error("Error importing JSON:", error);
            alert(
              "Error importing JSON file. Please make sure the file is valid."
            );
          }
        };
        reader.onerror = function () {
          alert("Error reading file");
        };
        reader.readAsText(file);

        // Reset the input so the same file can be selected again
        event.target.value = "";
      }

      // Previous functions remain the same
      function saveToLocalStorage() {
        const data = editor.export();
        localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
        alert("Flow saved to local storage!");
      }

      function exportToJson() {
        const data = editor.export();
        const dataStr = JSON.stringify(data, null, 2);
        const blob = new Blob([dataStr], { type: "application/json" });
        const url = URL.createObjectURL(blob);

        const a = document.createElement("a");
        a.href = url;
        a.download = "flowchart.json";
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      }

      function loadFromLocalStorage() {
        const savedData = localStorage.getItem(STORAGE_KEY);
        if (savedData) {
          try {
            const data = JSON.parse(savedData);
            editor.import(data);
          } catch (err) {
            console.error("Error loading saved data:", err);
          }
        }
      }

      // Helper function to create node HTML
      function createNodeHtml(nodeName, inputs, outputs) {
        return `
          <div class="node-wrapper text-white">
            <div class="node-header text-lg font-bold mb-2">${nodeName}</div>
            <div class="node-content">
              <input type="text" class="border rounded px-2 py-1 w-full mb-2" placeholder="Enter value..."/>
              <div class="text-sm text-white-600">
                Inputs: ${inputs} | Outputs: ${outputs}
              </div>
            </div>
          </div>
        `;
      }

      // Previous zoom functions remain the same
      function zoomIn() {
        const currentZoom = editor.zoom;
        if (currentZoom < MAX_ZOOM) {
          editor.zoom_in();
        }
      }

      function zoomOut() {
        const currentZoom = editor.zoom;
        if (currentZoom > MIN_ZOOM) {
          editor.zoom_out();
        }
      }

      function resetZoom() {
        editor.zoom_reset();
      }

      // Function to add custom node
      function addCustomNode(inputs, outputs, nodeName) {
        const nodeHtml = createNodeHtml(nodeName, inputs, outputs);

        const addedNode = editor.addNode(
          nodeName,
          inputs,
          outputs,
          100 + Math.random() * 200,
          100 + Math.random() * 200,
          "custom-node",
          { value: "" },
          nodeHtml
        );
      }

      // Rest of the initialization code and event listeners remain the same
      document.addEventListener("DOMContentLoaded", () => {
        editor = new Drawflow(document.getElementById("drawflow"));
        editor.reroute = true;
        editor.start();
        editor.editor_mode = "edit";

        loadFromLocalStorage();

        editor.on("nodeMoved", (id) => {
          const node = editor.getNodeFromId(id);
          console.log(`Node ${id} moved to:`, { x: node.pos_x, y: node.pos_y });
        });

        // Previous event listeners remain the same
        editor.on("nodeSelected", (id) => {
          selectedNodeId = id;
          console.log(`Node selected: ${id}`);
        });

        editor.on("nodeUnselected", () => {
          selectedNodeId = null;
          console.log("No node selected");
        });

        document.getElementById("drawflow").addEventListener("mousedown", (event) => {
  console.log(event);
  
  // Save initial state when starting to drag
  const saveTimeout = setTimeout(() => {
    const data = editor.export();
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    console.log('Flow state saved to local storage');
  }, 100); // Small delay to ensure the drag operation is complete
  
  // Clean up the timeout if the mouse is released quickly
  document.addEventListener('mouseup', () => {
    clearTimeout(saveTimeout);
    
    // Save the final state after mouse up
    const data = editor.export();
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    console.log('Flow state saved to local storage after mouse up');
  }, { once: true }); // Remove the listener after it's fired once
});
        document
          .getElementById("drawflow")
          .addEventListener("dblclick", (event) => {
            console.log(event);
            const nodeId = event.target.getAttribute("data-nodeid");
            if (nodeId) {
              const node = editor.getNodeFromId(nodeId);
              console.log(`Double-clicked on node ${nodeId}:`, node);
              // Perform any action on double-click (e.g., editing the node or showing a modal)
              // Example: You can open a modal or change some properties of the node
            }
          });

        // Previous keyboard shortcuts remain the same
        document.addEventListener("keydown", (event) => {
          if (event.ctrlKey && event.key === "s") {
            event.preventDefault();
            saveToLocalStorage();
          }

          if (event.ctrlKey && event.key === "=") {
            zoomIn();
            event.preventDefault();
          }
          if (event.ctrlKey && event.key === "-") {
            zoomOut();
            event.preventDefault();
          }
          if (event.ctrlKey && event.key === "r") {
            resetZoom();
            event.preventDefault();
          }

          if (!selectedNodeId) return;

          if (event.ctrlKey && event.key === "c") {
            copiedNodeData = editor.getNodeFromId(selectedNodeId);
          }

          if (event.ctrlKey && event.key === "v" && copiedNodeData) {
            const offset = 20;
            const nodeHtml = createNodeHtml(
              copiedNodeData.name,
              Object.keys(copiedNodeData.inputs).length,
              Object.keys(copiedNodeData.outputs).length
            );

            editor.addNode(
              copiedNodeData.name,
              Object.keys(copiedNodeData.inputs).length,
              Object.keys(copiedNodeData.outputs).length,
              copiedNodeData.pos_x + offset,
              copiedNodeData.pos_y + offset,
              copiedNodeData.class,
              copiedNodeData.data,
              nodeHtml
            );
          }

          if (event.ctrlKey && event.key === "d") {
            const nodeData = editor.getNodeFromId(selectedNodeId);
            const offset = 30;
            const nodeHtml = createNodeHtml(
              nodeData.name,
              Object.keys(nodeData.inputs).length,
              Object.keys(nodeData.outputs).length
            );

            editor.addNode(
              nodeData.name,
              Object.keys(nodeData.inputs).length,
              Object.keys(nodeData.outputs).length,
              nodeData.pos_x + offset,
              nodeData.pos_y + offset,
              nodeData.class,
              nodeData.data,
              nodeHtml
            );
          }
        });

        // Mouse wheel zoom support
        document.getElementById("drawflow").addEventListener("wheel", (e) => {
          if (e.ctrlKey) {
            e.preventDefault();
            if (e.deltaY < 0) {
              zoomIn();
            } else {
              zoomOut();
            }
          }
        });
      });
    </script>

    <style>
      #drawflow {
        position: relative;
        background-size: 40px 40px;
        background-image: linear-gradient(
            to right,
            rgba(0, 0, 0, 0.1) 1px,
            transparent 1px
          ),
          linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 1px, transparent 1px);
      }

      .drawflow .drawflow-node {
        background: #2d3436;
        border: 2px solid #2d3436;
        border-radius: 8px;
        min-width: 200px;
      }
    </style>
  </body>
</html>
`

https://github.com/user-attachments/assets/c43b8eab-76b1-40c2-b98a-37f98afab0be

**Comment by jerosoler** [comment]
Canvas x, y not exported on data. Only data nodes. 

You can see a solution here
- https://github.com/jerosoler/Drawflow/issues/387
