### ISSUE TITLE
Editor Keeps Moving When Cursor Leaves and Re-enters Canvas During Panning

### ISSUE THREAD

**Issue by azimsyncross** [jerosoler/Drawflow#918]
I'm encountering an issue with Drawflow.js where the editor's panning behavior persists incorrectly. Specifically, when I left-click and drag to move the editor, then move the cursor outside the canvas area while still holding the mouse button, the editor continues to move even after returning the cursor to the canvas.

https://github.com/user-attachments/assets/9dc3a3c9-4779-447d-8bd5-89a802cd2267

**Comment by jerosoler** [comment]
view this:
- https://github.com/jerosoler/Drawflow/issues/443

**Comment by azimsyncross** [comment]
@jerosoler thanks
