### ISSUE TITLE
keydown event is being triggered twice

### ISSUE THREAD

**Issue by azimsyncross** [jerosoler/Drawflow#919]
$scope.editor.on("keydown",function(event){
		    
		    
		    console.log("keydown event",event)
		 
		    
		    // Handle copy (Ctrl+c)
		    if (event.ctrlKey && event.key === 'c') {
		        copySelectedNode();
		    }
		  //  Handle paste (Ctrl+v)
		    if (event.ctrlKey && event.key === 'v') {
		        console.log("pasiting node ")
		        pasteNode();
		    }
		})
		
		
		any keypress trigger event twice 
		
		any issue in implementation?

**Comment by jerosoler** [comment]
It only runs once.

Are you using a reactivity system?

Note: The control key is an event and the "C" or "V" key is another event.

Example with simple html.  

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css"/>
  <script src="https://unpkg.com/drawflow@0.0.60/dist/drawflow.min.js"></script>
<style>
  #drawflow { 
    position: relative;
    text-align:initial;
    width: 100%;
    height: 800px;
    border: 1px solid red;
  }
</style>
</head>
<body>
<div id="drawflow"></div>
<script>
    var id = document.getElementById("drawflow");
    const editor = new Drawflow(id);
    editor.on("keydown",function(event){
	    console.log("keydown event",event)
	  })
    editor.start();
    editor.addNode("item", 1, 1, 700, 400, "", {}, '<input type="text"></input>');
    editor.addNode("item", 1, 1, 900, 700, "", {}, '<textarea></textarea>');
    editor.addNode("item", 1, 1, 500, 550, "", {}, 'C');
</script>
</body>
</html>
```

**Comment by azimsyncross** [comment]
Yes, I am using Drawflow with a reactivity system. Is there any way to stop Drawflow's keydown event from working and implement keydown in the document instead?

**Comment by jerosoler** [comment]
You can use the addeventlistener event:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

Or you can look at why your system sends 2 events.
