### ISSUE TITLE
how to change node selected status ?

### ISSUE THREAD

**Issue by linpan** [jerosoler/Drawflow#92]
when I drag a connection from unselected node。 how I can get  the  unselected node info or set it to be selected stauts ?
![image](https://user-images.githubusercontent.com/6077601/103074048-c510f080-4603-11eb-9f92-5d944dcc9a18.png)

**Comment by jerosoler** [comment]
Hello @linpan 

I could do something like that.

```javascript
editor.on("clickEnd", function(event){
    if(event.target.classList[0] === "output") {
      event.target.closest(".drawflow-node").classList.add("selected")
      editor.node_selected = event.target.closest(".drawflow-node");
    }
  })
```

**Comment by linpan** [comment]
thks, Happy new year.
