### ISSUE TITLE
Safari select bug

### ISSUE THREAD

**Issue by barbudour** [jerosoler/Drawflow#95]
Hi, I found a bug in Safari. If you select the Select value for an element, then it sticks to the cursor. Has anyone come across a similar one?
![image](https://user-images.githubusercontent.com/29177814/104298950-a51f6f00-54d5-11eb-8fcb-ca5171d8178d.png)
![image](https://user-images.githubusercontent.com/29177814/104298965-aa7cb980-54d5-11eb-8e21-78f116f19475.png)

**Comment by jerosoler** [comment]
Hello @barbudour 

I don't have safari, but I see the error happens also on https://wiki.gnome.org/Apps/Web based on webkit.

I take a look at it.

**Comment by jerosoler** [comment]
Thanks! 

Fix on version 0.0.33 🎉

**Comment by barbudour** [comment]
> Thanks!
> 
> Fix on version 0.0.33 🎉

Thanks!
