### ISSUE TITLE
Connections within one node

### ISSUE THREAD

**Issue by barbudour** [jerosoler/Drawflow#96]
Hi, is it possible to create connections between inputs and outputs within one node?

![image](https://user-images.githubusercontent.com/29177814/104568696-733b1380-5661-11eb-8f66-4a726383ccf8.png)

**Comment by jerosoler** [comment]
Hello @barbudour 

Use  `addConnection`

Example: 
```javascript
editor.addConnection(12,12,'output_1', 'input_1');
```
😉

**Comment by pavlyuts** [comment]
> Use `addConnection`
> Example:
> ```js
> editor.addConnection(12,12,'output_1', 'input_1');
> ```
But not in the editor window? ;) Something prevents it.

**Comment by jerosoler** [comment]
Hello @pavlyuts 

By default it is not allowed. It is not logical.
An intermediate node could be created to send the same signal.

On the other hand, the line is hidden behind the node.

You can override the `dragEnd` function to allow connection to the same node.

**Comment by barbudour** [comment]
> Hello @pavlyuts
> 
> By default it is not allowed. It is not logical.
> An intermediate node could be created to send the same signal.
> 
> On the other hand, the line is hidden behind the node.
> 
> You can override the `dragEnd` function to allow connection to the same node.

Yes, that's what I need. Thank you!
