### ISSUE TITLE
Vuex on registered component

### ISSUE THREAD

**Issue by ananddoesembed** [jerosoler/Drawflow#99]
Thank you for this interesting library. I have a query about vuex. vuex works everywhere except registered component.
(https://stackoverflow.com/questions/65681442/error-in-v-on-handler-typeerror-cannot-read-property-dispatch-of-undefined)
I have mentioned everything in above link . click.vue is the registered component. Is there anything else I should be doing for vuex to work on this particular component.?

**Comment by jerosoler** [comment]
Hello @ananddoesembed 

View https://github.com/jerosoler/Drawflow/issues/37#issuecomment-717822302 (example with event bus) 

Components are isolated. 
I think this is how it could work.

Viewing the documentation of vuex: https://vuex.vuejs.org/guide/#the-simplest-store
```javascript
new Vue({
  el: '#app',
  store: store,
})
```

Other option is inject the store to the component. 

Drawflow create a node with: 
```javascript 
 new this.render({
          render: h => h(this.noderegister[html].html, { props: this.noderegister[html].props }),
          ...this.noderegister[html].options
        }).$mount()
```
Translated: 
```javascript
 new Vue({
          render: h => h(this.noderegister[html].html, { props: this.noderegister[html].props }),
          ...this.noderegister[html].options
        }).$mount()
```

Pass in the options the store. 
https://github.com/jerosoler/Drawflow#register-node

```javascript 
editor.registerNode('name', component, props, options);
```

Test and comment

**Comment by ananddoesembed** [comment]
thank you @jerosoler . I'll go with event-bus
